package cn.ibizlab.crm.crm.logic.payeelogic.addpayeetoworkprogress;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee payeeaddpayeetoworkprogressdefault;
                global cn.ibizlab.crm.core.crm.domain.work_progress payeeaddpayeetoworkprogresswork_progress;
                    global cn.ibizlab.crm.core.crm.service.Iwork_progressService work_progressservice;
        global cn.ibizlab.crm.core.crm.service.IpayeeService iBzSysPayeeDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payeeaddpayeetoworkprogressbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payeeaddpayeetoworkprogressend1"
            when
            then
                        update(payeeaddpayeetoworkprogressdefault);//更新fact中变量值
                        update(payeeaddpayeetoworkprogresswork_progress);//更新fact中变量值
            end

            //逻辑处理节点[准备工作进展参数]
            rule "prepareparam1"
            ruleflow-group "payeeaddpayeetoworkprogressprepareparam1"
            when
            then
                            payeeaddpayeetoworkprogresswork_progress.set("actiontype","create");
                            payeeaddpayeetoworkprogresswork_progress.set("targetid",payeeaddpayeetoworkprogressdefault.get("id"));
                            payeeaddpayeetoworkprogresswork_progress.set("targettype","PAYEE");
                            payeeaddpayeetoworkprogresswork_progress.set("targetname",payeeaddpayeetoworkprogressdefault.get("projectname"));
                            payeeaddpayeetoworkprogresswork_progress.set("description",payeeaddpayeetoworkprogressdefault.get("description"));
                        update(payeeaddpayeetoworkprogressdefault);//更新fact中变量值
                        update(payeeaddpayeetoworkprogresswork_progress);//更新fact中变量值
            end

            //逻辑处理节点[创建工作进展]
            rule "deaction1"
            ruleflow-group "payeeaddpayeetoworkprogressdeaction1"
            when
            then
                        work_progressservice.create(payeeaddpayeetoworkprogresswork_progress);
                        update(payeeaddpayeetoworkprogressdefault);//更新fact中变量值
                        update(payeeaddpayeetoworkprogresswork_progress);//更新fact中变量值
            end