package cn.ibizlab.crm.crm.logic.payeelogic.asyncpayeetoworkprogres;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee payeeasyncpayeetoworkprogresdefault;
                    global cn.ibizlab.crm.core.crm.service.IpayeeService payeeservice;
        global cn.ibizlab.crm.core.crm.service.IpayeeService iBzSysPayeeDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payeeasyncpayeetoworkprogresbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payeeasyncpayeetoworkprogresend1"
            when
            then
                        update(payeeasyncpayeetoworkprogresdefault);//更新fact中变量值
            end

            //逻辑处理节点[异步添加收款记录到工作进展]
            rule "deaction1"
            ruleflow-group "payeeasyncpayeetoworkprogresdeaction1"
            when
            then
                        payeeservice.async_addPayeeToWorkProgress(payeeasyncpayeetoworkprogresdefault);
                        update(payeeasyncpayeetoworkprogresdefault);//更新fact中变量值
            end