package cn.ibizlab.crm.crm.logic.payeelogic.plan_account_get;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee payeeplan_account_getdefault;
                global cn.ibizlab.crm.core.crm.domain.payee_plan payeeplan_account_getpayee_plan;
                    global cn.ibizlab.crm.core.crm.service.Ipayee_planService payee_planservice;
        global cn.ibizlab.crm.core.crm.service.IpayeeService iBzSysPayeeDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payeeplan_account_getbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payeeplan_account_getend1"
            when
            then
                        update(payeeplan_account_getdefault);//更新fact中变量值
                        update(payeeplan_account_getpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "payeeplan_account_getprepareparam1"
            when
            then
                            payeeplan_account_getpayee_plan.set("id",payeeplan_account_getdefault.get("payeeplanid"));
                        update(payeeplan_account_getdefault);//更新fact中变量值
                        update(payeeplan_account_getpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "payeeplan_account_getdeaction1"
            when
            then
                            cn.ibizlab.crm.util.helper.CachedBeanCopier.copy(payee_planservice.get(payeeplan_account_getpayee_plan.getId()),payeeplan_account_getpayee_plan);
                        update(payeeplan_account_getdefault);//更新fact中变量值
                        update(payeeplan_account_getpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "payeeplan_account_getdebugparam1"
            when
            then
                        update(payeeplan_account_getdefault);//更新fact中变量值
                        update(payeeplan_account_getpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "payeeplan_account_getprepareparam2"
            when
            then
                            payeeplan_account_getdefault.set("planamount",payeeplan_account_getpayee_plan.get("amount"));
                            payeeplan_account_getdefault.set("plannedtime",payeeplan_account_getpayee_plan.get("plannedtime"));
                            payeeplan_account_getdefault.set("plandescription",payeeplan_account_getpayee_plan.get("description"));
                        update(payeeplan_account_getdefault);//更新fact中变量值
                        update(payeeplan_account_getpayee_plan);//更新fact中变量值
            end