package cn.ibizlab.crm.crm.logic.payeelogic.plan_get_project_id;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee payeeplan_get_project_iddefault;
                global cn.ibizlab.crm.core.crm.domain.payee_plan payeeplan_get_project_idpayee_plan;
                    global cn.ibizlab.crm.core.crm.service.Ipayee_planService payee_planservice;
        global cn.ibizlab.crm.core.crm.service.IpayeeService iBzSysPayeeDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payeeplan_get_project_idbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payeeplan_get_project_idend1"
            when
            then
                        update(payeeplan_get_project_iddefault);//更新fact中变量值
                        update(payeeplan_get_project_idpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "payeeplan_get_project_idprepareparam1"
            when
            then
                            payeeplan_get_project_idpayee_plan.set("projectid",payeeplan_get_project_iddefault.get("projectid"));
                        update(payeeplan_get_project_iddefault);//更新fact中变量值
                        update(payeeplan_get_project_idpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "payeeplan_get_project_iddeaction1"
            when
            then
                            cn.ibizlab.crm.util.helper.CachedBeanCopier.copy(payee_planservice.get(payeeplan_get_project_idpayee_plan.getId()),payeeplan_get_project_idpayee_plan);
                        update(payeeplan_get_project_iddefault);//更新fact中变量值
                        update(payeeplan_get_project_idpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "payeeplan_get_project_iddebugparam1"
            when
            then
                        update(payeeplan_get_project_iddefault);//更新fact中变量值
                        update(payeeplan_get_project_idpayee_plan);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "payeeplan_get_project_idprepareparam2"
            when
            then
                            payeeplan_get_project_iddefault.set("planamount",payeeplan_get_project_idpayee_plan.get("amount"));
                            payeeplan_get_project_iddefault.set("plannedtime",payeeplan_get_project_idpayee_plan.get("plannedtime"));
                            payeeplan_get_project_iddefault.set("plandescription",payeeplan_get_project_idpayee_plan.get("description"));
                        update(payeeplan_get_project_iddefault);//更新fact中变量值
                        update(payeeplan_get_project_idpayee_plan);//更新fact中变量值
            end