package cn.ibizlab.crm.crm.logic.payeelogic.project_to_payee;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee payeeproject_to_payeedefault;
                global cn.ibizlab.crm.core.crm.domain.order_allocate payeeproject_to_payeeorder_allocate;
                global cn.ibizlab.crm.core.crm.domain.order_allocate payeeproject_to_payeeorder_allocates;
                global cn.ibizlab.crm.core.crm.domain.payee_allocate payeeproject_to_payeepayee_allocate;
                global cn.ibizlab.crm.core.crm.domain.payee_allocate payeeproject_to_payeepayee_allocates;
                global cn.ibizlab.crm.core.crm.domain.order_allocate payeeproject_to_payeeorder_allocate_filter;
                global cn.ibizlab.crm.core.crm.domain.order_allocate payeeproject_to_payeesub;
                    global cn.ibizlab.crm.core.crm.service.Iorder_allocateService order_allocateservice;
        global cn.ibizlab.crm.core.crm.service.IpayeeService iBzSysPayeeDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payeeproject_to_payeebegin"
            when
            then
            end

            //逻辑处理节点[查看结果数据]
            rule "debugparam3"
            ruleflow-group "payeeproject_to_payeedebugparam3"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "payeeproject_to_payeedebugparam2"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[每次sub数据]
            rule "debugparam4"
            ruleflow-group "payeeproject_to_payeedebugparam4"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "payeeproject_to_payeededataset1"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "payeeproject_to_payeeloopsubcall1"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "payeeproject_to_payeeprepareparam1"
            when
            then
                            payeeproject_to_payeeorder_allocate_filter.set("n_owner_id_eq",payeeproject_to_payeedefault.get("projectid"));
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "payeeproject_to_payeeprepareparam2"
            when
            then
                                payeeproject_to_payeepayee_allocate.set("id",null);
                            payeeproject_to_payeepayee_allocate.set("ratio",payeeproject_to_payeesub.get("ratio"));
                            payeeproject_to_payeepayee_allocate.set("userid",payeeproject_to_payeesub.get("userid"));
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[重新建立参数]
            rule "renewparam1"
            ruleflow-group "payeeproject_to_payeerenewparam1"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam1"
            ruleflow-group "payeeproject_to_payeeappendparam1"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "payeeproject_to_payeeprepareparam3"
            when
            then
                            payeeproject_to_payeedefault.set("payeeallocates",payeeproject_to_payeepayee_allocates.get(""));
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payeeproject_to_payeeend1"
            when
            then
                        update(payeeproject_to_payeedefault);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocates);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocate);//更新fact中变量值
                        update(payeeproject_to_payeepayee_allocates);//更新fact中变量值
                        update(payeeproject_to_payeeorder_allocate_filter);//更新fact中变量值
                        update(payeeproject_to_payeesub);//更新fact中变量值
            end