global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService  payeeStatisticService;
global cn.ibizlab.crm.core.crm.domain.payee_plan et;

    no-loop

    rule "payee_statisticcalculation"
    ruleflow-group "b792b49f2ec5fcddc07873201489b61a"
    when
    then
    cn.ibizlab.crm.core.crm.domain.payee_statistic actionLogicDE =new cn.ibizlab.crm.core.crm.domain.payee_statistic();
    et.copyTo(actionLogicDE,true);
    payeeStatisticService.calculation(actionLogicDE);
    end