export default {
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: '424cbd226acef51502ab6af53c351523',
  accUserMode: 2,
  caption: '客户',
  codeName: 'account_redirect_view',
  appDataEntityId: 'crmweb.account',
  controls: [
    {
      caption: '客户',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.account',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.account',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '客户数据重定向视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: 'dd273297dc4f35674064439137c301e1',
  modelType: 'PSAPPDEVIEW',
  name: 'accountRedirectView',
  id: 'crmweb.account_redirect_view',
};
