export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'test_main_view',
  deviewId: 'dbdae35942ff504695d60c51ba68b491',
  accUserMode: 2,
  caption: '客户信息',
  codeName: 'account_test_main_view',
  appDataEntityId: 'crmweb.account',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView2',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      key: 'N_OWNER_ID_EQ',
      value: 'account',
      name: 'N_OWNER_ID_EQ',
      id: 'n_owner_id_eq',
    },
    {
      key: 'OWNER_ID',
      value: 'account',
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      key: 'PRINCIPAL_ID',
      value: 'account',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'OWNER_TYPE',
      value: 'ACCOUNT',
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'ACCOUNT',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'account',
      id: 'n_owner_id_eq',
    },
    {
      key: 'principal_id',
      value: 'account',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'owner_type',
      value: 'ACCOUNT',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'principal_type',
      value: 'ACCOUNT',
      id: 'principal_type',
    },
    {
      key: 'owner_id',
      value: 'account',
      id: 'owner_id',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          buttonStyle: 'INFO',
          noPrivDisplayMode: 2,
          uiactionId: 'open_edit_view@account',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '编辑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-edit',
            glyph: 'xf044@FontAwesome',
          },
          tooltip: '编辑',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction4',
        },
        {
          actionLevel: 100,
          buttonStyle: 'INFO',
          detoolbarItems: [
            {
              actionLevel: 100,
              buttonStyle: 'INFO',
              noPrivDisplayMode: 2,
              uiactionId: 'editview_removeandexitaction',
              uiactionTarget: 'SINGLEKEY',
              valid: true,
              capLanguageRes: {
                lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
              },
              caption: '删除并关闭',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-remove',
                glyph: 'xf00d@FontAwesome',
              },
              tooltip: '删除并关闭',
              tooltipLanguageRes: {
                lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
              },
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'open_marge_view@account',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '合并客户',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-cogs',
                glyph: 'xf085@FontAwesome',
              },
              tooltip: '合并客户',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysImage: {
            cssClass: 'fa fa-ellipsis-h',
            glyph: 'xf141@FontAwesome',
          },
          showIcon: true,
          id: 'items1',
        },
        {
          actionLevel: 100,
          buttonStyle: 'INVERSE',
          noPrivDisplayMode: 2,
          uiactionId: 'editview_prevrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '上一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-chevron-left',
            glyph: 'xf053@FontAwesome',
          },
          tooltip: '上一个记录',
          showIcon: true,
          id: 'deuiaction6',
        },
        {
          actionLevel: 100,
          buttonStyle: 'INVERSE',
          noPrivDisplayMode: 2,
          uiactionId: 'editview_nextrecordaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '下一个记录',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-chevron-right',
            glyph: 'xf054@FontAwesome',
          },
          tooltip: '下一个记录',
          showIcon: true,
          id: 'deuiaction7',
        },
      ],
      xdataControlName: 'form',
      codeName: 'test_main_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '客户主数据视图_工具栏',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '12994806244e4784b8463c63024cc57f',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'test_main_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.account',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.account',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.account',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.account',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.account',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.account',
        id: 'update',
      },
      infoFormMode: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'grouppanel4',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  appViewId: 'crmweb.deal_list_view_relation',
                  parentDataJO: {
                    SRFPARENTTYPE: 'DER1N',
                    srfparentdename: 'ACCOUNT',
                    srfparentmode: 'DER1N_DEAL_ACCOUNT_ACCOUNT_ID',
                    srfparentdefname: 'ACCOUNT_ID',
                    SRFDER1NID: 'DER1N_DEAL_ACCOUNT_ACCOUNT_ID',
                  },
                  codeName: 'druipart2',
                  detailStyle: 'DEFAULT',
                  detailType: 'DRUIPART',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'druipart2',
                },
              ],
              caption: '商机',
              codeName: 'grouppanel11',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel11',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  appViewId: 'crmweb.task_list_view_relation',
                  navigateContexts: [
                    {
                      key: 'N_OWNER_ID_EQ',
                      value: 'id',
                      name: 'N_OWNER_ID_EQ',
                      id: 'n_owner_id_eq',
                    },
                  ],
                  navigateParams: [
                    {
                      key: 'n_owner_id_eq',
                      value: 'id',
                      id: 'n_owner_id_eq',
                    },
                  ],
                  parentDataJO: {
                    srfparentdename: 'ACCOUNT',
                    SRFPARENTTYPE: 'CUSTOM',
                  },
                  codeName: 'druipart3',
                  detailStyle: 'DEFAULT',
                  detailType: 'DRUIPART',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'druipart3',
                },
              ],
              caption: '下一个活动',
              codeName: 'grouppanel12',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel12',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  appViewId: 'crmweb.contact_list_view_relation',
                  navigateContexts: [
                    {
                      key: 'N_ACCOUNT_ID_EQ',
                      value: 'id',
                      name: 'N_ACCOUNT_ID_EQ',
                      id: 'n_account_id_eq',
                    },
                  ],
                  navigateParams: [
                    {
                      key: 'n_account_id_eq',
                      value: 'id',
                      id: 'n_account_id_eq',
                    },
                  ],
                  parentDataJO: {
                    srfparentdename: 'ACCOUNT',
                    SRFPARENTTYPE: 'CUSTOM',
                  },
                  codeName: 'druipart4',
                  detailStyle: 'DEFAULT',
                  detailType: 'DRUIPART',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'druipart4',
                },
              ],
              caption: '联系人',
              codeName: 'grouppanel13',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel13',
            },
            {
              titleBarCloseMode: 1,
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'account_number',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'account_number',
                          },
                          allowEmpty: true,
                          caption: '客户编号',
                          codeName: 'account_number',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'account_number',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'account_name',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'account_name',
                          },
                          allowEmpty: true,
                          caption: '客户名称',
                          codeName: 'account_name',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'account_name',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          ignoreInput: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'account_type',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'crmweb.crm__account_type',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'account_type',
                          },
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '客户类型',
                          codeName: 'account_type',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'account_type',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'account_site',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'account_site',
                          },
                          allowEmpty: true,
                          caption: '客户所在地',
                          codeName: 'account_site',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'account_site',
                        },
                      ],
                      codeName: 'grouppanel7',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 8,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel7',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          ignoreInput: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'owner',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'crmweb.crm__owner',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'owner',
                          },
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '所有者',
                          codeName: 'owner',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'owner',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'p_account_name',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'paccount_name',
                          },
                          allowEmpty: true,
                          caption: '父客户',
                          codeName: 'paccount_name',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'paccount_name',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          ignoreInput: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'industry',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'crmweb.crm__industry',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'industry',
                          },
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '行业',
                          codeName: 'industry',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'industry',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          ignoreInput: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'rating',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'crmweb.crm__rating',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'rating',
                          },
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '等级',
                          codeName: 'rating',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'rating',
                        },
                      ],
                      codeName: 'grouppanel8',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 8,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel8',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 21,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'description',
                          editor: {
                            maxLength: 1048576,
                            showMaxLength: true,
                            editorParams: {
                              readonly: 'true',
                            },
                            editorType: 'TEXTAREA',
                            valueType: 'SIMPLE',
                            editable: true,
                            readOnly: true,
                            id: 'description',
                          },
                          allowEmpty: true,
                          caption: '描述',
                          codeName: 'description',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 16,
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          sysCss: {
                            cssName: 'input-readonly',
                          },
                          showCaption: true,
                          id: 'description',
                        },
                      ],
                      caption: '描述',
                      codeName: 'grouppanel3',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 24,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel3',
                    },
                  ],
                  caption: '客户信息',
                  codeName: 'group1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'group1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'phone',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'phone',
                      },
                      allowEmpty: true,
                      caption: '电话',
                      codeName: 'phone',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'phone',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'fax',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'fax',
                      },
                      allowEmpty: true,
                      caption: '传真',
                      codeName: 'fax',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'fax',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'annual_revenue',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'annual_revenue',
                      },
                      allowEmpty: true,
                      caption: '年收入',
                      codeName: 'annual_revenue',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'annual_revenue',
                    },
                    {
                      dataType: 9,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'employees',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'employees',
                      },
                      allowEmpty: true,
                      caption: '员工数',
                      codeName: 'employees',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'employees',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'website',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'website',
                      },
                      allowEmpty: true,
                      caption: '网站',
                      codeName: 'website',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'website',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'ticker_symbol',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'ticker_symbol',
                      },
                      allowEmpty: true,
                      caption: '股票代码',
                      codeName: 'ticker_symbol',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'ticker_symbol',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      ignoreInput: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'ownership',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        appCodeListId: 'crmweb.crm__ownership',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'ownership',
                      },
                      allowEmpty: true,
                      convertToCodeItemText: true,
                      caption: '公司所有权',
                      codeName: 'ownership',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'ownership',
                    },
                    {
                      dataType: 9,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'sic_code',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'sic_code',
                      },
                      allowEmpty: true,
                      caption: 'SIC代码',
                      codeName: 'sic_code',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'sic_code',
                    },
                  ],
                  caption: '其他信息',
                  codeName: 'grouppanel14',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 16,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel14',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'billing_street',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'billing_street',
                          },
                          allowEmpty: true,
                          caption: '开单地址-街道',
                          codeName: 'billing_street',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'billing_street',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'billing_city',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'billing_city',
                          },
                          allowEmpty: true,
                          caption: '开单地址-城市',
                          codeName: 'billing_city',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'billing_city',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'billing_state',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'billing_state',
                          },
                          allowEmpty: true,
                          caption: '开单地址-省/市',
                          codeName: 'billing_state',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'billing_state',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'billing_code',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'billing_code',
                          },
                          allowEmpty: true,
                          caption: '开单地址-邮编',
                          codeName: 'billing_code',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'billing_code',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'billing_country',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'billing_country',
                          },
                          allowEmpty: true,
                          caption: '开单地址-国家/地区',
                          codeName: 'billing_country',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'billing_country',
                        },
                      ],
                      codeName: 'grouppanel9',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 8,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel9',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'shipping_street',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'shipping_street',
                          },
                          allowEmpty: true,
                          caption: '发货地址-街道',
                          codeName: 'shipping_street',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'shipping_street',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'shipping_city',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'shipping_city',
                          },
                          allowEmpty: true,
                          caption: '发货地址-城市',
                          codeName: 'shipping_city',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'shipping_city',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'shipping_state',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'shipping_state',
                          },
                          allowEmpty: true,
                          caption: '发货地址-省/市',
                          codeName: 'shipping_state',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'shipping_state',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'shipping_code',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'shipping_code',
                          },
                          allowEmpty: true,
                          caption: '发货地址-邮编',
                          codeName: 'shipping_code',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'shipping_code',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'shipping_country',
                          editor: {
                            halign: 'LEFT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'shipping_country',
                          },
                          allowEmpty: true,
                          caption: '发货地址-国家/地区',
                          codeName: 'shipping_country',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'shipping_country',
                        },
                      ],
                      codeName: 'grouppanel10',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 8,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel10',
                    },
                  ],
                  caption: '地址信息',
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel2',
                },
              ],
              caption: '详细信息',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 190,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '概览',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  appViewId: 'crmweb.activitiy_time_line_view',
                  parentDataJO: {
                    srfparentdename: 'ACCOUNT',
                    SRFPARENTTYPE: 'CUSTOM',
                  },
                  codeName: 'druipart1',
                  detailStyle: 'DEFAULT',
                  detailType: 'DRUIPART',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'druipart1',
                },
              ],
              caption: '历史信息',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
          ],
          caption: '时间轴',
          codeName: 'formpage2',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage2',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main_view_form',
      controlStyle: 'ANCHOR_STYLE',
      controlType: 'FORM',
      logicName: '客户主数据视图_表单',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'form',
      },
      sysPFPluginId: 'anchor_style',
      modelId: '97a0b5179593fe7817ec2f56232798bf',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.account.main_view_form',
    },
    {
      dedrbarGroups: [
        {
          caption: '详细信息',
          name: '详细信息',
          id: 'drgroup',
        },
      ],
      showTitle: true,
      dataRelationTag: 'main_view_DR',
      editItemCaption: '客户',
      appCounterRefId: '713ed510e7b1a77c66ccfd9caa4d02cd',
      dedrctrlItems: [
        {
          dedrbarGroupId: 'drgroup',
          caption: '附件',
          counterId: 'attachment',
          appViewId: 'crmweb.account_attachment_view',
          id: 'attachment',
        },
        {
          dedrbarGroupId: 'drgroup',
          caption: '商机',
          counterId: 'deal',
          appViewId: 'crmweb.deal_grid_view_relation',
          id: 'deal',
        },
        {
          dedrbarGroupId: 'drgroup',
          caption: '联系人',
          counterId: 'contact',
          appViewId: 'crmweb.contact_grid_view_relation',
          id: 'contact',
        },
        {
          dedrbarGroupId: 'drgroup',
          caption: '待办任务',
          counterId: 'not_close',
          appViewId: 'crmweb.schedule_not_close_tab_exp_view9',
          navigateContexts: [
            {
              key: 'OWNER_ID',
              value: 'principal_id',
              name: 'OWNER_ID',
              id: 'owner_id',
            },
            {
              key: 'OWNER_TYPE',
              value: 'owner_type',
              name: 'OWNER_TYPE',
              id: 'owner_type',
            },
          ],
          navigateParams: [
            {
              key: 'owner_id',
              value: 'principal_id',
              id: 'owner_id',
            },
            {
              key: 'owner_type',
              value: 'owner_type',
              id: 'owner_type',
            },
          ],
          id: 'not_close',
        },
        {
          dedrbarGroupId: 'drgroup',
          caption: '已完成的任务&历史活动',
          counterId: 'taskhisact',
          appViewId: 'crmweb.task_task_act_list_view',
          id: 'taskhisact',
        },
        {
          dedrbarGroupId: 'drgroup',
          caption: '关联销售人员',
          counterId: 'user',
          dataAccessAction: 'SRFUR__ASSIGNRELATEDSALES',
          enableMode: 'DEOPPRIV',
          appViewId: 'crmweb.user_grid_view_relation',
          id: 'user',
        },
      ],
      uniqueTag: 'account_test_main_view__drbar',
      autoLoad: true,
      showBusyIndicator: true,
      appCounterRefs: [
        {
          appCounter: {
            codeName: 'account_main_view_dr',
            counterType: 'DEDR',
            getAppDEActionId: 'main_view_dr_count',
            appDataEntityId: 'crmweb.account',
            timer: 60000,
            uniqueTag: 'account_main_view_dr',
            name: '客户main_view关系',
            id: 'crmweb.account_main_view_dr',
          },
          refMode: {
            srfdeid: 'ACCOUNT',
          },
          tag: '713ed510e7b1a77c66ccfd9caa4d02cd',
          uniqueTag: 'account_main_view_dr',
          id: '713ed510e7b1a77c66ccfd9caa4d02cd',
        },
      ],
      codeName: 'main_view_dr',
      controlStyle: 'DRBAR_ANCHOR_STYLE',
      controlType: 'DRBAR',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'drbar',
      },
      sysPFPluginId: 'drbar_anchor_style',
      modelId: '733ec373734a18f958ea5f7126fe056e',
      modelType: 'PSDEDRBAR',
      name: 'drbar',
      id: 'main_view_dr',
    },
    {
      codeName: 'test_main_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'test_main_view_datainfobar',
    },
    {
      caption: '客户信息',
      codeName: 'test_main_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.account',
      controlParam: {},
      name: 'captionbar',
      id: 'test_main_view_captionbar',
    },
  ],
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionType: 'UIACTION',
                        buttonStyle: 'INFO',
                        buttonType: 'PANELBUTTON',
                        uiactionId: 'editview_exitaction',
                        renderMode: 'BUTTON',
                        tooltip: '退出',
                        capLanguageRes: {
                          lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
                        },
                        caption: '退出',
                        itemStyle: 'INFO',
                        itemType: 'BUTTON',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysImage: {
                          cssClass: 'fa fa-arrow-left',
                          glyph: 'xf060@FontAwesome',
                        },
                        id: 'button_calluilogic',
                      },
                      {
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 70,
                          editorParams: {
                            MAXCOUNT: '1',
                          },
                          editorStyle: 'CRM_IMAGE_UPLOAD',
                          editorType: 'PICTURE_ONE',
                          editorWidth: 70,
                          sysPFPluginId: 'crm_image_upload',
                          predefinedType: 'FIELD_TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_textbox',
                        },
                        allowEmpty: true,
                        caption: '文本框',
                        contentHeight: 70,
                        contentWidth: 70,
                        height: 70,
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          height: 70,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 70,
                          widthMode: 'PX',
                        },
                        width: 70,
                        id: 'field_textbox',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfmajortext',
                        },
                        viewFieldName: 'srfmajortext',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'srfmajortext',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataName: 'srfactiveviewdata',
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'VIEWSESSIONPARAM',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系数据栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'drbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_drbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_exp_content',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    codeName: 'usr0407327281',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主数据通用布局面板（测试）',
    appDataEntityId: 'crmweb.account',
    controlParam: {},
    modelId: '7e73ebca8d5845147395c6058e80b520',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0407327281',
  },
  title: '客户信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: true,
  modelId: '5d8dfd10c2a14320ad54d70434967802',
  modelType: 'PSAPPDEVIEW',
  name: 'accounttest_main_view',
  id: 'crmweb.account_test_main_view',
};
