export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '8bc00602cab51f9c4a44d20a2b033457',
  accUserMode: 2,
  caption: '客户',
  codeName: 'account_pickup_view',
  appDataEntityId: 'crmweb.account',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'crmweb.account_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      caption: '客户',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.account',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.account',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '客户数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'aa869cd534b6d85e94c06da34d5a8963',
  modelType: 'PSAPPDEVIEW',
  name: 'accountPickupView',
  id: 'crmweb.account_pickup_view',
};
