export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_multimode',
  deviewId: 'ce1929cfd44d2d13cd556a5bfae920ed',
  accUserMode: 2,
  caption: '客户',
  codeName: 'account_grid_view_multimode',
  appDataEntityId: 'crmweb.account',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'crmweb.account_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.account_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'crmweb.account_test_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.account_test_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '客户信息',
        refAppViewId: 'crmweb.account_test_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '客户编辑视图',
        refAppViewId: 'crmweb.account_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '客户信息',
        refAppViewId: 'crmweb.account_test_main_view',
        name: 'OPENDATA',
        id: 'opendata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '创建客户',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '创建客户',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_refreshaction',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '刷新',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-refresh',
              glyph: 'xf021@FontAwesome',
            },
            tooltip: '刷新',
            showIcon: true,
            id: 'deuiaction7',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'importdata@account',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '导入客户',
                itemType: 'DEUIACTION',
                tooltip: '导入客户',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5_importdata',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'import@note_attach',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '导入备注',
                itemType: 'DEUIACTION',
                tooltip: '导入备注',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5_import',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysCss: {
              cssName: 'toolbar_group',
            },
            sysImage: {
              cssClass: 'fa fa-chevron-down',
              glyph: 'xf078@FontAwesome',
            },
            showIcon: true,
            id: 'items2',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_multimode_toolbar',
        controlType: 'TOOLBAR',
        logicName: '客户多模式表格视图_工具栏',
        appDataEntityId: 'crmweb.account',
        controlParam: {
          ctrlParams: {
            TELEPORTTAG: '#account_test_tab_search_view-tabtoolbar',
          },
          id: 'toolbar',
        },
        modelId: '3231902f0f379f15c5e8928156a58805',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_multimode_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'create_time',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'account_name',
            excelCaption: '客户名称',
            appDEFieldId: 'account_name',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_edit_view@account',
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  id: 'u525b2e4',
                },
              ],
              appDataEntityId: 'crmweb.account',
              uniqueTag: 'account__Usr0624337740',
              name: '客户敏捷操作列',
              id: 'usr0624337740',
            },
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '客户名称',
            codeName: 'account_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'account_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'phone',
            excelCaption: '电话',
            appDEFieldId: 'phone',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '电话',
            codeName: 'phone',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'phone',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'industry',
            excelCaption: '行业',
            appCodeListId: 'crmweb.crm__industry',
            appDEFieldId: 'industry',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '行业',
            codeName: 'industry',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'industry',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'account_type',
            excelCaption: '客户类型',
            appCodeListId: 'crmweb.crm__account_type',
            appDEFieldId: 'account_type',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '客户类型',
            codeName: 'account_type',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'account_type',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'rating',
            excelCaption: '等级',
            appCodeListId: 'crmweb.crm__rating',
            appDEFieldId: 'rating',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '等级',
            codeName: 'rating',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'rating',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'update_time',
            excelCaption: '更新时间',
            appDEFieldId: 'update_time',
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.UPDATE_TIME',
            },
            caption: '更新时间',
            codeName: 'update_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'update_time',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'owner',
            excelCaption: '所有者',
            appCodeListId: 'crmweb.crm__owner',
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '所有者',
            codeName: 'owner',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'owner',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_name',
          },
          {
            appDEFieldId: 'phone',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'phone',
          },
          {
            appDEFieldId: 'industry',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'industry',
          },
          {
            appDEFieldId: 'account_type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_type',
          },
          {
            appDEFieldId: 'rating',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'rating',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'owner',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'pid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pid',
          },
          {
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        forceFit: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_all',
          appDataEntityId: 'crmweb.account',
          id: 'fetch',
        },
        dedataImportId: 'dataimport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.account',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'create_task@account',
                uiactionTarget: 'MULTIKEY',
                hiddenItem: true,
                valid: true,
                caption: '创建任务',
                itemType: 'DEUIACTION',
                tooltip: '创建任务',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'remove@account',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '删除',
                itemType: 'DEUIACTION',
                tooltip: '删除',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'add_tags@account',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '添加标签',
                    itemType: 'DEUIACTION',
                    tooltip: '添加标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'delete_tags@account',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '移除标签',
                    itemType: 'DEUIACTION',
                    tooltip: '移除标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction3',
                  },
                ],
                valid: true,
                caption: '标签',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '标签',
                showCaption: true,
                showIcon: true,
                id: 'items1',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'batch_update@account',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '批量更新',
                    itemType: 'DEUIACTION',
                    tooltip: '批量更新',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction4',
                  },
                ],
                valid: true,
                caption: '操作',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '操作',
                showCaption: true,
                showIcon: true,
                id: 'items2',
              },
            ],
            codeName: 'grid_view_multimode_grid_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作_工具栏',
            appDataEntityId: 'crmweb.account',
            controlParam: {
              id: 'grid_batchtoolbar',
            },
            modelId: 'af432e3756753bc26f64ce05f8deeccd',
            modelType: 'PSDETOOLBAR',
            name: 'grid_batchtoolbar',
            id: 'grid_view_multimode_grid_batchtoolbar',
          },
        ],
        codeName: 'grid_view_multimode_grid',
        controlStyle: 'NUMBER_GRID',
        controlType: 'GRID',
        logicName: '客户多模式表格视图_表格',
        appDataEntityId: 'crmweb.account',
        controlParam: {
          id: 'grid',
        },
        sysPFPluginId: 'number_grid',
        modelId: 'dae8cfd75c779d3162efaf484950ccc1',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'crmweb.account.grid_view_multimode_grid',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_view_multimode_search_form',
        controlType: 'SEARCHFORM',
        logicName: '客户多模式表格视图_搜索表单',
        appDataEntityId: 'crmweb.account',
        controlParam: {
          id: 'searchform',
        },
        modelId: 'c6eee73397cdcf8dd793df8cb17a0dbb',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.account.grid_view_multimode_search_form',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.account',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '客户',
        codeName: 'grid_view_multimode_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.account',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_multimode_captionbar',
      },
    ],
    codeName: 'usr0415540230',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索内表格视图通用布局',
    appDataEntityId: 'crmweb.account',
    controlParam: {},
    modelId: '539d683107e4178ee9be6197d342453c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0415540230',
  },
  title: '客户',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '160b0ad8e8456183e07e733fe050dbd0',
  modelType: 'PSAPPDEVIEW',
  name: 'accountgrid_view_multimode',
  id: 'crmweb.account_grid_view_multimode',
};
