export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'edit_view',
  deviewId: 'fc92699c8cb7afc8d85a409abd496181',
  accUserMode: 2,
  caption: '客户',
  codeName: 'account_edit_view',
  appDataEntityId: 'crmweb.account',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          buttonStyle: 'INFO',
          noPrivDisplayMode: 2,
          uiactionId: 'editview_exitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
          },
          caption: '取消',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-sign-out',
            glyph: 'xf08b@FontAwesome',
          },
          tooltip: '取消',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.CLOSE',
          },
          showCaption: true,
          id: 'cancel',
        },
        {
          actionLevel: 100,
          buttonStyle: 'INFO',
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandnewaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
          },
          caption: '保存并新建',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'saveAndNew',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode: 'data.id == null',
              triggerType: 'ITEMVISIBLE',
              name: 'showSaveAndNew',
              id: 'showsaveandnew',
            },
          ],
          sysImage: {
            cssClass: 'sx-tb-saveandnew',
          },
          tooltip: '保存并新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
          },
          showCaption: true,
          name: 'saveAndNew',
          id: 'saveandnew',
        },
        {
          actionLevel: 100,
          buttonStyle: 'PRIMARY',
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandexitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'saveAndQuit',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode: 'data.id',
              triggerType: 'ITEMVISIBLE',
              name: 'showSaveAndQuit',
              id: 'showsaveandquit',
            },
          ],
          sysImage: {
            cssClass: 'sx-tb-saveandclose',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
          },
          showCaption: true,
          name: 'saveAndQuit',
          id: 'saveandquit',
        },
        {
          actionLevel: 100,
          buttonStyle: 'PRIMARY',
          noPrivDisplayMode: 2,
          uiactionId: 'saveandopenaccount@account',
          uiactionTarget: 'SINGLEDATA',
          valid: true,
          caption: '保存',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'saveAndOpen',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode: 'data.id == null',
              triggerType: 'ITEMVISIBLE',
              name: 'saveAndOpen',
              id: 'saveandopen',
            },
          ],
          tooltip: '保存',
          showCaption: true,
          name: 'saveAndOpen',
          id: 'saveandopen',
        },
      ],
      xdataControlName: 'form',
      codeName: 'edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '客户编辑视图_工具栏',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '3c87c8b6f6fb24b27c441e07ef577293',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.account',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.account',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.account',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.account',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.account',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.account',
        id: 'update',
      },
      deformItemUpdates: [
        {
          codeName: 'shippingTobilling',
          defiupdateDetails: [
            {
              id: 'billing_street',
            },
            {
              id: 'billing_state',
            },
            {
              id: 'billing_code',
            },
            {
              id: 'billing_city',
            },
            {
              id: 'billing_country',
            },
          ],
          scriptCode:
            'data.billing_street = data.shipping_street\r\ndata.billing_city = data.shipping_city\r\ndata.billing_state = data.shipping_state\r\ndata.billing_code = data.shipping_code\r\ndata.billing_country = data.shipping_country',
          customCode: true,
          showBusyIndicator: true,
          name: '从发货到开单',
          id: 'shippingtobilling',
        },
        {
          codeName: 'billingToshiping',
          defiupdateDetails: [
            {
              id: 'shipping_city',
            },
            {
              id: 'shipping_country',
            },
            {
              id: 'shipping_code',
            },
            {
              id: 'shipping_street',
            },
            {
              id: 'shipping_state',
            },
          ],
          scriptCode:
            'data.shipping_street = data.billing_street\r\ndata.shipping_city = data.billing_city\r\ndata.shipping_state = data.billing_state\r\ndata.shipping_code = data.billing_code\r\ndata.shipping_country = data.billing_country',
          customCode: true,
          showBusyIndicator: true,
          name: '从开单到发货',
          id: 'billingtoshiping',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'record_image',
                  editor: {
                    maxFileCount: 1,
                    editorParams: {
                      MAXCOUNT: '1',
                    },
                    editorType: 'PICTURE_ONE',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'record_lmage',
                  },
                  allowEmpty: true,
                  caption: '客户图片',
                  codeName: 'record_lmage',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 4,
                    colMD: 4,
                    layout: 'TABLE_24COL',
                  },
                  id: 'record_lmage',
                },
              ],
              caption: '客户图片',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'account_number',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'account_number',
                      },
                      allowEmpty: true,
                      caption: '客户编号',
                      codeName: 'account_number',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'account_number',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'account_name',
                      editor: {
                        maxLength: 200,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'account_name',
                      },
                      caption: '客户名称',
                      codeName: 'account_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'account_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'account_type',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__account_type',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'account_type',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '客户类型',
                      codeName: 'account_type',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'account_type',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'account_site',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'account_site',
                      },
                      allowEmpty: true,
                      caption: '客户所在地',
                      codeName: 'account_site',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'account_site',
                    },
                  ],
                  codeName: 'grouppanel7',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel7',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      createDV: 'userid',
                      createDVT: 'SESSION',
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'owner',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__owner',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'owner',
                      },
                      needCodeListConfig: true,
                      caption: '所有者',
                      codeName: 'owner',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'owner',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'p_account_name',
                      editor: {
                        enablePickupView: true,
                        singleSelect: true,
                        pickupAppViewId: 'crmweb.account_pickup_view',
                        handlerType: 'PickupText',
                        appDEACModeId: 'default',
                        appDEDataSetId: 'fetch_not_current',
                        appDataEntityId: 'crmweb.account',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'pid',
                        editorParams: {
                          AC: 'TRUE',
                          PICKUPVIEW: 'TRUE',
                        },
                        editorType: 'PICKER',
                        editorItems: [
                          {
                            id: 'pid',
                          },
                        ],
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'paccount_name',
                      },
                      allowEmpty: true,
                      caption: '父客户',
                      codeName: 'paccount_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'paccount_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'industry',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__industry',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'industry',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '行业',
                      codeName: 'industry',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'industry',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'rating',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__rating',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'rating',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '等级',
                      codeName: 'rating',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'rating',
                    },
                  ],
                  codeName: 'grouppanel8',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel8',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 21,
                      enableCond: 3,
                      itemHeight: 200,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'description',
                      editor: {
                        maxLength: 1048576,
                        showMaxLength: true,
                        editorHeight: 200,
                        editorParams: {
                          HEIGHT: '200',
                        },
                        editorType: 'TEXTAREA_10',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'description',
                      },
                      allowEmpty: true,
                      caption: '描述',
                      codeName: 'description',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 16,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'description',
                    },
                  ],
                  caption: '描述',
                  codeName: 'grouppanel3',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 24,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel3',
                },
              ],
              caption: '客户信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'phone',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'phone',
                      },
                      allowEmpty: true,
                      caption: '电话',
                      codeName: 'phone',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'phone',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'fax',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'fax',
                      },
                      allowEmpty: true,
                      caption: '传真',
                      codeName: 'fax',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'fax',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'annual_revenue',
                      editor: {
                        maxLength: 200,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'annual_revenue',
                      },
                      valueFormat: '￥#,##0',
                      allowEmpty: true,
                      caption: '年收入',
                      codeName: 'annual_revenue',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'annual_revenue',
                    },
                    {
                      dataType: 9,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'employees',
                      editor: {
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'employees',
                      },
                      allowEmpty: true,
                      caption: '员工数',
                      codeName: 'employees',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'employees',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'website',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'website',
                      },
                      allowEmpty: true,
                      caption: '网站',
                      codeName: 'website',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'website',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'ticker_symbol',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'ticker_symbol',
                      },
                      allowEmpty: true,
                      caption: '股票代码',
                      codeName: 'ticker_symbol',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'ticker_symbol',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'ownership',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__ownership',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'ownership',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '公司所有权',
                      codeName: 'ownership',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'ownership',
                    },
                    {
                      dataType: 9,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'sic_code',
                      editor: {
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'sic_code',
                      },
                      allowEmpty: true,
                      caption: 'SIC代码',
                      codeName: 'sic_code',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 12,
                        colMD: 12,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'sic_code',
                    },
                  ],
                  codeName: 'grouppanel6',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 16,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel6',
                },
              ],
              caption: '其他信息',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'billing_street',
                      editor: {
                        maxLength: 250,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'billing_street',
                      },
                      allowEmpty: true,
                      caption: '开单地址-街道',
                      codeName: 'billing_street',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'billing_street',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'billing_city',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'billing_city',
                      },
                      allowEmpty: true,
                      caption: '开单地址-城市',
                      codeName: 'billing_city',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'billing_city',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'billing_state',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'billing_state',
                      },
                      allowEmpty: true,
                      caption: '开单地址-省/市',
                      codeName: 'billing_state',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'billing_state',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'billing_code',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'billing_code',
                      },
                      allowEmpty: true,
                      caption: '开单地址-邮编',
                      codeName: 'billing_code',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'billing_code',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'billing_country',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'billing_country',
                      },
                      allowEmpty: true,
                      caption: '开单地址-国家/地区',
                      codeName: 'billing_country',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'billing_country',
                    },
                  ],
                  codeName: 'grouppanel9',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel9',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'shipping_street',
                      editor: {
                        maxLength: 250,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'shipping_street',
                      },
                      allowEmpty: true,
                      caption: '发货地址-街道',
                      codeName: 'shipping_street',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'shipping_street',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'shipping_city',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'shipping_city',
                      },
                      allowEmpty: true,
                      caption: '发货地址-城市',
                      codeName: 'shipping_city',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'shipping_city',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'shipping_state',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'shipping_state',
                      },
                      allowEmpty: true,
                      caption: '发货地址-省/市',
                      codeName: 'shipping_state',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'shipping_state',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'shipping_code',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'shipping_code',
                      },
                      allowEmpty: true,
                      caption: '发货地址-邮编',
                      codeName: 'shipping_code',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'shipping_code',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'shipping_country',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'shipping_country',
                      },
                      allowEmpty: true,
                      caption: '发货地址-国家/地区',
                      codeName: 'shipping_country',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'shipping_country',
                    },
                  ],
                  codeName: 'grouppanel10',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel10',
                },
                {
                  layout: {
                    align: 'flex-start',
                    dir: 'column',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      actionType: 'FIUPDATE',
                      buttonStyle: 'DEFAULT',
                      deformItemUpdateId: 'billingtoshiping',
                      tooltip: '从开单到发货',
                      uiactionTarget: 'NONE',
                      caption: '从开单到发货',
                      codeName: 'button1',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTON',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'button1',
                    },
                    {
                      actionType: 'FIUPDATE',
                      buttonStyle: 'DEFAULT',
                      deformItemUpdateId: 'shippingtobilling',
                      tooltip: '从发货到开单',
                      uiactionTarget: 'NONE',
                      caption: '从发货到开单',
                      codeName: 'button2',
                      detailStyle: 'DEFAULT',
                      detailType: 'BUTTON',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 130,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'button2',
                    },
                  ],
                  codeName: 'grouppanel4',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  defdgroupLogics: [
                    {
                      logicCat: 'PANELVISIBLE',
                      relatedDetailNames: ['owner'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'EQ',
                          defdname: 'owner',
                          value: '1',
                          logicType: 'SINGLE',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colLG: 8,
                    colMD: 8,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel4',
                },
              ],
              caption: '地址信息',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 190,
              noPrivDisplayMode: 1,
              appDEFieldId: 'pid',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'pid',
              },
              allowEmpty: true,
              hidden: true,
              caption: '父标识',
              codeName: 'pid',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'pid',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 190,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '概览',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'edit_view_form',
      controlType: 'FORM',
      logicName: '编辑_表单',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'form',
      },
      modelId: '46fad87602e1605a7cd17fb8cf9019ad',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.account.edit_view_form',
    },
    {
      codeName: 'edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.account',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view_datainfobar',
    },
    {
      caption: '客户',
      codeName: 'edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.account',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.account',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '客户编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1564028659ba1a3ed16cd0ccdc3cf5b1',
  modelType: 'PSAPPDEVIEW',
  name: 'accountedit_view',
  id: 'crmweb.account_edit_view',
};
