export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'data_view_multimode',
  deviewId: '258a3dd601806a2629a8a42cd6b56d47',
  accUserMode: 2,
  caption: '市场活动',
  codeName: 'campaign_data_view_multimode',
  appDataEntityId: 'crmweb.campaign',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建市场活动',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建市场活动',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'importdata@campaign',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入市场活动',
              itemType: 'DEUIACTION',
              tooltip: '导入市场活动',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_importdata',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'import@note_attach',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入备注',
              itemType: 'DEUIACTION',
              tooltip: '导入备注',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_import',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysCss: {
            cssName: 'toolbar_group',
          },
          sysImage: {
            cssClass: 'fa fa-chevron-down',
            glyph: 'xf078@FontAwesome',
          },
          showIcon: true,
          id: 'items2',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'mgr_tags@campaign',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '管理标签',
              itemType: 'DEUIACTION',
              tooltip: '管理标签',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          valid: true,
          caption: '操作',
          itemType: 'ITEMS',
          tooltip: '操作',
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'dataview',
      codeName: 'data_view_multimode_toolbar',
      controlType: 'TOOLBAR',
      logicName: '市场活动多模式卡片视图_工具栏',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '113d0c07d9aab813b8b64c78ab59493e',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'data_view_multimode_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_view_multimode_search_form',
      controlType: 'SEARCHFORM',
      logicName: '市场活动多模式卡片视图_搜索表单',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {
        id: 'searchform',
      },
      modelId: '4530fcc7292aeeb97d604a2f6a7dee65',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.campaign.data_view_multimode_search_form',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        codeName: 'usr0318649260',
        controlType: 'PANEL',
        logicName: '客户多模式卡片视图_卡片视图_卡片面板',
        appDataEntityId: 'crmweb.campaign',
        controlParam: {},
        modelId: 'dcb0f880a55f69f272a909b0f0d31340',
        modelType: 'PSSYSVIEWPANEL',
        name: 'itemlayoutpanel',
        id: 'crmweb.campaign.usr0318649260',
      },
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      appendDEItems: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.campaign',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'crmweb.campaign',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.campaign',
        id: 'load',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.campaign',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.campaign',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_view_multimode_data_view',
      controlType: 'DATAVIEW',
      logicName: '市场活动多模式卡片视图_卡片视图',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {
        id: 'dataview',
      },
      modelId: '562902312ff28e8e1495a62202eed7ff',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'crmweb.campaign.data_view_multimode_data_view',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '市场活动',
      codeName: 'data_view_multimode_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {},
      name: 'captionbar',
      id: 'data_view_multimode_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.campaign',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '市场活动',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '9a591e3b2c18861ad0629b0d18fc0b67',
  modelType: 'PSAPPDEVIEW',
  name: 'campaigndata_view_multimode',
  id: 'crmweb.campaign_data_view_multimode',
};
