export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'edit_view',
  deviewId: 'e33f685e7a1e3918c3fe9ff8b4d27bad',
  accUserMode: 2,
  caption: '市场活动',
  codeName: 'campaign_edit_view',
  appDataEntityId: 'crmweb.campaign',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_exitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
          },
          caption: '取消',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-sign-out',
            glyph: 'xf08b@FontAwesome',
          },
          tooltip: '取消',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.CLOSE',
          },
          showCaption: true,
          id: 'tbitem1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandnewaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
          },
          caption: '保存并新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'sx-tb-saveandnew',
          },
          tooltip: '保存并新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
          },
          showCaption: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandexitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'sx-tb-saveandclose',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
          },
          showCaption: true,
          name: 'saveAndClose',
          id: 'saveandclose',
        },
      ],
      xdataControlName: 'form',
      codeName: 'edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '主数据编辑',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '6a3def7b7dd36f54dae617818c68e025',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.campaign',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.campaign',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.campaign',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.campaign',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.campaign',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.campaign',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        contentType: 'PLACEHOLDER',
                        id: 'rawitem1',
                      },
                      codeName: 'rawitem1',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'rawitem1',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'campaign_name',
                      editor: {
                        maxLength: 255,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'campaign_name',
                      },
                      caption: '市场活动名称',
                      codeName: 'campaign_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'campaign_name',
                    },
                    {
                      dataType: 5,
                      enableCond: 3,
                      itemWidth: 230,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'start_date',
                      editor: {
                        dateTimeFormat: 'YYYY-MM-DD',
                        editorParams: {
                          TIMEFMT: 'YYYY-MM-DD',
                        },
                        editorType: 'DATEPICKEREX_NOTIME',
                        editorWidth: 100,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'start_date',
                      },
                      valueFormat: 'YYYY-MM-DD',
                      allowEmpty: true,
                      caption: '开始日期',
                      codeName: 'start_date',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'start_date',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'expected_revenue',
                      editor: {
                        maxLength: 200,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'expected_revenue',
                      },
                      allowEmpty: true,
                      caption: '预期收益',
                      codeName: 'expected_revenue',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'expected_revenue',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'actual_cost',
                      editor: {
                        maxLength: 200,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'actual_cost',
                      },
                      allowEmpty: true,
                      caption: '实际成本',
                      codeName: 'actual_cost',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'actual_cost',
                    },
                    {
                      dataType: 1,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'num_sent',
                      editor: {
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'num_sent',
                      },
                      allowEmpty: true,
                      caption: '发出数量',
                      codeName: 'num_sent',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'num_sent',
                    },
                  ],
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel2',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'type',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__campaign_type',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'type',
                      },
                      needCodeListConfig: true,
                      caption: '类型',
                      codeName: 'type',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'type',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'status',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__campaign_status',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'status',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '状态',
                      codeName: 'status',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'status',
                    },
                    {
                      dataType: 5,
                      enableCond: 3,
                      itemWidth: 230,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'end_date',
                      editor: {
                        dateTimeFormat: 'YYYY-MM-DD',
                        editorParams: {
                          TIMEFMT: 'YYYY-MM-DD',
                        },
                        editorType: 'DATEPICKEREX_NOTIME',
                        editorWidth: 100,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'end_date',
                      },
                      valueFormat: 'YYYY-MM-DD',
                      allowEmpty: true,
                      caption: '结束日期',
                      codeName: 'end_date',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'end_date',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'budgeted_cost',
                      editor: {
                        maxLength: 200,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'budgeted_cost',
                      },
                      allowEmpty: true,
                      caption: '预算成本',
                      codeName: 'budgeted_cost',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'budgeted_cost',
                    },
                    {
                      dataType: 1,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'expected_response',
                      editor: {
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'expected_response',
                      },
                      allowEmpty: true,
                      caption: '期望成功率(%)',
                      codeName: 'expected_response',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'expected_response',
                    },
                  ],
                  codeName: 'grouppanel4',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel4',
                },
              ],
              caption: '市场活动信息',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 21,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'description',
                  editor: {
                    maxLength: 32000,
                    showMaxLength: true,
                    editorType: 'TEXTAREA',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'description',
                  },
                  allowEmpty: true,
                  caption: '描述',
                  codeName: 'description',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'description',
                },
              ],
              caption: '描述',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colLG: 16,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '概览',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'edit_view_form',
      controlType: 'FORM',
      logicName: '编辑_表单',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {
        id: 'form',
      },
      modelId: '11e71242519b504f51b1c9a7ecd0370d',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.campaign.edit_view_form',
    },
    {
      codeName: 'edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view_datainfobar',
    },
    {
      caption: '市场活动',
      codeName: 'edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.campaign',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.campaign',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '市场活动编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd2ea52d4350a905e6638ee469eb25963',
  modelType: 'PSAPPDEVIEW',
  name: 'campaignedit_view',
  id: 'crmweb.campaign_edit_view',
};
