export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'edit_view',
  deviewId: '4b6ecbd38f487f0c84ca7012293ec7e3',
  accUserMode: 2,
  caption: '联系人',
  codeName: 'contact_edit_view',
  appDataEntityId: 'crmweb.contact',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_exitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
          },
          caption: '取消',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-sign-out',
            glyph: 'xf08b@FontAwesome',
          },
          tooltip: '取消',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.CLOSE',
          },
          showCaption: true,
          id: 'cancel',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandnewaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
          },
          caption: '保存并新建',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'saveAndNew',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode: 'data.id == null',
              triggerType: 'ITEMVISIBLE',
              name: 'saveAndNew',
              id: 'saveandnew',
            },
          ],
          sysImage: {
            cssClass: 'sx-tb-saveandnew',
          },
          tooltip: '保存并新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
          },
          showCaption: true,
          name: 'saveAndNew',
          id: 'saveandnew',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandexitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'saveAndQuit',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode: 'data.id',
              triggerType: 'ITEMVISIBLE',
              name: 'saveAndQuit',
              id: 'saveandquit',
            },
          ],
          sysImage: {
            cssClass: 'sx-tb-saveandclose',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
          },
          showCaption: true,
          name: 'saveAndQuit',
          id: 'saveandquit',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'saveandopencontact@contact',
          uiactionTarget: 'SINGLEDATA',
          valid: true,
          caption: '保存',
          itemType: 'DEUIACTION',
          controlLogics: [
            {
              itemName: 'saveAndOpen',
              logicTag: 'toolbar',
              logicType: 'SCRIPT',
              scriptCode: 'data.id == null',
              triggerType: 'ITEMVISIBLE',
              name: 'saveAndOpen',
              id: 'saveandopen',
            },
          ],
          tooltip: '保存',
          showCaption: true,
          name: 'saveAndOpen',
          id: 'saveandopen',
        },
      ],
      xdataControlName: 'form',
      codeName: 'edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '联系人编辑视图_工具栏',
      appDataEntityId: 'crmweb.contact',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'e347c372abb6a2d0dea960df01af6591',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.contact',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.contact',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.contact',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.contact',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.contact',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.contact',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'record_image',
                  editor: {
                    maxFileCount: 1,
                    editorParams: {
                      MAXCOUNT: '1',
                    },
                    editorType: 'PICTURE_ONE',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'record_image',
                  },
                  allowEmpty: true,
                  emptyCaption: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.RECORD_IMAGE',
                  },
                  codeName: 'record_image',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'record_image',
                },
              ],
              caption: '联系人图片',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'full_name',
                      editor: {
                        maxLength: 120,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'full_name',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.FULL_NAME',
                      },
                      caption: '名字',
                      codeName: 'full_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'full_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'account_name',
                      editor: {
                        enablePickupView: true,
                        singleSelect: true,
                        pickupAppViewId: 'crmweb.account_pickup_view',
                        handlerType: 'PickupText',
                        appDEACModeId: 'default',
                        appDEDataSetId: 'fetch_all',
                        appDataEntityId: 'crmweb.account',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'account_id',
                        editorParams: {
                          AC: 'TRUE',
                          PICKUPVIEW: 'TRUE',
                        },
                        editorType: 'PICKER',
                        editorItems: [
                          {
                            id: 'account_id',
                          },
                        ],
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'account_name',
                      },
                      allowEmpty: true,
                      caption: '客户名称',
                      codeName: 'account_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'account_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'email',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'email',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.EMAIL',
                      },
                      caption: '电子邮件',
                      codeName: 'email',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'email',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'title',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'title',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.TITLE',
                      },
                      caption: '职位/职称',
                      codeName: 'title',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'title',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'phone',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'phone',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.PHONE',
                      },
                      caption: '电话',
                      codeName: 'phone',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'phone',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'mobile',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'mobile',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MOBILE',
                      },
                      caption: '手机',
                      codeName: 'mobile',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'mobile',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'assistant',
                      editor: {
                        maxLength: 50,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'assistant',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.ASSISTANT',
                      },
                      caption: '助理',
                      codeName: 'assistant',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'assistant',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'asst_phone',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'asst_phone',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.ASST_PHONE',
                      },
                      caption: '助理电话',
                      codeName: 'asst_phone',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'asst_phone',
                    },
                  ],
                  codeName: 'grouppanel4',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel4',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      createDV: 'userid',
                      createDVT: 'SESSION',
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'owner',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__owner',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'owner',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '所有者',
                      codeName: 'owner',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'owner',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'lead_source',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__lead_source',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'lead_source',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.LEAD_SOURCE',
                      },
                      caption: '线索来源',
                      codeName: 'lead_source',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'lead_source',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'department',
                      editor: {
                        maxLength: 50,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'department',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.DEPARTMENT',
                      },
                      caption: '部门',
                      codeName: 'department',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'department',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'home_phone',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'home_phone',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.HOME_PHONE',
                      },
                      caption: '住宅电话',
                      codeName: 'home_phone',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'home_phone',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'fax',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'fax',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.FAX',
                      },
                      caption: '传真',
                      codeName: 'fax',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'fax',
                    },
                    {
                      dataType: 5,
                      enableCond: 3,
                      itemWidth: 230,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'date_of_birth',
                      editor: {
                        dateTimeFormat: 'YYYY-MM-DD',
                        editorParams: {
                          TIMEFMT: 'YYYY-MM-DD',
                        },
                        editorType: 'DATEPICKEREX_NOTIME',
                        editorWidth: 100,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'date_of_birth',
                      },
                      valueFormat: 'YYYY-MM-DD',
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.DATE_OF_BIRTH',
                      },
                      caption: '生日',
                      codeName: 'date_of_birth',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'date_of_birth',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'secondary_email',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'secondary_email',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.SECONDARY_EMAIL',
                      },
                      caption: '备用邮箱',
                      codeName: 'secondary_email',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'secondary_email',
                    },
                  ],
                  codeName: 'grouppanel5',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel5',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 21,
                      enableCond: 3,
                      itemHeight: 200,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'description',
                      editor: {
                        maxLength: 32000,
                        showMaxLength: true,
                        editorHeight: 200,
                        editorParams: {
                          HEIGHT: '200',
                        },
                        editorType: 'TEXTAREA_10',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'description',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.DESCRIPTION',
                      },
                      caption: '描述',
                      codeName: 'description',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 16,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'description',
                    },
                  ],
                  caption: '描述',
                  codeName: 'grouppanel3',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel3',
                },
              ],
              caption: '联系人信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'mailing_street',
                      editor: {
                        maxLength: 250,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'mailing_street',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAILING_STREET',
                      },
                      caption: '邮寄地址-街道',
                      codeName: 'mailing_street',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'mailing_street',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'mailing_city',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'mailing_city',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAILING_CITY',
                      },
                      caption: '邮寄地址-城市',
                      codeName: 'mailing_city',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'mailing_city',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'mailing_state',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'mailing_state',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAILING_STATE',
                      },
                      caption: '邮寄地址-省/市',
                      codeName: 'mailing_state',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'mailing_state',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'mailing_zip',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'mailing_zip',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAILING_ZIP',
                      },
                      caption: '邮寄地址-邮编',
                      codeName: 'mailing_zip',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'mailing_zip',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'mailing_country',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'mailing_country',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.MAILING_COUNTRY',
                      },
                      caption: '邮寄地址-国家/地',
                      codeName: 'mailing_country',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'mailing_country',
                    },
                  ],
                  codeName: 'grouppanel6',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel6',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'other_street',
                      editor: {
                        maxLength: 250,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'other_street',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.OTHER_STREET',
                      },
                      caption: '其它街道',
                      codeName: 'other_street',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'other_street',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'other_city',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'other_city',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.OTHER_CITY',
                      },
                      caption: '其它城市',
                      codeName: 'other_city',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'other_city',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'other_state',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'other_state',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.OTHER_STATE',
                      },
                      caption: '其它省/市',
                      codeName: 'other_state',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'other_state',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'other_zip',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'other_zip',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.OTHER_ZIP',
                      },
                      caption: '其他邮编',
                      codeName: 'other_zip',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'other_zip',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'other_country',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'other_country',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.OTHER_COUNTRY',
                      },
                      caption: '其它国家/地区',
                      codeName: 'other_country',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'other_country',
                    },
                  ],
                  codeName: 'grouppanel7',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel7',
                },
              ],
              caption: '地址信息',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'account_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'account_id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '客户ID',
              codeName: 'account_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'account_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '概览',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'edit_view_form',
      controlType: 'FORM',
      logicName: '编辑_表单',
      appDataEntityId: 'crmweb.contact',
      controlParam: {
        id: 'form',
      },
      modelId: 'e183a6fd1f5e0b1eaa675aaa40762674',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.contact.edit_view_form',
    },
    {
      codeName: 'edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.contact',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'edit_view_datainfobar',
    },
    {
      caption: '联系人',
      codeName: 'edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.contact',
      controlParam: {},
      name: 'captionbar',
      id: 'edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.contact',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '联系人编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '3101bc50f4c39baad16b805c1eb6e70c',
  modelType: 'PSAPPDEVIEW',
  name: 'contactedit_view',
  id: 'crmweb.contact_edit_view',
};
