export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_relation',
  deviewId: '4f010d82bd217324ddd2031d6cefbcf9',
  accUserMode: 2,
  caption: '联系人',
  codeName: 'contact_grid_view_relation',
  appDataEntityId: 'crmweb.contact',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    buttonType: 'PANELBUTTON',
                    uiactionId:
                      'panel_usr0422974089_button_openview_click@contact',
                    renderMode: 'LINK',
                    tooltip: '层级视图',
                    uiactionTarget: 'SINGLEDATA',
                    caption: '层级视图',
                    itemStyle: 'DEFAULT',
                    itemType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'button_openview',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'crmweb.contact_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.contact_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'crmweb.contact_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.contact_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '联系人编辑视图',
        refAppViewId: 'crmweb.contact_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '联系人编辑视图',
        refAppViewId: 'crmweb.contact_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_relation_toolbar',
        controlType: 'TOOLBAR',
        logicName: '联系人嵌入表格视图_工具栏',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '4ca9a83fb0fb4b5bc7bc7e64d3ea0a1e',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_relation_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'full_name',
            excelCaption: '联系人名称',
            appDEFieldId: 'full_name',
            deuiactionId: 'gridview_editaction',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.FULL_NAME',
            },
            caption: '联系人名称',
            codeName: 'full_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'full_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'email',
            excelCaption: '电子邮件',
            appDEFieldId: 'email',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.EMAIL',
            },
            caption: '电子邮件',
            codeName: 'email',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'email',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'phone',
            excelCaption: '电话',
            appDEFieldId: 'phone',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.PHONE',
            },
            caption: '电话',
            codeName: 'phone',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'phone',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'mobile',
            excelCaption: '手机',
            appDEFieldId: 'mobile',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MOBILE',
            },
            caption: '手机',
            codeName: 'mobile',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'mobile',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'fax',
            excelCaption: '传真',
            appDEFieldId: 'fax',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.FAX',
            },
            caption: '传真',
            codeName: 'fax',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'fax',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'full_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'full_name',
          },
          {
            appDEFieldId: 'email',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'email',
          },
          {
            appDEFieldId: 'phone',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'phone',
          },
          {
            appDEFieldId: 'mobile',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'mobile',
          },
          {
            appDEFieldId: 'fax',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'fax',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'account_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_id',
          },
          {
            appDEFieldId: 'full_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        forceFit: true,
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_all',
          appDataEntityId: 'crmweb.contact',
          id: 'fetch',
        },
        dedataImportId: 'dataimport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.contact',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_view_relation_grid',
        controlType: 'GRID',
        logicName: '联系人嵌入表格视图_表格',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          ctrlParams: {
            SHOWMODE: 'MIXIN',
          },
          id: 'grid',
        },
        modelId: '7132affc9ed04336308d525be69b87d3',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'crmweb.contact.grid_view_relation_grid',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_view_relation_search_form',
        controlType: 'SEARCHFORM',
        logicName: '联系人嵌入表格视图_搜索表单',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'searchform',
        },
        modelId: '62b9fd1c0b79cf5f86ac9f4a51bc9001',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.contact.grid_view_relation_search_form',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '联系人',
        codeName: 'grid_view_relation_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.contact',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_relation_captionbar',
      },
    ],
    codeName: 'usr0422974089',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'grid_view_relation表格视图布局',
    appDataEntityId: 'crmweb.contact',
    controlParam: {},
    modelId: '5663c51bb789f2a6c33bcab9c6832426',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0422974089',
  },
  title: '联系人',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a33e82fb2022b66df9c6ce7d1d36b1de',
  modelType: 'PSAPPDEVIEW',
  name: 'contactgrid_view_relation',
  id: 'crmweb.contact_grid_view_relation',
};
