export default {
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_view_relation',
  deviewId: '233392f6d0d230ef3bd6d6ace8c60798',
  accUserMode: 2,
  caption: '联系人',
  codeName: 'contact_list_view_relation',
  appDataEntityId: 'crmweb.contact',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView9',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.contact_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.contact_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.contact_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.contact_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '联系人编辑视图',
      refAppViewId: 'crmweb.contact_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '联系人编辑视图',
      refAppViewId: 'crmweb.contact_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        fieldStates: 1,
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 32,
                          editorParams: {
                            MAXCOUNT: '1',
                            READONLY: 'TRUE',
                          },
                          editorType: 'PICTURE_ONE',
                          editorWidth: 32,
                          predefinedType: 'FIELD_IMAGE',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'record_image',
                        },
                        viewFieldName: 'record_image',
                        allowEmpty: true,
                        caption: '图片(动态)',
                        contentHeight: 32,
                        contentWidth: 32,
                        height: 32,
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          height: 32,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 32,
                          widthMode: 'PX',
                        },
                        width: 32,
                        id: 'record_image',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 32,
                    contentWidth: 32,
                    height: 32,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 32,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      width: 32,
                      widthMode: 'PX',
                    },
                    width: 32,
                    id: 'container',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'full_name',
                        },
                        viewFieldName: 'full_name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingBottom: 'OUTERSMALL',
                        },
                        id: 'full_name',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'email',
                        },
                        viewFieldName: 'email',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingBottom: 'OUTERSMALL',
                        },
                        id: 'email',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'home_phone',
                            },
                            viewFieldName: 'home_phone',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'home_phone',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingBottom: 'OUTERSMALL',
                        },
                        panelItemGroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedItemNames: ['home_phone'],
                            groupOP: 'AND',
                            panelItemLogics: [
                              {
                                condOp: 'ISNOTNULL',
                                dstModelField: 'home_phone',
                                logicType: 'SINGLE',
                                id: '逻辑项',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        id: 'container3',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'phone',
                            },
                            viewFieldName: 'phone',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'phone',
                          },
                        ],
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingBottom: 'OUTERSMALL',
                        },
                        panelItemGroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedItemNames: ['phone'],
                            groupOP: 'AND',
                            panelItemLogics: [
                              {
                                condOp: 'ISNOTNULL',
                                dstModelField: 'phone',
                                logicType: 'SINGLE',
                                id: '逻辑项',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        id: 'container4',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERMEDIUM',
                    },
                    id: 'container1',
                  },
                ],
                layout: {
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container2',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0418477245',
        controlType: 'PANEL',
        logicName: 'List2_列表项面板',
        appDataEntityId: 'crmweb.contact',
        controlParam: {},
        modelId: 'f048c1df0fe5f43a9fd58be6461a717e',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'crmweb.contact.usr0418477245',
      },
      delistDataItems: [
        {
          appDEFieldId: 'home_phone',
          dataType: 25,
          id: 'home_phone',
        },
        {
          appDEFieldId: 'full_name',
          dataType: 25,
          id: 'full_name',
        },
        {
          appDEFieldId: 'email',
          dataType: 25,
          id: 'email',
        },
        {
          appDEFieldId: 'phone',
          dataType: 25,
          id: 'phone',
        },
        {
          appDEFieldId: 'record_image',
          dataType: 25,
          id: 'record_image',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'full_name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'account_id',
          dataType: 25,
          id: 'account_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.contact',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_all',
        appDataEntityId: 'crmweb.contact',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.contact',
        id: 'load',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.contact',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.contact',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_view_relation_list',
      controlType: 'LIST',
      logicName: 'List2',
      appDataEntityId: 'crmweb.contact',
      controlParam: {
        ctrlParams: {
          SHOWMODE: 'MIXIN',
        },
        id: 'list',
      },
      modelId: '049656034576ee56c3604dca4974744e',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'crmweb.contact.list_view_relation_list',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.contact',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '联系人',
      codeName: 'list_view_relation_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.contact',
      controlParam: {},
      name: 'captionbar',
      id: 'list_view_relation_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW9',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.contact',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '联系人',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW9',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5b4f706313a728e7b457a9f27e1f502c',
  modelType: 'PSAPPDEVIEW',
  name: 'contactlist_view_relation',
  id: 'crmweb.contact_list_view_relation',
};
