export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'main_view',
  deviewId: '8ef8244ade25c5ced6bab9e97d87b131',
  accUserMode: 2,
  caption: '联系人信息',
  codeName: 'contact_main_view',
  appDataEntityId: 'crmweb.contact',
  appViewNavContexts: [
    {
      key: 'N_OWNER_ID_EQ',
      value: 'contact',
      name: 'N_OWNER_ID_EQ',
      id: 'n_owner_id_eq',
    },
    {
      key: 'OWNER_ID',
      value: 'contact',
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      key: 'PRINCIPAL_ID',
      value: 'contact',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'OWNER_TYPE',
      value: 'CONTACT',
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'CONTACT',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'contact',
      id: 'n_owner_id_eq',
    },
    {
      key: 'principal_id',
      value: 'contact',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'owner_type',
      value: 'CONTACT',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'principal_type',
      value: 'CONTACT',
      id: 'principal_type',
    },
    {
      key: 'owner_id',
      value: 'contact',
      id: 'owner_id',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionType: 'UIACTION',
                        buttonStyle: 'INFO',
                        buttonType: 'PANELBUTTON',
                        uiactionId: 'editview_exitaction',
                        renderMode: 'BUTTON',
                        tooltip: '退出',
                        capLanguageRes: {
                          lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
                        },
                        caption: '退出',
                        itemStyle: 'INFO',
                        itemType: 'BUTTON',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysImage: {
                          cssClass: 'fa fa-arrow-left',
                          glyph: 'xf060@FontAwesome',
                        },
                        id: 'button_calluilogic',
                      },
                      {
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 70,
                          editorParams: {
                            MAXCOUNT: '1',
                          },
                          editorStyle: 'CRM_IMAGE_UPLOAD',
                          editorType: 'PICTURE_ONE',
                          editorWidth: 70,
                          sysPFPluginId: 'crm_image_upload',
                          predefinedType: 'FIELD_TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_textbox',
                        },
                        allowEmpty: true,
                        caption: '文本框',
                        contentHeight: 70,
                        contentWidth: 70,
                        height: 70,
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          height: 70,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 70,
                          widthMode: 'PX',
                        },
                        width: 70,
                        id: 'field_textbox',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfmajortext',
                        },
                        viewFieldName: 'srfmajortext',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'srfmajortext',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataName: 'srfactiveviewdata',
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'VIEWSESSIONPARAM',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系数据栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'drbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_drbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_exp_content',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView2',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_edit_view@contact',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '编辑',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-edit',
              glyph: 'xf044@FontAwesome',
            },
            tooltip: '编辑',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction4',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'editview_copyaction',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.COPY',
                },
                caption: '复制',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-copy',
                  glyph: 'xf0c5@FontAwesome',
                },
                tooltip: '复制',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.COPY',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'editview_removeandexitaction',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                },
                caption: '删除并关闭',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除并关闭',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-ellipsis-h',
              glyph: 'xf141@FontAwesome',
            },
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_prevrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '上一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-left',
              glyph: 'xf053@FontAwesome',
            },
            tooltip: '上一个记录',
            showIcon: true,
            id: 'deuiaction6',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_nextrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '下一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-right',
              glyph: 'xf054@FontAwesome',
            },
            tooltip: '下一个记录',
            showIcon: true,
            id: 'deuiaction7',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '联系人主数据视图_工具栏',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '258d33e57376e8b47f579ee82650a71c',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.contact',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.contact',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.contact',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.contact',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.contact',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.contact',
          id: 'update',
        },
        infoFormMode: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'record_image',
                    editor: {
                      maxFileCount: 1,
                      editorParams: {
                        MAXCOUNT: '1',
                      },
                      editorType: 'PICTURE_ONE',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'record_image',
                    },
                    allowEmpty: true,
                    emptyCaption: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RECORD_IMAGE',
                    },
                    codeName: 'record_image',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'record_image',
                  },
                ],
                caption: '联系人图片',
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'full_name',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'full_name',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.FULL_NAME',
                        },
                        caption: '名字',
                        codeName: 'full_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'full_name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'account_name',
                        editor: {
                          linkAppViewId: 'crmweb.account_redirect_view',
                          enableLinkView: true,
                          singleSelect: true,
                          appDEACModeId: 'default',
                          appDEDataSetId: 'fetch_all',
                          appDataEntityId: 'crmweb.account',
                          forceSelection: true,
                          valueItemName: 'account_id',
                          editorParams: {
                            EDITABLE: 'FALSE',
                            LINKVIEW: 'TRUE',
                            AC: 'FALSE',
                            TRIGGER: 'FALSE',
                            PICKUPVIEW: 'FALSE',
                          },
                          editorType: 'PICKEREX_LINKONLY',
                          editorItems: [
                            {
                              id: 'account_id',
                            },
                          ],
                          valueType: 'SIMPLE',
                          id: 'account_name',
                        },
                        allowEmpty: true,
                        caption: '客户名称',
                        codeName: 'account_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'account_name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'email',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'email',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.EMAIL',
                        },
                        caption: '电子邮件',
                        codeName: 'email',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'email',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'title',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'title',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.TITLE',
                        },
                        caption: '职位/职称',
                        codeName: 'title',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'title',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'phone',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'phone',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.PHONE',
                        },
                        caption: '电话',
                        codeName: 'phone',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'phone',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'mobile',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'mobile',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MOBILE',
                        },
                        caption: '手机',
                        codeName: 'mobile',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'mobile',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'assistant',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'assistant',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.ASSISTANT',
                        },
                        caption: '助理',
                        codeName: 'assistant',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'assistant',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'asst_phone',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'asst_phone',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.ASST_PHONE',
                        },
                        caption: '助理电话',
                        codeName: 'asst_phone',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'asst_phone',
                      },
                    ],
                    codeName: 'grouppanel4',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 8,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel4',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'owner',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'crmweb.crm__owner',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'owner',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '所有者',
                        codeName: 'owner',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'owner',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'lead_source',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'crmweb.crm__lead_source',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'lead_source',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.LEAD_SOURCE',
                        },
                        caption: '线索来源',
                        codeName: 'lead_source',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'lead_source',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'department',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'department',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DEPARTMENT',
                        },
                        caption: '部门',
                        codeName: 'department',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'department',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'home_phone',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'home_phone',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HOME_PHONE',
                        },
                        caption: '住宅电话',
                        codeName: 'home_phone',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'home_phone',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'fax',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'fax',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.FAX',
                        },
                        caption: '传真',
                        codeName: 'fax',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'fax',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'date_of_birth',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'date_of_birth',
                        },
                        valueFormat: 'YYYY-MM-DD',
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DATE_OF_BIRTH',
                        },
                        caption: '生日',
                        codeName: 'date_of_birth',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'date_of_birth',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'secondary_email',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'secondary_email',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.SECONDARY_EMAIL',
                        },
                        caption: '备用邮箱',
                        codeName: 'secondary_email',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'secondary_email',
                      },
                    ],
                    codeName: 'grouppanel5',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 8,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel5',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 21,
                        enableCond: 3,
                        itemHeight: 200,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'description',
                        editor: {
                          maxLength: 32000,
                          showMaxLength: true,
                          editorHeight: 200,
                          editorParams: {
                            readonly: 'true',
                            HEIGHT: '200',
                          },
                          editorType: 'TEXTAREA_10',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'description',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.DESCRIPTION',
                        },
                        caption: '描述',
                        codeName: 'description',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 16,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        sysCss: {
                          cssName: 'input-readonly',
                        },
                        showCaption: true,
                        id: 'description',
                      },
                    ],
                    caption: '描述',
                    codeName: 'grouppanel3',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel3',
                  },
                ],
                caption: '联系人信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'mailing_street',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'mailing_street',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAILING_STREET',
                        },
                        caption: '邮寄地址-街道',
                        codeName: 'mailing_street',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'mailing_street',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'mailing_city',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'mailing_city',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAILING_CITY',
                        },
                        caption: '邮寄地址-城市',
                        codeName: 'mailing_city',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'mailing_city',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'mailing_state',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'mailing_state',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAILING_STATE',
                        },
                        caption: '邮寄地址-省/市',
                        codeName: 'mailing_state',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'mailing_state',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'mailing_zip',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'mailing_zip',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAILING_ZIP',
                        },
                        caption: '邮寄地址-邮编',
                        codeName: 'mailing_zip',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'mailing_zip',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'mailing_country',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'mailing_country',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.MAILING_COUNTRY',
                        },
                        caption: '邮寄地址-国家/地',
                        codeName: 'mailing_country',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'mailing_country',
                      },
                    ],
                    codeName: 'grouppanel6',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 8,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel6',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'other_street',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'other_street',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.OTHER_STREET',
                        },
                        caption: '其它街道',
                        codeName: 'other_street',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'other_street',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'other_city',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'other_city',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.OTHER_CITY',
                        },
                        caption: '其它城市',
                        codeName: 'other_city',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'other_city',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'other_state',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'other_state',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.OTHER_STATE',
                        },
                        caption: '其它省/市',
                        codeName: 'other_state',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'other_state',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'other_zip',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'other_zip',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.OTHER_ZIP',
                        },
                        caption: '其他邮编',
                        codeName: 'other_zip',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'other_zip',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'other_country',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'other_country',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.OTHER_COUNTRY',
                        },
                        caption: '其它国家/地区',
                        codeName: 'other_country',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'other_country',
                      },
                    ],
                    codeName: 'grouppanel7',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 8,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel7',
                  },
                ],
                caption: '地址信息',
                codeName: 'grouppanel2',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel2',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'account_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'account_id',
                },
                allowEmpty: true,
                hidden: true,
                caption: '客户ID',
                codeName: 'account_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'account_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '概览',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    appViewId: 'crmweb.activitiy_time_line_view',
                    parentDataJO: {
                      srfparentdename: 'CONTACT',
                      SRFPARENTTYPE: 'CUSTOM',
                    },
                    codeName: 'druipart1',
                    detailStyle: 'DEFAULT',
                    detailType: 'DRUIPART',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'druipart1',
                  },
                ],
                caption: '历史信息',
                codeName: 'grouppanel9',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel9',
              },
            ],
            caption: '时间轴',
            codeName: 'formpage2',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage2',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main_view_form',
        controlStyle: 'ANCHOR_STYLE',
        controlType: 'FORM',
        logicName: '联系人主数据视图_表单',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'form',
        },
        sysPFPluginId: 'anchor_style',
        modelId: '28a50b1ec60f35e405447078e84177b8',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'crmweb.contact.main_view_form',
      },
      {
        dedrbarGroups: [
          {
            caption: '详细信息',
            name: '详细信息',
            id: 'drgroup',
          },
        ],
        showTitle: true,
        dataRelationTag: 'main_view_DR',
        editItemCaption: '联系人',
        appCounterRefId: 'f6a36f14cef4818403c3f19d0b5673e9',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'drgroup',
            caption: '附件',
            counterId: 'attachment',
            appViewId: 'crmweb.contact_attachment_view',
            id: 'attachment',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '待办任务',
            counterId: 'not_close',
            appViewId: 'crmweb.schedule_not_close_tab_exp_view9',
            navigateContexts: [
              {
                key: 'OWNER_ID',
                value: 'owner_id',
                name: 'OWNER_ID',
                id: 'owner_id',
              },
              {
                key: 'OWNER_TYPE',
                value: 'owner_type',
                name: 'OWNER_TYPE',
                id: 'owner_type',
              },
            ],
            navigateParams: [
              {
                key: 'owner_id',
                value: 'owner_id',
                id: 'owner_id',
              },
              {
                key: 'owner_type',
                value: 'owner_type',
                id: 'owner_type',
              },
            ],
            id: 'not_close',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '已完成的任务&历史活动',
            counterId: 'taskhisact',
            appViewId: 'crmweb.task_task_act_list_view',
            id: 'taskhisact',
          },
        ],
        uniqueTag: 'contact_main_view__drbar',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'contact_main_view_dr',
              counterType: 'DEDR',
              getAppDEActionId: 'main_view_dr_count',
              appDataEntityId: 'crmweb.contact',
              timer: 60000,
              uniqueTag: 'contact_main_view_dr',
              name: '联系人main_view关系',
              id: 'crmweb.contact_main_view_dr',
            },
            refMode: {
              srfdeid: 'CONTACT',
            },
            tag: 'f6a36f14cef4818403c3f19d0b5673e9',
            uniqueTag: 'contact_main_view_dr',
            id: 'f6a36f14cef4818403c3f19d0b5673e9',
          },
        ],
        codeName: 'main_view_dr',
        controlStyle: 'DRBAR_ANCHOR_STYLE',
        controlType: 'DRBAR',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'drbar_anchor_style',
        modelId: 'f14d953538c5e7d2888bd53b257cb301',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'main_view_dr',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.contact',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.contact',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.contact',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.contact',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.contact',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.contact',
          id: 'update',
        },
        infoFormMode: true,
        formStyle: 'INFOPANEL',
        deformPages: [
          {
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            deformDetails: [
              {
                layout: {
                  dir: 'row',
                  layout: 'FLEX',
                },
                deformDetails: [
                  {
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'grouppanel1',
                  },
                  {
                    layout: {
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'name',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.NAME',
                        },
                        caption: '名称',
                        codeName: 'name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'name',
                      },
                      {
                        layout: {
                          layout: 'FLEX',
                        },
                        codeName: 'grouppanel3',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'grouppanel3',
                      },
                    ],
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'grouppanel2',
                  },
                ],
                caption: '客户基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'mini_form',
        controlType: 'FORM',
        logicName: '主数据小表单',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'miniform',
        },
        modelId: '4858120dda6128cb7a1e5fd4a2d71c24',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'miniform',
        id: 'crmweb.contact.mini_form',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'crmweb.contact',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        caption: '联系人信息',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.contact',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'usr0319628389',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主数据通用布局面板',
    appDataEntityId: 'crmweb.contact',
    controlParam: {},
    modelId: '6169ec687d45a098f7102272c1f7c4ca',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0319628389',
  },
  title: '联系人信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: false,
  modelId: '26078ac4883d58c61e7456f3dd0ff0d3',
  modelType: 'PSAPPDEVIEW',
  name: 'contactmain_view',
  id: 'crmweb.contact_main_view',
};
