export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_multimode',
  deviewId: '5bc288e19b56127119d8e352201f94ec',
  accUserMode: 2,
  caption: '商机',
  codeName: 'deal_grid_view_multimode',
  appDataEntityId: 'crmweb.deal',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'crmweb.deal_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.deal_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            navigateContexts: [
              {
                key: 'PRINCIPAL_NAME',
                value: 'DEAL_NAME',
                name: 'PRINCIPAL_NAME',
                id: 'principal_name',
              },
            ],
            refAppViewId: 'crmweb.deal_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              navigateContexts: [
                {
                  key: 'PRINCIPAL_NAME',
                  value: 'DEAL_NAME',
                  name: 'PRINCIPAL_NAME',
                  id: 'principal_name',
                },
              ],
              refAppViewId: 'crmweb.deal_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        navigateContexts: [
          {
            key: 'PRINCIPAL_NAME',
            value: 'DEAL_NAME',
            name: 'PRINCIPAL_NAME',
            id: 'principal_name',
          },
        ],
        realTitle: '商机信息',
        refAppViewId: 'crmweb.deal_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '商机编辑视图',
        refAppViewId: 'crmweb.deal_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        navigateContexts: [
          {
            key: 'PRINCIPAL_NAME',
            value: 'DEAL_NAME',
            name: 'PRINCIPAL_NAME',
            id: 'principal_name',
          },
        ],
        realTitle: '商机信息',
        refAppViewId: 'crmweb.deal_main_view',
        name: 'OPENDATA',
        id: 'opendata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '创建商机',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '创建商机',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_refreshaction',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '刷新',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-refresh',
              glyph: 'xf021@FontAwesome',
            },
            tooltip: '刷新',
            showIcon: true,
            id: 'deuiaction7',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'importdata@deal',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '导入商机',
                itemType: 'DEUIACTION',
                tooltip: '导入商机',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5_importdata',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'import@note_attach',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '导入备注',
                itemType: 'DEUIACTION',
                tooltip: '导入备注',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5_import',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysCss: {
              cssName: 'toolbar_group',
            },
            sysImage: {
              cssClass: 'fa fa-chevron-down',
              glyph: 'xf078@FontAwesome',
            },
            showIcon: true,
            id: 'items2',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_multimode_toolbar',
        controlType: 'TOOLBAR',
        logicName: '商机多模式表格视图_工具栏',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          ctrlParams: {
            TELEPORTTAG: '#deal_tab_search_view-tabtoolbar',
          },
          id: 'toolbar',
        },
        modelId: 'ad22e355ea9bfec3591ce6e3133d9f21',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_multimode_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        frozenFirstColumn: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'update_time',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'deal_name',
            excelCaption: '商机名称',
            appDEFieldId: 'deal_name',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_edit_view@deal',
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  id: 'ud216885',
                },
              ],
              appDataEntityId: 'crmweb.deal',
              uniqueTag: 'deal__Usr0625262359',
              name: '商机敏捷操作列',
              id: 'usr0625262359',
            },
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '商机名称',
            codeName: 'deal_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 250,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'deal_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'account_name',
            excelCaption: '客户名称',
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '客户名称',
            codeName: 'account_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'account_name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'stage',
            excelCaption: '阶段',
            appCodeListId: 'crmweb.crm__dealstage',
            appDEFieldId: 'stage',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '阶段',
            codeName: 'stage',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'stage',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'amount',
            excelCaption: '预计成交金额',
            appDEFieldId: 'amount',
            unitName: '元',
            valueFormat: '￥#,##0',
            valueType: 'SIMPLE',
            enableUnitName: true,
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '预计成交金额',
            codeName: 'amount',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'amount',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'stage_probability',
            excelCaption: '概率',
            appDEFieldId: 'stage_probability',
            unitName: '%',
            valueType: 'SIMPLE',
            enableUnitName: true,
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '概率',
            codeName: 'stage_probability',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'stage_probability',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'expected_revenue',
            excelCaption: '成交概率金额',
            appDEFieldId: 'expected_revenue',
            unitName: '元',
            valueFormat: '￥#,##0',
            valueType: 'SIMPLE',
            enableUnitName: true,
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '成交概率金额',
            codeName: 'expected_revenue',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'expected_revenue',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'closing_date',
            excelCaption: '预计成交日期',
            appDEFieldId: 'closing_date',
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '预计成交日期',
            codeName: 'closing_date',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'closing_date',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'business_line',
            excelCaption: '业务条线',
            appCodeListId: 'crmweb.crm__business_line',
            appDEFieldId: 'business_line',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '业务条线',
            codeName: 'business_line',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'business_line',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'executors',
            excelCaption: '执行人',
            objectIdField: 'id',
            objectNameField: 'name',
            appDEFieldId: 'executors',
            valueType: 'OBJECTS',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '执行人',
            codeName: 'executors',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            id: 'executors',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'owner',
            excelCaption: '所有者',
            appCodeListId: 'crmweb.crm__owner',
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '所有者',
            codeName: 'owner',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'owner',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'deal_name',
            scriptCode:
              'var newname = data.deal_name ? data.deal_name : \'\'; // 如果 data.subject 为空，则 newname 为 \'\'\r\nvar svgIcon = \'\';\r\n\r\nif (data.last_assess_time) {\r\n    var nowDate = Date.parse(new Date().toISOString().slice(0, 10));\r\n    var accessDate = Date.parse(data.last_assess_time.slice(0, 10));\r\n    var days = (nowDate - accessDate) / (1 * 24 * 60 * 60 * 1000);\r\n    var fireColor = "";\r\n\r\n    if (days <= 7) {\r\n        fireColor = "red";\r\n    } else if (days <= 14) {\r\n        fireColor = "orange";\r\n    } else if (days <= 30) {\r\n        fireColor = "gray";\r\n    }\r\n\r\n    if (fireColor) {\r\n        svgIcon = `<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="${fireColor}" class="bi bi-fire" viewBox="0 0 16 16"><path d="M8 16c3.314 0 6-2 6-5.5 0-1.5-.5-4-2.5-6 .25 1.5-1.25 2-1.25 2C11 4 9 .5 6 0c.357 2 .5 4-2 6-1.25 1-2 2.729-2 4.5C2 14 4.686 16 8 16Zm0-1c-1.657 0-3-1-3-2.75 0-.75.25-2 1.25-3C6.125 10 7 10.5 7 10.5c-.375-1.25.5-3.25 2-3.5-.179 1-.25 2 1 3 .625.5 1 1.364 1 2.25C11 14 9.657 15 8 15Z"/></svg></span>`;\r\n    }\r\n}\r\n\r\nif (!svgIcon) {\r\n    newname = `<span style="margin-left: 16px;"></span>${newname}`;\r\n}\r\n\r\nreturn svgIcon + newname;',
            valueType: 'SIMPLE',
            customCode: true,
            dataType: 25,
            id: 'deal_name',
          },
          {
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_name',
          },
          {
            appDEFieldId: 'stage',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'stage',
          },
          {
            format: '￥#,##0',
            appDEFieldId: 'amount',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'amount',
          },
          {
            appDEFieldId: 'stage_probability',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'stage_probability',
          },
          {
            format: '￥#,##0',
            appDEFieldId: 'expected_revenue',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'expected_revenue',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'closing_date',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'closing_date',
          },
          {
            appDEFieldId: 'business_line',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'business_line',
          },
          {
            appDEFieldId: 'executors',
            valueType: 'OBJECTS',
            dataType: 21,
            id: 'executors',
          },
          {
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'owner',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'last_assess_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'last_assess_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'account_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_id',
          },
          {
            appDEFieldId: 'contact_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'contact_id',
          },
          {
            appDEFieldId: 'deal_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_all',
          appDataEntityId: 'crmweb.deal',
          id: 'fetch',
        },
        dedataImportId: 'dataimport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.deal',
          id: 'remove',
        },
        autoLoad: true,
        enableItemPrivilege: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'create_task@deal',
                uiactionTarget: 'MULTIKEY',
                hiddenItem: true,
                valid: true,
                caption: '创建任务',
                itemType: 'DEUIACTION',
                tooltip: '创建任务',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 1,
                uiactionId: 'remove@deal',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '删除',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'add_tags@deal',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '添加标签',
                    itemType: 'DEUIACTION',
                    tooltip: '添加标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'delete_tags@deal',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '移除标签',
                    itemType: 'DEUIACTION',
                    tooltip: '移除标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction3',
                  },
                ],
                valid: true,
                caption: '标签',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '标签',
                showCaption: true,
                showIcon: true,
                id: 'items1',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'batch_update@deal',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '批量更新',
                    itemType: 'DEUIACTION',
                    tooltip: '批量更新',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction4',
                  },
                ],
                valid: true,
                caption: '操作',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '操作',
                showCaption: true,
                showIcon: true,
                id: 'items2',
              },
            ],
            codeName: 'grid_view_multimode_grid_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作_工具栏',
            appDataEntityId: 'crmweb.deal',
            controlParam: {
              id: 'grid_batchtoolbar',
            },
            modelId: '78ba4971880bc75a4782ba5cd0cc3341',
            modelType: 'PSDETOOLBAR',
            name: 'grid_batchtoolbar',
            id: 'grid_view_multimode_grid_batchtoolbar',
          },
        ],
        codeName: 'grid_view_multimode_grid',
        controlStyle: 'NUMBER_GRID',
        controlType: 'GRID',
        logicName: '商机多模式表格视图_表格',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'grid',
        },
        sysPFPluginId: 'number_grid',
        modelId: 'bb62ae8cb7c2f1adc628d96d749e5342',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'crmweb.deal.grid_view_multimode_grid',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_view_multimode_search_form',
        controlType: 'SEARCHFORM',
        logicName: '商机多模式表格视图_搜索表单',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'searchform',
        },
        modelId: '8c9a462c943fe9cf5b131bcec69808b9',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.deal.grid_view_multimode_search_form',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '商机',
        codeName: 'grid_view_multimode_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.deal',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_multimode_captionbar',
      },
    ],
    codeName: 'usr0415540230',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索内表格视图通用布局',
    appDataEntityId: 'crmweb.deal',
    controlParam: {},
    modelId: '539d683107e4178ee9be6197d342453c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0415540230',
  },
  title: '商机',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '80d0e2670898d19603db70b4b65c194a',
  modelType: 'PSAPPDEVIEW',
  name: 'dealgrid_view_multimode',
  id: 'crmweb.deal_grid_view_multimode',
};
