export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'main_view',
  deviewId: 'a28aa1990cde7a11611b3ef8fab1b08a',
  accUserMode: 2,
  caption: '商机信息',
  codeName: 'deal_main_view',
  appDataEntityId: 'crmweb.deal',
  appViewNavContexts: [
    {
      key: 'N_OWNER_ID_EQ',
      value: 'deal',
      name: 'N_OWNER_ID_EQ',
      id: 'n_owner_id_eq',
    },
    {
      key: 'OWNER_ID',
      value: 'deal',
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      key: 'PRINCIPAL_ID',
      value: 'deal',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'OWNER_TYPE',
      value: 'DEAL',
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'DEAL',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'deal',
      id: 'n_owner_id_eq',
    },
    {
      key: 'principal_id',
      value: 'deal',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'owner_type',
      value: 'DEAL',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'principal_type',
      value: 'DEAL',
      id: 'principal_type',
    },
    {
      key: 'owner_id',
      value: 'deal',
      id: 'owner_id',
    },
  ],
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionType: 'UIACTION',
                        buttonStyle: 'INFO',
                        buttonType: 'PANELBUTTON',
                        uiactionId: 'editview_exitaction',
                        renderMode: 'BUTTON',
                        tooltip: '退出',
                        capLanguageRes: {
                          lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
                        },
                        caption: '退出',
                        itemStyle: 'INFO',
                        itemType: 'BUTTON',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysImage: {
                          cssClass: 'fa fa-arrow-left',
                          glyph: 'xf060@FontAwesome',
                        },
                        id: 'button_calluilogic',
                      },
                      {
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 70,
                          editorParams: {
                            MAXCOUNT: '1',
                          },
                          editorStyle: 'CRM_IMAGE_UPLOAD',
                          editorType: 'PICTURE_ONE',
                          editorWidth: 70,
                          sysPFPluginId: 'crm_image_upload',
                          predefinedType: 'FIELD_TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_textbox',
                        },
                        allowEmpty: true,
                        caption: '文本框',
                        contentHeight: 70,
                        contentWidth: 70,
                        height: 70,
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          height: 70,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 70,
                          widthMode: 'PX',
                        },
                        width: 70,
                        id: 'field_textbox',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfmajortext',
                        },
                        viewFieldName: 'srfmajortext',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'srfmajortext',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataName: 'srfactiveviewdata',
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'VIEWSESSIONPARAM',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系数据栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'drbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_drbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_exp_content',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView2',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_edit_view@deal',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '编辑',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-edit',
              glyph: 'xf044@FontAwesome',
            },
            tooltip: '编辑',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction4',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'editview_copyaction',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.COPY',
                },
                caption: '复制',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-copy',
                  glyph: 'xf0c5@FontAwesome',
                },
                tooltip: '复制',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.COPY',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'editview_removeandexitaction',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                },
                caption: '删除并关闭',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除并关闭',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-ellipsis-h',
              glyph: 'xf141@FontAwesome',
            },
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_prevrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '上一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-left',
              glyph: 'xf053@FontAwesome',
            },
            tooltip: '上一个记录',
            showIcon: true,
            id: 'deuiaction6',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_nextrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '下一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-right',
              glyph: 'xf054@FontAwesome',
            },
            tooltip: '下一个记录',
            showIcon: true,
            id: 'deuiaction7',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '商机主数据视图_工具栏',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '90a7d2ea539306f9f106b055bfff84f1',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        autoSaveMode: 1,
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.deal',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.deal',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.deal',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.deal',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.deal',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.deal',
          id: 'update',
        },
        enableAutoSave: true,
        infoFormMode: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                titleBarCloseMode: 1,
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'deal_name',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'deal_name',
                                },
                                allowEmpty: true,
                                caption: '商机名称',
                                codeName: 'deal_name',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'deal_name',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                ignoreInput: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'business_line',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId: 'crmweb.crm__industry',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'business_line',
                                },
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                caption: '业务条线',
                                codeName: 'business_line',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 16,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'business_line',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                ignoreInput: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'type',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId: 'crmweb.crm__type',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'type',
                                },
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                caption: '类型',
                                codeName: 'type',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 16,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'type',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                ignoreInput: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'lead_source',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId: 'crmweb.crm__lead_source',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'lead_source',
                                },
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                caption: '线索来源',
                                codeName: 'lead_source',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 16,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'lead_source',
                              },
                            ],
                            codeName: 'grouppanel1',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colLG: 12,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'grouppanel1',
                          },
                          {
                            layout: {
                              columnCount: 24,
                              layout: 'TABLE_24COL',
                            },
                            deformDetails: [
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'account_name',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'account_name',
                                },
                                allowEmpty: true,
                                caption: '客户名称',
                                codeName: 'account_name',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'account_name',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                ignoreInput: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'owner',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId: 'crmweb.crm__owner',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'owner',
                                },
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                caption: '所有者',
                                codeName: 'owner',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 16,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'owner',
                              },
                              {
                                dataType: 21,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'executors',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  editorType: 'SPAN',
                                  objectIdField: 'id',
                                  objectNameField: 'name',
                                  valueType: 'OBJECTS',
                                  editable: true,
                                  id: 'executors',
                                },
                                allowEmpty: true,
                                caption: '执行人',
                                codeName: 'executors',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'executors',
                              },
                              {
                                dataType: 25,
                                enableCond: 3,
                                labelPos: 'LEFT',
                                labelWidth: 130,
                                noPrivDisplayMode: 1,
                                appDEFieldId: 'contact_name',
                                editor: {
                                  halign: 'LEFT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  editorType: 'SPAN',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'contact_name',
                                },
                                allowEmpty: true,
                                caption: '联系人',
                                codeName: 'contact_name',
                                detailStyle: 'DEFAULT',
                                detailType: 'FORMITEM',
                                layoutPos: {
                                  colLG: 16,
                                  colMD: 24,
                                  layout: 'TABLE_24COL',
                                },
                                showCaption: true,
                                id: 'contact_name',
                              },
                            ],
                            codeName: 'grouppanel2',
                            detailStyle: 'DEFAULT',
                            detailType: 'GROUPPANEL',
                            layoutPos: {
                              colLG: 12,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'grouppanel2',
                          },
                        ],
                        codeName: 'grouppanel7',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 18,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel7',
                      },
                      {
                        dataType: 21,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'description',
                        editor: {
                          maxLength: 32000,
                          showMaxLength: true,
                          editorParams: {
                            readonly: 'true',
                          },
                          editorType: 'TEXTAREA',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'description',
                        },
                        allowEmpty: true,
                        caption: '描述',
                        codeName: 'description',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 18,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        sysCss: {
                          cssName: 'input-readonly',
                        },
                        showCaption: true,
                        id: 'description',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'account_id',
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'account_id',
                        },
                        allowEmpty: true,
                        hidden: true,
                        caption: '客户ID',
                        codeName: 'account_id',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 16,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'account_id',
                      },
                    ],
                    caption: '商机信息',
                    codeName: 'group1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'group1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 5,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'closing_date',
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'closing_date',
                            },
                            valueFormat: 'YYYY-MM-DD',
                            allowEmpty: true,
                            caption: '预计成交日期',
                            codeName: 'closing_date',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 12,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'closing_date',
                          },
                          {
                            dataType: 6,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'amount',
                            editor: {
                              precision: 2,
                              editorParams: {
                                readonly: 'true',
                              },
                              editorType: 'NUMBER',
                              valueType: 'SIMPLE',
                              editable: true,
                              readOnly: true,
                              id: 'amount',
                            },
                            unitName: '元',
                            valueFormat: '#,##0.00',
                            allowEmpty: true,
                            enableUnitName: true,
                            caption: '金额',
                            codeName: 'amount',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'amount',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            ignoreInput: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'stage',
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              appCodeListId: 'crmweb.crm__dealstage',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'stage',
                            },
                            allowEmpty: true,
                            convertToCodeItemText: true,
                            caption: '阶段',
                            codeName: 'stage',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 12,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'stage',
                          },
                          {
                            dataType: 6,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'stage_probability',
                            editor: {
                              halign: 'LEFT',
                              precision: 2,
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'stage_probability',
                            },
                            unitName: '%',
                            allowEmpty: true,
                            enableUnitName: true,
                            caption: '阶段参考概率',
                            codeName: 'stage_probability',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'stage_probability',
                          },
                          {
                            dataType: 6,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'probability',
                            editor: {
                              editorParams: {
                                readonly: 'true',
                              },
                              editorType: 'NUMBER',
                              valueType: 'SIMPLE',
                              editable: true,
                              readOnly: true,
                              id: 'probability',
                            },
                            unitName: '%',
                            allowEmpty: true,
                            enableUnitName: true,
                            caption: '评估概率',
                            codeName: 'probability',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 6,
                              colMD: 6,
                              layout: 'TABLE_24COL',
                            },
                            sysCss: {
                              cssName: 'itemLeft',
                            },
                            showCaption: true,
                            id: 'probability',
                          },
                          {
                            dataType: 6,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'expected_revenue',
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'expected_revenue',
                            },
                            unitName: '元',
                            allowEmpty: true,
                            enableUnitName: true,
                            caption: '预期收益',
                            codeName: 'expected_revenue',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 12,
                              colMD: 12,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'expected_revenue',
                          },
                          {
                            rawItem: {
                              caption: '预期收益 = 商机金额 * 评估概率',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              sysCss: {
                                cssName: 'dealText',
                              },
                              id: 'rawitem1',
                            },
                            codeName: 'rawitem1',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              colLG: 12,
                              colMD: 12,
                              layout: 'TABLE_24COL',
                            },
                            sysCss: {
                              cssName: 'dealText',
                            },
                            showCaption: true,
                            id: 'rawitem1',
                          },
                        ],
                        codeName: 'grouppanel8',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colLG: 18,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel8',
                      },
                    ],
                    caption: '商机明细',
                    codeName: 'grouppanel3',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'grouppanel3',
                  },
                ],
                caption: '详细信息',
                codeName: 'grouppanel5',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel5',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '概览',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    appViewId: 'crmweb.activitiy_time_line_view',
                    parentDataJO: {
                      srfparentdename: 'DEAL',
                      SRFPARENTTYPE: 'CUSTOM',
                    },
                    codeName: 'druipart1',
                    detailStyle: 'DEFAULT',
                    detailType: 'DRUIPART',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'druipart1',
                  },
                ],
                caption: '历史信息',
                codeName: 'grouppanel4',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel4',
              },
            ],
            caption: '时间轴',
            codeName: 'formpage2',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage2',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        autoLoad: true,
        enableItemPrivilege: true,
        showBusyIndicator: true,
        codeName: 'main_view_form',
        controlStyle: 'ANCHOR_STYLE',
        controlType: 'FORM',
        logicName: '商机主数据视图_表单',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'form',
        },
        sysPFPluginId: 'anchor_style',
        modelId: '964741e2cd3031197ff0afdd48f21d7a',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'crmweb.deal.main_view_form',
      },
      {
        dedrbarGroups: [
          {
            caption: '详细信息',
            name: '详细信息',
            id: 'drgroup',
          },
        ],
        showTitle: true,
        dataRelationTag: 'main_view_DR',
        editItemCaption: '商机',
        appCounterRefId: 'caa3ba51fd97645efb3ccb29143451b6',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'drgroup',
            caption: '附件',
            counterId: 'attachment',
            appViewId: 'crmweb.deal_attachment_view',
            id: 'attachment',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '进展评估',
            counterId: 'note_attach',
            appViewId: 'crmweb.deal_note_attach_view',
            id: 'note_attach',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '待办任务',
            counterId: 'not_close',
            appViewId: 'crmweb.schedule_not_close_tab_exp_view9',
            navigateContexts: [
              {
                key: 'OWNER_ID',
                value: 'owner_id',
                name: 'OWNER_ID',
                id: 'owner_id',
              },
              {
                key: 'OWNER_TYPE',
                value: 'owner_type',
                name: 'OWNER_TYPE',
                id: 'owner_type',
              },
            ],
            navigateParams: [
              {
                key: 'owner_id',
                value: 'owner_id',
                id: 'owner_id',
              },
              {
                key: 'owner_type',
                value: 'owner_type',
                id: 'owner_type',
              },
            ],
            id: 'not_close',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '已完成的任务&历史活动',
            counterId: 'taskhisact',
            appViewId: 'crmweb.deal_task_list_view',
            id: 'taskhisact',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '产品',
            counterId: 'product',
            appViewId: 'crmweb.product_grid_view_relation',
            id: 'product',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '阶段历史',
            counterId: 'dealhis',
            appViewId: 'crmweb.deal_history_deal_deal_his_grid_view',
            id: 'dealhis',
          },
        ],
        uniqueTag: 'deal_main_view__drbar',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'deal_main_view_dr',
              counterType: 'DEDR',
              getAppDEActionId: 'main_view_dr_count',
              appDataEntityId: 'crmweb.deal',
              timer: 60000,
              uniqueTag: 'deal_main_view_dr',
              name: '商机main_view关系',
              id: 'crmweb.deal_main_view_dr',
            },
            refMode: {
              srfdeid: 'DEAL',
            },
            tag: 'caa3ba51fd97645efb3ccb29143451b6',
            uniqueTag: 'deal_main_view_dr',
            id: 'caa3ba51fd97645efb3ccb29143451b6',
          },
        ],
        codeName: 'main_view_dr',
        controlStyle: 'DRBAR_ANCHOR_STYLE',
        controlType: 'DRBAR',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'drbar_anchor_style',
        modelId: '214727585f078b8ab08d42bd82d1aa5e',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'main_view_dr',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        caption: '商机信息',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.deal',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'usr0319628389',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主数据通用布局面板',
    appDataEntityId: 'crmweb.deal',
    controlParam: {},
    modelId: '6169ec687d45a098f7102272c1f7c4ca',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0319628389',
  },
  title: '商机信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: false,
  modelId: '2943db33f47c9dc9ac87724da8a0b14b',
  modelType: 'PSAPPDEVIEW',
  name: 'dealmain_view',
  id: 'crmweb.deal_main_view',
};
