export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_relation',
  deviewId: '487e63049149ae22c5b87a3d1c91b870',
  accUserMode: 2,
  caption: '商机',
  codeName: 'deal_grid_view_relation',
  appDataEntityId: 'crmweb.deal',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.deal_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.deal_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.deal_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.deal_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '商机数据重定向视图',
      refAppViewId: 'crmweb.deal_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '商机编辑视图',
      refAppViewId: 'crmweb.deal_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建商机',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建商机',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'open_edit_view@deal',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          caption: '编辑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-pencil',
            glyph: 'xf040@FontAwesome',
          },
          tooltip: '编辑',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_relation_toolbar',
      controlType: 'TOOLBAR',
      logicName: '商机嵌入表格视图_工具栏',
      appDataEntityId: 'crmweb.deal',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '4b78317b82f68b89b6404bc6acd1c4d4',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_relation_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'DESC',
      minorSortAppDEFieldId: 'closing_date',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'deal_name',
          excelCaption: '商机名称',
          appDEFieldId: 'deal_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '商机名称',
          codeName: 'deal_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'deal_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'account_name',
          excelCaption: '客户名称',
          appDEFieldId: 'account_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '客户名称',
          codeName: 'account_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'account_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'business_line',
          excelCaption: '业务条线',
          appCodeListId: 'crmweb.crm__business_line',
          appDEFieldId: 'business_line',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '业务条线',
          codeName: 'business_line',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'business_line',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'amount',
          excelCaption: '预计成交金额',
          appDEFieldId: 'amount',
          unitName: '元',
          valueFormat: '￥#,##0',
          valueType: 'SIMPLE',
          enableUnitName: true,
          aggMode: 'NONE',
          align: 'RIGHT',
          caption: '预计成交金额',
          codeName: 'amount',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'amount',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'expected_revenue',
          excelCaption: '成交概率金额',
          appDEFieldId: 'expected_revenue',
          unitName: '元',
          valueFormat: '￥#,##0',
          valueType: 'SIMPLE',
          enableUnitName: true,
          aggMode: 'NONE',
          align: 'RIGHT',
          caption: '成交概率金额',
          codeName: 'expected_revenue',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'expected_revenue',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'closing_date',
          excelCaption: '预计成交日期',
          appDEFieldId: 'closing_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '预计成交日期',
          codeName: 'closing_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'closing_date',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'owner',
          excelCaption: '所有者',
          appCodeListId: 'crmweb.crm__owner',
          appDEFieldId: 'owner',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '所有者',
          codeName: 'owner',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'owner',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'stage',
          excelCaption: '阶段标识',
          appCodeListId: 'crmweb.crm__dealstage',
          appDEFieldId: 'stage',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '阶段标识',
          codeName: 'stage',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'stage',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'deal_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'deal_name',
        },
        {
          appDEFieldId: 'account_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'account_name',
        },
        {
          appDEFieldId: 'business_line',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'business_line',
        },
        {
          format: '￥#,##0',
          appDEFieldId: 'amount',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'amount',
        },
        {
          format: '￥#,##0',
          appDEFieldId: 'expected_revenue',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'expected_revenue',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'closing_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'closing_date',
        },
        {
          appDEFieldId: 'owner',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'owner',
        },
        {
          appDEFieldId: 'stage',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'stage',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'account_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'account_id',
        },
        {
          appDEFieldId: 'contact_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'contact_id',
        },
        {
          appDEFieldId: 'deal_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      forceFit: true,
      singleSelect: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_target_relation',
        appDataEntityId: 'crmweb.deal',
        id: 'fetch',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.deal',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_relation_grid',
      controlType: 'GRID',
      logicName: '商机嵌入表格视图_表格',
      appDataEntityId: 'crmweb.deal',
      controlParam: {
        ctrlParams: {
          SHOWMODE: 'MIXIN',
        },
        id: 'grid',
      },
      modelId: '045d3d9bfd244c59f11a449e1869a801',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.deal.grid_view_relation_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'business_line',
              editor: {
                singleSelect: true,
                appCodeListId: 'crmweb.crm__industry',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_business_line_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '业务条线',
              codeName: 'n_business_line_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_business_line_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'owner',
              editor: {
                singleSelect: true,
                appCodeListId: 'crmweb.crm__owner',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_owner_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '所有者',
              codeName: 'n_owner_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_owner_eq',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_relation_search_form',
      controlType: 'SEARCHFORM',
      logicName: '商机嵌入表格视图_搜索表单',
      appDataEntityId: 'crmweb.deal',
      controlParam: {
        id: 'searchform',
      },
      modelId: '28d2c704a7203fb59341e052786299f0',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.deal.grid_view_relation_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.deal',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '商机',
      codeName: 'grid_view_relation_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.deal',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_relation_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.deal',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '商机',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1a6662ffb18150365f0d4adc60bffe14',
  modelType: 'PSAPPDEVIEW',
  name: 'dealgrid_view_relation',
  id: 'crmweb.deal_grid_view_relation',
};
