export default {
  redirectAppViewRefs: [
    {
      realTitle: '阶段历史编辑视图',
      refAppViewId: 'crmweb.deal_history_edit_view',
      name: 'DEAL_HISTORY:EDITVIEW',
      id: 'deal_history:editview',
    },
    {
      realTitle: '阶段历史编辑视图',
      refAppViewId: 'crmweb.deal_history_edit_view',
      name: 'EDITVIEW',
      id: 'editview',
    },
  ],
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: '317b35d5c50f058da59db56320926200',
  accUserMode: 2,
  caption: '阶段历史',
  codeName: 'deal_history_redirect_view',
  appDataEntityId: 'crmweb.deal_history',
  controls: [
    {
      caption: '阶段历史',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.deal_history',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.deal_history',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '阶段历史数据重定向视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: 'c0d60ee3803ed67e7cc419bb71d9bd0e',
  modelType: 'PSAPPDEVIEW',
  name: 'deal_historyRedirectView',
  id: 'crmweb.deal_history_redirect_view',
};
