export default {
  tabLayout: 'TOP',
  expandSearchForm: true,
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_search_view',
  deviewId: '8d316b8c1248545cc87055663d77b628',
  accUserMode: 2,
  caption: '商机',
  codeName: 'deal_tab_search_view',
  appDataEntityId: 'crmweb.deal',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId: 'panel_usr0318980456_button_filter_click@account',
                renderMode: 'BUTTON',
                tooltip: '过滤',
                uiactionTarget: 'SINGLEDATA',
                caption: '过滤',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysImage: {
                  cssClass: 'fa fa-filter',
                  glyph: 'xf0b0@FontAwesome',
                },
                id: 'button_filter',
              },
              {
                rawItem: {
                  caption: '文本内容',
                  halign: 'LEFT',
                  renderMode: 'TEXT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'static_text',
                },
                caption: '文本',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysPFPluginId: 'group_searchbar',
                showCaption: true,
                id: 'static_text',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '关系分页部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabexppanel',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel',
              },
              {
                rawItem: {
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar',
                },
                caption: '工具栏占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingRight: 'INNERMEDIUM',
            },
            id: 'container3',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
              spacingBottom: 'INNERSMALL',
              spacingLeft: 'INNERMEDIUM',
              spacingTop: 'INNERSMALL',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'view_searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupMode: 'SINGLE',
        searchBarFilters: [
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_DEAL_NAME_LIKE',
              stdDataType: 25,
              valueOP: 'LIKE',
              name: 'N_DEAL_NAME_LIKE',
              id: 'n_deal_name_like',
            },
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              name: 'DEAL_NAME',
              id: 'deal_name',
            },
            allowEmpty: true,
            caption: '商机名称',
            itemType: 'FILTER',
            appDEFieldId: 'deal_name',
            name: 'DEAL_NAME',
            id: 'deal_name',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_ACCOUNT_NAME_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_ACCOUNT_NAME_EQ',
              id: 'n_account_name_eq',
            },
            editor: {
              enablePickupView: true,
              singleSelect: true,
              pickupAppViewId: 'crmweb.account_pickup_view',
              appDEACModeId: 'default',
              appDEDataSetId: 'fetch_all',
              appDataEntityId: 'crmweb.account',
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              editorParams: {
                AC: 'TRUE',
                PICKUPVIEW: 'TRUE',
              },
              editorType: 'PICKER',
              valueType: 'SIMPLE',
              editable: true,
              name: 'ACCOUNT_NAME',
              id: 'account_name',
            },
            allowEmpty: true,
            caption: '客户名称',
            itemType: 'FILTER',
            appDEFieldId: 'account_name',
            name: 'ACCOUNT_NAME',
            id: 'account_name',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              editorType: 'NUMBERRANGE',
              editorItems: [
                {
                  name: 'N_AMOUNT_GTANDEQ',
                  id: 'n_amount_gtandeq',
                },
                {
                  name: 'N_AMOUNT_LTANDEQ',
                  id: 'n_amount_ltandeq',
                },
              ],
              valueType: 'SIMPLE',
              editable: true,
              name: 'AMOUNT',
              id: 'amount',
            },
            allowEmpty: true,
            caption: '预计成交金额',
            itemType: 'FILTER',
            name: 'AMOUNT',
            id: 'amount',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_CLOSING_DATE_IN',
              stdDataType: 5,
              valueOP: 'IN',
              name: 'N_CLOSING_DATE_IN',
              id: 'n_closing_date_in',
            },
            editor: {
              editorParams: {
                TIMEFMT: 'YYYY-MM-DD',
              },
              editorType: 'DATERANGE_NOTIME',
              editorItems: [
                {
                  name: 'N_CLOSING_DATE_GT',
                  id: 'n_closing_date_gt',
                },
                {
                  name: 'N_CLOSING_DATE_LT',
                  id: 'n_closing_date_lt',
                },
              ],
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_CLOSING_DATE_IN',
              id: 'n_closing_date_in',
            },
            allowEmpty: true,
            caption: '预计成交日期',
            itemType: 'FILTER',
            appDEFieldId: 'closing_date',
            name: 'N_CLOSING_DATE_IN',
            id: 'n_closing_date_in',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_BUSINESS_LINE_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_BUSINESS_LINE_EQ',
              id: 'n_business_line_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__industry',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'BUSINESS_LINE',
              id: 'business_line',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '业务条线',
            itemType: 'FILTER',
            appDEFieldId: 'business_line',
            name: 'BUSINESS_LINE',
            id: 'business_line',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_TYPE_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_TYPE_EQ',
              id: 'n_type_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__type',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'TYPE',
              id: 'type',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '类型',
            itemType: 'FILTER',
            appDEFieldId: 'type',
            name: 'TYPE',
            id: 'type',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_LEAD_SOURCE_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_LEAD_SOURCE_EQ',
              id: 'n_lead_source_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__lead_source',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'LEAD_SOURCE',
              id: 'lead_source',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '线索来源',
            itemType: 'FILTER',
            appDEFieldId: 'lead_source',
            name: 'LEAD_SOURCE',
            id: 'lead_source',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_GT',
              stdDataType: 6,
              valueOP: 'GT',
              name: 'N_AMOUNT_GT',
              id: 'n_amount_gt',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_GT',
              id: 'n_amount_gt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '金额(>)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_GT',
            id: 'n_amount_gt',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_LT',
              stdDataType: 6,
              valueOP: 'LT',
              name: 'N_AMOUNT_LT',
              id: 'n_amount_lt',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_LT',
              id: 'n_amount_lt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '金额(<)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_LT',
            id: 'n_amount_lt',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_CLOSING_DATE_GTANDEQ',
              stdDataType: 5,
              valueOP: 'GTANDEQ',
              name: 'N_CLOSING_DATE_GTANDEQ',
              id: 'n_closing_date_gtandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_CLOSING_DATE_GT',
              id: 'n_closing_date_gt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '预计成交日期(>=)',
            itemType: 'FILTER',
            appDEFieldId: 'closing_date',
            name: 'N_CLOSING_DATE_GT',
            id: 'n_closing_date_gt',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_CLOSING_DATE_LTANDEQ',
              stdDataType: 5,
              valueOP: 'LTANDEQ',
              name: 'N_CLOSING_DATE_LTANDEQ',
              id: 'n_closing_date_ltandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_CLOSING_DATE_LT',
              id: 'n_closing_date_lt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '预计成交日期(<=)',
            itemType: 'FILTER',
            appDEFieldId: 'closing_date',
            name: 'N_CLOSING_DATE_LT',
            id: 'n_closing_date_lt',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_OWNER_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_OWNER_EQ',
              id: 'n_owner_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__owner',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'OWNER',
              id: 'owner',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '所有者',
            itemType: 'FILTER',
            appDEFieldId: 'owner',
            name: 'OWNER',
            id: 'owner',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__dealstage',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'STAGE',
              id: 'stage',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '商机阶段',
            itemType: 'FILTER',
            appDEFieldId: 'stage',
            name: 'STAGE',
            id: 'stage',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_GTANDEQ',
              stdDataType: 6,
              valueOP: 'GTANDEQ',
              name: 'N_AMOUNT_GTANDEQ',
              id: 'n_amount_gtandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_GTANDEQ',
              id: 'n_amount_gtandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '金额(>=)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_GTANDEQ',
            id: 'n_amount_gtandeq',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_LTANDEQ',
              stdDataType: 6,
              valueOP: 'LTANDEQ',
              name: 'N_AMOUNT_LTANDEQ',
              id: 'n_amount_ltandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_LTANDEQ',
              id: 'n_amount_ltandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '金额(<=)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_LTANDEQ',
            id: 'n_amount_ltandeq',
          },
        ],
        searchBarGroups: [
          {
            caption: '所有商机',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'all',
          },
          {
            defaultGroup: true,
            caption: '进行中',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"OR","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"stage","condop":"EQ","value":"10"},{"condtype":"DEFIELD","fieldname":"stage","condop":"EQ","value":"20"},{"condtype":"DEFIELD","fieldname":"stage","condop":"EQ","value":"30"},{"condtype":"DEFIELD","fieldname":"stage","condop":"EQ","value":"40"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'toward',
          },
          {
            caption: '成交关闭',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"stage","condop":"EQ","value":"50"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            name: 'ClosingtheDeal',
            id: 'closingthedeal',
          },
          {
            caption: '失败关闭',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"stage","condop":"EQ","value":"60"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            name: 'ClosingDuetoFailure',
            id: 'closingduetofailure',
          },
          {
            caption: '挂起',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"stage","condop":"EQ","value":"70"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            name: 'Suspending',
            id: 'suspending',
          },
        ],
        quickSearchMode: 1,
        enableFilter: true,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'searchbar',
        controlStyle: 'FILTER_SEARCHBAR',
        controlType: 'SEARCHBAR',
        logicName: '默认搜索栏',
        appDataEntityId: 'crmweb.deal',
        controlParam: {
          id: 'searchbar',
        },
        sysPFPluginId: 'filter_searchbar',
        modelId: 'ebdc6887517f29b20bd6d726d560fa02',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'crmweb.deal.searchbar',
      },
      {
        tabExpPageIds: ['grid', 'data_view', 'list'],
        tabLayout: 'TOP',
        uniqueTag: 'deal_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '商机',
            refAppViewId: 'crmweb.deal_grid_view_multimode',
            name: 'EXPITEM:grid',
            id: 'expitem:grid',
          },
          {
            realTitle: '商机',
            refAppViewId: 'crmweb.deal_data_view_multimode',
            name: 'EXPITEM:data_view',
            id: 'expitem:data_view',
          },
          {
            realTitle: '商机',
            refAppViewId: 'crmweb.deal_list_view_multimode',
            name: 'EXPITEM:list',
            id: 'expitem:list',
          },
        ],
        controls: [
          {
            sysImage: {
              cssClass: 'fa fa-table',
              glyph: 'xf0ce@FontAwesome',
            },
            caption: '表格视图',
            embeddedAppDEViewId: 'crmweb.deal_grid_view_multimode',
            codeName: 'tab_search_view_grid',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.deal',
            controlParam: {
              id: 'grid',
            },
            modelId: '524e4ce2ce79415f5c6ba3a74d12ce7e_grid',
            modelType: 'PSVIEWPANEL',
            name: 'grid',
            id: 'tab_search_view_grid',
          },
          {
            sysImage: {
              cssClass: 'fa fa-th-large',
              glyph: 'xf009@FontAwesome',
            },
            caption: '平铺视图',
            embeddedAppDEViewId: 'crmweb.deal_data_view_multimode',
            codeName: 'tab_search_view_data_view',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.deal',
            controlParam: {
              id: 'data_view',
            },
            modelId: '524e4ce2ce79415f5c6ba3a74d12ce7e_data_view',
            modelType: 'PSVIEWPANEL',
            name: 'data_view',
            id: 'tab_search_view_data_view',
          },
          {
            sysImage: {
              cssClass: 'fa fa-list',
              glyph: 'xf03a@FontAwesome',
            },
            caption: '列表视图',
            embeddedAppDEViewId: 'crmweb.deal_list_view_multimode',
            codeName: 'tab_search_view_list',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.deal',
            controlParam: {
              id: 'list',
            },
            modelId: '524e4ce2ce79415f5c6ba3a74d12ce7e_list',
            modelType: 'PSVIEWPANEL',
            name: 'list',
            id: 'tab_search_view_list',
          },
        ],
        codeName: 'tab_search_view_tabexppanel',
        controlStyle: 'TABEXPPANEL_DROPDOWN',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'crmweb.deal',
        controlParam: {},
        sysPFPluginId: 'tabexppanel_dropdown',
        modelId: '524e4ce2ce79415f5c6ba3a74d12ce7e_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'tab_search_view_tabexppanel',
      },
      {
        caption: '商机',
        codeName: 'tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.deal',
        controlParam: {},
        name: 'captionbar',
        id: 'tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0318980456',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索通用布局',
    appDataEntityId: 'crmweb.deal',
    controlParam: {},
    modelId: 'f9a64be769ab83bfc4ff869c38a9192b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0318980456',
  },
  title: '商机',
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '524e4ce2ce79415f5c6ba3a74d12ce7e',
  modelType: 'PSAPPDEVIEW',
  name: 'dealtab_search_view',
  id: 'crmweb.deal_tab_search_view',
};
