export default {
  enableRowEdit: true,
  rowEditDefault: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view',
  deviewId: '183b8d61c8a19ad0cfa9d2eb844e70d5',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.DEAL_STAGE',
  },
  caption: '阶段管理',
  codeName: 'deal_stage_grid_view',
  appDataEntityId: 'crmweb.deal_stage',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.deal_stage_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.deal_stage_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.deal_stage_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.deal_stage_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '阶段维护',
      refAppViewId: 'crmweb.deal_stage_edit_view',
      name: 'OPENDATA',
      id: 'opendata',
    },
    {
      realTitle: '阶段维护',
      refAppViewId: 'crmweb.deal_stage_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '阶段维护',
      refAppViewId: 'crmweb.deal_stage_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newrowaction',
          valid: true,
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '新建',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_removeaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.REMOVE',
          },
          caption: '删除',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.REMOVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '阶段管理_工具栏',
      appDataEntityId: 'crmweb.deal_stage',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'c275fc141d03c69f4c3e74e3d820f784',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '阶段名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '阶段名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'probability',
          excelCaption: '默认阶段成交概率（%）',
          appDEFieldId: 'probability',
          unitName: '%',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          enableUnitName: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '默认阶段成交概率（%）',
          codeName: 'probability',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          id: 'probability',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'probability',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'probability',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '阶段名称',
          codeName: 'name',
          enableCond: 3,
          appDEFieldId: 'name',
          editor: {
            maxLength: 200,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'name',
          },
          allowEmpty: true,
          id: 'name',
        },
        {
          caption: '默认阶段成交概率（%）',
          codeName: 'probability',
          createDV: '0',
          enableCond: 3,
          appDEFieldId: 'probability',
          editor: {
            precision: 2,
            editorType: 'NUMBER',
            valueType: 'SIMPLE',
            editable: true,
            id: 'probability',
          },
          unitName: '%',
          updateDV: '0',
          allowEmpty: true,
          enableUnitName: true,
          id: 'probability',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      enableRowEdit: true,
      enableRowNew: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.deal_stage',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'crmweb.deal_stage',
        id: 'fetch',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.deal_stage',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.deal_stage',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.deal_stage',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.deal_stage',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_grid',
      controlType: 'GRID',
      logicName: '阶段管理_表格',
      appDataEntityId: 'crmweb.deal_stage',
      controlParam: {
        id: 'grid',
      },
      modelId: '4634a4187e1341da4528aff68f08fb53',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.deal_stage.grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '阶段管理_搜索表单',
      appDataEntityId: 'crmweb.deal_stage',
      controlParam: {
        id: 'searchform',
      },
      modelId: '441e5a276fcbb46a64108ee037333355',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.deal_stage.grid_view_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.deal_stage',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.DEAL_STAGE',
      },
      caption: '阶段管理',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.deal_stage',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.deal_stage',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '阶段管理',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '7b5ee2ab903532e430701a0542525bf7',
  modelType: 'PSAPPDEVIEW',
  name: 'deal_stagegrid_view',
  id: 'crmweb.deal_stage_grid_view',
};
