export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_multimode',
  deviewId: 'fb3b73f452410e2eec73c2c66ad93051',
  accUserMode: 2,
  caption: '发货单',
  codeName: 'invoice_grid_view_multimode',
  appDataEntityId: 'crmweb.invoice',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'crmweb.invoice_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.invoice_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'crmweb.invoice_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.invoice_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '发货单信息',
        refAppViewId: 'crmweb.invoice_main_view',
        name: 'OPENDATA',
        id: 'opendata',
      },
      {
        realTitle: '发货单信息',
        refAppViewId: 'crmweb.invoice_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '发货单编辑视图',
        refAppViewId: 'crmweb.invoice_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '创建发货单',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '创建发货单',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'importdata@invoice',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '导入发货单',
                itemType: 'DEUIACTION',
                tooltip: '导入发货单',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5_importdata',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'import@note_attach',
                uiactionTarget: 'NONE',
                valid: true,
                caption: '导入备注',
                itemType: 'DEUIACTION',
                tooltip: '导入备注',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5_import',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysCss: {
              cssName: 'toolbar_group',
            },
            sysImage: {
              cssClass: 'fa fa-chevron-down',
              glyph: 'xf078@FontAwesome',
            },
            showIcon: true,
            id: 'items2',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_multimode_toolbar',
        controlType: 'TOOLBAR',
        logicName: '发货单多模式表格视图_工具栏',
        appDataEntityId: 'crmweb.invoice',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'd047487f431b935f3b9ffab72d67d79c',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_multimode_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'crmweb.invoice',
          id: 'fetch',
        },
        dedataImportId: 'dataimport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.invoice',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'create_task@invoice',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '创建任务',
                itemType: 'DEUIACTION',
                tooltip: '创建任务',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'add_tags@invoice',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '添加标签',
                    itemType: 'DEUIACTION',
                    tooltip: '添加标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'delete_tags@invoice',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '移除标签',
                    itemType: 'DEUIACTION',
                    tooltip: '移除标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction3',
                  },
                ],
                valid: true,
                caption: '标签',
                itemType: 'ITEMS',
                tooltip: '标签',
                showCaption: true,
                showIcon: true,
                id: 'items1',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'batch_update@invoice',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '批量更新',
                    itemType: 'DEUIACTION',
                    tooltip: '批量更新',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction4',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'remove@invoice',
                    uiactionTarget: 'MULTIKEY',
                    valid: true,
                    caption: '删除',
                    itemType: 'DEUIACTION',
                    tooltip: '删除',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction5',
                  },
                ],
                valid: true,
                caption: '操作',
                itemType: 'ITEMS',
                tooltip: '操作',
                showCaption: true,
                showIcon: true,
                id: 'items2',
              },
            ],
            codeName: 'grid_view_multimode_grid_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作_工具栏',
            appDataEntityId: 'crmweb.invoice',
            controlParam: {
              id: 'grid_batchtoolbar',
            },
            modelId: '559901577b02ee4d157cd9e9bde7ba34',
            modelType: 'PSDETOOLBAR',
            name: 'grid_batchtoolbar',
            id: 'grid_view_multimode_grid_batchtoolbar',
          },
        ],
        codeName: 'grid_view_multimode_grid',
        controlType: 'GRID',
        logicName: '发货单多模式表格视图_表格',
        appDataEntityId: 'crmweb.invoice',
        controlParam: {
          id: 'grid',
        },
        modelId: 'a1e81903fdacd6528fc471313d875420',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'crmweb.invoice.grid_view_multimode_grid',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'grid_view_multimode_search_form',
        controlType: 'SEARCHFORM',
        logicName: '发货单多模式表格视图_搜索表单',
        appDataEntityId: 'crmweb.invoice',
        controlParam: {
          id: 'searchform',
        },
        modelId: '5418225e93c65603aee7139965473f14',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.invoice.grid_view_multimode_search_form',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.invoice',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '发货单',
        codeName: 'grid_view_multimode_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.invoice',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_multimode_captionbar',
      },
    ],
    codeName: 'usr0415540230',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索内表格视图通用布局',
    appDataEntityId: 'crmweb.invoice',
    controlParam: {},
    modelId: '539d683107e4178ee9be6197d342453c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0415540230',
  },
  title: '发货单',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '5efeaf348e4556e220e0e3dce6bb9da7',
  modelType: 'PSAPPDEVIEW',
  name: 'invoicegrid_view_multimode',
  id: 'crmweb.invoice_grid_view_multimode',
};
