export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_view_multimode',
  deviewId: '8ea4f2080d9032ffd0c21441bcf78cbc',
  accUserMode: 2,
  caption: '线索',
  codeName: 'lead_list_view_multimode',
  appDataEntityId: 'crmweb.lead',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.lead_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.lead_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.lead_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.lead_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '线索编辑视图',
      refAppViewId: 'crmweb.lead_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '线索编辑视图',
      refAppViewId: 'crmweb.lead_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建线索',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建线索',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'importdata@lead',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入线索',
              itemType: 'DEUIACTION',
              tooltip: '导入线索',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_importdata',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'import@note_attach',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入备注',
              itemType: 'DEUIACTION',
              tooltip: '导入备注',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_import',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysCss: {
            cssName: 'toolbar_group',
          },
          sysImage: {
            cssClass: 'fa fa-chevron-down',
            glyph: 'xf078@FontAwesome',
          },
          showIcon: true,
          id: 'items2',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'mgr_tags@lead',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '管理标签',
              itemType: 'DEUIACTION',
              tooltip: '管理标签',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          valid: true,
          caption: '操作',
          itemType: 'ITEMS',
          tooltip: '操作',
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'list',
      codeName: 'list_view_multimode_toolbar',
      controlType: 'TOOLBAR',
      logicName: '线索多模式列表视图_工具栏',
      appDataEntityId: 'crmweb.lead',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '9ab498ffce1c067073a56a0ec7e06d38',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'list_view_multimode_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_view_multimode_search_form',
      controlType: 'SEARCHFORM',
      logicName: '线索多模式列表视图_搜索表单',
      appDataEntityId: 'crmweb.lead',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'a8459ab0c6b028c86cf0c49e61e57553',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.lead.list_view_multimode_search_form',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        codeName: 'usr0318595478',
        controlType: 'PANEL',
        logicName: 'List_列表项面板',
        appDataEntityId: 'crmweb.lead',
        controlParam: {},
        modelId: '620986d66886be969433087b342c3a81',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'crmweb.lead.usr0318595478',
      },
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'subject',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'account_id',
          dataType: 25,
          id: 'account_id',
        },
        {
          appDEFieldId: 'pid',
          dataType: 25,
          id: 'pid',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.lead',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'crmweb.lead',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.lead',
        id: 'load',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.lead',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.lead',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_view_multimode_list',
      controlType: 'LIST',
      logicName: 'List',
      appDataEntityId: 'crmweb.lead',
      controlParam: {
        id: 'list',
      },
      modelId: '70c8a7c416fef16d4210f7a04efa2fed',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'crmweb.lead.list_view_multimode_list',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.lead',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '线索',
      codeName: 'list_view_multimode_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.lead',
      controlParam: {},
      name: 'captionbar',
      id: 'list_view_multimode_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.lead',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '线索',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '57e322e8f25d1ea93c453aa33fcb0f4b',
  modelType: 'PSAPPDEVIEW',
  name: 'leadlist_view_multimode',
  id: 'crmweb.lead_list_view_multimode',
};
