export default {
  gridRowActiveMode: 2,
  loadDefault: true,
  deviewCodeName: 'tree_grid_view',
  deviewId: 'cd49aff35643c7223dbea665e31cb2b2',
  accUserMode: 2,
  caption: '线索树表格视图',
  codeName: 'lead_tree_grid_view',
  appDataEntityId: 'crmweb.lead',
  appViewNavParams: [
    {
      rawValue: true,
      key: 'srfshowmode',
      value: 'tree',
      id: 'srfshowmode',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '树表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'treegrid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'crmweb.lead_lead_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.lead_lead_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            navigateContexts: [
              {
                key: 'PRINCIPAL_NAME',
                value: 'SUBJECT',
                name: 'PRINCIPAL_NAME',
                id: 'principal_name',
              },
            ],
            refAppViewId: 'crmweb.lead_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              navigateContexts: [
                {
                  key: 'PRINCIPAL_NAME',
                  value: 'SUBJECT',
                  name: 'PRINCIPAL_NAME',
                  id: 'principal_name',
                },
              ],
              refAppViewId: 'crmweb.lead_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '线索编辑视图',
        refAppViewId: 'crmweb.lead_lead_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        navigateContexts: [
          {
            key: 'PRINCIPAL_NAME',
            value: 'SUBJECT',
            name: 'PRINCIPAL_NAME',
            id: 'principal_name',
          },
        ],
        realTitle: '线索信息',
        refAppViewId: 'crmweb.lead_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '创建线索',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '创建线索',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_refreshaction',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '刷新',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-refresh',
              glyph: 'xf021@FontAwesome',
            },
            tooltip: '刷新',
            showIcon: true,
            id: 'deuiaction7',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'createsublead@lead',
                uiactionTarget: 'SINGLEDATA',
                valid: true,
                caption: '创建子线索',
                itemType: 'DEUIACTION',
                tooltip: '创建子线索',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'leadtodeal@lead',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                caption: '线索转商机',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-retweet',
                  glyph: 'xf079@FontAwesome',
                },
                tooltip: '线索转商机',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction8',
              },
            ],
            valid: true,
            caption: '操作',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-chevron-down',
              glyph: 'xf078@FontAwesome',
            },
            tooltip: '操作',
            showIcon: true,
            id: 'items1',
          },
        ],
        codeName: 'tree_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '线索多模式表格视图_工具栏',
        appDataEntityId: 'crmweb.lead',
        controlParam: {
          ctrlParams: {
            TELEPORTTAG: '#lead_tab_search_view-tabtoolbar',
          },
          id: 'toolbar',
        },
        modelId: '6df70e7c080a0534ea6a6e73111fb074',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'tree_grid_view_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_grid_view_search_form',
        controlType: 'SEARCHFORM',
        logicName: '线索树表格视图_搜索表单',
        appDataEntityId: 'crmweb.lead',
        controlParam: {
          id: 'searchform',
        },
        modelId: 'bd22c91c5d7763c1fcfef764939e3101',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.lead.tree_grid_view_search_form',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        gridStyle: 'TREEGRID',
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'update_time',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'subject',
            excelCaption: '主题',
            appDEFieldId: 'subject',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_edit_view@lead',
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  id: 'u5c332bf',
                },
              ],
              appDataEntityId: 'crmweb.lead',
              uniqueTag: 'lead__Usr0624110139',
              name: '线索敏捷操作列',
              id: 'usr0624110139',
            },
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.SUBJECT',
            },
            caption: '主题',
            codeName: 'subject',
            columnType: 'DEFTREEGRIDCOLUMN',
            hideMode: 3,
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'subject',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'account_name',
            excelCaption: '客户名称',
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '客户名称',
            codeName: 'account_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'PX',
            enableSort: true,
            id: 'account_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'mobile',
            excelCaption: '手机',
            appDEFieldId: 'mobile',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.MOBILE',
            },
            caption: '手机',
            codeName: 'mobile',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'mobile',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'lead_status',
            excelCaption: '线索状态',
            appCodeListId: 'crmweb.crm__lead_status',
            appDEFieldId: 'lead_status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.LEAD_STATUS',
            },
            caption: '线索状态',
            codeName: 'lead_status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'lead_status',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'executors',
            excelCaption: '跟踪人',
            objectIdField: 'id',
            objectNameField: 'name',
            appDEFieldId: 'executors',
            valueType: 'OBJECTS',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '跟踪人',
            codeName: 'executors',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            id: 'executors',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'owner',
            excelCaption: '所有者',
            appCodeListId: 'crmweb.crm__owner',
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '所有者',
            codeName: 'owner',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'owner',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'pid',
            excelCaption: '父线索标识',
            appDEFieldId: 'pid',
            treeColumnMode: 4,
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '父线索标识',
            codeName: 'pid',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'pid',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'pname',
            excelCaption: '父线索',
            appDEFieldId: 'pname',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '父线索',
            codeName: 'pname',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'pname',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'id',
            excelCaption: '标识',
            appDEFieldId: 'id',
            treeColumnMode: 2,
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.ID',
            },
            caption: '标识',
            codeName: 'id',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'update_time',
            excelCaption: '更新时间',
            appDEFieldId: 'update_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.UPDATE_TIME',
            },
            caption: '更新时间',
            codeName: 'update_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'update_time',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'account_id',
            excelCaption: '客户标识',
            appDEFieldId: 'account_id',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '客户标识',
            codeName: 'account_id',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'account_id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'last_assess_time',
            excelCaption: '最近评估时间',
            appDEFieldId: 'last_assess_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '最近评估时间',
            codeName: 'last_assess_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'last_assess_time',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'subject',
            scriptCode:
              'var newname = data.subject ? data.subject : \'\'; // 如果 data.subject 为空，则 newname 为 \'\'\r\nvar svgIcon = \'\';\r\n\r\nif (data.last_assess_time) {\r\n    var nowDate = Date.parse(new Date().toISOString().slice(0, 10));\r\n    var accessDate = Date.parse(data.last_assess_time.slice(0, 10));\r\n    var days = (nowDate - accessDate) / (1 * 24 * 60 * 60 * 1000);\r\n    var fireColor = "";\r\n\r\n    if (days <= 7) {\r\n        fireColor = "red";\r\n    } else if (days <= 14) {\r\n        fireColor = "orange";\r\n    } else if (days <= 30) {\r\n        fireColor = "gray";\r\n    }\r\n\r\n    if (fireColor) {\r\n        svgIcon = `<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="${fireColor}" class="bi bi-fire" viewBox="0 0 16 16"><path d="M8 16c3.314 0 6-2 6-5.5 0-1.5-.5-4-2.5-6 .25 1.5-1.25 2-1.25 2C11 4 9 .5 6 0c.357 2 .5 4-2 6-1.25 1-2 2.729-2 4.5C2 14 4.686 16 8 16Zm0-1c-1.657 0-3-1-3-2.75 0-.75.25-2 1.25-3C6.125 10 7 10.5 7 10.5c-.375-1.25.5-3.25 2-3.5-.179 1-.25 2 1 3 .625.5 1 1.364 1 2.25C11 14 9.657 15 8 15Z"/></svg></span>`;\r\n    }\r\n}\r\n\r\nif (!svgIcon) {\r\n    newname = `<span style="margin-left: 16px;"></span>${newname}`;\r\n}\r\n\r\nreturn svgIcon + newname;',
            valueType: 'SIMPLE',
            customCode: true,
            dataType: 25,
            id: 'subject',
          },
          {
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_name',
          },
          {
            appDEFieldId: 'mobile',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'mobile',
          },
          {
            appDEFieldId: 'lead_status',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'lead_status',
          },
          {
            appDEFieldId: 'executors',
            valueType: 'OBJECTS',
            dataType: 21,
            id: 'executors',
          },
          {
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'owner',
          },
          {
            appDEFieldId: 'pid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pid',
          },
          {
            appDEFieldId: 'pname',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pname',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'id',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            appDEFieldId: 'account_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_id',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'last_assess_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'last_assess_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'subject',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'LOCAL',
        enableCustomized: true,
        enablePagingBar: true,
        forceFit: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_data_set2',
          appDataEntityId: 'crmweb.lead',
          id: 'fetch',
        },
        dedataImportId: 'dataimport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.lead',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'create_task@lead',
                uiactionTarget: 'MULTIKEY',
                hiddenItem: true,
                valid: true,
                caption: '创建任务',
                itemType: 'DEUIACTION',
                tooltip: '创建任务',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'remove@lead',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '删除',
                itemType: 'DEUIACTION',
                tooltip: '删除',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'add_tags@lead',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '添加标签',
                    itemType: 'DEUIACTION',
                    tooltip: '添加标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'delete_tags@lead',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '移除标签',
                    itemType: 'DEUIACTION',
                    tooltip: '移除标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction3',
                  },
                ],
                valid: true,
                caption: '标签',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '标签',
                showCaption: true,
                showIcon: true,
                id: 'items1',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'batch_update@lead',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '批量更新',
                    itemType: 'DEUIACTION',
                    tooltip: '批量更新',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction4',
                  },
                ],
                valid: true,
                caption: '操作',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '操作',
                showCaption: true,
                showIcon: true,
                id: 'items2',
              },
            ],
            codeName: 'tree_grid_view_treegrid_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作_工具栏',
            appDataEntityId: 'crmweb.lead',
            controlParam: {
              id: 'treegrid_batchtoolbar',
            },
            modelId: '7c0b69983a12e10619f5a147846ffc6d',
            modelType: 'PSDETOOLBAR',
            name: 'treegrid_batchtoolbar',
            id: 'tree_grid_view_treegrid_batchtoolbar',
          },
        ],
        codeName: 'grid_view_multimode_grid',
        controlStyle: 'NUMBER_GRID',
        controlType: 'TREEGRID',
        logicName: '线索多模式表格视图_表格',
        appDataEntityId: 'crmweb.lead',
        controlParam: {
          ctrlParams: {
            EXPANDCOLUMNINDEX: '0',
          },
          id: 'treegrid',
        },
        sysPFPluginId: 'number_grid',
        modelId: '7ecdd15fc89c0423d58e717c8acd67cd',
        modelType: 'PSDEGRID',
        name: 'treegrid',
        id: 'crmweb.lead.grid_view_multimode_grid',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.lead',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '线索树表格视图',
        codeName: 'tree_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.lead',
        controlParam: {},
        name: 'captionbar',
        id: 'tree_grid_view_captionbar',
      },
    ],
    codeName: 'usr0605020873',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'tree_grid_view树表格视图布局面板',
    appDataEntityId: 'crmweb.lead',
    controlParam: {},
    modelId: 'ed6fb9d1379fa07be50ba8093564cabc',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0605020873',
  },
  title: '线索树表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'ae750708b2092003ce7b19e11d4ebd3b',
  modelType: 'PSAPPDEVIEW',
  name: 'leadtree_grid_view',
  id: 'crmweb.lead_tree_grid_view',
};
