export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view',
  deviewId: '253d0b4f5b89d1d6031c362e0a2f022c',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAYEE_PLAN',
  },
  caption: '收款计划',
  codeName: 'payee_plan_grid_view',
  appDataEntityId: 'crmweb.payee_plan',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'crmweb.payee_plan_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'crmweb.payee_plan_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'crmweb.payee_plan_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'crmweb.payee_plan_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      openMode: 'POPUPMODAL',
      realOpenMode: 'POPUPMODAL',
      realTitle: '收款计划编辑视图',
      refAppViewId: 'crmweb.payee_plan_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      openMode: 'POPUPMODAL',
      realOpenMode: 'POPUPMODAL',
      realTitle: '收款计划编辑视图',
      refAppViewId: 'crmweb.payee_plan_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建收款计划',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建收款计划',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_refreshaction',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '刷新',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-refresh',
            glyph: 'xf021@FontAwesome',
          },
          tooltip: '刷新',
          showIcon: true,
          id: 'deuiaction8',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '收款计划_工具栏',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '752f46c0620889bac1576bde8a3cc57c',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'ASC',
      minorSortAppDEFieldId: 'planned_time',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'planned_time',
          excelCaption: '计划收款时间',
          appDEFieldId: 'planned_time',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '计划收款时间',
          codeName: 'planned_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 135,
          widthUnit: 'PX',
          enableSort: true,
          id: 'planned_time',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'amount',
          excelCaption: '收款金额',
          appDEFieldId: 'amount',
          unitName: '元',
          valueFormat: '#,##0.00',
          valueType: 'SIMPLE',
          enableUnitName: true,
          aggMode: 'NONE',
          align: 'RIGHT',
          caption: '收款金额',
          codeName: 'amount',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 110,
          widthUnit: 'PX',
          enableSort: true,
          id: 'amount',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'description',
          excelCaption: '款项说明',
          appDEFieldId: 'description',
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 200,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                detailType: 'DEUIACTION',
                uiactionId: 'create_payee@payee_plan',
                tooltip: '生成收款记录',
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-share-square-o',
                  glyph: 'xf045@FontAwesome',
                },
                id: 'u54591bd',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '拆分计划',
                detailType: 'DEUIACTION',
                uiactionId: 'split_plan@payee_plan',
                tooltip: '拆分计划',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-cut',
                  glyph: 'xf0c4@FontAwesome',
                },
                id: 'uba9c3e9',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '关闭计划',
                detailType: 'DEUIACTION',
                uiactionId: 'close_plan@payee_plan',
                showCaption: true,
                showIcon: true,
                sysImage: {
                  cssClass: 'fa fa-close',
                  glyph: 'xf00d@FontAwesome',
                },
                id: 'u0ef07c3',
              },
            ],
            appDataEntityId: 'crmweb.payee_plan',
            uniqueTag: 'payee_plan__Usr0606658416',
            name: '敏捷收款计划表格操作列',
            id: 'usr0606658416',
          },
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '款项说明',
          codeName: 'description',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          id: 'description',
        },
      ],
      degridDataItems: [
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'planned_time',
          scriptCode:
            '(data.planned_time !== null && data.planned_time !== undefined && data.planned_time !== \'\') ? data.planned_time : "未明确"',
          valueType: 'SIMPLE',
          customCode: true,
          dataType: 5,
          id: 'planned_time',
        },
        {
          format: '#,##0.00',
          appDEFieldId: 'amount',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'amount',
        },
        {
          appDEFieldId: 'description',
          valueType: 'SIMPLE',
          dataType: 21,
          id: 'description',
        },
        {
          appDEFieldId: 'plan_status',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'plan_status',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'project_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'project_id',
        },
        {
          appDEFieldId: 'plan_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 100,
      sortMode: 'REMOTE',
      enableRowEditOrder: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_toward',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'fetch',
      },
      moveControlAction: {
        appDEMethodId: 'move_order',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'move',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'create_task@payee_plan',
              uiactionTarget: 'MULTIKEY',
              hiddenItem: true,
              valid: true,
              caption: '创建任务',
              itemType: 'DEUIACTION',
              tooltip: '创建任务',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'remove@payee_plan',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '删除',
              itemType: 'DEUIACTION',
              tooltip: '删除',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'add_tags@payee_plan',
                  uiactionTarget: 'MULTIKEY',
                  hiddenItem: true,
                  valid: true,
                  caption: '添加标签',
                  itemType: 'DEUIACTION',
                  tooltip: '添加标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'delete_tags@payee_plan',
                  uiactionTarget: 'MULTIKEY',
                  hiddenItem: true,
                  valid: true,
                  caption: '移除标签',
                  itemType: 'DEUIACTION',
                  tooltip: '移除标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction3',
                },
              ],
              valid: true,
              caption: '标签',
              itemType: 'ITEMS',
              sysImage: {
                cssClass: 'fa fa-chevron-down',
                glyph: 'xf078@FontAwesome',
              },
              tooltip: '标签',
              showCaption: true,
              showIcon: true,
              id: 'items1',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'batch_update@payee_plan',
                  uiactionTarget: 'MULTIKEY',
                  hiddenItem: true,
                  valid: true,
                  caption: '批量更新',
                  itemType: 'DEUIACTION',
                  tooltip: '批量更新',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction4',
                },
              ],
              valid: true,
              caption: '操作',
              itemType: 'ITEMS',
              sysImage: {
                cssClass: 'fa fa-chevron-down',
                glyph: 'xf078@FontAwesome',
              },
              tooltip: '操作',
              showCaption: true,
              showIcon: true,
              id: 'items2',
            },
          ],
          codeName: 'grid_view_grid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '批操作_工具栏',
          appDataEntityId: 'crmweb.payee_plan',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: 'a1a0dfce290281ba2bcf70d9fdaf63ec',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'grid_view_grid_batchtoolbar',
        },
      ],
      codeName: 'grid_view_grid',
      controlType: 'GRID',
      logicName: '收款计划_表格',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {
        ctrlParams: {
          SHOWMODE: 'MIXIN',
        },
        id: 'grid',
      },
      modelId: '12deea6bac41b8a23ea67bde2d7410d0',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.payee_plan.grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '收款计划_搜索表单',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {
        id: 'searchform',
      },
      modelId: '81537e3e978cc90391c2544b64b3cb9c',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.payee_plan.grid_view_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAYEE_PLAN',
      },
      caption: '收款计划',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.payee_plan',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '收款计划',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f193d0b64201e136ed9496eb23c59a28',
  modelType: 'PSAPPDEVIEW',
  name: 'payee_plangrid_view',
  id: 'crmweb.payee_plan_grid_view',
};
