export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_search_view',
  deviewId: '7043cc9a0c42985d0c8b547cc957dfc2',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.PAYEE.TAB_SEARCH_VIEW',
  },
  caption: '收款记录',
  codeName: 'payee_tab_search_view',
  appDataEntityId: 'crmweb.payee',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId: 'panel_usr0318980456_button_filter_click@account',
                renderMode: 'BUTTON',
                tooltip: '过滤',
                uiactionTarget: 'SINGLEDATA',
                caption: '过滤',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysImage: {
                  cssClass: 'fa fa-filter',
                  glyph: 'xf0b0@FontAwesome',
                },
                id: 'button_filter',
              },
              {
                rawItem: {
                  caption: '文本内容',
                  halign: 'LEFT',
                  renderMode: 'TEXT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'static_text',
                },
                caption: '文本',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysPFPluginId: 'group_searchbar',
                showCaption: true,
                id: 'static_text',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '关系分页部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabexppanel',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel',
              },
              {
                rawItem: {
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar',
                },
                caption: '工具栏占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingRight: 'INNERMEDIUM',
            },
            id: 'container3',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
              spacingBottom: 'INNERSMALL',
              spacingLeft: 'INNERMEDIUM',
              spacingTop: 'INNERSMALL',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'view_searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupMode: 'SINGLE',
        searchBarFilters: [
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_PAYEE_DATE_IN',
              stdDataType: 5,
              valueOP: 'IN',
              name: 'N_PAYEE_DATE_IN',
              id: 'n_payee_date_in',
            },
            editor: {
              editorParams: {
                TIMEFMT: 'YYYY-MM-DD',
              },
              editorType: 'DATERANGE_NOTIME',
              editorItems: [
                {
                  name: 'N_PAYEE_DATE_GTANDEQ',
                  id: 'n_payee_date_gtandeq',
                },
                {
                  name: 'N_PAYEE_DATE_LTANDEQ',
                  id: 'n_payee_date_ltandeq',
                },
              ],
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_PAYEE_DATE_IN',
              id: 'n_payee_date_in',
            },
            allowEmpty: true,
            caption: '收款日期',
            itemType: 'FILTER',
            appDEFieldId: 'payee_date',
            name: 'N_PAYEE_DATE_IN',
            id: 'n_payee_date_in',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_PAYEE_DATE_GTANDEQ',
              stdDataType: 5,
              valueOP: 'GTANDEQ',
              name: 'N_PAYEE_DATE_GTANDEQ',
              id: 'n_payee_date_gtandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_PAYEE_DATE_GTANDEQ',
              id: 'n_payee_date_gtandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '收款日期(>=)',
            itemType: 'FILTER',
            appDEFieldId: 'payee_date',
            name: 'N_PAYEE_DATE_GTANDEQ',
            id: 'n_payee_date_gtandeq',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_PAYEE_DATE_LTANDEQ',
              stdDataType: 5,
              valueOP: 'LTANDEQ',
              name: 'N_PAYEE_DATE_LTANDEQ',
              id: 'n_payee_date_ltandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_PAYEE_DATE_LTANDEQ',
              id: 'n_payee_date_ltandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '收款日期(<=)',
            itemType: 'FILTER',
            appDEFieldId: 'payee_date',
            name: 'N_PAYEE_DATE_LTANDEQ',
            id: 'n_payee_date_ltandeq',
          },
        ],
        searchBarGroups: [
          {
            caption: '所有记录',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'all',
          },
        ],
        quickSearchMode: 1,
        enableFilter: true,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'searchbar',
        controlStyle: 'FILTER_SEARCHBAR',
        controlType: 'SEARCHBAR',
        logicName: '默认搜索栏',
        appDataEntityId: 'crmweb.payee',
        controlParam: {
          id: 'searchbar',
        },
        sysPFPluginId: 'filter_searchbar',
        modelId: 'd9338b26aef6db572f4cf65be14ee55b',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'crmweb.payee.searchbar',
      },
      {
        tabExpPageIds: ['grid'],
        tabLayout: 'TOP',
        uniqueTag: 'payee_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '收付款',
            realTitleLanguageRes: {
              lanResTag: 'PAGE.TITLE.PAYEE.GRID_VIEW_MULTIMODE',
            },
            refAppViewId: 'crmweb.payee_grid_view_multimode',
            name: 'EXPITEM:grid',
            id: 'expitem:grid',
          },
        ],
        controls: [
          {
            sysImage: {
              cssClass: 'fa fa-table',
              glyph: 'xf0ce@FontAwesome',
            },
            caption: '表格视图',
            embeddedAppDEViewId: 'crmweb.payee_grid_view_multimode',
            codeName: 'tab_search_view_grid',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.payee',
            controlParam: {
              id: 'grid',
            },
            modelId: '5b4a5449d287eba4ad7580b0b55c4f13_grid',
            modelType: 'PSVIEWPANEL',
            name: 'grid',
            id: 'tab_search_view_grid',
          },
        ],
        codeName: 'tab_search_view_tabexppanel',
        controlStyle: 'TABEXPPANEL_DROPDOWN',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'crmweb.payee',
        controlParam: {},
        sysPFPluginId: 'tabexppanel_dropdown',
        modelId: '5b4a5449d287eba4ad7580b0b55c4f13_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'tab_search_view_tabexppanel',
      },
      {
        capLanguageRes: {
          lanResTag: 'PAGE.CAPTION.PAYEE.TAB_SEARCH_VIEW',
        },
        caption: '收款记录',
        codeName: 'tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.payee',
        controlParam: {},
        name: 'captionbar',
        id: 'tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0318980456',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索通用布局',
    appDataEntityId: 'crmweb.payee',
    controlParam: {},
    modelId: 'f9a64be769ab83bfc4ff869c38a9192b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0318980456',
  },
  title: '收款记录',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PAYEE.TAB_SEARCH_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '5b4a5449d287eba4ad7580b0b55c4f13',
  modelType: 'PSAPPDEVIEW',
  name: 'payeetab_search_view',
  id: 'crmweb.payee_tab_search_view',
};
