export default {
  openMode: 'POPUPMODAL',
  deviewCodeName: 'wizard_view',
  deviewId: '734f54fc3bac5d71e2932ec160144cd9',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.PAYEE.WIZARD_VIEW',
  },
  caption: '收款记录',
  codeName: 'payee_wizard_view',
  height: 800,
  appDataEntityId: 'crmweb.payee',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'WizardView',
      id: 'engine',
    },
  ],
  controls: [
    {
      finishControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.payee',
        id: 'finish',
      },
      initControlAction: {
        appDEMethodId: 'createtemp',
        appDataEntityId: 'crmweb.payee',
        id: 'init',
      },
      deeditForms: [
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'crmweb.payee',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'crmweb.payee',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'payee_record',
            deformName: '收款记录向导-收款记录向导表单',
            dewizardStepId: '创建收款记录',
            stepActions: ['NEXT'],
            stepTag: 'payee_record',
            firstForm: true,
            id: '收款记录',
          },
          formFuncMode: 'WIZARDFORM',
          deformItemUpdates: [
            {
              codeName: 'getYear',
              defiupdateDetails: [
                {
                  id: 'year',
                },
              ],
              scriptCode:
                'var year = new Date(data.payee_date);\r\ndata.year = year.getFullYear()',
              customCode: true,
              showBusyIndicator: true,
              name: '更新所属年度',
              id: 'getyear',
            },
          ],
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'payee_number',
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'payee_number',
                          },
                          allowEmpty: true,
                          hidden: true,
                          capLanguageRes: {
                            lanResTag:
                              'CONTROL.DEFORM.PAYEE.WIZARD_FORM.FORMITEM.PAYEE_NUMBER',
                          },
                          caption: '编号',
                          codeName: 'payee_number',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 12,
                            colMD: 12,
                            layout: 'TABLE_24COL',
                          },
                          id: 'payee_number',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'name',
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'name',
                          },
                          allowEmpty: true,
                          hidden: true,
                          capLanguageRes: {
                            lanResTag:
                              'CONTROL.DEFORM.PAYEE.WIZARD_FORM.FORMITEM.NAME',
                          },
                          caption: '名称',
                          codeName: 'name',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 12,
                            colMD: 12,
                            layout: 'TABLE_24COL',
                          },
                          id: 'name',
                        },
                        {
                          createDVT: 'CURTIME',
                          dataType: 5,
                          enableCond: 3,
                          itemWidth: 230,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'payee_date',
                          deformItemUpdateId: 'getyear',
                          editor: {
                            dateTimeFormat: 'YYYY-MM-DD',
                            editorParams: {
                              TIMEFMT: 'YYYY-MM-DD',
                            },
                            editorType: 'DATEPICKEREX_NOTIME',
                            editorWidth: 100,
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'payee_date',
                          },
                          valueFormat: 'YYYY-MM-DD',
                          capLanguageRes: {
                            lanResTag:
                              'CONTROL.DEFORM.PAYEE.WIZARD_FORM.FORMITEM.PAYEE_DATE',
                          },
                          caption: '收款日期',
                          codeName: 'payee_date',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 8,
                            colMD: 12,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'payee_date',
                        },
                        {
                          dataType: 6,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'amount',
                          editor: {
                            precision: 2,
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'amount',
                          },
                          unitName: '元',
                          enableUnitName: true,
                          capLanguageRes: {
                            lanResTag:
                              'CONTROL.DEFORM.PAYEE.WIZARD_FORM.FORMITEM.AMOUNT',
                          },
                          caption: '收款金额',
                          codeName: 'amount',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 8,
                            colMD: 12,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'amount',
                        },
                        {
                          createDVT: 'CURTIME',
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'year',
                          editor: {
                            editorType: 'NUMBER',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'year',
                          },
                          valueFormat: 'YYYY',
                          allowEmpty: true,
                          caption: '所属年度',
                          codeName: 'year',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 8,
                            colMD: 12,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'year',
                        },
                        {
                          createDV: 'project_id',
                          createDVT: 'APPDATA',
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'project_id',
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'project_id',
                          },
                          allowEmpty: true,
                          hidden: true,
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.PROJECT_ID',
                          },
                          caption: '订单标识',
                          codeName: 'project_id',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 12,
                            colMD: 12,
                            layout: 'TABLE_24COL',
                          },
                          id: 'project_id',
                        },
                      ],
                      codeName: 'grouppanel1',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 16,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel1',
                    },
                    {
                      dataType: 21,
                      enableCond: 3,
                      itemHeight: 200,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'description',
                      editor: {
                        maxLength: 32000,
                        showMaxLength: true,
                        editorHeight: 200,
                        editorParams: {
                          HEIGHT: '200',
                        },
                        editorType: 'TEXTAREA_10',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'description',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.PAYEE.WIZARD_FORM.FORMITEM.DESCRIPTION',
                      },
                      caption: '描述',
                      codeName: 'description',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 16,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'description',
                    },
                  ],
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.PAYEE.WIZARD_FORM.GROUPPANEL.GROUP1',
                  },
                  caption: '收款信息',
                  codeName: 'group1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 24,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'group1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              capLanguageRes: {
                lanResTag:
                  'CONTROL.DEFORM.PAYEE.WIZARD_FORM.FORMPAGE.FORMPAGE1',
              },
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'wizard_form',
          controlType: 'FORM',
          logicName: '收款记录向导-收款记录向导表单',
          appDataEntityId: 'crmweb.payee',
          controlLogics: [
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_payee_record',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_payee_record',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_payee_record',
          },
          modelId: '619ce336fb34f96ee867fa23ea418d99',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_payee_record',
          id: 'crmweb.payee.wizard_form',
        },
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'crmweb.payee',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'crmweb.payee',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'payee_select_plan',
            deformName: '收款记录向导表单-收款计划',
            dewizardStepId: '选择收款计划',
            stepActions: ['PREV', 'NEXT'],
            stepTag: 'payee_select_plan',
            id: '计划选择',
          },
          formFuncMode: 'WIZARDFORM',
          deformItemUpdates: [
            {
              codeName: 'refresh_plan_amount',
              appDEMethodId: 'account_from_plan',
              defiupdateDetails: [
                {
                  id: 'plan_amount',
                },
              ],
              showBusyIndicator: false,
              name: '更新计划金额',
              id: 'refresh_plan_amount',
            },
          ],
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'payee_plan_id',
                      deformItemUpdateId: 'refresh_plan_amount',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'crmweb.crm__usrcodelist0625594962',
                        editorType: 'DROPDOWNLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'payee_plan_id',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.PAYEE_PLAN_ID',
                      },
                      caption: '收款计划标识',
                      codeName: 'payee_plan_id',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 7,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'payee_plan_id',
                    },
                    {
                      dataType: 6,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'plan_amount',
                      editor: {
                        halign: 'LEFT',
                        precision: 2,
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'plan_amount',
                      },
                      unitName: '元',
                      valueFormat: '#,##0.00',
                      allowEmpty: true,
                      enableUnitName: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.PLAN_AMOUNT',
                      },
                      caption: '计划金额',
                      codeName: 'plan_amount',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 7,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'plan_amount',
                    },
                    {
                      dataType: 5,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'planned_time',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'planned_time',
                      },
                      valueFormat: 'YYYY-MM-DD',
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.PLANNED_TIME',
                      },
                      caption: '原计划时间',
                      codeName: 'planned_time',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 8,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'planned_time',
                    },
                    {
                      dataType: 21,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'plan_description',
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'plan_description',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.PLAN_DESCRIPTION',
                      },
                      caption: '原计划说明',
                      codeName: 'plan_description',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'plan_description',
                    },
                  ],
                  caption: '收款记录基本信息',
                  codeName: 'group1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'group1',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'plan_form',
          controlType: 'FORM',
          logicName: '收款记录向导表单-收款计划',
          appDataEntityId: 'crmweb.payee',
          controlLogics: [
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_payee_select_plan',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_payee_select_plan',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_payee_select_plan',
          },
          modelId: '7e1cf9690ba80bf2aa2460a1564a8985',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_payee_select_plan',
          id: 'crmweb.payee.plan_form',
        },
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'crmweb.payee',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'crmweb.payee',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'payee_allocate',
            deformName: '收款记录向导-分配人员选择表单',
            dewizardStepId: '回款业绩分配',
            stepActions: ['PREV', 'FINISH'],
            stepTag: 'payee_allocate',
            id: '分配人员',
          },
          formFuncMode: 'WIZARDFORM',
          deformItemUpdates: [
            {
              codeName: 'allocate_from_project',
              appDEMethodId: 'allocate_from_project',
              defiupdateDetails: [
                {
                  id: 'mdctrl1',
                },
              ],
              showBusyIndicator: true,
              name: '获取订单分配信息',
              id: 'allocate_from_project',
            },
            {
              codeName: 'calculate_amount',
              defiupdateDetails: [
                {
                  id: 'mdctrl2',
                },
                {
                  id: 'mdctrl1',
                },
              ],
              scriptCode:
                "var payee_allocates_info = data.payee_allocates;\r\nfor(var i=0; i<payee_allocates_info.length; i++){\r\n    var payee_allocate = data.payee_allocates[i];\r\n    var amount = payee_allocate.amount;\r\n    var ratio = payee_allocate.ratio;\r\n    if (typeof amount !== 'undefined' && amount !== null && amount !== ''){\r\n\r\n    } else {        \r\n        amount =  data.amount_payee * ratio * 0.01;\r\n        amount = parseFloat(amount.toFixed(2));\r\n        var amountString = amount.toString();\r\n        if (amountString.indexOf('.') !== -1 && amountString.split('.')[1].length === 1) {\r\n            amountString += '0';\r\n        }\r\n        payee_allocate.amount = amountString;\r\n        data.payee_allocates[i] = payee_allocate;\r\n        }\r\n}",
              customCode: true,
              showBusyIndicator: true,
              name: '计算表分配金额',
              id: 'calculate_amount',
            },
          ],
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          createDV: '延续订单分配模式',
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'allocate_model',
                          deformItemUpdateId: 'allocate_from_project',
                          editor: {
                            appCodeListId: 'crmweb.crm__distribution_model',
                            editorType: 'RADIOBUTTONLIST',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'allocate_model',
                          },
                          allowEmpty: true,
                          needCodeListConfig: true,
                          capLanguageRes: {
                            lanResTag:
                              'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.FORMITEM.ALLOCATE_MODEL',
                          },
                          caption: '分配模式',
                          codeName: 'allocate_model',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'allocate_model',
                        },
                      ],
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.GROUPPANEL.GROUPPANEL1',
                      },
                      caption: '分配模式',
                      codeName: 'grouppanel1',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 16,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel1',
                    },
                    {
                      dataType: 6,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'amount',
                      deformItemUpdateId: 'calculate_amount',
                      editor: {
                        precision: 2,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'amount_payee',
                      },
                      unitName: '元',
                      valueFormat: '#,##0.00',
                      allowEmpty: true,
                      enableUnitName: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.AMOUNT',
                      },
                      caption: '金额',
                      codeName: 'amount_payee',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 9,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'amount_payee',
                    },
                  ],
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.GROUPPANEL.GROUP1',
                  },
                  caption: '收款记录基本信息',
                  codeName: 'group1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'group1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          contentType: 'REPEATER',
                          appDEFieldId: 'payee_allocates',
                          layout: {
                            columnCount: 24,
                            layout: 'TABLE_24COL',
                          },
                          deformDetails: [
                            {
                              dataType: 25,
                              enableCond: 3,
                              fieldName: 'user_name',
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                halign: 'LEFT',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'user_name_default',
                              },
                              allowEmpty: true,
                              capLanguageRes: {
                                lanResTag:
                                  'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.FORMITEM.USER_NAME',
                              },
                              caption: '销售人员',
                              codeName: 'user_name_default',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              showCaption: true,
                              id: 'user_name_default',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              fieldName: 'ratio',
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                halign: 'LEFT',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'ratio_default',
                              },
                              allowEmpty: true,
                              capLanguageRes: {
                                lanResTag:
                                  'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.FORMITEM.RATIO',
                              },
                              caption: '分配比率（%）',
                              codeName: 'ratio_default',
                              columnAlign: 'RIGHT',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              showCaption: true,
                              id: 'ratio_default',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              fieldName: 'amount',
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                halign: 'LEFT',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'amount_default',
                              },
                              allowEmpty: true,
                              caption: '分配金额（元）',
                              codeName: 'amount_default',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              showCaption: true,
                              id: 'amount_default',
                            },
                          ],
                          codeName: 'mdctrl1',
                          detailStyle: 'STYLE2',
                          detailType: 'MDCTRL',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'mdctrl1',
                        },
                      ],
                      codeName: 'grouppanel3',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 16,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel3',
                    },
                  ],
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.GROUPPANEL.GROUPPANEL2',
                  },
                  caption: '默认',
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  defdgroupLogics: [
                    {
                      logicCat: 'PANELVISIBLE',
                      relatedDetailNames: ['allocate_model'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'EQ',
                          defdname: 'allocate_model',
                          value: '延续订单分配模式',
                          logicType: 'SINGLE',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel2',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          buildInActions: 7,
                          contentType: 'REPEATER',
                          appDEFieldId: 'payee_allocates',
                          layout: {
                            columnCount: 24,
                            layout: 'TABLE_24COL',
                          },
                          deformDetails: [
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                enablePickupView: true,
                                singleSelect: true,
                                appDEACModeId: 'default',
                                appDEDataSetId: 'fetch_default',
                                appDataEntityId: 'crmweb.user',
                                enableAC: true,
                                forceSelection: true,
                                showTrigger: true,
                                valueItemName: 'user_id',
                                editorParams: {
                                  AC: 'TRUE',
                                  PICKUPVIEW: 'TRUE',
                                },
                                editorType: 'PICKER',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'user_name',
                              },
                              allowEmpty: true,
                              capLanguageRes: {
                                lanResTag:
                                  'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.FORMITEM.USER_NAME_DEFAULT',
                              },
                              caption: '销售人员',
                              codeName: 'user_name',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              showCaption: true,
                              id: 'user_name',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              fieldName: 'ratio',
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'NUMBER',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'ratio',
                              },
                              allowEmpty: true,
                              capLanguageRes: {
                                lanResTag:
                                  'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.FORMITEM.RATIO_DEFAULT',
                              },
                              caption: '分配比率（%）',
                              codeName: 'ratio',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              showCaption: true,
                              id: 'ratio',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'TEXTBOX',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'amount',
                              },
                              allowEmpty: true,
                              caption: '分配金额（元）',
                              codeName: 'amount',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              showCaption: true,
                              id: 'amount',
                            },
                          ],
                          codeName: 'mdctrl2',
                          detailStyle: 'STYLE2',
                          detailType: 'MDCTRL',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'mdctrl2',
                        },
                      ],
                      codeName: 'grouppanel5',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colLG: 16,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel5',
                    },
                  ],
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.GROUPPANEL.GROUPPANEL4',
                  },
                  caption: '自定义',
                  codeName: 'grouppanel4',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  defdgroupLogics: [
                    {
                      logicCat: 'PANELVISIBLE',
                      relatedDetailNames: ['allocate_model'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'EQ',
                          defdname: 'allocate_model',
                          value: '自定义',
                          logicType: 'SINGLE',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel4',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              capLanguageRes: {
                lanResTag:
                  'CONTROL.DEFORM.PAYEE.PAYEE_ALLOCATE_FORM.FORMPAGE.FORMPAGE1',
              },
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'payee_allocate_form',
          controlType: 'FORM',
          logicName: '收款记录向导-分配人员选择表单',
          appDataEntityId: 'crmweb.payee',
          controlLogics: [
            {
              eventNames: 'onLoadSuccess',
              itemName: 'group1',
              logicTag: 'wizardpanel_form_payee_allocate',
              logicType: 'APPDEUIACTION',
              appDEUIActionId: 'allocate_from_project@payee',
              triggerType: 'CTRLEVENT',
              id: 'get_allocate',
            },
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_payee_allocate',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_payee_allocate',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_payee_allocate',
          },
          modelId: '9d7182ca7ee56b76f32a40343e50410c',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_payee_allocate',
          id: 'crmweb.payee.payee_allocate_form',
        },
      ],
      dewizard: {
        codeName: 'wizard',
        firstDEWizardFormId: '收款记录',
        nextCaption: '下一步',
        dewizardForms: [
          {
            formTag: 'payee_record',
            deformName: '收款记录向导-收款记录向导表单',
            dewizardStepId: '创建收款记录',
            stepActions: ['NEXT'],
            stepTag: 'payee_record',
            firstForm: true,
            id: '收款记录',
          },
          {
            formTag: 'payee_select_plan',
            deformName: '收款记录向导表单-收款计划',
            dewizardStepId: '选择收款计划',
            stepActions: ['PREV', 'NEXT'],
            stepTag: 'payee_select_plan',
            id: '计划选择',
          },
          {
            formTag: 'payee_allocate',
            deformName: '收款记录向导-分配人员选择表单',
            dewizardStepId: '回款业绩分配',
            stepActions: ['PREV', 'FINISH'],
            stepTag: 'payee_allocate',
            id: '分配人员',
          },
        ],
        dewizardSteps: [
          {
            stepTag: 'payee_record',
            title: '创建收款记录',
            id: '创建收款记录',
          },
          {
            stepTag: 'payee_select_plan',
            title: '选择收款计划',
            id: '选择收款计划',
          },
          {
            stepTag: 'payee_allocate',
            title: '回款业绩分配',
            id: '回款业绩分配',
          },
        ],
        prevCaption: '上一步',
        wizardStyle: 'DEFAULT',
        name: '收款记录向导',
        id: 'crm.payee.wizard',
      },
      wizardStyle: 'DEFAULT',
      showActionBar: true,
      showStepBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'wizard',
      controlType: 'WIZARDPANEL',
      logicName: '收款记录向导',
      appDataEntityId: 'crmweb.payee',
      controlParam: {
        id: 'wizardpanel',
      },
      modelId: 'ef3ae28e9746fd853301b39c419dd4c8',
      modelType: 'PSDEWIZARDPANEL',
      name: 'wizardpanel',
      id: 'crmweb.payee.wizard',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.PAYEE.WIZARD_VIEW',
      },
      caption: '收款记录',
      codeName: 'wizard_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.payee',
      controlParam: {},
      name: 'captionbar',
      id: 'wizard_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEWIZARDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.payee',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '收款记录',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PAYEE.WIZARD_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEWIZARDVIEW',
  width: 1024,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'ec8916668acd49811c539e84ee83bf89',
  modelType: 'PSAPPDEVIEW',
  name: 'payeewizard_view',
  id: 'crmweb.payee_wizard_view',
};
