export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view',
  deviewId: 'cfdeaf69e46068325aae10d5ed34f068',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.PAYEE.GRID_VIEW',
  },
  caption: '收款记录',
  codeName: 'payee_grid_view',
  appDataEntityId: 'crmweb.payee',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'crmweb.payee_payee_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'crmweb.payee_payee_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'crmweb.payee_payee_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'crmweb.payee_payee_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '收付款编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.PAYEE.EDIT_VIEW',
      },
      refAppViewId: 'crmweb.payee_payee_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '收付款编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.PAYEE.EDIT_VIEW',
      },
      refAppViewId: 'crmweb.payee_payee_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建收付款',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建收付款',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_refreshaction',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '刷新',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-refresh',
            glyph: 'xf021@FontAwesome',
          },
          tooltip: '刷新',
          showIcon: true,
          id: 'deuiaction7',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'open_wizard@payee',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '向导',
          itemType: 'DEUIACTION',
          tooltip: '向导',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction9',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '收款记录_工具栏',
      appDataEntityId: 'crmweb.payee',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'b9569ba90d3c85243ccef2d9429cf202',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'ASC',
      minorSortAppDEFieldId: 'payee_date',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'payee_date',
          excelCaption: '收款日期',
          appDEFieldId: 'payee_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PAYEE_DATE',
          },
          caption: '收款日期',
          codeName: 'payee_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 135,
          widthUnit: 'PX',
          enableSort: true,
          id: 'payee_date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'amount',
          excelCaption: '收款金额',
          appDEFieldId: 'amount',
          unitName: '元',
          valueFormat: '#,##0.00',
          valueType: 'SIMPLE',
          enableUnitName: true,
          aggMode: 'NONE',
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEGRID.PAYEE.GRID_VIEW_GRID.DEFGRIDCOLUMN.AMOUNT',
          },
          caption: '收款金额',
          codeName: 'amount',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 110,
          widthUnit: 'PX',
          enableSort: true,
          id: 'amount',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'description',
          excelCaption: '收款说明',
          appDEFieldId: 'description',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEGRID.PAYEE.GRID_VIEW_GRID.DEFGRIDCOLUMN.DESCRIPTION',
          },
          caption: '收款说明',
          codeName: 'description',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          id: 'description',
        },
      ],
      degridDataItems: [
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'payee_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'payee_date',
        },
        {
          format: '#,##0.00',
          appDEFieldId: 'amount',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'amount',
        },
        {
          appDEFieldId: 'description',
          valueType: 'SIMPLE',
          dataType: 21,
          id: 'description',
        },
        {
          appDEFieldId: 'payee_number',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'payee_number',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'project_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'project_id',
        },
        {
          appDEFieldId: 'payee_plan_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'payee_plan_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 100,
      sortMode: 'REMOTE',
      enableRowEditOrder: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_all',
        appDataEntityId: 'crmweb.payee',
        id: 'fetch',
      },
      moveControlAction: {
        appDEMethodId: 'move_order',
        appDataEntityId: 'crmweb.payee',
        id: 'move',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.payee',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'create_task@payee',
              uiactionTarget: 'MULTIKEY',
              hiddenItem: true,
              valid: true,
              caption: '创建任务',
              itemType: 'DEUIACTION',
              tooltip: '创建任务',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'remove@payee',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '删除',
              itemType: 'DEUIACTION',
              tooltip: '删除',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'add_tags@payee',
                  uiactionTarget: 'MULTIKEY',
                  hiddenItem: true,
                  valid: true,
                  caption: '添加标签',
                  itemType: 'DEUIACTION',
                  tooltip: '添加标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'delete_tags@payee',
                  uiactionTarget: 'MULTIKEY',
                  hiddenItem: true,
                  valid: true,
                  caption: '移除标签',
                  itemType: 'DEUIACTION',
                  tooltip: '移除标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction3',
                },
              ],
              valid: true,
              caption: '标签',
              itemType: 'ITEMS',
              sysImage: {
                cssClass: 'fa fa-chevron-down',
                glyph: 'xf078@FontAwesome',
              },
              tooltip: '标签',
              showCaption: true,
              showIcon: true,
              id: 'items1',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'batch_update@payee',
                  uiactionTarget: 'MULTIKEY',
                  hiddenItem: true,
                  valid: true,
                  caption: '批量更新',
                  itemType: 'DEUIACTION',
                  tooltip: '批量更新',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction4',
                },
              ],
              valid: true,
              caption: '操作',
              itemType: 'ITEMS',
              sysImage: {
                cssClass: 'fa fa-chevron-down',
                glyph: 'xf078@FontAwesome',
              },
              tooltip: '操作',
              showCaption: true,
              showIcon: true,
              id: 'items2',
            },
          ],
          codeName: 'grid_view_grid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '批操作_工具栏',
          appDataEntityId: 'crmweb.payee',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: '2ebad0ef15501e82261737ac6a8e5e17',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'grid_view_grid_batchtoolbar',
        },
      ],
      codeName: 'grid_view_grid',
      controlType: 'GRID',
      logicName: '收款记录_表格',
      appDataEntityId: 'crmweb.payee',
      controlParam: {
        ctrlParams: {
          SHOWMODE: 'MIXIN',
        },
        id: 'grid',
      },
      modelId: '6909fe8564b5fc29f29c022e993ffe2b',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.payee.grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.PAYEE.GRID_VIEW_SEARCHFORM.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '收款管理_搜索表单',
      appDataEntityId: 'crmweb.payee',
      controlParam: {
        id: 'searchform',
      },
      modelId: '73a81dae695b6807957164e9e1846036',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.payee.grid_view_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.payee',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.PAYEE.GRID_VIEW',
      },
      caption: '收款记录',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.payee',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.payee',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '收款记录',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PAYEE.GRID_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '27ab9b87fb223f5a3d13bc70d30a56c6',
  modelType: 'PSAPPDEVIEW',
  name: 'payeegrid_view',
  id: 'crmweb.payee_grid_view',
};
