export default {
  enableSearch: true,
  expandSearchForm: true,
  loadDefault: true,
  deviewCodeName: 'chart_view',
  deviewId: '4663476e219aeb38bdac3872873132cd',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAYEE_STATISTIC',
  },
  caption: '收款情况统计',
  codeName: 'payee_statistic_chart_view',
  appDataEntityId: 'crmweb.payee_statistic',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ChartView',
      id: 'engine',
    },
  ],
  controls: [
    {
      searchButtonStyle: 'NONE',
      enableAutoSearch: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'owner',
              editor: {
                editorParams: {
                  blankItemName: '全部销售人员',
                },
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_owner_eq',
              },
              allowEmpty: true,
              hidden: true,
              caption: '销售人员',
              codeName: 'n_owner_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              id: 'n_owner_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'business_line',
              editor: {
                singleSelect: true,
                appCodeListId: 'crmweb.crm__industry',
                editorParams: {
                  blankItemName: '全部业务条线',
                },
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_business_line_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '业务条线',
              codeName: 'n_business_line_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_business_line_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorParams: {
                  TIMEFMT: 'YYYY-MM-DD',
                  format: 'YYYY-DD',
                },
                editorType: 'DATERANGE_NOTIME',
                editorItems: [
                  {
                    id: 'gt',
                  },
                  {
                    id: 'lt',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'date_range',
              },
              allowEmpty: true,
              caption: '统计时间',
              codeName: 'date_range',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              controlAttributes: [
                {
                  attrName: 'type',
                  attrValue: '"monthrange"',
                  id: 'monthrange',
                },
              ],
              layoutPos: {
                colLG: 8,
                colMD: 8,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'date_range',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'gt',
              },
              allowEmpty: true,
              hidden: true,
              caption: '表单项',
              codeName: 'gt',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'gt',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'lt',
              },
              allowEmpty: true,
              hidden: true,
              caption: '表单项',
              codeName: 'lt',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'lt',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '收款情况统计_搜索表单',
      appDataEntityId: 'crmweb.payee_statistic',
      controlParam: {
        id: 'searchform',
      },
      modelId: '11293868ffbf836ad636997077137852',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.payee_statistic.chart_view_search_form',
    },
    {
      coordinateSystem: 'XY',
      chartCoordinateSystems: [
        {
          chartGrid: {
            chartGridXAxis0Id: '0',
            chartGridYAxis0Id: '0',
            chartCoordinateSystemId: '0',
            type: 'grid',
            name: '[bar_0]直角坐标系[0]',
            id: '0',
          },
          echartsType: 'cartesian2d',
          type: 'XY',
          name: '[bar_0]直角坐标系[0]',
          id: '0',
        },
      ],
      dechartDataGrid: {
        id: '0',
      },
      dechartLegend: {
        id: '0',
      },
      dechartSerieses: [
        {
          stack: true,
          catalogField: 'NAME',
          echartsType: 'bar',
          chartCoordinateSystemId: '0',
          chartDataSetId: '0',
          chartSeriesEncode: {
            chartXAxisId: '0',
            chartYAxisId: '0',
            x: ['NAME'],
            y: ['AMOUNT'],
            itemId: 'TYPE',
            itemName: 'TYPE',
            type: 'XY',
            name: '坐标系编码',
            id: '0',
          },
          seriesField: 'TYPE',
          seriesLayoutBy: 'column',
          seriesCodeListId: 'crmweb.crm__collection_type',
          seriesType: 'bar',
          valueField: 'AMOUNT',
          enableChartDataSet: true,
          navAppViewId: 'crmweb.payee_statistic_chart_grid_view',
          navigateContexts: [
            {
              key: 'NAME',
              value: 'name_value',
              name: 'NAME',
              id: 'name',
            },
            {
              key: 'TYPE',
              value: 'type_value',
              name: 'TYPE',
              id: 'type',
            },
          ],
          navigateParams: [
            {
              key: 'n_owner_eq',
              value: 'n_owner_eq',
              id: 'n_owner_eq',
            },
            {
              key: 'lt',
              value: 'lt',
              id: 'lt',
            },
            {
              key: 'name',
              value: 'name_value',
              id: 'name',
            },
            {
              key: 'type',
              value: 'type_value',
              id: 'type',
            },
            {
              key: 'n_business_line_eq',
              value: 'n_business_line_eq',
              id: 'n_business_line_eq',
            },
          ],
          userParam: {
            'EC.label': '{"show":1,"fontSize":15}',
            'EC.select':
              "function (){ return {label: {fontSize: 20},labelLine: {show: false},itemStyle: {borderWidth: 0,shadowBlur: 0,shadowColor: 'transparent',borderColor: 'transparent', borderMiterLimit: 0,borderColor:'orange',borderWidth:5}}}()",
            'EC.barWidth': '40',
            'EC.selectedMode': 'single',
            'EC.stack': "'chart'",
          },
          id: 'bar_0',
        },
      ],
      dechartTitle: {
        title: '收款情况统计_图表',
        id: '0',
      },
      chartDataSetGroups: [
        {
          appDEDataSetId: 'fetch_statistic',
          appDataEntityId: 'crmweb.payee_statistic',
          name: 'statistic',
          id: '0',
        },
      ],
      chartDataSets: [
        {
          chartDataSetFields: [
            {
              groupField: true,
              name: 'NAME',
              id: '0',
            },
            {
              codeListId: 'crmweb.crm__collection_type',
              groupField: true,
              index: 1,
              name: 'TYPE',
              id: '1',
            },
            {
              index: 2,
              name: 'AMOUNT',
              id: '2',
            },
          ],
          name: 'bar_0-statistic',
          id: '0',
        },
      ],
      chartGrids: [
        {
          chartGridXAxis0Id: '0',
          chartGridYAxis0Id: '0',
          chartCoordinateSystemId: '0',
          type: 'grid',
          name: '[bar_0]直角坐标系[0]',
          id: '0',
        },
      ],
      chartXAxises: [
        {
          echartsPos: 'xAxis',
          echartsType: 'category',
          position: 'bottom',
          type: 'category',
          userParam: {
            'EC.interval': '0',
            'EC.nameLocation': '"BOTTOM"',
            'EC.nameRotate': '45',
            'EC.axisLabel': 'function (){ return { interval: 0 }}()',
          },
          name: 'axis_xAxis_0',
          id: '0',
        },
      ],
      chartYAxises: [
        {
          echartsPos: 'yAxis',
          echartsType: 'value',
          position: 'left',
          type: 'numeric',
          userParam: {
            'EC.axisTick': '{"show":0}',
            'EC.axisLabel': '{"show":0}',
          },
          name: 'axis_yAxis_0',
          id: '0',
        },
      ],
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_statistic',
        appDataEntityId: 'crmweb.payee_statistic',
        id: 'fetch',
      },
      readOnly: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'chart_view_chart',
      controlType: 'CHART',
      logicName: 'Chart',
      appDataEntityId: 'crmweb.payee_statistic',
      controlLogics: [
        {
          eventNames: 'onActive',
          logicTag: 'chart',
          logicType: 'SCRIPT',
          scriptCode:
            "const { _groupName, _catalog } = data[0];\r\nconst { series } = ctrl.options;\r\nif (series && series.length > 0) {\r\n\t// 取消选中\r\n\tconst seriesName = series.map(x => x.name);\r\n    const maxLength = Math.max(...series.map(x => x.data.length))\r\n\tctrl.chart.dispatchAction({\r\n        type: 'unselect',\r\n        seriesName,\r\n        dataIndex: [...Array(maxLength).keys()],\r\n    });\r\n    // 设置选中\r\n    ctrl.chart.dispatchAction({\r\n        type: 'select',\r\n        seriesName: _groupName,\r\n        name: _catalog,\r\n    });\r\n}",
          triggerType: 'CTRLEVENT',
          name: 'onAtive',
          id: 'onative',
        },
        {
          eventNames: 'onBeforeUpdate',
          logicTag: 'chart',
          logicType: 'SCRIPT',
          scriptCode:
            "const { series } = ctrl.options;\r\nif (series && series.length > 0) {\r\n    series.forEach(item => {\r\n        if (item.label) {\r\n            item.label.formatter = function (params) {\r\n                if(params.value[1] === 0)\r\n                {\r\n                    return '';\r\n                }\r\n                else\r\n                {\r\n                    return ibiz.util.text.format(params.value[1], '#,##0.00');\r\n                }\r\n            };\r\n        }\r\n    });\r\n};",
          triggerType: 'CTRLEVENT',
          name: 'onBeforeUpdate',
          id: 'onbeforeupdate',
        },
        {
          eventNames: 'onLoadSuccess',
          logicTag: 'chart',
          logicType: 'APPDEUIACTION',
          appDEUIActionId: 'nav_statistic_grid@payee_statistic',
          triggerType: 'CTRLEVENT',
          id: 'nav',
        },
      ],
      controlParam: {
        id: 'chart',
      },
      modelId: 'dcc4ca67bb9315bd62081fad768db138',
      modelType: 'PSDECHART',
      userParam: {
        'EC.color':
          '["#585AFB","#91cc75","#585AFB","#585AFB","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc","#585AFB","#91cc75"]',
      },
      name: 'chart',
      id: 'crmweb.payee_statistic.chart_view_chart',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'save_statistic_allocate@payee_statistic',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '更新收款统计',
          itemType: 'DEUIACTION',
          tooltip: '更新收款统计',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      codeName: 'chart_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '收款情况统计工具栏',
      appDataEntityId: 'crmweb.payee_statistic',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'fbe628090e8eca16447bf9b701c0fa12',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'chart_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.payee_statistic',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAYEE_STATISTIC',
      },
      caption: '收款情况统计',
      codeName: 'chart_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.payee_statistic',
      controlParam: {},
      name: 'captionbar',
      id: 'chart_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECHARTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.payee_statistic',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '收款情况统计',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'e1eeb14cd6276346f581f84b03a4f459',
  modelType: 'PSAPPDEVIEW',
  name: 'payee_statisticchart_view',
  id: 'crmweb.payee_statistic_chart_view',
};
