export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'multimode_edit_view',
  deviewId: 'e5ce10d9ed3dec57a3b8f78b7746e9d0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAYEE_PLAN',
  },
  caption: '收款计划编辑视图',
  codeName: 'payee_plan_multimode_edit_view',
  appDataEntityId: 'crmweb.payee_plan',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_exitaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
          },
          caption: '取消',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-sign-out',
            glyph: 'xf08b@FontAwesome',
          },
          tooltip: '取消',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.CLOSE',
          },
          showCaption: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveandnewaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
          },
          caption: '保存并新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'sx-tb-saveandnew',
          },
          tooltip: '保存并新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
          },
          showCaption: true,
          id: 'deuiaction2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'cut_save@payee_plan',
          uiactionTarget: 'SINGLEDATA',
          valid: true,
          caption: '保存',
          itemType: 'DEUIACTION',
          tooltip: '保存',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction3',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'split_plan@payee_plan',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '拆分计划',
              itemType: 'DEUIACTION',
              controlLogics: [
                {
                  itemName: 'cut_plan',
                  logicTag: 'toolbar',
                  logicType: 'SCRIPT',
                  scriptCode: 'data.id',
                  triggerType: 'ITEMVISIBLE',
                  name: 'idNotNull',
                  id: 'idnotnull',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-cut',
                glyph: 'xf0c4@FontAwesome',
              },
              tooltip: '拆分计划',
              showCaption: true,
              id: 'cut_plan',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'close_plan@payee_plan',
              uiactionTarget: 'SINGLEKEY',
              valid: true,
              caption: '关闭计划',
              itemType: 'DEUIACTION',
              controlLogics: [
                {
                  itemName: 'close_plan',
                  logicTag: 'toolbar',
                  logicType: 'SCRIPT',
                  scriptCode: 'data.id',
                  triggerType: 'ITEMVISIBLE',
                  name: 'idNotNull2',
                  id: 'idnotnull2',
                },
              ],
              sysImage: {
                cssClass: 'fa fa-times',
                glyph: 'xf00d@FontAwesome',
              },
              tooltip: '关闭计划',
              showCaption: true,
              id: 'close_plan',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysImage: {
            cssClass: 'fa fa-ellipsis-h',
            glyph: 'xf141@FontAwesome',
          },
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'form',
      codeName: 'multimode_edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '收款计划表格编辑视图工具栏',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'b3ed96724abb94526bcb1cc527e85b52',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'multimode_edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.payee_plan',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.payee_plan',
        id: 'update',
      },
      deformItemUpdates: [
        {
          codeName: 'get_result_amount',
          defiupdateDetails: [
            {
              id: 'last_result_amount',
            },
          ],
          scriptCode: 'data.last_result_amount = data.last_amount-data.amount',
          customCode: true,
          showBusyIndicator: true,
          name: '得出上一单金额应为多少',
          id: 'get_result_amount',
        },
        {
          codeName: 'add_project',
          appDEMethodId: 'add_project',
          defiupdateDetails: [
            {
              id: 'order_date',
            },
            {
              id: 'account_name',
            },
            {
              id: 'business_line',
            },
            {
              id: 'settlement_amount',
            },
          ],
          showBusyIndicator: true,
          name: '获取订单数据',
          id: 'add_project',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 5,
                      enableCond: 3,
                      itemWidth: 290,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'planned_time',
                      editor: {
                        dateTimeFormat: 'YYYY-MM-DD',
                        editorParams: {
                          TIMEFMT: 'YYYY-MM-DD',
                        },
                        editorType: 'DATEPICKEREX_NOTIME',
                        editorWidth: 100,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'planned_time',
                      },
                      resetItemNames: ['is_not_in_plan'],
                      valueFormat: 'YYYY-MM-DD',
                      allowEmpty: true,
                      caption: '计划收款日期',
                      codeName: 'planned_time',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 6,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'planned_time',
                    },
                    {
                      rawItem: {
                        caption: '(不填日期代表未列入收款计划)',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        sysCss: {
                          cssName: 'Center_Content',
                        },
                        id: 'rawitem1',
                      },
                      codeName: 'rawitem1',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colLG: 10,
                        colLGOffset: 1,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      sysCss: {
                        cssName: 'Center_Content',
                      },
                      showCaption: true,
                      id: 'rawitem1',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 6,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'amount',
                          deformItemUpdateId: 'get_result_amount',
                          editor: {
                            precision: 2,
                            editorType: 'NUMBER',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'amount',
                          },
                          unitName: '元',
                          valueFormat: '#,##0.00',
                          enableUnitName: true,
                          caption: '收款金额',
                          codeName: 'amount',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 8,
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          sysCss: {
                            cssName: 'input-right',
                          },
                          showCaption: true,
                          id: 'amount',
                        },
                        {
                          createDV: '10',
                          createDVT: 'PARAM',
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 190,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'plan_status',
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'plan_status',
                          },
                          allowEmpty: true,
                          hidden: true,
                          caption: '计划状态',
                          codeName: 'plan_status',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 6,
                            colMD: 12,
                            layout: 'TABLE_24COL',
                          },
                          id: 'plan_status',
                        },
                      ],
                      codeName: 'grouppanel2',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel2',
                    },
                  ],
                  codeName: 'grouppanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 21,
                      enableCond: 3,
                      itemHeight: 200,
                      labelPos: 'LEFT',
                      labelWidth: 190,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'description',
                      editor: {
                        maxLength: 32000,
                        showMaxLength: true,
                        editorHeight: 200,
                        editorParams: {
                          HEIGHT: '200',
                        },
                        editorType: 'TEXTAREA_10',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'description',
                      },
                      allowEmpty: true,
                      caption: '款项说明',
                      codeName: 'description',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 20,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'description',
                    },
                  ],
                  caption: '描述',
                  codeName: 'grouppanel3',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel3',
                },
              ],
              caption: '计划信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 190,
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'name',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.NAME',
              },
              caption: '名称',
              codeName: 'name',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'name',
            },
            {
              dataType: 9,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 190,
              noPrivDisplayMode: 1,
              appDEFieldId: 'is_not_in_plan',
              editor: {
                editorType: 'HIDDEN',
                editorItems: [
                  {
                    id: 'is_not_in_plan',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'is_not_in_plan',
              },
              allowEmpty: true,
              hidden: true,
              caption: '不能明确收款时间',
              codeName: 'is_not_in_plan',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 5,
                colLGOffset: 1,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'is_not_in_plan',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  itemWidth: 390,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'project_name',
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'crmweb.project_pickup_view',
                    handlerType: 'PickupText',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'crmweb.project',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'project_id',
                    editorParams: {
                      AC: 'TRUE',
                      n_status_eq: '10',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKER',
                    editorWidth: 200,
                    editorItems: [
                      {
                        id: 'project_id',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'project_name',
                  },
                  allowEmpty: true,
                  caption: '订单名称',
                  codeName: 'project_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'project_name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'project_id',
                  deformItemUpdateId: 'add_project',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'project_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '订单标识',
                  codeName: 'project_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'project_id',
                },
                {
                  dataType: 6,
                  enableCond: 3,
                  itemWidth: 340,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'settlement_amount',
                  editor: {
                    halign: 'LEFT',
                    precision: 2,
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    editorWidth: 150,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'settlement_amount',
                  },
                  allowEmpty: true,
                  caption: '业绩结算金额',
                  codeName: 'settlement_amount',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'settlement_amount',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  itemWidth: 340,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'business_line',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'crmweb.crm__industry',
                    editorType: 'SPAN',
                    editorWidth: 150,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'business_line',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  caption: '业务条线',
                  codeName: 'business_line',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 4,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'business_line',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'account_name',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'account_name',
                  },
                  allowEmpty: true,
                  caption: '订单客户',
                  codeName: 'account_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'account_name',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'order_date',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'order_date',
                  },
                  valueFormat: 'YYYY-MM-DD',
                  allowEmpty: true,
                  caption: '订单日期',
                  codeName: 'order_date',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'order_date',
                },
              ],
              caption: '订单信息',
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel5',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'last_amount',
                  },
                  allowEmpty: true,
                  caption: '上次计划金额',
                  codeName: 'last_amount',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'last_amount',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'last_result_amount',
                  },
                  allowEmpty: true,
                  caption: '拆分后上次计划的金额',
                  codeName: 'last_result_amount',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'last_result_amount',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 190,
                  noPrivDisplayMode: 1,
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'last_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  caption: '父订单标识',
                  codeName: 'last_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'last_id',
                },
              ],
              caption: '上次订单信息',
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              defdgroupLogics: [
                {
                  logicCat: 'PANELVISIBLE',
                  relatedDetailNames: ['view_mode'],
                  groupOP: 'AND',
                  defdlogics: [
                    {
                      condOP: 'EQ',
                      defdname: 'view_mode',
                      value: 'cut',
                      logicType: 'SINGLE',
                    },
                  ],
                  logicType: 'GROUP',
                },
              ],
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'grouppanel4',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 190,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 190,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'view_mode',
              },
              allowEmpty: true,
              hidden: true,
              caption: '页面模式',
              codeName: 'view_mode',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'view_mode',
            },
          ],
          caption: '概览',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'multimode_edit_view_form',
      controlType: 'FORM',
      logicName: '收款计划编辑视图表单',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {
        id: 'form',
      },
      modelId: '63bad8e68dd4daf2fe26aaaf0c9b227f',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.payee_plan.multimode_edit_view_form',
    },
    {
      codeName: 'multimode_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'multimode_edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAYEE_PLAN',
      },
      caption: '收款计划编辑视图',
      codeName: 'multimode_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.payee_plan',
      controlParam: {},
      name: 'captionbar',
      id: 'multimode_edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.payee_plan',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '收款计划编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'dc907fb214475804a0cb80ea66e508ca',
  modelType: 'PSAPPDEVIEW',
  name: 'payee_planmultimode_edit_view',
  id: 'crmweb.payee_plan_multimode_edit_view',
};
