export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_view_multimode',
  deviewId: 'c4f3092614e29436effcc88f2ff66367',
  accUserMode: 2,
  caption: '价格表',
  codeName: 'price_book_list_view_multimode',
  appDataEntityId: 'crmweb.price_book',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建价格表',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建价格表',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'importdata@price_book',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入价格表',
              itemType: 'DEUIACTION',
              tooltip: '导入价格表',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_importdata',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'import@note_attach',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入备注',
              itemType: 'DEUIACTION',
              tooltip: '导入备注',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_import',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysCss: {
            cssName: 'toolbar_group',
          },
          sysImage: {
            cssClass: 'fa fa-chevron-down',
            glyph: 'xf078@FontAwesome',
          },
          showIcon: true,
          id: 'items2',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'mgr_tags@price_book',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '管理标签',
              itemType: 'DEUIACTION',
              tooltip: '管理标签',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          valid: true,
          caption: '操作',
          itemType: 'ITEMS',
          tooltip: '操作',
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'list',
      codeName: 'list_view_multimode_toolbar',
      controlType: 'TOOLBAR',
      logicName: '价格表多模式列表视图_工具栏',
      appDataEntityId: 'crmweb.price_book',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'eb9224d592ea61fb0d6333e2804a21c7',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'list_view_multimode_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_view_multimode_search_form',
      controlType: 'SEARCHFORM',
      logicName: '价格表多模式列表视图_搜索表单',
      appDataEntityId: 'crmweb.price_book',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'cca4c2c677cc291cd7f3763397701c52',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.price_book.list_view_multimode_search_form',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        codeName: 'usr0318595478',
        controlType: 'PANEL',
        logicName: 'List_列表项面板',
        appDataEntityId: 'crmweb.price_book',
        controlParam: {},
        modelId: '258d349a64622e31f860b632ca055cb1',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'crmweb.price_book.usr0318595478',
      },
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.price_book',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'crmweb.price_book',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.price_book',
        id: 'load',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.price_book',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.price_book',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'list_view_multimode_list',
      controlType: 'LIST',
      logicName: 'List',
      appDataEntityId: 'crmweb.price_book',
      controlParam: {
        id: 'list',
      },
      modelId: '2b7f8894d2d6b934f71269566852bb41',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'crmweb.price_book.list_view_multimode_list',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.price_book',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '价格表',
      codeName: 'list_view_multimode_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.price_book',
      controlParam: {},
      name: 'captionbar',
      id: 'list_view_multimode_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.price_book',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '价格表',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a6480b6ed32ce0fe1c215a72f0ae1e84',
  modelType: 'PSAPPDEVIEW',
  name: 'price_booklist_view_multimode',
  id: 'crmweb.price_book_list_view_multimode',
};
