export default {
  enableDirtyChecking: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'attachment_view',
  deviewId: 'bd190d604ae2f3579094a6611d392dc7',
  accUserMode: 2,
  caption: '附件',
  codeName: 'price_book_attachment_view',
  appDataEntityId: 'crmweb.price_book',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: 'FORM',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            predefinedType: 'CONTAINER',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentHeight: 100,
            height: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              height: 100,
              heightMode: 'PERCENTAGE',
              layout: 'FLEX',
            },
            id: 'container3',
          },
        ],
        predefinedType: 'CONTAINER',
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'page_container',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView9',
        id: 'engine',
      },
    ],
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.price_book',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.price_book',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.price_book',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.price_book',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.price_book',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.price_book',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                actionGroupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '添加附件',
                      detailType: 'DEUIACTION',
                      uiactionId: 'add_attachments@price_book',
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-plus',
                        glyph: 'xf067@FontAwesome',
                      },
                      id: 'u631e661',
                    },
                  ],
                  appDataEntityId: 'crmweb.price_book',
                  uniqueTag: 'price_book__add_attachments',
                  name: '添加附件',
                  id: 'add_attachments',
                },
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    contentControl: {
                      aggMode: 'NONE',
                      columnEnableFilter: 2,
                      groupMode: 'NONE',
                      groupStyle: 'DEFAULT',
                      degridColumns: [
                        {
                          clconvertMode: 'NONE',
                          dataItemName: 'name',
                          excelCaption: '文件名',
                          appDEFieldId: 'name',
                          deuiactionGroup: {
                            uiactionGroupDetails: [
                              {
                                actionLevel: 250,
                                afterItemType: 'NONE',
                                beforeItemType: 'NONE',
                                buttonStyle: 'DEFAULT',
                                detailType: 'DEUIACTION',
                                uiactionId: 'download@attachment',
                                tooltip: '下载当前附件',
                                showIcon: true,
                                sysImage: {
                                  cssClass: 'fa fa-download',
                                  glyph: 'xf019@FontAwesome',
                                },
                                id: 'u99cc430',
                              },
                              {
                                actionLevel: 100,
                                afterItemType: 'NONE',
                                beforeItemType: 'NONE',
                                buttonStyle: 'DEFAULT',
                                caption: '删除',
                                detailType: 'DEUIACTION',
                                uiactionId: 'delete@attachment',
                                tooltip: '删除',
                                showCaption: true,
                                showIcon: true,
                                sysImage: {
                                  cssClass: 'fa fa-trash-o',
                                  glyph: 'xf014@FontAwesome',
                                },
                                id: 'uf033a67',
                              },
                            ],
                            appDataEntityId: 'crmweb.attachment',
                            uniqueTag: 'attachment__Usr0103721999',
                            name: '附件表格操作列',
                            id: 'usr0103721999',
                          },
                          valueType: 'SIMPLE',
                          aggMode: 'NONE',
                          align: 'LEFT',
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.NAME',
                          },
                          caption: '文件名',
                          codeName: 'name',
                          columnType: 'DEFGRIDCOLUMN',
                          noPrivDisplayMode: 1,
                          width: 250,
                          widthUnit: 'STAR',
                          enableSort: true,
                          id: 'name',
                        },
                        {
                          clconvertMode: 'FRONT',
                          dataItemName: 'create_man',
                          excelCaption: '附件添加者',
                          appCodeListId: 'crmweb.crm__sysoperator',
                          appDEFieldId: 'create_man',
                          valueType: 'SIMPLE',
                          aggMode: 'NONE',
                          align: 'LEFT',
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.CREATE_MAN',
                          },
                          caption: '附件添加者',
                          codeName: 'create_man',
                          columnType: 'DEFGRIDCOLUMN',
                          noPrivDisplayMode: 1,
                          width: 200,
                          widthUnit: 'STAR',
                          enableSort: true,
                          id: 'create_man',
                        },
                        {
                          clconvertMode: 'NONE',
                          dataItemName: 'update_time',
                          excelCaption: '添加的日期',
                          appDEFieldId: 'update_time',
                          valueFormat: 'YYYY-MM-DD HH:mm:ss',
                          valueType: 'SIMPLE',
                          aggMode: 'NONE',
                          align: 'LEFT',
                          capLanguageRes: {
                            lanResTag: 'DEF.LNAME.UPDATE_TIME',
                          },
                          caption: '添加的日期',
                          codeName: 'update_time',
                          columnType: 'DEFGRIDCOLUMN',
                          noPrivDisplayMode: 1,
                          width: 200,
                          widthUnit: 'STAR',
                          enableSort: true,
                          id: 'update_time',
                        },
                        {
                          clconvertMode: 'NONE',
                          dataItemName: 'owner_id',
                          excelCaption: '所属数据标识',
                          appDEFieldId: 'owner_id',
                          valueType: 'SIMPLE',
                          enableRowEdit: true,
                          aggMode: 'NONE',
                          align: 'LEFT',
                          caption: '所属数据标识',
                          codeName: 'owner_id',
                          columnType: 'DEFGRIDCOLUMN',
                          hideMode: 1,
                          noPrivDisplayMode: 1,
                          width: 100,
                          widthUnit: 'PX',
                          enableSort: true,
                          hideDefault: true,
                          id: 'owner_id',
                        },
                      ],
                      degridDataItems: [
                        {
                          appDEFieldId: 'name',
                          valueType: 'SIMPLE',
                          dataType: 25,
                          id: 'name',
                        },
                        {
                          appDEFieldId: 'create_man',
                          valueType: 'SIMPLE',
                          dataType: 25,
                          id: 'create_man',
                        },
                        {
                          format: 'YYYY-MM-DD HH:mm:ss',
                          appDEFieldId: 'update_time',
                          valueType: 'SIMPLE',
                          dataType: 5,
                          id: 'update_time',
                        },
                        {
                          appDEFieldId: 'owner_id',
                          valueType: 'SIMPLE',
                          dataType: 25,
                          id: 'owner_id',
                        },
                        {
                          appDEFieldId: 'file_id',
                          valueType: 'SIMPLE',
                          dataType: 25,
                          id: 'file_id',
                        },
                        {
                          appDEFieldId: 'id',
                          valueType: 'SIMPLE',
                          dataType: 25,
                          id: 'srfkey',
                        },
                        {
                          appDEFieldId: 'id',
                          valueType: 'SIMPLE',
                          dataType: 25,
                          id: 'srfdataaccaction',
                        },
                        {
                          appDEFieldId: 'name',
                          valueType: 'SIMPLE',
                          dataType: 25,
                          id: 'srfmajortext',
                        },
                      ],
                      degridEditItems: [
                        {
                          caption: '所属数据标识',
                          codeName: 'owner_id',
                          createDV: 'srfowner_id',
                          createDVT: 'APPDATA',
                          enableCond: 3,
                          appDEFieldId: 'owner_id',
                          editor: {
                            maxLength: 100,
                            editorType: 'TEXTBOX',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'owner_id',
                          },
                          allowEmpty: true,
                          id: 'owner_id',
                        },
                        {
                          caption: '标识',
                          codeName: 'srfkey',
                          enableCond: 3,
                          appDEFieldId: 'id',
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'srfkey',
                          },
                          allowEmpty: true,
                          id: 'srfkey',
                        },
                      ],
                      pagingSize: 20,
                      sortMode: 'REMOTE',
                      enableRowEdit: true,
                      enableRowNew: true,
                      navViewPos: 'NONE',
                      createControlAction: {
                        appDEMethodId: 'create',
                        appDataEntityId: 'crmweb.attachment',
                        id: 'create',
                      },
                      fetchControlAction: {
                        appDEMethodId: 'fetchdefault',
                        appDataEntityId: 'crmweb.attachment',
                        id: 'fetch',
                      },
                      getDraftControlAction: {
                        appDEMethodId: 'getdraft',
                        appDataEntityId: 'crmweb.attachment',
                        id: 'loaddraft',
                      },
                      getControlAction: {
                        appDEMethodId: 'get',
                        appDataEntityId: 'crmweb.attachment',
                        id: 'load',
                      },
                      removeControlAction: {
                        appDEMethodId: 'remove',
                        appDataEntityId: 'crmweb.attachment',
                        id: 'remove',
                      },
                      updateControlAction: {
                        appDEMethodId: 'update',
                        appDataEntityId: 'crmweb.attachment',
                        id: 'update',
                      },
                      autoLoad: true,
                      showBusyIndicator: true,
                      codeName: 'attachment',
                      controlStyle: 'ATTACHMENT_GRID',
                      controlType: 'GRID',
                      logicName: '附件表格',
                      appDataEntityId: 'crmweb.attachment',
                      controlLogics: [
                        {
                          eventNames: 'onLoadSuccess',
                          logicTag: 'attachments_grid',
                          logicType: 'APPDEUILOGIC',
                          appDEUILogicId: 'calc_attachment_hidden',
                          appDataEntityId: 'crmweb.attachment',
                          triggerType: 'CTRLEVENT',
                          id: 'logic2',
                        },
                      ],
                      controlParam: {},
                      sysPFPluginId: 'attachment_grid',
                      modelId: 'dd007d8834df66bbd116cebc73b93e82',
                      modelType: 'PSDEGRID',
                      name: 'attachments_grid',
                      id: 'crmweb.attachment.attachment',
                    },
                    contentType: 'GRID',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    codeName: 'attachments',
                    detailStyle: 'DEFAULT',
                    detailType: 'MDCTRL',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'attachments',
                  },
                ],
                caption: '附件',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'attachment_view_form',
        controlType: 'FORM',
        logicName: '附件_表单',
        appDataEntityId: 'crmweb.price_book',
        controlParam: {
          id: 'form',
        },
        modelId: '1c57dbdf540b7441753380900ed14022',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'crmweb.price_book.attachment_view_form',
      },
      {
        caption: '附件',
        codeName: 'attachment_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.price_book',
        controlParam: {},
        name: 'captionbar',
        id: 'attachment_view_captionbar',
      },
    ],
    codeName: 'usr0322943168',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'attachment_viewDEEDITVIEW',
    appDataEntityId: 'crmweb.price_book',
    controlParam: {},
    modelId: '4cef85f4472ed626f975a9457fdd568e',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0322943168',
  },
  title: '附件',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW9',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a129c93b943456c6fe5400fc904c5053',
  modelType: 'PSAPPDEVIEW',
  name: 'price_bookattachment_view',
  id: 'crmweb.price_book_attachment_view',
};
