export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'main_view',
  deviewId: '5c3f815078207b9af9eb72726372a97a',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PRODUCT_CERTIFICATE',
  },
  caption: '产品证书信息',
  codeName: 'product_certificate_main_view',
  appDataEntityId: 'crmweb.product_certificate',
  appViewNavContexts: [
    {
      key: 'N_OWNER_ID_EQ',
      value: 'product_certificate',
      name: 'N_OWNER_ID_EQ',
      id: 'n_owner_id_eq',
    },
    {
      key: 'OWNER_ID',
      value: 'product_certificate',
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      key: 'PRINCIPAL_ID',
      value: 'product_certificate',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'OWNER_TYPE',
      value: 'PRODUCT_CERTIFICATE',
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'PRODUCT_CERTIFICATE',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'product_certificate',
      id: 'n_owner_id_eq',
    },
    {
      key: 'principal_id',
      value: 'product_certificate',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'owner_type',
      value: 'PRODUCT_CERTIFICATE',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'principal_type',
      value: 'PRODUCT_CERTIFICATE',
      id: 'principal_type',
    },
    {
      key: 'owner_id',
      value: 'product_certificate',
      id: 'owner_id',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionType: 'UIACTION',
                        buttonStyle: 'INFO',
                        buttonType: 'PANELBUTTON',
                        uiactionId: 'editview_exitaction',
                        renderMode: 'BUTTON',
                        tooltip: '退出',
                        capLanguageRes: {
                          lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
                        },
                        caption: '退出',
                        itemStyle: 'INFO',
                        itemType: 'BUTTON',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysImage: {
                          cssClass: 'fa fa-arrow-left',
                          glyph: 'xf060@FontAwesome',
                        },
                        id: 'button_calluilogic',
                      },
                      {
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 70,
                          editorParams: {
                            MAXCOUNT: '1',
                          },
                          editorStyle: 'CRM_IMAGE_UPLOAD',
                          editorType: 'PICTURE_ONE',
                          editorWidth: 70,
                          sysPFPluginId: 'crm_image_upload',
                          predefinedType: 'FIELD_TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_textbox',
                        },
                        allowEmpty: true,
                        caption: '文本框',
                        contentHeight: 70,
                        contentWidth: 70,
                        height: 70,
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          height: 70,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 70,
                          widthMode: 'PX',
                        },
                        width: 70,
                        id: 'field_textbox',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfmajortext',
                        },
                        viewFieldName: 'srfmajortext',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'srfmajortext',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataName: 'srfactiveviewdata',
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'VIEWSESSIONPARAM',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系数据栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'drbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_drbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_exp_content',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView2',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_edit_view@product_certificate',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '编辑',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-edit',
              glyph: 'xf044@FontAwesome',
            },
            tooltip: '编辑',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction4',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'editview_copyaction',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.COPY',
                },
                caption: '复制',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-copy',
                  glyph: 'xf0c5@FontAwesome',
                },
                tooltip: '复制',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.COPY',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'editview_removeandexitaction',
                uiactionTarget: 'SINGLEKEY',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                },
                caption: '删除并关闭',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除并关闭',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-ellipsis-h',
              glyph: 'xf141@FontAwesome',
            },
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_prevrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '上一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-left',
              glyph: 'xf053@FontAwesome',
            },
            tooltip: '上一个记录',
            showIcon: true,
            id: 'deuiaction6',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_nextrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '下一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-right',
              glyph: 'xf054@FontAwesome',
            },
            tooltip: '下一个记录',
            showIcon: true,
            id: 'deuiaction7',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '产品证书主数据视图_工具栏',
        appDataEntityId: 'crmweb.product_certificate',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '7a5b1c9eea8adf399180b4887665bab8',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.product_certificate',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.product_certificate',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.product_certificate',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.product_certificate',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.product_certificate',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.product_certificate',
          id: 'update',
        },
        infoFormMode: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.NAME',
                    },
                    caption: '证书名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'pc_number',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'pc_number',
                    },
                    allowEmpty: true,
                    caption: '证书编号',
                    codeName: 'pc_number',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'pc_number',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'awarding_organization',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'awarding_organization',
                    },
                    allowEmpty: true,
                    caption: '颁证机构',
                    codeName: 'awarding_organization',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'awarding_organization',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'accredited_organization',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'accredited_organization',
                    },
                    allowEmpty: true,
                    caption: '受证单位',
                    codeName: 'accredited_organization',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'accredited_organization',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'service_name',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'service_name',
                    },
                    allowEmpty: true,
                    caption: '产品/服务名称及型号',
                    codeName: 'service_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'service_name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'scope',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'scope',
                    },
                    allowEmpty: true,
                    caption: '认证范围',
                    codeName: 'scope',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'scope',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'start_date',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'start_date',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    caption: '有效期起',
                    codeName: 'start_date',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'start_date',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'end_date',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'end_date',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    caption: '有效期止',
                    codeName: 'end_date',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'end_date',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'issue_date',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'issue_date',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    caption: '签发日期',
                    codeName: 'issue_date',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'issue_date',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'issue_man',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'issue_man',
                    },
                    allowEmpty: true,
                    caption: '签发人',
                    codeName: 'issue_man',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'issue_man',
                  },
                  {
                    dataType: 21,
                    enableCond: 3,
                    itemHeight: 200,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'description',
                    editor: {
                      maxLength: 32000,
                      showMaxLength: true,
                      editorHeight: 200,
                      editorParams: {
                        redonly: 'true',
                        HEIGHT: '200',
                      },
                      editorType: 'TEXTAREA_10',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'description',
                    },
                    allowEmpty: true,
                    caption: '描述',
                    codeName: 'description',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'description',
                  },
                ],
                caption: '证书信息',
                codeName: 'grouppanel7',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 16,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel7',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                caption: '描述',
                codeName: 'grouppanel3',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 24,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel3',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 190,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '概览',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                caption: '历史信息',
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel1',
              },
            ],
            caption: '时间轴',
            codeName: 'formpage2',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage2',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main_view_form',
        controlStyle: 'ANCHOR_STYLE',
        controlType: 'FORM',
        logicName: '产品证书主数据视图_表单',
        appDataEntityId: 'crmweb.product_certificate',
        controlParam: {
          id: 'form',
        },
        sysPFPluginId: 'anchor_style',
        modelId: 'c21419ce33a507b298d36ca118fc62b8',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'crmweb.product_certificate.main_view_form',
      },
      {
        dedrbarGroups: [
          {
            caption: '详细信息',
            name: '详细信息',
            id: 'drgroup',
          },
        ],
        showTitle: true,
        dataRelationTag: 'main_view_DR',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.PRODUCT_CERTIFICATE',
        },
        editItemCaption: '产品证书',
        appCounterRefId: '9e59c9fb5ae5abfa5284734d4631ffbc',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'drgroup',
            caption: '附件',
            appViewId: 'crmweb.product_certificate_attachment_view',
            id: 'note',
          },
        ],
        uniqueTag: 'product_certificate_main_view__drbar',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'product_certificate_main_view_dr',
              counterType: 'DEDR',
              getAppDEActionId: 'main_view_dr_count',
              appDataEntityId: 'crmweb.product_certificate',
              timer: 60000,
              uniqueTag: 'product_certificate_main_view_dr',
              name: '产品证书main_view关系',
              id: 'crmweb.product_certificate_main_view_dr',
            },
            refMode: {
              srfdeid: 'PRODUCT_CERTIFICATE',
            },
            tag: '9e59c9fb5ae5abfa5284734d4631ffbc',
            uniqueTag: 'product_certificate_main_view_dr',
            id: '9e59c9fb5ae5abfa5284734d4631ffbc',
          },
        ],
        codeName: 'main_view_dr',
        controlStyle: 'DRBAR_ANCHOR_STYLE',
        controlType: 'DRBAR',
        appDataEntityId: 'crmweb.product_certificate',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'drbar_anchor_style',
        modelId: 'e7cf82b7ef9575649aa8dd815a3b0c21',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'main_view_dr',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'crmweb.product_certificate',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.PRODUCT_CERTIFICATE',
        },
        caption: '产品证书信息',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.product_certificate',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'usr0319628389',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主数据通用布局面板',
    appDataEntityId: 'crmweb.product_certificate',
    controlParam: {},
    modelId: '6169ec687d45a098f7102272c1f7c4ca',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0319628389',
  },
  title: '产品证书信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'dbf80c164740f9d7bc5a29a1c787d678',
  modelType: 'PSAPPDEVIEW',
  name: 'product_certificatemain_view',
  id: 'crmweb.product_certificate_main_view',
};
