export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'data_view_multimode',
  deviewId: '12bcc9fb1a5d611c56823ec6f2520fa4',
  accUserMode: 2,
  caption: '产品',
  codeName: 'product_data_view_multimode',
  appDataEntityId: 'crmweb.product',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.product_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.product_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.product_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.product_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '产品编辑视图',
      refAppViewId: 'crmweb.product_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '产品编辑视图',
      refAppViewId: 'crmweb.product_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建产品',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建产品',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'importdata@product',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入产品',
              itemType: 'DEUIACTION',
              tooltip: '导入产品',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_importdata',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'import@note_attach',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入备注',
              itemType: 'DEUIACTION',
              tooltip: '导入备注',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_import',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysCss: {
            cssName: 'toolbar_group',
          },
          sysImage: {
            cssClass: 'fa fa-chevron-down',
            glyph: 'xf078@FontAwesome',
          },
          showIcon: true,
          id: 'items2',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'mgr_tags@product',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '管理标签',
              itemType: 'DEUIACTION',
              tooltip: '管理标签',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          valid: true,
          caption: '操作',
          itemType: 'ITEMS',
          tooltip: '操作',
          showCaption: true,
          showIcon: true,
          id: 'items1',
        },
      ],
      xdataControlName: 'dataview',
      codeName: 'data_view_multimode_toolbar',
      controlType: 'TOOLBAR',
      logicName: '产品多模式卡片视图_工具栏',
      appDataEntityId: 'crmweb.product',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'fb55ead15c14660d3cc425f2f7e2173d',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'data_view_multimode_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_view_multimode_search_form',
      controlType: 'SEARCHFORM',
      logicName: '产品多模式卡片视图_搜索表单',
      appDataEntityId: 'crmweb.product',
      controlParam: {
        id: 'searchform',
      },
      modelId: '0d61a42b00cacd6cdf3a7a9f548b30c6',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.product.data_view_multimode_search_form',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        codeName: 'usr0318649260',
        controlType: 'PANEL',
        logicName: '客户多模式卡片视图_卡片视图_卡片面板',
        appDataEntityId: 'crmweb.product',
        controlParam: {},
        modelId: '3b07cf138f4605830252a58ffe4d390c',
        modelType: 'PSSYSVIEWPANEL',
        name: 'itemlayoutpanel',
        id: 'crmweb.product.usr0318649260',
      },
      dedataViewDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'product_name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'vendor_id',
          dataType: 25,
          id: 'vendor_id',
        },
      ],
      pagingSize: 1000,
      appendDEItems: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.product',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'crmweb.product',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.product',
        id: 'load',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.product',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.product',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'data_view_multimode_data_view',
      controlType: 'DATAVIEW',
      logicName: '产品多模式卡片视图_卡片视图',
      appDataEntityId: 'crmweb.product',
      controlParam: {
        id: 'dataview',
      },
      modelId: '5aab22abbb287da15528b3461c56aaf3',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'crmweb.product.data_view_multimode_data_view',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.product',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '产品',
      codeName: 'data_view_multimode_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.product',
      controlParam: {},
      name: 'captionbar',
      id: 'data_view_multimode_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.product',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '产品',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '38b86b252a03b6e67b1e9d161cf27ce9',
  modelType: 'PSAPPDEVIEW',
  name: 'productdata_view_multimode',
  id: 'crmweb.product_data_view_multimode',
};
