export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: '52f57ed0cb6f2a9cdb53053b48e5610b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PRODUCT_CERTIFICATE',
  },
  caption: '产品证书',
  codeName: 'product_certificate_grid_view',
  appDataEntityId: 'crmweb.product_certificate',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.product_certificate_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.product_certificate_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.product_certificate_main_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.product_certificate_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '产品证书编辑视图',
      refAppViewId: 'crmweb.product_certificate_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '产品证书信息',
      refAppViewId: 'crmweb.product_certificate_main_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.PRODUCT_CERTIFICATE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'crmweb.product_certificate',
      controlParam: {
        id: 'searchform',
      },
      modelId: '689bb79c02bdf0a211c7a2ea17d3dad6',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.product_certificate.default',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '证书名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '证书名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'pc_number',
          excelCaption: '证书编号',
          appDEFieldId: 'pc_number',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '证书编号',
          codeName: 'pc_number',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'pc_number',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'issue_date',
          excelCaption: '签发日期',
          appDEFieldId: 'issue_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '签发日期',
          codeName: 'issue_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'issue_date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'start_date',
          excelCaption: '有效期起',
          appDEFieldId: 'start_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '有效期起',
          codeName: 'start_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'start_date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'end_date',
          excelCaption: '有效期止',
          appDEFieldId: 'end_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '有效期止',
          codeName: 'end_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'end_date',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'pc_number',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'pc_number',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'issue_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'issue_date',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'start_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'start_date',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'end_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'end_date',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'product_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'product_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      forceFit: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_all',
        appDataEntityId: 'crmweb.product_certificate',
        id: 'fetch',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.product_certificate',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'create_task@product_certificate',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '创建任务',
              itemType: 'DEUIACTION',
              tooltip: '创建任务',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'add_tags@product_certificate',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '添加标签',
                  itemType: 'DEUIACTION',
                  tooltip: '添加标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'delete_tags@product_certificate',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '移除标签',
                  itemType: 'DEUIACTION',
                  tooltip: '移除标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction3',
                },
              ],
              valid: true,
              caption: '标签',
              itemType: 'ITEMS',
              tooltip: '标签',
              showCaption: true,
              showIcon: true,
              id: 'items1',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'batch_update@product_certificate',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '批量更新',
                  itemType: 'DEUIACTION',
                  tooltip: '批量更新',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction4',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'remove@product_certificate',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction5',
                },
              ],
              valid: true,
              caption: '操作',
              itemType: 'ITEMS',
              tooltip: '操作',
              showCaption: true,
              showIcon: true,
              id: 'items2',
            },
          ],
          codeName: 'grid_view_grid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '批操作_工具栏',
          appDataEntityId: 'crmweb.product_certificate',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: 'f2a5a1f700501082b67355c4bde01d35',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'grid_view_grid_batchtoolbar',
        },
      ],
      codeName: 'grid_view_multimode_grid',
      controlType: 'GRID',
      logicName: '产品证书多模式表格视图_表格',
      appDataEntityId: 'crmweb.product_certificate',
      controlParam: {
        ctrlParams: {
          SHOWMODE: 'MIXIN',
        },
        id: 'grid',
      },
      modelId: 'df7b89ce033cd0588f0ff659edaa0629',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.product_certificate.grid_view_multimode_grid',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建产品证书',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建产品证书',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '产品证书多模式表格视图_工具栏',
      appDataEntityId: 'crmweb.product_certificate',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'e80a8e765c62d3b6aceddb2bc9c30afe',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.product_certificate',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PRODUCT_CERTIFICATE',
      },
      caption: '产品证书',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.product_certificate',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.product_certificate',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '产品证书表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PRODUCT_CERTIFICATE.GRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a975d11ab06629526053eb1b16fe0ad3',
  modelType: 'PSAPPDEVIEW',
  name: 'product_certificateGridView',
  id: 'crmweb.product_certificate_grid_view',
};
