export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'chart_exp_view',
  deviewId: '8f1a38b9a44f8d93d61fb5bc7789c0a7',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT',
  },
  caption: '签单情况统计',
  codeName: 'project_chart_exp_view',
  appDataEntityId: 'crmweb.project',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        caption: '搜索表单',
                        itemStyle: 'DEFAULT',
                        itemType: 'CTRLPOS',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'searchform',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 70,
                    height: 70,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 70,
                      heightMode: 'PX',
                      layout: 'FLEX',
                    },
                    id: 'container3',
                  },
                  {
                    caption: '图表导航',
                    cssStyle: 'position: relative',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'chartexpbar',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  heightMode: 'FULL',
                  layout: 'TABLE_24COL',
                },
                id: 'container',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container1',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  colMD: 24,
                  heightMode: 'FULL',
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container2',
          },
        ],
        predefinedType: 'CONTAINER_V_SPLIT',
        layout: {
          layout: 'SIMPLEFLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '分割容器(上下)',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'view_exp_split',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        eventNames: 'onCreated',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, c) => {\r\n    if(name==='searchform'){\r\n        const time = new Date();\r\n\t\t\t\tconst currentYear = time.getFullYear();\r\n\t\t\t\tconst nextYear = currentYear + 1;\r\n\t\t\t\tconst gt = currentYear + '-01-01'\r\n        const lt = nextYear+ '-01-01'\r\n        const date_range = gt + ',' + lt;\r\n        Object.assign(c.params, {gt,lt,date_range})\r\n    }\r\n    if(name==='chartexpbar_chart'){\r\n        const searchForm = view.getController('searchform');\r\n        c.evt.on('onBeforeLoad', () => {\r\n            c.state.searchParams = searchForm.getFilterParams();\r\n            c.params = searchForm.getFilterParams();\r\n        });\r\n    }\r\n});",
        builtinLogic: true,
        name: 'LOGIC',
        id: 'logic',
      },
      {
        eventNames: 'onViewMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        scriptCode:
          "const searchForm = view.getController('searchform');\r\nconst xdataControlName = 'chartexpbar_chart';\r\nconst xdataControl = view.getController(xdataControlName);\r\nif (searchForm && xdataControl) {\r\n    searchForm.evt.on('onSearch', () => {\r\n      xdataControl.state.searchParams={};\r\n      xdataControl.params={};\r\n        xdataControl.load({ isInitialLoad: true });\r\n    });\r\n}\r\n// 点击图表空白区域\r\nxdataControl.chart.getZr().on('click', function(event) {\r\n  if (!event.target) {\r\n    const { series } = xdataControl.options;\r\n    if (series && series.length > 0) {\r\n      // 取消选中\r\n      const seriesName = series.map(x => x.name);\r\n      const maxLength = Math.max(...series.map(x => x.data.length))\r\n\t    xdataControl.chart.dispatchAction({\r\n          type: 'unselect',\r\n          seriesName,\r\n          dataIndex: [...Array(maxLength).keys()],\r\n      });\r\n    }\r\n    // 刷新表格\r\n    ibiz.util.action.execAndResolved(\r\n      'nav_project_grid@project',\r\n      {\r\n        context: view.context,\r\n        data: [],\r\n        view: view,\r\n      },\r\n      view.context.srfappid,\r\n    );\r\n  }\r\n});",
        builtinLogic: true,
        name: 'LOGIC2',
        id: 'logic2',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        xdataControlName: 'chartexpbar_chart',
        enableCounter: true,
        showTitleBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        appViewRefs: [
          {
            realTitle: '签单分析',
            refAppViewId: 'crmweb.project_order_analysis_grid_view',
            name: 'EXPITEM:bar',
            id: 'expitem:bar',
          },
        ],
        controls: [
          {
            coordinateSystem: 'XY',
            chartCoordinateSystems: [
              {
                chartGrid: {
                  chartGridXAxis0Id: '0',
                  chartGridYAxis0Id: '0',
                  chartCoordinateSystemId: '0',
                  type: 'grid',
                  name: '[bar_0]直角坐标系[0]',
                  id: '0',
                },
                echartsType: 'cartesian2d',
                type: 'XY',
                name: '[bar_0]直角坐标系[0]',
                id: '0',
              },
            ],
            dechartDataGrid: {
              id: '0',
            },
            dechartLegend: {
              id: '0',
            },
            dechartSerieses: [
              {
                caption: '订单金额',
                catalogField: 'ORDER_DATE',
                echartsType: 'bar',
                groupMode: 'MONTH',
                chartCoordinateSystemId: '0',
                chartDataSetId: '0',
                chartSeriesEncode: {
                  chartXAxisId: '0',
                  chartYAxisId: '0',
                  x: ['ORDER_DATE'],
                  y: ['AMOUNT'],
                  type: 'XY',
                  name: '坐标系编码',
                  id: '0',
                },
                seriesLayoutBy: 'column',
                seriesType: 'bar',
                valueField: 'AMOUNT',
                enableChartDataSet: true,
                navAppViewId: 'crmweb.project_order_analysis_grid_view',
                navigateParams: [
                  {
                    key: 'order_date',
                    value: 'ORDER_DATE',
                    id: 'order_date',
                  },
                  {
                    key: 'lt',
                    value: 'lt',
                    id: 'lt',
                  },
                  {
                    key: 'gt',
                    value: 'gt',
                    id: 'gt',
                  },
                  {
                    key: 'n_executors_exists__n_user_id_eq',
                    value: 'n_executors_exists__n_user_id_eq',
                    id: 'n_executors_exists__n_user_id_eq',
                  },
                  {
                    key: 'n_business_line_eq',
                    value: 'n_business_line_eq',
                    id: 'n_business_line_eq',
                  },
                ],
                userParam: {
                  'EC.label': '{"show":1,"fontSize":15}',
                  'EC.select':
                    "function (){ return {label: {fontSize: 20},labelLine: {show: false},itemStyle: {borderWidth: 0,shadowBlur: 0,shadowColor: 'transparent',borderColor: 'transparent', borderMiterLimit: 0,borderColor:'orange',borderWidth:5}}}()",
                  'EC.barWidth': '40',
                  'EC.selectedMode': 'single',
                  'EC.stack': "'chart'",
                },
                id: 'bar_0',
              },
            ],
            dechartTitle: {
              title: '签单情况统计_图表',
              id: '0',
            },
            chartDataSetGroups: [
              {
                appDEDataSetId: 'fetch_order_statistics',
                appDataEntityId: 'crmweb.project',
                name: 'OrderStatistics',
                id: '0',
              },
            ],
            chartDataSets: [
              {
                chartDataSetFields: [
                  {
                    groupMode: 'MONTH',
                    groupField: true,
                    name: 'ORDER_DATE',
                    id: '0',
                  },
                  {
                    index: 1,
                    name: 'AMOUNT',
                    id: '1',
                  },
                ],
                name: 'bar_0-OrderStatistics',
                id: '0',
              },
            ],
            chartGrids: [
              {
                chartGridXAxis0Id: '0',
                chartGridYAxis0Id: '0',
                chartCoordinateSystemId: '0',
                type: 'grid',
                name: '[bar_0]直角坐标系[0]',
                id: '0',
              },
            ],
            chartXAxises: [
              {
                echartsPos: 'xAxis',
                echartsType: 'category',
                position: 'bottom',
                type: 'category',
                userParam: {
                  'EC.interval': '0',
                  'EC.nameLocation': '"BOTTOM"',
                  'EC.nameRotate': '45',
                  'EC.axisLabel': 'function (){ return { interval: 0 }}()',
                },
                name: 'axis_xAxis_0',
                id: '0',
              },
            ],
            chartYAxises: [
              {
                caption: '订单金额',
                echartsPos: 'yAxis',
                echartsType: 'value',
                position: 'left',
                type: 'numeric',
                userParam: {
                  'EC.axisTick': '{"show":0}',
                  'EC.axisLabel': '{"show":0}',
                },
                name: 'axis_yAxis_0',
                id: '0',
              },
            ],
            navViewPos: 'NONE',
            fetchControlAction: {
              appDEMethodId: 'fetch_order_statistics',
              appDataEntityId: 'crmweb.project',
              id: 'fetch',
            },
            readOnly: true,
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'chart_exp_view_chart',
            controlType: 'CHART',
            logicName: 'Chart',
            appDataEntityId: 'crmweb.project',
            controlLogics: [
              {
                eventNames: 'onAtive',
                logicTag: 'chartexpbar_chart',
                logicType: 'SCRIPT',
                scriptCode:
                  "const { _groupName, _catalog } = data[0];\r\nconst { series } = ctrl.options;\r\nif (series && series.length > 0) {\r\n\t// 取消选中\r\n\tconst seriesName = series.map(x => x.name);\r\n    const maxLength = Math.max(...series.map(x => x.data.length))\r\n\tctrl.chart.dispatchAction({\r\n        type: 'unselect',\r\n        seriesName,\r\n        dataIndex: [...Array(maxLength).keys()],\r\n    });\r\n    // 设置选中\r\n    ctrl.chart.dispatchAction({\r\n        type: 'select',\r\n        seriesName: _groupName,\r\n        name: _catalog,\r\n    });\r\n}",
                triggerType: 'CTRLEVENT',
                name: 'onAtive',
                id: 'onative',
              },
              {
                eventNames: 'onBeforeUpdate',
                logicTag: 'chartexpbar_chart',
                logicType: 'SCRIPT',
                scriptCode:
                  "const { series } = ctrl.options;\r\nif (series && series.length > 0) {\r\n    series.forEach(item => {\r\n        if (item.label) {\r\n            item.label.formatter = function (params) {\r\n                if(params.value[1] === 0)\r\n                {\r\n                    return '';\r\n                }\r\n                else\r\n                {\r\n                    return ibiz.util.text.format(params.value[1], '#,##0.00');\r\n                }\r\n            };\r\n        }\r\n    });\r\n};",
                triggerType: 'CTRLEVENT',
                name: 'onBeforeUpdate',
                id: 'onbeforeupdate',
              },
              {
                eventNames: 'onLoadSuccess',
                logicTag: 'chartexpbar_chart',
                logicType: 'APPDEUIACTION',
                appDEUIActionId: 'nav_project_grid@project',
                triggerType: 'CTRLEVENT',
                id: 'nav',
              },
              {
                eventNames: 'SELECTIONCHANGE',
                logicTag: 'chartexpbar_chart',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'chartexpbar_selectionchange',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'chartexpbar_chart',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'chartexpbar_load',
              },
            ],
            controlParam: {
              id: 'chartexpbar_chart',
            },
            modelId: 'a9731c4ded4e1eb97fa33d2019d2d36b',
            modelType: 'PSDECHART',
            userParam: {
              'EC.color':
                '["#5470c6","#91cc75","#fac858","#ee6666","#73c0de","#3ba272","#fc8452","#9a60b4","#ea7ccc","#5470c6","#91cc75"]',
            },
            name: 'chartexpbar_chart',
            id: 'crmweb.project.chart_exp_view_chart',
          },
        ],
        codeName: 'chart_exp_view_chartexpbar',
        controlType: 'CHARTEXPBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'chartexpbar',
        },
        modelId: 'e5a3e7081f53f7b0364a293ab4f6da2b_chartexpbar',
        modelType: 'PSEXPBAR',
        name: 'chartexpbar',
        id: 'chart_exp_view_chartexpbar',
      },
      {
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                fieldName: 'user_name',
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  enablePickupView: true,
                  singleSelect: true,
                  pickupAppViewId: 'crmweb.user_m_pickup_view',
                  appDEACModeId: 'default',
                  appDEDataSetId: 'fetch_all',
                  appDataEntityId: 'crmweb.user',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  valueItemName: 'user_id',
                  editorParams: {
                    AC: 'TRUE',
                    PICKUPVIEW: 'TRUE',
                  },
                  editorType: 'PICKER',
                  editorItems: [
                    {
                      id: 'user_id',
                    },
                  ],
                  placeHolder: '全部执行人',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'user_name',
                },
                allowEmpty: true,
                caption: '执行人',
                codeName: 'user_name',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'user_name',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'business_line',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'crmweb.crm__industry',
                  editorParams: {
                    blankItemName: '全部条线',
                  },
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_business_line_eq',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '业务条线',
                codeName: 'n_business_line_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_business_line_eq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorParams: {
                    TIMEFMT: 'YYYY-MM-DD',
                    format: 'YYYY-DD',
                  },
                  editorType: 'DATERANGE_NOTIME',
                  editorItems: [
                    {
                      id: 'gt',
                    },
                    {
                      id: 'lt',
                    },
                  ],
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'date_range',
                },
                allowEmpty: true,
                caption: '统计范围',
                codeName: 'date_range',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                controlAttributes: [
                  {
                    attrName: 'type',
                    attrValue: '"monthrange"',
                    id: 'monthrange',
                  },
                ],
                layoutPos: {
                  colLG: 8,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'date_range',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'gt',
                },
                allowEmpty: true,
                hidden: true,
                caption: '订单日期(大于等于)',
                codeName: 'gt',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'gt',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'lt',
                },
                allowEmpty: true,
                hidden: true,
                caption: '订单日期(小于)',
                codeName: 'lt',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'lt',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'owner',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_owner_eq',
                },
                allowEmpty: true,
                hidden: true,
                caption: '所有者',
                codeName: 'n_owner_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_owner_eq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'user_id',
                },
                allowEmpty: true,
                hidden: true,
                codeName: 'user_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'user_id',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'chart_exp_view_search_form',
        controlType: 'SEARCHFORM',
        logicName: '签单分析_搜索表单',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'searchform',
        },
        modelId: '9c48feebd8fdcd81fdd25730be02d6eb',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.project.chart_exp_view_search_form',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.PROJECT',
        },
        caption: '签单情况统计',
        codeName: 'chart_exp_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {},
        name: 'captionbar',
        id: 'chart_exp_view_captionbar',
      },
    ],
    codeName: 'usr0617245522',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'chart_exp_view图表导航视图布局面板',
    appDataEntityId: 'crmweb.project',
    controlParam: {},
    modelId: '417322f38b62f1ca2b406d428253f3be',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0617245522',
  },
  title: '签单情况统计',
  viewStyle: 'DEFAULT',
  viewType: 'DECHARTEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'e5a3e7081f53f7b0364a293ab4f6da2b',
  modelType: 'PSAPPDEVIEW',
  name: 'projectchart_exp_view',
  id: 'crmweb.project_chart_exp_view',
};
