export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: '2ec7906c00c1a2cb713e19c35144bd8a',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT',
  },
  caption: '订单',
  codeName: 'project_pickup_view',
  appDataEntityId: 'crmweb.project',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'crmweb.project_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'crmweb.project',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PROJECT',
      },
      caption: '订单',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.project',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.project',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '订单数据选择视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PROJECT.PICKUPVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3621854bad672e30ca05cc6ff1291aae',
  modelType: 'PSAPPDEVIEW',
  name: 'projectPickupView',
  id: 'crmweb.project_pickup_view',
};
