export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: 'd91f8eb9c01d390b316a116ba7b8e933',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT',
  },
  caption: '订单',
  codeName: 'project_pickup_grid_view',
  appDataEntityId: 'crmweb.project',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '订单名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '订单名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'business_line',
          excelCaption: '业务条线',
          appCodeListId: 'crmweb.crm__business_line',
          appDEFieldId: 'business_line',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '业务条线',
          codeName: 'business_line',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 80,
          widthUnit: 'PX',
          enableSort: true,
          id: 'business_line',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'settlement_cost',
          excelCaption: '结算成本',
          appDEFieldId: 'settlement_cost',
          unitName: '元',
          valueFormat: '￥#,##0.00',
          valueType: 'SIMPLE',
          enableUnitName: true,
          aggMode: 'NONE',
          align: 'RIGHT',
          caption: '结算成本',
          codeName: 'settlement_cost',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'settlement_cost',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'amount',
          excelCaption: '订单金额',
          appDEFieldId: 'amount',
          unitName: '元',
          valueFormat: '￥#,##0.00',
          valueType: 'SIMPLE',
          enableUnitName: true,
          aggMode: 'NONE',
          align: 'RIGHT',
          caption: '订单金额',
          codeName: 'amount',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'amount',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'executors',
          excelCaption: '执行人',
          objectIdField: 'id',
          objectNameField: 'name',
          appDEFieldId: 'executors',
          valueType: 'OBJECTS',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '执行人',
          codeName: 'executors',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'PX',
          id: 'executors',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'business_line',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'business_line',
        },
        {
          format: '￥#,##0.00',
          appDEFieldId: 'settlement_cost',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'settlement_cost',
        },
        {
          format: '￥#,##0.00',
          appDEFieldId: 'amount',
          valueType: 'SIMPLE',
          dataType: 6,
          id: 'amount',
        },
        {
          appDEFieldId: 'executors',
          valueType: 'OBJECTS',
          dataType: 21,
          id: 'executors',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'account_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'account_id',
        },
        {
          appDEFieldId: 'pid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'pid',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_all',
        appDataEntityId: 'crmweb.project',
        id: 'fetch',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.project',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'crmweb.project',
      controlParam: {
        id: 'grid',
      },
      modelId: '4f126a8af59324f2eeb533410af6253c',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.project.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_name_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.PROJECT.N_NAME_LIKE',
              },
              caption: '订单名称',
              codeName: 'n_name_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_name_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'business_line',
              editor: {
                singleSelect: true,
                appCodeListId: 'crmweb.crm__industry',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_business_line_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '业务条线',
              codeName: 'n_business_line_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_business_line_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'account_name',
              editor: {
                enablePickupView: true,
                singleSelect: true,
                pickupAppViewId: 'crmweb.account_pickup_view',
                handlerType: 'PickupText',
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_all',
                appDataEntityId: 'crmweb.account',
                enableAC: true,
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'n_account_id_eq',
                editorParams: {
                  AC: 'TRUE',
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'PICKER',
                editorItems: [
                  {
                    id: 'n_account_id_eq',
                  },
                ],
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_account_name_eq',
              },
              allowEmpty: true,
              caption: '客户名称',
              codeName: 'n_account_name_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_account_name_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_account_id_eq',
              },
              allowEmpty: true,
              hidden: true,
              codeName: 'n_account_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'n_account_id_eq',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.PROJECT.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'crmweb.project',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'd0d392412baf3e5974b13d7664ae33f1',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.project.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.project',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PROJECT',
      },
      caption: '订单',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.project',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.project',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '订单选择表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PROJECT.PICKUPGRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '7a868b1b4b3d17c5d5c23fa74c4af9c8',
  modelType: 'PSAPPDEVIEW',
  name: 'projectPickupGridView',
  id: 'crmweb.project_pickup_grid_view',
};
