export default {
  redirectAppViewRefs: [
    {
      realTitle: '订单编辑视图',
      refAppViewId: 'crmweb.project_edit_view3',
      name: 'PROJECT:EDITVIEW',
      id: 'project:editview',
    },
    {
      realTitle: '订单编辑视图',
      refAppViewId: 'crmweb.project_edit_view3',
      name: 'EDITVIEW',
      id: 'editview',
    },
  ],
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: '3c35858cd1e33defad59c97094c64622',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT',
  },
  caption: '订单',
  codeName: 'project_redirect_view',
  appDataEntityId: 'crmweb.project',
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PROJECT',
      },
      caption: '订单',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.project',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.project',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '订单数据重定向视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.PROJECT.REDIRECTVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: '42ce288e475a2357a31b75a4e77940a5',
  modelType: 'PSAPPDEVIEW',
  name: 'projectRedirectView',
  id: 'crmweb.project_redirect_view',
};
