export default {
  tabLayout: 'TOP',
  expandSearchForm: true,
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_search_view',
  deviewId: 'a7e025ed6332123f5255b5d27fff88a0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT',
  },
  caption: '订单',
  codeName: 'project_tab_search_view',
  appDataEntityId: 'crmweb.project',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId: 'panel_usr0318980456_button_filter_click@account',
                renderMode: 'BUTTON',
                tooltip: '过滤',
                uiactionTarget: 'SINGLEDATA',
                caption: '过滤',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysImage: {
                  cssClass: 'fa fa-filter',
                  glyph: 'xf0b0@FontAwesome',
                },
                id: 'button_filter',
              },
              {
                rawItem: {
                  caption: '文本内容',
                  halign: 'LEFT',
                  renderMode: 'TEXT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'static_text',
                },
                caption: '文本',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysPFPluginId: 'group_searchbar',
                showCaption: true,
                id: 'static_text',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '关系分页部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabexppanel',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel',
              },
              {
                rawItem: {
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar',
                },
                caption: '工具栏占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingRight: 'INNERMEDIUM',
            },
            id: 'container3',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
              spacingBottom: 'INNERSMALL',
              spacingLeft: 'INNERMEDIUM',
              spacingTop: 'INNERSMALL',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'view_searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupMode: 'SINGLE',
        searchBarFilters: [
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_NAME_LIKE',
              stdDataType: 25,
              valueOP: 'LIKE',
              name: 'N_NAME_LIKE',
              id: 'n_name_like',
            },
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              name: 'NAME',
              id: 'name',
            },
            allowEmpty: true,
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFSFITEM.PROJECT.N_NAME_LIKE',
            },
            caption: '订单名称',
            itemType: 'FILTER',
            appDEFieldId: 'name',
            name: 'NAME',
            id: 'name',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_O_NUMBER_LIKE',
              stdDataType: 25,
              valueOP: 'LIKE',
              name: 'N_O_NUMBER_LIKE',
              id: 'n_o_number_like',
            },
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              name: 'O_NUMBER',
              id: 'o_number',
            },
            allowEmpty: true,
            caption: '订单编号',
            itemType: 'FILTER',
            appDEFieldId: 'o_number',
            name: 'O_NUMBER',
            id: 'o_number',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_BUSINESS_LINE_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_BUSINESS_LINE_EQ',
              id: 'n_business_line_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__industry',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'BUSINESS_LINE',
              id: 'business_line',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '业务条线',
            itemType: 'FILTER',
            appDEFieldId: 'business_line',
            name: 'BUSINESS_LINE',
            id: 'business_line',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_ACCOUNT_NAME_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_ACCOUNT_NAME_EQ',
              id: 'n_account_name_eq',
            },
            editor: {
              enablePickupView: true,
              singleSelect: true,
              pickupAppViewId: 'crmweb.account_pickup_view',
              appDEACModeId: 'default',
              appDEDataSetId: 'fetch_all',
              appDataEntityId: 'crmweb.account',
              enableAC: true,
              forceSelection: true,
              showTrigger: true,
              editorParams: {
                AC: 'TRUE',
                PICKUPVIEW: 'TRUE',
              },
              editorType: 'PICKER',
              valueType: 'SIMPLE',
              editable: true,
              name: 'ACCOUNT_NAME',
              id: 'account_name',
            },
            allowEmpty: true,
            caption: '客户名称',
            itemType: 'FILTER',
            appDEFieldId: 'account_name',
            name: 'ACCOUNT_NAME',
            id: 'account_name',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              editorType: 'NUMBERRANGE',
              editorItems: [
                {
                  name: 'N_AMOUNT_GTANDEQ',
                  id: 'n_amount_gtandeq',
                },
                {
                  name: 'N_AMOUNT_LTANDEQ',
                  id: 'n_amount_ltandeq',
                },
              ],
              valueType: 'SIMPLE',
              editable: true,
              name: 'AMOUNT',
              id: 'amount',
            },
            allowEmpty: true,
            caption: '订单金额',
            itemType: 'FILTER',
            name: 'AMOUNT',
            id: 'amount',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            editor: {
              editorParams: {
                TIMEFMT: 'YYYY-MM-DD',
              },
              editorType: 'DATERANGE_NOTIME',
              editorItems: [
                {
                  name: 'N_ORDER_DATE_GT',
                  id: 'n_order_date_gt',
                },
                {
                  name: 'N_ORDER_DATE_LT',
                  id: 'n_order_date_lt',
                },
              ],
              valueType: 'SIMPLE',
              editable: true,
              name: 'ORDER_DATE',
              id: 'order_date',
            },
            allowEmpty: true,
            caption: '订单日期',
            itemType: 'FILTER',
            name: 'ORDER_DATE',
            id: 'order_date',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_GT',
              stdDataType: 6,
              valueOP: 'GT',
              name: 'N_AMOUNT_GT',
              id: 'n_amount_gt',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_GT',
              id: 'n_amount_gt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '订单金额(>)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_GT',
            id: 'n_amount_gt',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_LT',
              stdDataType: 6,
              valueOP: 'LT',
              name: 'N_AMOUNT_LT',
              id: 'n_amount_lt',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_LT',
              id: 'n_amount_lt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '订单金额(<)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_LT',
            id: 'n_amount_lt',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_ORDER_DATE_GT',
              stdDataType: 5,
              valueOP: 'GT',
              name: 'N_ORDER_DATE_GT',
              id: 'n_order_date_gt',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_ORDER_DATE_GT',
              id: 'n_order_date_gt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '订单日期(>)',
            itemType: 'FILTER',
            appDEFieldId: 'order_date',
            name: 'N_ORDER_DATE_GT',
            id: 'n_order_date_gt',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_ORDER_DATE_LT',
              stdDataType: 5,
              valueOP: 'LT',
              name: 'N_ORDER_DATE_LT',
              id: 'n_order_date_lt',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_ORDER_DATE_LT',
              id: 'n_order_date_lt',
            },
            allowEmpty: true,
            hidden: true,
            caption: '订单日期(<)',
            itemType: 'FILTER',
            appDEFieldId: 'order_date',
            name: 'N_ORDER_DATE_LT',
            id: 'n_order_date_lt',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_OWNER_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_OWNER_EQ',
              id: 'n_owner_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__owner',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'OWNER',
              id: 'owner',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            caption: '所有者',
            itemType: 'FILTER',
            appDEFieldId: 'owner',
            name: 'OWNER',
            id: 'owner',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_GTANDEQ',
              stdDataType: 6,
              valueOP: 'GTANDEQ',
              name: 'N_AMOUNT_GTANDEQ',
              id: 'n_amount_gtandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_GTANDEQ',
              id: 'n_amount_gtandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '订单金额(>=)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_GTANDEQ',
            id: 'n_amount_gtandeq',
          },
          {
            dataType: 6,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_AMOUNT_LTANDEQ',
              stdDataType: 6,
              valueOP: 'LTANDEQ',
              name: 'N_AMOUNT_LTANDEQ',
              id: 'n_amount_ltandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_AMOUNT_LTANDEQ',
              id: 'n_amount_ltandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '订单金额(<=)',
            itemType: 'FILTER',
            appDEFieldId: 'amount',
            name: 'N_AMOUNT_LTANDEQ',
            id: 'n_amount_ltandeq',
          },
        ],
        searchBarGroups: [
          {
            defaultGroup: true,
            caption: '在建订单',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"10"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'under_construction',
          },
          {
            caption: '本年度新签订单',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"is_new_this_year","condop":"EQ","value":"1"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'is_new_this_year',
          },
          {
            caption: '本年度执行订单',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"is_close_this_year","condop":"EQ","value":"1"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'is_close_this_year',
          },
          {
            caption: '所有订单',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'all',
          },
        ],
        quickSearchMode: 1,
        enableFilter: true,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'searchbar',
        controlStyle: 'FILTER_SEARCHBAR',
        controlType: 'SEARCHBAR',
        logicName: '默认搜索栏',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'searchbar',
        },
        sysPFPluginId: 'filter_searchbar',
        modelId: '9795e4f522e2f14695cbb91496d03bc8',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'crmweb.project.searchbar',
      },
      {
        tabExpPageIds: ['grid'],
        tabLayout: 'TOP',
        uniqueTag: 'project_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '订单',
            refAppViewId: 'crmweb.project_tree_grid_view',
            name: 'EXPITEM:grid',
            id: 'expitem:grid',
          },
        ],
        controls: [
          {
            sysImage: {
              cssClass: 'fa fa-table',
              glyph: 'xf0ce@FontAwesome',
            },
            caption: '表格视图',
            embeddedAppDEViewId: 'crmweb.project_tree_grid_view',
            codeName: 'tab_search_view_grid',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.project',
            controlParam: {
              id: 'grid',
            },
            modelId: '4d9c63f7ed489665e3aad555c28b92b0_grid',
            modelType: 'PSVIEWPANEL',
            name: 'grid',
            id: 'tab_search_view_grid',
          },
        ],
        codeName: 'tab_search_view_tabexppanel',
        controlStyle: 'TABEXPPANEL_DROPDOWN',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'crmweb.project',
        controlParam: {},
        sysPFPluginId: 'tabexppanel_dropdown',
        modelId: '4d9c63f7ed489665e3aad555c28b92b0_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'tab_search_view_tabexppanel',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.PROJECT',
        },
        caption: '订单',
        codeName: 'tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {},
        name: 'captionbar',
        id: 'tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0318980456',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索通用布局',
    appDataEntityId: 'crmweb.project',
    controlParam: {},
    modelId: 'f9a64be769ab83bfc4ff869c38a9192b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0318980456',
  },
  title: '订单',
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '4d9c63f7ed489665e3aad555c28b92b0',
  modelType: 'PSAPPDEVIEW',
  name: 'projecttab_search_view',
  id: 'crmweb.project_tab_search_view',
};
