export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'main_view',
  deviewId: '0aa56d1dae8a01d106d261ca200bb3f5',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT',
  },
  caption: '订单信息',
  codeName: 'project_main_view',
  appDataEntityId: 'crmweb.project',
  appViewNavContexts: [
    {
      key: 'N_OWNER_ID_EQ',
      value: 'project',
      name: 'N_OWNER_ID_EQ',
      id: 'n_owner_id_eq',
    },
    {
      key: 'OWNER_ID',
      value: 'project',
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      key: 'PRINCIPAL_ID',
      value: 'project',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'OWNER_TYPE',
      value: 'PROJECT',
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'PROJECT',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'project',
      id: 'n_owner_id_eq',
    },
    {
      key: 'principal_id',
      value: 'project',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'owner_type',
      value: 'PROJECT',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'principal_type',
      value: 'PROJECT',
      id: 'principal_type',
    },
    {
      key: 'owner_id',
      value: 'project',
      id: 'owner_id',
    },
  ],
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionType: 'UIACTION',
                        buttonStyle: 'INFO',
                        buttonType: 'PANELBUTTON',
                        uiactionId: 'editview_exitaction',
                        renderMode: 'BUTTON',
                        tooltip: '退出',
                        capLanguageRes: {
                          lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
                        },
                        caption: '退出',
                        itemStyle: 'INFO',
                        itemType: 'BUTTON',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysImage: {
                          cssClass: 'fa fa-arrow-left',
                          glyph: 'xf060@FontAwesome',
                        },
                        id: 'button_calluilogic',
                      },
                      {
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 70,
                          editorParams: {
                            MAXCOUNT: '1',
                          },
                          editorStyle: 'CRM_IMAGE_UPLOAD',
                          editorType: 'PICTURE_ONE',
                          editorWidth: 70,
                          sysPFPluginId: 'crm_image_upload',
                          predefinedType: 'FIELD_TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_textbox',
                        },
                        allowEmpty: true,
                        caption: '文本框',
                        contentHeight: 70,
                        contentWidth: 70,
                        height: 70,
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          height: 70,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 70,
                          widthMode: 'PX',
                        },
                        width: 70,
                        id: 'field_textbox',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfmajortext',
                        },
                        viewFieldName: 'srfmajortext',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'srfmajortext',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataName: 'srfactiveviewdata',
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'VIEWSESSIONPARAM',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系数据栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'drbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_drbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_exp_content',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView2',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'open_edit_view@project',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '编辑',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-edit',
              glyph: 'xf044@FontAwesome',
            },
            tooltip: '编辑',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction4',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'close_project@project',
            uiactionTarget: 'SINGLEDATA',
            valid: true,
            caption: '关闭订单',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-remove',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '关闭订单',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction2',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_prevrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '上一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-left',
              glyph: 'xf053@FontAwesome',
            },
            tooltip: '上一个记录',
            showIcon: true,
            id: 'deuiaction6',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_nextrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '下一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-right',
              glyph: 'xf054@FontAwesome',
            },
            tooltip: '下一个记录',
            showIcon: true,
            id: 'deuiaction7',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '订单主数据视图_工具栏',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'ad55da0cff0aeb8558d762292c373a3b',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.project',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.project',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.project',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.project',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.project',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.project',
          id: 'update',
        },
        infoFormMode: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 9,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'is_physical_order',
                        editor: {
                          editorParams: {
                            readonly: 'true',
                          },
                          editorType: 'CHECKBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'is_physical_order',
                        },
                        allowEmpty: true,
                        caption: '对应实体订单',
                        codeName: 'is_physical_order',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'is_physical_order',
                      },
                      {
                        rawItem: {
                          contentType: 'PLACEHOLDER',
                          id: 'rawitem1',
                        },
                        codeName: 'rawitem1',
                        detailStyle: 'DEFAULT',
                        detailType: 'RAWITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'rawitem1',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'name',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.NAME',
                        },
                        caption: '订单名称',
                        codeName: 'name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'o_number',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'o_number',
                        },
                        allowEmpty: true,
                        caption: '订单编号',
                        codeName: 'o_number',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'o_number',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'pname',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'pname',
                        },
                        allowEmpty: true,
                        caption: '父订单',
                        codeName: 'pname',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'pname',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'owner',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'crmweb.crm__owner',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'owner',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '所有者',
                        codeName: 'owner',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'owner',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'business_line',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'crmweb.crm__industry',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'business_line',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '业务条线',
                        codeName: 'business_line',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'business_line',
                      },
                      {
                        dataType: 21,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'executors',
                        editor: {
                          enablePickupView: true,
                          forceSelection: true,
                          showTrigger: true,
                          editorParams: {
                            readonly: 'true',
                            PICKUPVIEW: 'TRUE',
                          },
                          editorType: 'ADDRESSPICKUP',
                          objectIdField: 'id',
                          objectNameField: 'name',
                          valueType: 'OBJECTS',
                          editable: true,
                          readOnly: true,
                          id: 'executors',
                        },
                        allowEmpty: true,
                        caption: '执行人',
                        codeName: 'executors',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        sysCss: {
                          cssName: 'blackfont',
                        },
                        showCaption: true,
                        id: 'executors',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'account_name',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'account_name',
                        },
                        allowEmpty: true,
                        caption: '客户名称',
                        codeName: 'account_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'account_name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        ignoreInput: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'status',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'crmweb.crm__order_status',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'status',
                        },
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '状态',
                        codeName: 'status',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'status',
                      },
                      {
                        dataType: 6,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'amount',
                        editor: {
                          halign: 'LEFT',
                          precision: 2,
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'amount',
                        },
                        unitName: '元',
                        valueFormat: '#,##0.00',
                        allowEmpty: true,
                        enableUnitName: true,
                        caption: '订单金额',
                        codeName: 'amount',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        dynaClass:
                          '{negative_red: Number(data.amount || 0) < 0}',
                        defdgroupLogics: [
                          {
                            logicCat: 'SCRIPTCODE_FOCUS',
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colLG: 10,
                          colMD: 10,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'amount',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'order_date',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'order_date',
                        },
                        valueFormat: 'YYYY-MM-DD',
                        allowEmpty: true,
                        caption: '订单日期',
                        codeName: 'order_date',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 8,
                          colLGOffset: 2,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'order_date',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'closed_date',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'closed_date',
                        },
                        valueFormat: 'YYYY-MM-DD',
                        allowEmpty: true,
                        caption: '关闭日期',
                        codeName: 'closed_date',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['status'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'status',
                                value: '20',
                                logicType: 'SINGLE',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colLG: 8,
                          colLGOffset: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'closed_date',
                      },
                      {
                        dataType: 21,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'description',
                        editor: {
                          maxLength: 32000,
                          showMaxLength: true,
                          editorParams: {
                            readonly: 'true',
                          },
                          editorType: 'TEXTAREA',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'description',
                        },
                        allowEmpty: true,
                        caption: '描述',
                        codeName: 'description',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 24,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        sysCss: {
                          cssName: 'input-readonly',
                        },
                        showCaption: true,
                        id: 'description',
                      },
                    ],
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 18,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel1',
                  },
                ],
                caption: '订单信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'group1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 9,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'is_in_sales_cal',
                        editor: {
                          editorParams: {
                            readonly: 'true',
                          },
                          editorType: 'CHECKBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'is_in_sales_cal',
                        },
                        allowEmpty: true,
                        caption: '是否纳入销售业绩计算',
                        codeName: 'is_in_sales_cal',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'is_in_sales_cal',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'year',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'year',
                        },
                        allowEmpty: true,
                        caption: '业绩归属年度',
                        codeName: 'year',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 8,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'year',
                      },
                    ],
                    codeName: 'grouppanel3',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 18,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel3',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 6,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'settlement_cost',
                        editor: {
                          halign: 'LEFT',
                          precision: 2,
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'settlement_cost',
                        },
                        unitName: '元',
                        valueFormat: '#,##0.00',
                        allowEmpty: true,
                        enableUnitName: true,
                        caption: '结算成本',
                        codeName: 'settlement_cost',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        dynaClass:
                          '{negative_red: Number(data.settlement_cost || 0) < 0}',
                        layoutPos: {
                          colLG: 10,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'settlement_cost',
                      },
                      {
                        dataType: 6,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'tax',
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'tax',
                        },
                        unitName: '%',
                        allowEmpty: true,
                        enableUnitName: true,
                        caption: '税率',
                        codeName: 'tax',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 7,
                          colLGOffset: 2,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'tax',
                      },
                      {
                        dataType: 6,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 190,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'settlement_amount',
                        editor: {
                          halign: 'LEFT',
                          precision: 2,
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'settlement_amount',
                        },
                        unitName: '元',
                        valueFormat: '#,##0.00',
                        allowEmpty: true,
                        enableUnitName: true,
                        caption: '业绩结算金额',
                        codeName: 'settlement_amount',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        dynaClass:
                          '{negative_red: Number(data.settlement_amount || 0) < 0}',
                        layoutPos: {
                          colLG: 10,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'settlement_amount',
                      },
                    ],
                    codeName: 'grouppanel5',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 18,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel5',
                  },
                  {
                    contentType: 'REPEATER',
                    appDEFieldId: 'order_allocates',
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        captionItemName: 'user_id',
                        dataType: 25,
                        enableCond: 3,
                        fieldName: 'user_name',
                        labelPos: 'LEFT',
                        labelWidth: 250,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'user_name',
                        },
                        allowEmpty: true,
                        caption: '销售人员',
                        codeName: 'user_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        repeatContent: true,
                        showCaption: true,
                        id: 'user_name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 250,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'ratio',
                        },
                        allowEmpty: true,
                        caption: '分配比率',
                        codeName: 'ratio',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        repeatContent: true,
                        showCaption: true,
                        id: 'ratio',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        fieldName: 'amount',
                        labelPos: 'LEFT',
                        labelWidth: 250,
                        noPrivDisplayMode: 1,
                        editor: {
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          editorItems: [
                            {
                              id: 'amount',
                            },
                          ],
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'amount_order',
                        },
                        allowEmpty: true,
                        caption: '分配金额',
                        codeName: 'amount_order',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        repeatContent: true,
                        showCaption: true,
                        id: 'amount_order',
                      },
                    ],
                    codeName: 'mdctrl1',
                    detailStyle: 'STYLE2',
                    detailType: 'MDCTRL',
                    layoutPos: {
                      colLG: 14,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'mdctrl1',
                  },
                ],
                caption: '业绩计算与分配',
                codeName: 'grouppanel4',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel4',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 190,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '概览',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    appViewId: 'crmweb.activitiy_time_line_view',
                    parentDataJO: {
                      srfparentdename: 'PROJECT',
                      SRFPARENTTYPE: 'CUSTOM',
                    },
                    codeName: 'druipart1',
                    detailStyle: 'DEFAULT',
                    detailType: 'DRUIPART',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'druipart1',
                  },
                ],
                caption: '历史信息',
                codeName: 'grouppanel2',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel2',
              },
            ],
            caption: '时间轴',
            codeName: 'formpage2',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage2',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main_view_form',
        controlStyle: 'ANCHOR_STYLE',
        controlType: 'FORM',
        logicName: '订单主数据视图_表单',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'form',
        },
        sysPFPluginId: 'anchor_style',
        modelId: 'ec5a8af016fcaf1428d91e12750e5d7b',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'crmweb.project.main_view_form',
      },
      {
        dedrbarGroups: [
          {
            caption: '详细信息',
            name: '详细信息',
            id: 'drgroup',
          },
        ],
        showTitle: true,
        dataRelationTag: 'main_view_DR',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.PROJECT',
        },
        editItemCaption: '订单',
        appCounterRefId: '189507c8677cc415c2a6628ae91c8cbf',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'drgroup',
            caption: '附件',
            counterId: 'attachment',
            appViewId: 'crmweb.project_attachment_view',
            id: 'attachment',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '进展评估',
            counterId: 'note_attach',
            appViewId: 'crmweb.project_note_attach_view',
            id: 'note_attach',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '待办任务',
            counterId: 'not_close',
            appViewId: 'crmweb.schedule_not_close_tab_exp_view9',
            navigateContexts: [
              {
                key: 'OWNER_ID',
                value: 'principal_id',
                name: 'OWNER_ID',
                id: 'owner_id',
              },
              {
                key: 'OWNER_TYPE',
                value: 'owner_type',
                name: 'OWNER_TYPE',
                id: 'owner_type',
              },
            ],
            navigateParams: [
              {
                key: 'owner_id',
                value: 'principal_id',
                id: 'owner_id',
              },
              {
                key: 'owner_type',
                value: 'owner_type',
                id: 'owner_type',
              },
            ],
            id: 'not_close',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '已完成的任务&历史活动',
            counterId: 'taskhisact',
            appViewId: 'crmweb.task_task_act_list_view',
            id: 'taskhisact',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '收款计划和记录',
            appViewId: 'crmweb.project_pro_pay_and_plan_edit_view',
            id: 'payee_plan_payee',
          },
        ],
        uniqueTag: 'project_main_view__drbar',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'project_main_view_dr',
              counterType: 'DEDR',
              getAppDEActionId: 'main_view_dr_count',
              appDataEntityId: 'crmweb.project',
              timer: 60000,
              uniqueTag: 'project_main_view_dr',
              name: '在线项目main_view关系',
              id: 'crmweb.project_main_view_dr',
            },
            refMode: {
              srfdeid: 'PROJECT',
            },
            tag: '189507c8677cc415c2a6628ae91c8cbf',
            uniqueTag: 'project_main_view_dr',
            id: '189507c8677cc415c2a6628ae91c8cbf',
          },
        ],
        codeName: 'main_view_dr',
        controlStyle: 'DRBAR_ANCHOR_STYLE',
        controlType: 'DRBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'drbar_anchor_style',
        modelId: '442f316f34eb018d825e4db1c9397512',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'main_view_dr',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.PROJECT',
        },
        caption: '订单信息',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'usr0319628389',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主数据通用布局面板',
    appDataEntityId: 'crmweb.project',
    controlParam: {},
    modelId: '6169ec687d45a098f7102272c1f7c4ca',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0319628389',
  },
  title: '订单信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: false,
  modelId: '3e1de6c23fce73a54a40e9eb600bacbc',
  modelType: 'PSAPPDEVIEW',
  name: 'projectmain_view',
  id: 'crmweb.project_main_view',
};
