export default {
  gridRowActiveMode: 2,
  loadDefault: true,
  deviewCodeName: 'tree_grid_view',
  deviewId: '21d99eb86ca5af02548dab0a31ec7937',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PROJECT',
  },
  caption: '订单',
  codeName: 'project_tree_grid_view',
  appDataEntityId: 'crmweb.project',
  appViewNavParams: [
    {
      rawValue: true,
      key: 'srfshowmode',
      value: 'tree',
      id: 'srfshowmode',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '树表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'treegrid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          heightMode: 'FULL',
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'crmweb.project_edit_view3',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.project_edit_view3',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            navigateContexts: [
              {
                key: 'PRINCIPAL_NAME',
                value: 'NAME',
                name: 'PRINCIPAL_NAME',
                id: 'principal_name',
              },
            ],
            refAppViewId: 'crmweb.project_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              navigateContexts: [
                {
                  key: 'PRINCIPAL_NAME',
                  value: 'NAME',
                  name: 'PRINCIPAL_NAME',
                  id: 'principal_name',
                },
              ],
              refAppViewId: 'crmweb.project_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        navigateContexts: [
          {
            key: 'PRINCIPAL_NAME',
            value: 'NAME',
            name: 'PRINCIPAL_NAME',
            id: 'principal_name',
          },
        ],
        realTitle: '订单信息',
        refAppViewId: 'crmweb.project_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '订单编辑视图',
        refAppViewId: 'crmweb.project_edit_view3',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'create_node_project@project',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '创建订单',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '创建订单',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction7',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_refreshaction',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '刷新',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-refresh',
              glyph: 'xf021@FontAwesome',
            },
            tooltip: '刷新',
            showIcon: true,
            id: 'deuiaction8',
          },
        ],
        codeName: 'tree_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '订单多模式表格视图_工具栏',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          ctrlParams: {
            TELEPORTTAG: '#project_tab_search_view-tabtoolbar',
          },
          id: 'toolbar',
        },
        modelId: 'd14751bfcdcfcbc47d637fae4b58d2f8',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'tree_grid_view_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'tree_grid_view_search_form',
        controlType: 'SEARCHFORM',
        logicName: '订单树表格_搜索表单',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'searchform',
        },
        modelId: '649219165130da171c640cf08816b0f6',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.project.tree_grid_view_search_form',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'update_time',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'o_number',
            excelCaption: '订单编号',
            appDEFieldId: 'o_number',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '订单编号',
            codeName: 'o_number',
            columnType: 'DEFTREEGRIDCOLUMN',
            hideMode: 3,
            noPrivDisplayMode: 1,
            width: 190,
            widthUnit: 'PX',
            enableSort: true,
            id: 'o_number',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '订单名称',
            appDEFieldId: 'name',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'open_edit_view@project',
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  id: 'ua4c369d',
                },
              ],
              appDataEntityId: 'crmweb.project',
              uniqueTag: 'project__Usr0625602379',
              name: '订单敏捷操作列',
              id: 'usr0625602379',
            },
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.NAME',
            },
            caption: '订单名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 280,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'account_name',
            excelCaption: '客户名称',
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '客户名称',
            codeName: 'account_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'account_name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '状态',
            appCodeListId: 'crmweb.crm__order_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 90,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'order_date',
            excelCaption: '订单日期',
            appDEFieldId: 'order_date',
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '订单日期',
            codeName: 'order_date',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 120,
            widthUnit: 'PX',
            enableSort: true,
            id: 'order_date',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'amount',
            excelCaption: '订单金额',
            appDEFieldId: 'amount',
            unitName: '元',
            valueFormat: '#,##0.00',
            valueType: 'SIMPLE',
            enableUnitName: true,
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '订单金额',
            codeName: 'amount',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'amount',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'settlement_cost',
            excelCaption: '结算成本',
            appDEFieldId: 'settlement_cost',
            unitName: '元',
            valueFormat: '#,##0.00',
            valueType: 'SIMPLE',
            enableUnitName: true,
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '结算成本',
            codeName: 'settlement_cost',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'settlement_cost',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'settlement_amount',
            excelCaption: '业绩结算金额',
            appDEFieldId: 'settlement_amount',
            unitName: '元',
            valueFormat: '#,##0.00',
            valueType: 'SIMPLE',
            enableUnitName: true,
            aggMode: 'NONE',
            align: 'RIGHT',
            caption: '业绩结算金额',
            codeName: 'settlement_amount',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 140,
            widthUnit: 'PX',
            enableSort: true,
            id: 'settlement_amount',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'last_assess_time',
            excelCaption: '最近评估时间',
            appDEFieldId: 'last_assess_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '最近评估时间',
            codeName: 'last_assess_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'last_assess_time',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'year',
            excelCaption: '所属年度',
            appDEFieldId: 'year',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '所属年度',
            codeName: 'year',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 120,
            widthUnit: 'PX',
            enableSort: true,
            id: 'year',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'business_line',
            excelCaption: '业务条线',
            appCodeListId: 'crmweb.crm__business_line',
            appDEFieldId: 'business_line',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '业务条线',
            codeName: 'business_line',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'business_line',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'executors',
            excelCaption: '执行人',
            objectIdField: 'id',
            objectNameField: 'name',
            appDEFieldId: 'executors',
            valueType: 'OBJECTS',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '执行人',
            codeName: 'executors',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 250,
            widthUnit: 'PX',
            id: 'executors',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'owner',
            excelCaption: '所有者',
            appCodeListId: 'crmweb.crm__owner',
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '所有者',
            codeName: 'owner',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'owner',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'pname',
            excelCaption: '父订单',
            appDEFieldId: 'pname',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '父订单',
            codeName: 'pname',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'pname',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'update_time',
            excelCaption: '更新时间',
            appDEFieldId: 'update_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'CENTER',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.UPDATE_TIME',
            },
            caption: '更新时间',
            codeName: 'update_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'update_time',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'id',
            excelCaption: '标识',
            appDEFieldId: 'id',
            treeColumnMode: 2,
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.ID',
            },
            caption: '标识',
            codeName: 'id',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            id: 'id',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'pid',
            excelCaption: '父标识',
            appDEFieldId: 'pid',
            treeColumnMode: 4,
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '父标识',
            codeName: 'pid',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hiddenDataItem: true,
            hideDefault: true,
            id: 'pid',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'o_number',
            scriptCode:
              'var newname = data.o_number ? data.o_number : \'\'; // 如果 data.subject 为空，则 newname 为 \'\'\r\nvar svgIcon = \'\';\r\n\r\nif (data.last_assess_time) {\r\n    var nowDate = Date.parse(new Date().toISOString().slice(0, 10));\r\n    var accessDate = Date.parse(data.last_assess_time.slice(0, 10));\r\n    var days = (nowDate - accessDate) / (1 * 24 * 60 * 60 * 1000);\r\n    var fireColor = "";\r\n\r\n    if (days <= 7) {\r\n        fireColor = "red";\r\n    } else if (days <= 14) {\r\n        fireColor = "orange";\r\n    } else if (days <= 30) {\r\n        fireColor = "gray";\r\n    }\r\n\r\n    if (fireColor) {\r\n        svgIcon = `<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="${fireColor}" class="bi bi-fire" viewBox="0 0 16 16"><path d="M8 16c3.314 0 6-2 6-5.5 0-1.5-.5-4-2.5-6 .25 1.5-1.25 2-1.25 2C11 4 9 .5 6 0c.357 2 .5 4-2 6-1.25 1-2 2.729-2 4.5C2 14 4.686 16 8 16Zm0-1c-1.657 0-3-1-3-2.75 0-.75.25-2 1.25-3C6.125 10 7 10.5 7 10.5c-.375-1.25.5-3.25 2-3.5-.179 1-.25 2 1 3 .625.5 1 1.364 1 2.25C11 14 9.657 15 8 15Z"/></svg></span>`;\r\n    }\r\n}\r\n\r\nif (!svgIcon) {\r\n    newname = `<span style="margin-left: 16px;"></span>${newname}`;\r\n}\r\n\r\nreturn svgIcon + newname;\r\n',
            valueType: 'SIMPLE',
            customCode: true,
            dataType: 25,
            id: 'o_number',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'account_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_name',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'status',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'order_date',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'order_date',
          },
          {
            format: '#,##0.00',
            appDEFieldId: 'amount',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'amount',
          },
          {
            format: '#,##0.00',
            appDEFieldId: 'settlement_cost',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'settlement_cost',
          },
          {
            format: '#,##0.00',
            appDEFieldId: 'settlement_amount',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'settlement_amount',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'last_assess_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'last_assess_time',
          },
          {
            appDEFieldId: 'year',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'year',
          },
          {
            appDEFieldId: 'business_line',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'business_line',
          },
          {
            appDEFieldId: 'executors',
            valueType: 'OBJECTS',
            dataType: 21,
            id: 'executors',
          },
          {
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'owner',
          },
          {
            appDEFieldId: 'pname',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pname',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'update_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'update_time',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'id',
          },
          {
            appDEFieldId: 'pid',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'pid',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'account_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'account_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'LOCAL',
        enableCustomized: true,
        enablePagingBar: true,
        forceFit: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_tree',
          appDataEntityId: 'crmweb.project',
          id: 'fetch',
        },
        dedataImportId: 'dataimport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.project',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'create_task@project',
                uiactionTarget: 'MULTIKEY',
                hiddenItem: true,
                valid: true,
                caption: '创建任务',
                itemType: 'DEUIACTION',
                tooltip: '创建任务',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'remove@project',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '删除',
                itemType: 'DEUIACTION',
                tooltip: '删除',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'add_tags@project',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '添加标签',
                    itemType: 'DEUIACTION',
                    tooltip: '添加标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction2',
                  },
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'delete_tags@project',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '移除标签',
                    itemType: 'DEUIACTION',
                    tooltip: '移除标签',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction3',
                  },
                ],
                valid: true,
                caption: '标签',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '标签',
                showCaption: true,
                showIcon: true,
                id: 'items1',
              },
              {
                actionLevel: 100,
                detoolbarItems: [
                  {
                    actionLevel: 100,
                    noPrivDisplayMode: 2,
                    uiactionId: 'batch_update@project',
                    uiactionTarget: 'MULTIKEY',
                    hiddenItem: true,
                    valid: true,
                    caption: '批量更新',
                    itemType: 'DEUIACTION',
                    tooltip: '批量更新',
                    showCaption: true,
                    showIcon: true,
                    id: 'deuiaction4',
                  },
                ],
                valid: true,
                caption: '操作',
                itemType: 'ITEMS',
                sysImage: {
                  cssClass: 'fa fa-chevron-down',
                  glyph: 'xf078@FontAwesome',
                },
                tooltip: '操作',
                showCaption: true,
                showIcon: true,
                id: 'items2',
              },
            ],
            codeName: 'tree_grid_view_treegrid_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作_工具栏',
            appDataEntityId: 'crmweb.project',
            controlParam: {
              id: 'treegrid_batchtoolbar',
            },
            modelId: '19ee0949732f8079e925cd339e6cbc46',
            modelType: 'PSDETOOLBAR',
            name: 'treegrid_batchtoolbar',
            id: 'tree_grid_view_treegrid_batchtoolbar',
          },
        ],
        codeName: 'grid_view_multimode_grid',
        controlStyle: 'NUMBER_GRID',
        controlType: 'TREEGRID',
        logicName: '订单多模式表格视图_表格',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          ctrlParams: {
            EXPANDCOLUMNINDEX: '1',
          },
          id: 'treegrid',
        },
        sysPFPluginId: 'number_grid',
        modelId: '83b56a889e67606736b119bbdba318ba',
        modelType: 'PSDEGRID',
        name: 'treegrid',
        id: 'crmweb.project.grid_view_multimode_grid',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.PROJECT',
        },
        caption: '订单',
        codeName: 'tree_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.project',
        controlParam: {},
        name: 'captionbar',
        id: 'tree_grid_view_captionbar',
      },
    ],
    codeName: 'usr0605020873',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'tree_grid_view树表格视图布局面板',
    appDataEntityId: 'crmweb.project',
    controlParam: {},
    modelId: 'ed6fb9d1379fa07be50ba8093564cabc',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0605020873',
  },
  title: '订单',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '8a777366e04991df39008d34f1a207a2',
  modelType: 'PSAPPDEVIEW',
  name: 'projecttree_grid_view',
  id: 'crmweb.project_tree_grid_view',
};
