export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'not_close_tab_exp_view9',
  deviewId: '932893b86cfd323a5517d22137b4955d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.SCHEDULE',
  },
  caption: '待办任务',
  codeName: 'schedule_not_close_tab_exp_view9',
  appDataEntityId: 'crmweb.schedule',
  appViewNavContexts: [
    {
      key: 'PRINCIPAL_ID',
      value: 'principal_id',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
  ],
  appViewNavParams: [
    {
      key: 'principal_id',
      value: 'principal_id',
      id: 'principal_id',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '分页导航',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingRight: 'OUTERMEDIUM',
                },
                showCaption: true,
                id: 'tabexppanel',
              },
              {
                caption: '工具栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
            ],
            layout: {
              dir: 'row-reverse',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
          {
            actionGroupExtractMode: 'ITEM',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel_right',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'gridview_newaction',
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.*.NEW',
                },
                caption: '新建',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-file-text-o',
                  glyph: 'xf0f6@FontAwesome',
                },
                tooltip: '新建',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.*.NEW',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction1',
              },
            ],
            valid: true,
            caption: '添加新的',
            itemType: 'ITEMS',
            tooltip: '添加新的',
            showCaption: true,
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_viewaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.VIEW',
            },
            caption: '查看',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-edit',
              glyph: 'xf044@FontAwesome',
            },
            tooltip: '查看',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.VIEW',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction2',
          },
        ],
        codeName: 'not_close_tab_exp_view9_tabtoolbar',
        controlType: 'TOOLBAR',
        logicName: ' 待办任务嵌入分页导航视图工具栏',
        appDataEntityId: 'crmweb.schedule',
        controlParam: {
          id: 'tabtoolbar',
        },
        modelId: '7ffb16b7aace127ce583e6ed0055accf',
        modelType: 'PSDETOOLBAR',
        name: 'tabtoolbar',
        id: 'not_close_tab_exp_view9_tabtoolbar',
      },
      {
        tabExpPageIds: ['tab'],
        tabLayout: 'TOP',
        uniqueTag: 'schedule_not_close_tab_exp_view9__tabexppanel',
        appViewRefs: [
          {
            realTitle: '待办任务',
            refAppViewId:
              'crmweb.schedule_not_close_tab_tabs_exp_view_multimode',
            name: 'EXPITEM:tab',
            id: 'expitem:tab',
          },
        ],
        controls: [
          {
            sysImage: {
              cssClass: 'fa fa-trello',
              glyph: 'xf181@FontAwesome',
            },
            caption: '页签视图',
            embeddedAppDEViewId:
              'crmweb.schedule_not_close_tab_tabs_exp_view_multimode',
            codeName: 'not_close_tab_exp_view9_tab',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.schedule',
            controlParam: {
              id: 'tab',
            },
            modelId: '8bc4613b174a6325d4789fd2a4466d27_tab',
            modelType: 'PSVIEWPANEL',
            name: 'tab',
            id: 'not_close_tab_exp_view9_tab',
          },
        ],
        codeName: 'not_close_tab_exp_view9_tabexppanel',
        controlStyle: 'TABEXPPANEL_DROPDOWN',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'crmweb.schedule',
        controlParam: {},
        sysPFPluginId: 'tabexppanel_dropdown',
        modelId: '8bc4613b174a6325d4789fd2a4466d27_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'not_close_tab_exp_view9_tabexppanel',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.SCHEDULE',
        },
        caption: '待办任务',
        codeName: 'not_close_tab_exp_view9_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.schedule',
        controlParam: {},
        name: 'captionbar',
        id: 'not_close_tab_exp_view9_captionbar',
      },
    ],
    codeName: 'usr0407652381',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '嵌入分页导航通用布局',
    appDataEntityId: 'crmweb.schedule',
    controlParam: {},
    modelId: 'ff7c43c88890c50b9322f5eb9a1e34fe',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0407652381',
  },
  title: '待办任务',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW9',
  enableDP: true,
  showCaptionBar: true,
  modelId: '8bc4613b174a6325d4789fd2a4466d27',
  modelType: 'PSAPPDEVIEW',
  name: 'schedulenot_close_tab_exp_view9',
  id: 'crmweb.schedule_not_close_tab_exp_view9',
};
