export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'not_close_tab_tabs_exp_view_multimode',
  deviewId: '57703224f2e488697db7ff6d3f6d21e9',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.SCHEDULE',
  },
  caption: '待办任务',
  codeName: 'schedule_not_close_tab_tabs_exp_view_multimode',
  appDataEntityId: 'crmweb.schedule',
  controls: [
    {
      tabExpPageIds: ['task'],
      tabLayout: 'TOP',
      uniqueTag: 'schedule_not_close_tab_tabs_exp_view_multimode__tabexppanel',
      appViewRefs: [
        {
          realTitle: '待办任务（任务）',
          realTitleLanguageRes: {
            lanResTag: 'PAGE.TITLE.TASK.GRID_NOT_CLOSE_VIEW',
          },
          refAppViewId: 'crmweb.task_grid_not_close_view',
          name: 'EXPITEM:task',
          id: 'expitem:task',
        },
      ],
      controls: [
        {
          caption: '任务',
          embeddedAppDEViewId: 'crmweb.task_grid_not_close_view',
          codeName: 'not_close_tab_tabs_exp_view_multimode_task',
          controlType: 'TABVIEWPANEL',
          appDataEntityId: 'crmweb.schedule',
          controlParam: {
            id: 'task',
          },
          modelId: '750d58d6ff6dc9843b4e45213b46946f_task',
          modelType: 'PSVIEWPANEL',
          name: 'task',
          id: 'not_close_tab_tabs_exp_view_multimode_task',
        },
      ],
      codeName: 'not_close_tab_tabs_exp_view_multimode_tabexppanel',
      controlType: 'TABEXPPANEL',
      appDataEntityId: 'crmweb.schedule',
      controlParam: {},
      modelId: '750d58d6ff6dc9843b4e45213b46946f_tabexppanel',
      modelType: 'PSTABEXPPANEL',
      name: 'tabexppanel',
      id: 'not_close_tab_tabs_exp_view_multimode_tabexppanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.SCHEDULE',
      },
      caption: '待办任务',
      codeName: 'not_close_tab_tabs_exp_view_multimode_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.schedule',
      controlParam: {},
      name: 'captionbar',
      id: 'not_close_tab_tabs_exp_view_multimode_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETABEXPVIEW9',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.schedule',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '待办任务',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW9',
  enableDP: true,
  showCaptionBar: false,
  modelId: '750d58d6ff6dc9843b4e45213b46946f',
  modelType: 'PSAPPDEVIEW',
  name: 'schedulenot_close_tab_tabs_exp_view_multimode',
  id: 'crmweb.schedule_not_close_tab_tabs_exp_view_multimode',
};
