export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_search_view',
  deviewId: '7f8c0efc498cbc6b613cbb8d9596d0b5',
  accUserMode: 2,
  caption: '服务支持',
  codeName: 'service_case_tab_search_view',
  appDataEntityId: 'crmweb.service_case',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId: 'panel_usr0318980456_button_filter_click@account',
                renderMode: 'BUTTON',
                tooltip: '过滤',
                uiactionTarget: 'SINGLEDATA',
                caption: '过滤',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysImage: {
                  cssClass: 'fa fa-filter',
                  glyph: 'xf0b0@FontAwesome',
                },
                id: 'button_filter',
              },
              {
                rawItem: {
                  caption: '文本内容',
                  halign: 'LEFT',
                  renderMode: 'TEXT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'static_text',
                },
                caption: '文本',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysPFPluginId: 'group_searchbar',
                showCaption: true,
                id: 'static_text',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '关系分页部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabexppanel',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel',
              },
              {
                rawItem: {
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar',
                },
                caption: '工具栏占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingRight: 'INNERMEDIUM',
            },
            id: 'container3',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
              spacingBottom: 'INNERSMALL',
              spacingLeft: 'INNERMEDIUM',
              spacingTop: 'INNERSMALL',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'view_searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        codeName: 'searchbar',
        controlType: 'SEARCHBAR',
        logicName: '默认搜索栏',
        appDataEntityId: 'crmweb.service_case',
        controlParam: {
          id: 'searchbar',
        },
        modelId: '91998b354e1b81e8840bd2f3dfcdaf76',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'crmweb.service_case.searchbar',
      },
      {
        tabExpPageIds: ['grid', 'data_view', 'list'],
        tabLayout: 'TOP',
        uniqueTag: 'service_case_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '服务支持',
            refAppViewId: 'crmweb.service_case_grid_view_multimode',
            name: 'EXPITEM:grid',
            id: 'expitem:grid',
          },
          {
            realTitle: '服务支持',
            refAppViewId: 'crmweb.service_case_data_view_multimode',
            name: 'EXPITEM:data_view',
            id: 'expitem:data_view',
          },
          {
            realTitle: '服务支持',
            refAppViewId: 'crmweb.service_case_list_view_multimode',
            name: 'EXPITEM:list',
            id: 'expitem:list',
          },
        ],
        controls: [
          {
            caption: '表格视图',
            embeddedAppDEViewId: 'crmweb.service_case_grid_view_multimode',
            codeName: 'tab_search_view_grid',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.service_case',
            controlParam: {
              id: 'grid',
            },
            modelId: '69889cfa58ca02e5825b06ee7adbdf7a_grid',
            modelType: 'PSVIEWPANEL',
            name: 'grid',
            id: 'tab_search_view_grid',
          },
          {
            caption: '平铺视图',
            embeddedAppDEViewId: 'crmweb.service_case_data_view_multimode',
            codeName: 'tab_search_view_data_view',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.service_case',
            controlParam: {
              id: 'data_view',
            },
            modelId: '69889cfa58ca02e5825b06ee7adbdf7a_data_view',
            modelType: 'PSVIEWPANEL',
            name: 'data_view',
            id: 'tab_search_view_data_view',
          },
          {
            caption: '列表视图',
            embeddedAppDEViewId: 'crmweb.service_case_list_view_multimode',
            codeName: 'tab_search_view_list',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.service_case',
            controlParam: {
              id: 'list',
            },
            modelId: '69889cfa58ca02e5825b06ee7adbdf7a_list',
            modelType: 'PSVIEWPANEL',
            name: 'list',
            id: 'tab_search_view_list',
          },
        ],
        codeName: 'tab_search_view_tabexppanel',
        controlStyle: 'TABEXPPANEL_DROPDOWN',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'crmweb.service_case',
        controlParam: {},
        sysPFPluginId: 'tabexppanel_dropdown',
        modelId: '69889cfa58ca02e5825b06ee7adbdf7a_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'tab_search_view_tabexppanel',
      },
      {
        caption: '服务支持',
        codeName: 'tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.service_case',
        controlParam: {},
        name: 'captionbar',
        id: 'tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0318980456',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索通用布局',
    appDataEntityId: 'crmweb.service_case',
    controlParam: {},
    modelId: 'f9a64be769ab83bfc4ff869c38a9192b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0318980456',
  },
  title: '服务支持',
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '69889cfa58ca02e5825b06ee7adbdf7a',
  modelType: 'PSAPPDEVIEW',
  name: 'casetab_search_view',
  id: 'crmweb.service_case_tab_search_view',
};
