export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'batch_create_view',
  deviewId: '35e4351b3975dd68f5bec23ad24c0ad6',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.TASK.BATCH_CREATE_VIEW',
  },
  caption: '批创建',
  codeName: 'task_batch_create_view',
  height: 600,
  appDataEntityId: 'crmweb.task',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  appViewNavParams: [
    {
      key: 'owner_id',
      value: 'owner_id',
      id: 'owner_id',
    },
    {
      key: 'owner_type',
      value: 'owner_type',
      id: 'owner_type',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'ingore',
        appDataEntityId: 'crmweb.task',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.task',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'ingore',
        appDataEntityId: 'crmweb.task',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'ingore',
        appDataEntityId: 'crmweb.task',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.task',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'ingore',
        appDataEntityId: 'crmweb.task',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'owner_subtype',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'owner_subtype',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.OWNER_SUBTYPE',
                  },
                  caption: '所属对象子类型',
                  codeName: 'owner_subtype',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'owner_subtype',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'owner_type',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'owner_type',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.OWNER_TYPE',
                  },
                  caption: '所属数据对象',
                  codeName: 'owner_type',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'owner_type',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'owner_id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'owner_id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.OWNER_ID',
                  },
                  caption: '所属数据标识',
                  codeName: 'owner_id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'owner_id',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'subject',
                  editor: {
                    maxLength: 255,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'subject',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.SUBJECT',
                  },
                  caption: '主题',
                  codeName: 'subject',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'subject',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  itemWidth: 230,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'due_date',
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD',
                    },
                    editorType: 'DATEPICKEREX_NOTIME',
                    editorWidth: 100,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'due_date',
                  },
                  valueFormat: 'YYYY-MM-DD',
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.DUE_DATE',
                  },
                  caption: '到期日期',
                  codeName: 'due_date',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'due_date',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'status',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'crmweb.crm__task_status',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'status',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.STATUS',
                  },
                  caption: '状态',
                  codeName: 'status',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'status',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  itemWidth: 290,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'closed_time',
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                    },
                    editorType: 'DATEPICKER',
                    editorWidth: 160,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'closed_time',
                  },
                  valueFormat: 'YYYY-MM-DD HH:mm:ss',
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.CLOSED_TIME',
                  },
                  caption: '关闭时间',
                  codeName: 'closed_time',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'closed_time',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'priority',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'crmweb.crm__priority',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'priority',
                  },
                  allowEmpty: true,
                  needCodeListConfig: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.PRIORITY',
                  },
                  caption: '优先级',
                  codeName: 'priority',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'priority',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  itemWidth: 290,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'remind_at',
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                    },
                    editorType: 'DATEPICKER',
                    editorWidth: 160,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'remind_at',
                  },
                  valueFormat: 'YYYY-MM-DD HH:mm:ss',
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.REMIND_AT',
                  },
                  caption: '提醒时间',
                  codeName: 'remind_at',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'remind_at',
                },
                {
                  dataType: 21,
                  enableCond: 3,
                  itemHeight: 200,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'description',
                  editor: {
                    maxLength: 32000,
                    showMaxLength: true,
                    editorHeight: 200,
                    editorParams: {
                      HEIGHT: '200',
                    },
                    editorType: 'TEXTAREA_10',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'description',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag:
                      'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMITEM.DESCRIPTION',
                  },
                  caption: '描述',
                  codeName: 'description',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'description',
                },
              ],
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFORM.TASK.BATCH_CREATE.GROUPPANEL.GROUP1',
              },
              caption: '任务信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.TASK.BATCH_CREATE.FORMPAGE.FORMPAGE1',
          },
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'batch_create',
      controlType: 'FORM',
      logicName: '批创建',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'form',
      },
      ctrlMsg: {
        codeName: 'UsrCtrlMsg0228593610',
        ctrlMsgItems: [
          {
            name: 'CREATESUCCESS_HIDDEN',
            id: 'createsuccess_hidden',
          },
          {
            name: 'UPDATESUCCESS_HIDDEN',
            id: 'updatesuccess_hidden',
          },
        ],
        name: '编辑表单自定义消息(隐藏)',
        id: 'usrctrlmsg0228593610',
      },
      modelId: '62dd9896ce7920603118183b89c6337c',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.task.batch_create',
    },
    {
      codeName: 'batch_create_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'batch_create_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.TASK.BATCH_CREATE_VIEW',
      },
      caption: '批创建',
      codeName: 'batch_create_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {},
      name: 'captionbar',
      id: 'batch_create_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '批创建',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.TASK.BATCH_CREATE_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 800,
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ccedcbb0f87995fa8606a5cae4fc74fe',
  modelType: 'PSAPPDEVIEW',
  name: 'taskbatch_create_view',
  id: 'crmweb.task_batch_create_view',
};
