export default {
  caption: '活动与任务',
  codeName: 'task_index_view',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS_INDEX',
                      id: 'nav_pos_index',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos_index',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                contentHeight: 100,
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  height: 100,
                  heightMode: 'PERCENTAGE',
                  layout: 'BORDER',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
              width: 100,
              widthMode: 'PERCENTAGE',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '首页菜单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    showCaption: true,
                    id: 'appmenu',
                  },
                ],
                predefinedType: 'AppHeader',
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                },
                id: 'app_header',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_LEFT',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 160,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'WEST',
              layout: 'BORDER',
              width: 160,
              widthMode: 'PX',
            },
            width: 160,
            showCaption: true,
            id: 'container_scroll_left',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        layoutMode: 'TABLE_24COL',
        appMenuItems: [
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0528093606',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '待办任务',
                tooltip: '待办任务',
                expanded: true,
                id: 'menuitem5',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0528918425',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '追踪中的任务',
                tooltip: '追踪中的任务',
                id: 'menuitem6',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0528941694',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '已完成任务',
                tooltip: '已完成任务',
                id: 'menuitem7',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0528092584',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '已取消任务',
                tooltip: '已取消任务',
                id: 'menuitem8',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '我的任务',
            tooltip: '我的任务',
            expanded: true,
            id: 'menuitem1',
          },
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                itemType: 'MENUITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '进行中的任务',
                tooltip: '进行中的任务',
                expanded: true,
                id: 'menuitem9',
              },
              {
                itemType: 'MENUITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '已完成任务',
                tooltip: '已完成任务',
                id: 'menuitem10',
              },
              {
                itemType: 'MENUITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '已取消任务',
                tooltip: '已取消任务',
                id: 'menuitem11',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '全部任务',
            tooltip: '全部任务',
            expanded: true,
            id: 'menuitem2',
          },
          {
            itemType: 'MENUITEM',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '我的活动',
            tooltip: '我的活动',
            id: 'menuitem3',
          },
          {
            itemType: 'MENUITEM',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '全部活动',
            tooltip: '全部活动',
            id: 'menuitem4',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'usr0528444165_menu',
        controlType: 'APPMENU',
        logicName: '应用首页视图菜单',
        controlParam: {},
        modelId: '1cae71b258d6032b9444757a953a2749',
        modelType: 'PSAPPMENU',
        name: 'appmenu',
        id: 'usr0528444165_menu',
      },
      {
        caption: '活动与任务',
        codeName: 'captionbar',
        controlType: 'CAPTIONBAR',
        controlParam: {},
        id: 'captionbar',
      },
    ],
    codeName: 'usr0528855884',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'TaskIndexView',
    controlParam: {},
    modelId: '2a484685ae984f24a1a7c10778ebef42',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0528855884',
  },
  title: '活动与任务',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ec8ad9680def7c49317d7f0da26bbfae',
  modelType: 'PSAPPINDEXVIEW',
  name: 'TaskIndexView',
  id: 'crmweb.task_index_view',
};
