export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'maneuver_tree_exp_view',
  deviewId: '424f3fd4994d837597da8440ab67e11a',
  accUserMode: 2,
  caption: '全部活动',
  codeName: 'task_maneuver_tree_exp_view',
  appDataEntityId: 'crmweb.task',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '树导航栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'treeexpbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 200,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              width: 200,
              widthMode: 'PX',
            },
            width: 200,
            id: 'view_content_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_content_right',
          },
        ],
        predefinedType: 'CONTAINER_H_SPLIT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_exp_split',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'TreeExpView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        title: '销售人员',
        xdataControlName: 'treeexpbar_tree',
        enableCounter: true,
        showTitleBar: true,
        autoLoad: true,
        showBusyIndicator: true,
        appViewRefs: [
          {
            realTitle: '全部活动',
            refAppViewId: 'crmweb.task_all_maneuver_tab_search_view',
            name: 'EXPITEM:all',
            id: 'expitem:all',
          },
          {
            parentDataJO: {
              srfparentdefname: 'owner',
            },
            realTitle: '全部活动',
            refAppViewId: 'crmweb.task_all_maneuver_tab_search_view',
            name: 'EXPITEM:user',
            id: 'expitem:user',
          },
        ],
        controls: [
          {
            detreeNodeRSs: [
              {
                childDETreeNodeId: 'all',
                parentDETreeNodeId: 'root',
                parentValueLevel: 1,
                searchMode: 3,
                id: '默认根节点 - 全部',
              },
              {
                childDETreeNodeId: 'user',
                parentDETreeNodeId: 'root',
                parentValueLevel: 1,
                searchMode: 3,
                id: '默认根节点 - 销售人员',
              },
            ],
            detreeNodes: [
              {
                nodeValue: 'root',
                text: '默认根节点',
                nodeType: 'ROOT',
                treeNodeType: 'STATIC',
                hasDETreeNodeRSs: true,
                rootNode: true,
                name: '默认根节点',
                id: 'root',
              },
              {
                text: '全部',
                navAppViewId: 'crmweb.task_all_maneuver_tab_search_view',
                nodeType: 'all',
                treeNodeType: 'STATIC',
                name: '全部',
                id: 'all',
              },
              {
                dataSourceType: 'DEDATASET',
                idAppDEFieldId: 'id',
                appDEDataSetId: 'fetch_all',
                textAppDEFieldId: 'first_name',
                navFilter: 'owner',
                navAppViewId: 'crmweb.task_all_maneuver_tab_search_view',
                nodeType: 'user',
                appDataEntityId: 'crmweb.user',
                treeNodeType: 'DE',
                expanded: true,
                name: '销售人员',
                id: 'user',
              },
            ],
            outputIconDefault: true,
            navViewPos: 'NONE',
            createControlAction: {
              appDEMethodId: 'create',
              appDataEntityId: 'crmweb.task',
              id: 'create',
            },
            fetchControlAction: {
              appDataEntityId: 'crmweb.task',
              id: 'fetch',
            },
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'crmweb.task',
              id: 'load',
            },
            dedataImportId: 'dataimport',
            removeControlAction: {
              appDEMethodId: 'remove',
              appDataEntityId: 'crmweb.task',
              id: 'remove',
            },
            updateControlAction: {
              appDEMethodId: 'update',
              appDataEntityId: 'crmweb.task',
              id: 'update',
            },
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'all_maneuver_tree_exp_view_tree_view',
            controlType: 'TREEVIEW',
            logicName: '全部活动树_树视图',
            appDataEntityId: 'crmweb.task',
            controlLogics: [
              {
                eventNames: 'SELECTIONCHANGE',
                logicTag: 'treeexpbar_tree',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'treeexpbar_selectionchange',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'treeexpbar_tree',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'treeexpbar_load',
              },
            ],
            controlParam: {
              id: 'treeexpbar_tree',
            },
            modelId: '6eeb5d3728af476e90f1d9962afb35f0',
            modelType: 'PSDETREEVIEW',
            name: 'treeexpbar_tree',
            id: 'crmweb.task.all_maneuver_tree_exp_view_tree_view',
          },
        ],
        codeName: 'maneuver_tree_exp_view_treeexpbar',
        controlType: 'TREEEXPBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'treeexpbar',
        },
        modelId: '45e16931f6f0b0c88bb4d761fd562f43_treeexpbar',
        modelType: 'PSEXPBAR',
        name: 'treeexpbar',
        id: 'maneuver_tree_exp_view_treeexpbar',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '全部活动',
        codeName: 'maneuver_tree_exp_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {},
        name: 'captionbar',
        id: 'maneuver_tree_exp_view_captionbar',
      },
    ],
    codeName: 'usr0604571347',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'tree_exp_view实体树导航视图布局面板',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    modelId: '8260fa3c6f095b7364eb39e1ce28130c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0604571347',
  },
  title: '全部活动',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '45e16931f6f0b0c88bb4d761fd562f43',
  modelType: 'PSAPPDEVIEW',
  name: 'taskmaneuver_tree_exp_view',
  id: 'crmweb.task_maneuver_tree_exp_view',
};
