export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'my_all_tab_search_view',
  deviewId: 'bd300c8e07c1a97158a3e39573e370ed',
  accUserMode: 2,
  caption: '我的全部任务',
  codeName: 'task_my_all_tab_search_view',
  appDataEntityId: 'crmweb.task',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId: 'panel_usr0318980456_button_filter_click@account',
                renderMode: 'BUTTON',
                tooltip: '过滤',
                uiactionTarget: 'SINGLEDATA',
                caption: '过滤',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysImage: {
                  cssClass: 'fa fa-filter',
                  glyph: 'xf0b0@FontAwesome',
                },
                id: 'button_filter',
              },
              {
                rawItem: {
                  caption: '文本内容',
                  halign: 'LEFT',
                  renderMode: 'TEXT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'static_text',
                },
                caption: '文本',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysPFPluginId: 'group_searchbar',
                showCaption: true,
                id: 'static_text',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '关系分页部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'tabexppanel',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel',
              },
              {
                rawItem: {
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar',
                },
                caption: '工具栏占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              spacingRight: 'INNERMEDIUM',
            },
            id: 'container3',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
              spacingBottom: 'INNERSMALL',
              spacingLeft: 'INNERMEDIUM',
              spacingTop: 'INNERSMALL',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'view_searchbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        groupMode: 'SINGLE',
        searchBarFilters: [
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_SUBJECT_LIKE',
              stdDataType: 25,
              valueOP: 'LIKE',
              name: 'N_SUBJECT_LIKE',
              id: 'n_subject_like',
            },
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              name: 'SUBJECT',
              id: 'subject',
            },
            allowEmpty: true,
            caption: '主题',
            itemType: 'FILTER',
            appDEFieldId: 'subject',
            name: 'SUBJECT',
            id: 'subject',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_STATUS_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_STATUS_EQ',
              id: 'n_status_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__task_status',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'STATUS',
              id: 'status',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFSFITEM.TASK.N_STATUS_EQ',
            },
            caption: '状态',
            itemType: 'FILTER',
            appDEFieldId: 'status',
            name: 'STATUS',
            id: 'status',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_PRIORITY_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_PRIORITY_EQ',
              id: 'n_priority_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__priority',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'PRIORITY',
              id: 'priority',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFSFITEM.TASK.N_PRIORITY_EQ',
            },
            caption: '优先级',
            itemType: 'FILTER',
            appDEFieldId: 'priority',
            name: 'PRIORITY',
            id: 'priority',
          },
          {
            dataType: 25,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_OWNER_EQ',
              stdDataType: 25,
              valueOP: 'EQ',
              name: 'N_OWNER_EQ',
              id: 'n_owner_eq',
            },
            editor: {
              singleSelect: true,
              appCodeListId: 'crmweb.crm__owner',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              name: 'OWNER',
              id: 'owner',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFSFITEM.TASK.N_OWNER_EQ',
            },
            caption: '所有者',
            itemType: 'FILTER',
            appDEFieldId: 'owner',
            name: 'OWNER',
            id: 'owner',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_DUE_DATE_GTANDEQ',
              stdDataType: 5,
              valueOP: 'GTANDEQ',
              name: 'N_DUE_DATE_GTANDEQ',
              id: 'n_due_date_gtandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_DUE_DATE_GTANDEQ',
              id: 'n_due_date_gtandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '到期日期(>=)',
            itemType: 'FILTER',
            appDEFieldId: 'due_date',
            name: 'N_DUE_DATE_GTANDEQ',
            id: 'n_due_date_gtandeq',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_DUE_DATE_LTANDEQ',
              stdDataType: 5,
              valueOP: 'LTANDEQ',
              name: 'N_DUE_DATE_LTANDEQ',
              id: 'n_due_date_ltandeq',
            },
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_DUE_DATE_LTANDEQ',
              id: 'n_due_date_ltandeq',
            },
            allowEmpty: true,
            hidden: true,
            caption: '到期日期(<=)',
            itemType: 'FILTER',
            appDEFieldId: 'due_date',
            name: 'N_DUE_DATE_LTANDEQ',
            id: 'n_due_date_ltandeq',
          },
          {
            dataType: 5,
            labelPos: 'NONE',
            defsearchMode: {
              codeName: 'N_DUE_DATE_IN',
              stdDataType: 5,
              valueOP: 'IN',
              name: 'N_DUE_DATE_IN',
              id: 'n_due_date_in',
            },
            editor: {
              editorParams: {
                TIMEFMT: 'YYYY-MM-DD',
              },
              editorType: 'DATERANGE_NOTIME',
              editorItems: [
                {
                  name: 'N_DUE_DATE_GTANDEQ',
                  id: 'n_due_date_gtandeq',
                },
                {
                  name: 'N_DUE_DATE_LTANDEQ',
                  id: 'n_due_date_ltandeq',
                },
              ],
              valueType: 'SIMPLE',
              editable: true,
              name: 'N_DUE_DATE_IN',
              id: 'n_due_date_in',
            },
            allowEmpty: true,
            caption: '到期日期',
            itemType: 'FILTER',
            appDEFieldId: 'due_date',
            name: 'N_DUE_DATE_IN',
            id: 'n_due_date_in',
          },
        ],
        searchBarGroups: [
          {
            defaultGroup: true,
            caption: '正在执行的任务',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"30"}]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'taskdoing',
          },
          {
            caption: '所有任务',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[]}]}}',
            itemType: 'GROUP',
            userTag: 'PUBLIC',
            id: 'all',
          },
        ],
        quickSearchMode: 1,
        enableFilter: true,
        enableGroup: true,
        enableQuickSearch: true,
        codeName: 'myalltask',
        controlStyle: 'FILTER_SEARCHBAR',
        controlType: 'SEARCHBAR',
        logicName: '我的全部任务搜索栏',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'searchbar',
        },
        sysPFPluginId: 'filter_searchbar',
        modelId: 'a94a7af91ecea9e85c05d405dd1a7ec6',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'crmweb.task.myalltask',
      },
      {
        tabExpPageIds: ['grid', 'kanban'],
        tabLayout: 'TOP',
        uniqueTag: 'task_my_all_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '我的全部任务',
            refAppViewId: 'crmweb.task_my_all_grid_view',
            name: 'EXPITEM:grid',
            id: 'expitem:grid',
          },
          {
            realTitle: '我得全部任务看板',
            refAppViewId: 'crmweb.task_my_all_task_kanban_view',
            name: 'EXPITEM:kanban',
            id: 'expitem:kanban',
          },
        ],
        controls: [
          {
            sysImage: {
              cssClass: 'fa fa-table',
              glyph: 'xf0ce@FontAwesome',
            },
            caption: '表格视图',
            embeddedAppDEViewId: 'crmweb.task_my_all_grid_view',
            codeName: 'my_all_tab_search_view_grid',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.task',
            controlParam: {
              id: 'grid',
            },
            modelId: 'ecec6bf7acdb4239f96d20ca27ecbadd_grid',
            modelType: 'PSVIEWPANEL',
            name: 'grid',
            id: 'my_all_tab_search_view_grid',
          },
          {
            sysImage: {
              cssClass: 'fa fa-columns',
              glyph: 'xf0db@FontAwesome',
            },
            caption: '看板视图',
            embeddedAppDEViewId: 'crmweb.task_my_all_task_kanban_view',
            codeName: 'my_all_tab_search_view_kanban',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'crmweb.task',
            controlParam: {
              id: 'kanban',
            },
            modelId: 'ecec6bf7acdb4239f96d20ca27ecbadd_kanban',
            modelType: 'PSVIEWPANEL',
            name: 'kanban',
            id: 'my_all_tab_search_view_kanban',
          },
        ],
        codeName: 'my_all_tab_search_view_tabexppanel',
        controlStyle: 'TABEXPPANEL_DROPDOWN',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'crmweb.task',
        controlParam: {},
        sysPFPluginId: 'tabexppanel_dropdown',
        modelId: 'ecec6bf7acdb4239f96d20ca27ecbadd_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'my_all_tab_search_view_tabexppanel',
      },
      {
        caption: '我的全部任务',
        codeName: 'my_all_tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {},
        name: 'captionbar',
        id: 'my_all_tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0318980456',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索通用布局',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    modelId: 'f9a64be769ab83bfc4ff869c38a9192b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0318980456',
  },
  title: '我的全部任务',
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'ecec6bf7acdb4239f96d20ca27ecbadd',
  modelType: 'PSAPPDEVIEW',
  name: 'taskmy_all_tab_search_view',
  id: 'crmweb.task_my_all_tab_search_view',
};
