export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_not_close_view',
  deviewId: 'f89a3525859577082ca8aa7b1f1c023d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.TASK.GRID_NOT_CLOSE_VIEW',
  },
  caption: '待办任务（任务）',
  codeName: 'task_grid_not_close_view',
  appDataEntityId: 'crmweb.task',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.task_task_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.task_task_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.task_main_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.task_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavContexts: [
    {
      key: 'PRINCIPAL_ID',
      value: 'principal_id',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
  ],
  appViewNavParams: [
    {
      key: 'principal_id',
      value: 'principal_id',
      id: 'principal_id',
    },
  ],
  appViewRefs: [
    {
      realTitle: '任务编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.TASK.EDIT_VIEW',
      },
      refAppViewId: 'crmweb.task_task_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realTitle: '任务信息',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.TASK.MAIN_VIEW',
      },
      refAppViewId: 'crmweb.task_main_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'DESC',
      minorSortAppDEFieldId: 'due_date',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'subject',
          excelCaption: '主题',
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SUBJECT',
          },
          caption: '主题',
          codeName: 'subject',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 400,
          widthUnit: 'PX',
          enableSort: true,
          id: 'subject',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'due_date',
          excelCaption: '到期日期',
          appDEFieldId: 'due_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DUE_DATE',
          },
          caption: '到期日期',
          codeName: 'due_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'due_date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'closed_time',
          excelCaption: '关闭时间',
          appDEFieldId: 'closed_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CLOSED_TIME',
          },
          caption: '关闭时间',
          codeName: 'closed_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'closed_time',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'subject',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'due_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'due_date',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'closed_time',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'closed_time',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      forceFit: true,
      singleSelect: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_not_close_task_related',
        appDataEntityId: 'crmweb.task',
        id: 'fetch',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.task',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_not_close_view_grid',
      controlType: 'GRID',
      logicName: '待办任务（任务）（表格）_表格',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        ctrlParams: {
          SHOWMODE: 'MIXIN',
        },
        id: 'grid',
      },
      modelId: '9ff30aec4d3f326e250244ea53789bd9',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.task.grid_not_close_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.TASK.GRID_NOT_CLOSE_VIEW_SEARCHFORM.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_not_close_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '待办任务（任务）（表格）_搜索表单',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'searchform',
      },
      modelId: '1a9cacf62ef5a673244424bbba48ab79',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.task.grid_not_close_view_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.TASK.GRID_NOT_CLOSE_VIEW',
      },
      caption: '待办任务（任务）',
      codeName: 'grid_not_close_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_not_close_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '待办任务（任务）',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.TASK.GRID_NOT_CLOSE_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a6ec1cf1862bfc66cf4b5f32db593c2b',
  modelType: 'PSAPPDEVIEW',
  name: 'taskgrid_not_close_view',
  id: 'crmweb.task_grid_not_close_view',
};
