export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 're_mpick_up_view_PickupGridView',
  deviewId: '0d814ce9e01926b309ab876d86052047',
  accUserMode: 2,
  caption: '任务&活动',
  codeName: 'task_re_mpick_up_view_pickup_grid_view',
  appDataEntityId: 'crmweb.task',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  appViewNavParams: [
    {
      key: 'principal_id',
      value: 'principal_id',
      id: 'principal_id',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'subject',
          excelCaption: '主题',
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SUBJECT',
          },
          caption: '主题',
          codeName: 'subject',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 250,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'subject',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'status',
          excelCaption: '状态',
          appCodeListId: 'crmweb.crm__task_status',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.STATUS',
          },
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'owner',
          excelCaption: '所有者',
          appCodeListId: 'crmweb.crm__owner',
          appDEFieldId: 'owner',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.OWNER',
          },
          caption: '所有者',
          codeName: 'owner',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'owner',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'subject',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'status',
        },
        {
          appDEFieldId: 'owner',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'owner',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'subject',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_not_related_task_and_maneuver',
        appDataEntityId: 'crmweb.task',
        id: 'fetch',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.task',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 're_mpick_up_view_pickup_grid_view_grid',
      controlType: 'GRID',
      logicName: '任务活动多项数据选择视图_选择数据视图_表格',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'grid',
      },
      modelId: 'd3948ec14e6b8ab63fed8b406ede5395',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.task.re_mpick_up_view_pickup_grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'subject',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '请输入主题',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_subject_like',
              },
              allowEmpty: true,
              caption: '主题',
              codeName: 'n_subject_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 12,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'n_subject_like',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'usr07184658_search_form',
      controlType: 'SEARCHFORM',
      logicName: '任务活动多项数据选择视图_选择数据视图_搜索表单',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'searchform',
      },
      modelId: '7254ce1a23120c5840ef607a65831168',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.task.usr07184658_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '任务&活动',
      codeName: 're_mpick_up_view_pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {},
      name: 'captionbar',
      id: 're_mpick_up_view_pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '任务活动多项数据选择视图_选择数据视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'fc82bd45176ebfd972fe917c3ecc00fb',
  modelType: 'PSAPPDEVIEW',
  name: 'taskre_mpick_up_view_PickupGridView',
  id: 'crmweb.task_re_mpick_up_view_pickup_grid_view',
};
