export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'work_task_main_view',
  deviewId: 'd0261bccdd14b20ba6ba191946cd0d04',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.TASK.MAIN_VIEW',
  },
  caption: '工作信息',
  codeName: 'task_work_task_main_view',
  appDataEntityId: 'crmweb.task',
  appViewNavContexts: [
    {
      key: 'N_OWNER_ID_EQ',
      value: 'task',
      name: 'N_OWNER_ID_EQ',
      id: 'n_owner_id_eq',
    },
    {
      key: 'OWNER_ID',
      value: 'task',
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      key: 'PRINCIPAL_ID',
      value: 'task',
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'OWNER_TYPE',
      value: 'TASK',
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'TASK',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'task',
      id: 'n_owner_id_eq',
    },
    {
      key: 'principal_id',
      value: 'task',
      id: 'principal_id',
    },
    {
      rawValue: true,
      key: 'owner_type',
      value: 'TASK',
      id: 'owner_type',
    },
    {
      rawValue: true,
      key: 'principal_type',
      value: 'TASK',
      id: 'principal_type',
    },
    {
      key: 'owner_id',
      value: 'task',
      id: 'owner_id',
    },
  ],
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionType: 'UIACTION',
                        buttonStyle: 'INFO',
                        buttonType: 'PANELBUTTON',
                        uiactionId: 'editview_exitaction',
                        renderMode: 'BUTTON',
                        tooltip: '退出',
                        capLanguageRes: {
                          lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
                        },
                        caption: '退出',
                        itemStyle: 'INFO',
                        itemType: 'BUTTON',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        sysImage: {
                          cssClass: 'fa fa-arrow-left',
                          glyph: 'xf060@FontAwesome',
                        },
                        id: 'button_calluilogic',
                      },
                      {
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 70,
                          editorParams: {
                            MAXCOUNT: '1',
                          },
                          editorStyle: 'CRM_IMAGE_UPLOAD',
                          editorType: 'PICTURE_ONE',
                          editorWidth: 70,
                          sysPFPluginId: 'crm_image_upload',
                          predefinedType: 'FIELD_TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'field_textbox',
                        },
                        allowEmpty: true,
                        caption: '文本框',
                        contentHeight: 70,
                        contentWidth: 70,
                        height: 70,
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          height: 70,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          width: 70,
                          widthMode: 'PX',
                        },
                        width: 70,
                        id: 'field_textbox',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'srfmajortext',
                        },
                        viewFieldName: 'srfmajortext',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'srfmajortext',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                predefinedType: 'CONTAINER_SINGLEDATA',
                layout: {
                  layout: 'FLEX',
                },
                dataName: 'srfactiveviewdata',
                dataRegionType: 'SINGLEDATA',
                dataSourceType: 'VIEWSESSIONPARAM',
                caption: '单项数据容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container_singledata',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系数据栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'drbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_drbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'form',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_exp_content',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView2',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'work_task_open_edit_view@task',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '编辑',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-edit',
              glyph: 'xf044@FontAwesome',
            },
            tooltip: '编辑',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction4',
          },
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'editview_removeandexitaction',
                uiactionTarget: 'SINGLEKEY',
                hiddenItem: true,
                valid: true,
                capLanguageRes: {
                  lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                },
                caption: '删除并关闭',
                itemType: 'DEUIACTION',
                sysImage: {
                  cssClass: 'fa fa-remove',
                  glyph: 'xf00d@FontAwesome',
                },
                tooltip: '删除并关闭',
                tooltipLanguageRes: {
                  lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                },
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-ellipsis-h',
              glyph: 'xf141@FontAwesome',
            },
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_prevrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '上一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-left',
              glyph: 'xf053@FontAwesome',
            },
            tooltip: '上一个记录',
            showIcon: true,
            id: 'deuiaction6',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_nextrecordaction',
            uiactionTarget: 'SINGLEKEY',
            valid: true,
            caption: '下一个记录',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-chevron-right',
              glyph: 'xf054@FontAwesome',
            },
            tooltip: '下一个记录',
            showIcon: true,
            id: 'deuiaction7',
          },
        ],
        xdataControlName: 'form',
        codeName: 'work_task_main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '任务主数据视图_工具栏（工作任务）',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '3525f5b9adf432bb21cdda63a39510f5',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'work_task_main_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.task',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.task',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.task',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.task',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.task',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.task',
          id: 'update',
        },
        infoFormMode: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'subject',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'subject',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.SUBJECT',
                    },
                    caption: '任务名称',
                    codeName: 'subject',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'subject',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'due_date',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'due_date',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.DUE_DATE',
                    },
                    caption: '到期日期',
                    codeName: 'due_date',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['type'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'type',
                            value: 'TASK',
                            logicType: 'SINGLE',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'due_date',
                  },
                  {
                    createDV: 'userid',
                    createDVT: 'SESSION',
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'owner',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'crmweb.crm__owner',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'owner',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.OWNER',
                    },
                    caption: '所有者',
                    codeName: 'owner',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'owner',
                  },
                  {
                    createDV: 'STATUS',
                    createDVT: 'CONTEXT',
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'status',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'crmweb.crm__task_status',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'status',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.STATUS',
                    },
                    caption: '状态',
                    codeName: 'status',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['type'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'type',
                            value: 'TASK',
                            logicType: 'SINGLE',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'status',
                  },
                  {
                    dataType: 21,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'executors',
                    editor: {
                      enablePickupView: true,
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_all',
                      appDataEntityId: 'crmweb.user',
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        readonly: 'true',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'ADDRESSPICKUP',
                      objectIdField: 'user_id',
                      objectNameField: 'name',
                      valueType: 'OBJECTS',
                      editable: true,
                      readOnly: true,
                      id: 'executors',
                    },
                    allowEmpty: true,
                    caption: '执行人',
                    codeName: 'executors',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    sysCss: {
                      cssName: 'blackfont',
                    },
                    showCaption: true,
                    id: 'executors',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'start_time',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'start_time',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.START_TIME',
                    },
                    caption: '活动时间',
                    codeName: 'start_time',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['type'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'type',
                            value: 'MANEUVER',
                            logicType: 'SINGLE',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'start_time',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'end_time',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'end_time',
                    },
                    valueFormat: 'YYYY-MM-DD HH:mm:ss',
                    allowEmpty: true,
                    hidden: true,
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.END_TIME',
                    },
                    caption: '结束时间',
                    codeName: 'end_time',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'end_time',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'remind_at',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'remind_at',
                    },
                    valueFormat: 'YYYY-MM-DD HH:mm:ss',
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.REMIND_AT',
                    },
                    caption: '提醒时间',
                    codeName: 'remind_at',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['type'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'type',
                            value: 'TASK',
                            logicType: 'SINGLE',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'remind_at',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 190,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'priority',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'crmweb.crm__priority',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'priority',
                    },
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.PRIORITY',
                    },
                    caption: '优先级',
                    codeName: 'priority',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['type'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'type',
                            value: 'TASK',
                            logicType: 'SINGLE',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'priority',
                  },
                ],
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.GROUPPANEL.GROUPPANEL1',
                },
                caption: '详细信息',
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 16,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel1',
              },
              {
                dataType: 21,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 190,
                noPrivDisplayMode: 1,
                appDEFieldId: 'description',
                editor: {
                  maxLength: 32000,
                  showMaxLength: true,
                  editorParams: {
                    readonly: 'true',
                  },
                  editorType: 'TEXTAREA',
                  valueType: 'SIMPLE',
                  editable: true,
                  readOnly: true,
                  id: 'description',
                },
                allowEmpty: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.DESCRIPTION',
                },
                caption: '描述',
                codeName: 'description',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 16,
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                sysCss: {
                  cssName: 'input-readonly',
                },
                showCaption: true,
                id: 'description',
              },
              {
                createDV: 'TYPE',
                createDVT: 'CONTEXT',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 190,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'type',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.TYPE',
                },
                caption: '类型',
                codeName: 'type',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'type',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 190,
                noPrivDisplayMode: 1,
                appDEFieldId: 'owner_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'owner_id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.OWNER_ID',
                },
                caption: '所属数据标识',
                codeName: 'owner_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'owner_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 190,
                noPrivDisplayMode: 1,
                appDEFieldId: 'owner_name',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'owner_name',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMITEM.OWNER_NAME',
                },
                caption: '所属数据名称',
                codeName: 'owner_name',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'owner_name',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 190,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            capLanguageRes: {
              lanResTag:
                'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMPAGE.FORMPAGE1',
            },
            caption: '概览',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    appViewId: 'crmweb.activitiy_time_line_view',
                    parentDataJO: {
                      srfparentdename: 'TASK',
                      SRFPARENTTYPE: 'CUSTOM',
                    },
                    codeName: 'druipart1',
                    detailStyle: 'DEFAULT',
                    detailType: 'DRUIPART',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'druipart1',
                  },
                ],
                capLanguageRes: {
                  lanResTag:
                    'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.GROUPPANEL.GROUPPANEL14',
                },
                caption: '历史信息',
                codeName: 'grouppanel14',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel14',
              },
            ],
            capLanguageRes: {
              lanResTag:
                'CONTROL.DEFORM.TASK.MAIN_VIEW_FORM.FORMPAGE.FORMPAGE2',
            },
            caption: '时间轴',
            codeName: 'formpage2',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage2',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'work_task_main_view_form',
        controlStyle: 'ANCHOR_STYLE',
        controlType: 'FORM',
        logicName: '任务主数据视图_表单（工作）',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'form',
        },
        sysPFPluginId: 'anchor_style',
        modelId: 'c23cb3d19166973b06019cbc5aaf30d9',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'crmweb.task.work_task_main_view_form',
      },
      {
        dedrbarGroups: [
          {
            caption: '详细信息',
            name: '详细信息',
            id: 'drgroup',
          },
        ],
        showTitle: true,
        dataRelationTag: 'work_task_main_view_DR',
        editItemCaption: '任务',
        appCounterRefId: '32e24308d1153ecfe362250132464b6a',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'drgroup',
            caption: '附件',
            counterId: 'attachment',
            appViewId: 'crmweb.task_attachment_view',
            id: 'attachment',
          },
          {
            dedrbarGroupId: 'drgroup',
            caption: '进展情况',
            appViewId: 'crmweb.task_note_condition_view',
            id: 'note_condition',
          },
        ],
        uniqueTag: 'task_work_task_main_view__drbar',
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'task_main_view_dr',
              counterType: 'DEDR',
              getAppDEActionId: 'main_view_dr_count',
              appDataEntityId: 'crmweb.task',
              timer: 60000,
              uniqueTag: 'task_main_view_dr',
              name: '任务main_view关系',
              id: 'crmweb.task_main_view_dr',
            },
            refMode: {
              srfdeid: 'TASK',
            },
            tag: '32e24308d1153ecfe362250132464b6a',
            uniqueTag: 'task_main_view_dr',
            id: '32e24308d1153ecfe362250132464b6a',
          },
        ],
        codeName: 'work_task_main_view_dr',
        controlStyle: 'DRBAR_ANCHOR_STYLE',
        controlType: 'DRBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'drbar_anchor_style',
        modelId: '2c4db99cba8f1257fc48febc1a51f3db',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'work_task_main_view_dr',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'crmweb.task',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.task',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.task',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.task',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.task',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.task',
          id: 'update',
        },
        infoFormMode: true,
        formStyle: 'INFOPANEL',
        deformPages: [
          {
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            deformDetails: [
              {
                layout: {
                  dir: 'row',
                  layout: 'FLEX',
                },
                deformDetails: [
                  {
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    codeName: 'grouppanel1',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'grouppanel1',
                  },
                  {
                    layout: {
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    deformDetails: [
                      {
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'NONE',
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'name',
                            editor: {
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'name',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'CONTROL.DEFORM.TASK.MINI_FORM.FORMITEM.NAME',
                            },
                            caption: '名称',
                            codeName: 'name',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'name',
                          },
                          {
                            rawItem: {
                              caption: '-',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem2',
                            },
                            codeName: 'rawitem2',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'rawitem2',
                          },
                        ],
                        codeName: 'grouppanel4',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'grouppanel4',
                      },
                      {
                        layout: {
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        deformDetails: [
                          {
                            rawItem: {
                              sysImage: {
                                rawContent:
                                  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAKJJREFUOE+lk9EVgjAMRS87wBAuwTwO4SdD6BAMIUOwBA7BeRz1BEwTkP60H723SZpUnFzVDr4FLsALmN73dR51zgSCr4VHOkkiQQTLGQo8WEBtIroDgxeBByv3x0bQA/1WkIVty/GU1AqOwBKtUvgLtt/YADdAe7aWlz+XbAp7JCvYa6RI8gOXOtGTuHDUylZShLNZkERD9C2YV91smLIfYQa8YiARsoU2QwAAAABJRU5ErkJggg==',
                              },
                              contentType: 'IMAGE',
                              id: 'rawitem1',
                            },
                            codeName: 'rawitem1',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            sysImage: {
                              rawContent:
                                'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAKJJREFUOE+lk9EVgjAMRS87wBAuwTwO4SdD6BAMIUOwBA7BeRz1BEwTkP60H723SZpUnFzVDr4FLsALmN73dR51zgSCr4VHOkkiQQTLGQo8WEBtIroDgxeBByv3x0bQA/1WkIVty/GU1AqOwBKtUvgLtt/YADdAe7aWlz+XbAp7JCvYa6RI8gOXOtGTuHDUylZShLNZkERD9C2YV91smLIfYQa8YiARsoU2QwAAAABJRU5ErkJggg==',
                            },
                            showCaption: true,
                            id: 'rawitem1',
                          },
                        ],
                        codeName: 'grouppanel3',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'grouppanel3',
                      },
                    ],
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'grouppanel2',
                  },
                ],
                capLanguageRes: {
                  lanResTag: 'CONTROL.DEFORM.TASK.MINI_FORM.GROUPPANEL.GROUP1',
                },
                caption: '客户基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'id',
              },
            ],
            capLanguageRes: {
              lanResTag: 'CONTROL.DEFORM.TASK.MINI_FORM.FORMPAGE.FORMPAGE1',
            },
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'mini_form',
        controlType: 'FORM',
        logicName: '主数据小表单',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'miniform',
        },
        modelId: '7f4db28363ebddf2ee6fb7b2fc83b279',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'miniform',
        id: 'crmweb.task.mini_form',
      },
      {
        codeName: 'work_task_main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'work_task_main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'PAGE.CAPTION.TASK.MAIN_VIEW',
        },
        caption: '工作信息',
        codeName: 'work_task_main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {},
        name: 'captionbar',
        id: 'work_task_main_view_captionbar',
      },
    ],
    codeName: 'usr0319628389',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主数据通用布局面板',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    modelId: '6169ec687d45a098f7102272c1f7c4ca',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0319628389',
  },
  title: '工作信息',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.TASK.MAIN_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'ac4f40e283b8a984bdaefa1a1f4abf03',
  modelType: 'PSAPPDEVIEW',
  name: 'taskwork_task_main_view',
  id: 'crmweb.task_work_task_main_view',
};
