export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'portal_calendar_view',
  deviewId: 'b7845b3f8b8b405555606e1a63e5ec89',
  accUserMode: 2,
  caption: '我的本周活动',
  codeName: 'task_portal_calendar_view',
  appDataEntityId: 'crmweb.task',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavParams: [
    {
      rawValue: true,
      key: 'n_is_this_week_eq',
      value: '1',
      id: 'n_is_this_week_eq',
    },
  ],
  controls: [
    {
      calendarStyle: 'WEEK',
      emptyText: '本周暂无活动',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_time',
          contentAppDEFieldId: 'description',
          endTimeAppDEFieldId: 'start_time',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'maneuver',
          appDEDataSetId: 'fetch_my_maneuver',
          textAppDEFieldId: 'subject',
          appDataEntityId: 'crmweb.task',
          name: '活动',
          id: 'maneuver',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'portal_calendar_view_calendar',
      controlType: 'CALENDAR',
      logicName: '门户_我的本周活动（日历）_日历部件',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'calendar',
      },
      modelId: '69fb7a1c4f57f67c16ea2e7ff6d5fa11',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'crmweb.task.portal_calendar_view_calendar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '我的本周活动',
      codeName: 'portal_calendar_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.task',
      controlParam: {},
      name: 'captionbar',
      id: 'portal_calendar_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '我的本周活动',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9adcee218ca4dc4606bca1b64b7cf93e',
  modelType: 'PSAPPDEVIEW',
  name: 'taskportal_calendar_view',
  id: 'crmweb.task_portal_calendar_view',
};
