export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'all_maneuver_grid_view',
  deviewId: 'a28f440021ebcce7e219c6452a627e98',
  accUserMode: 2,
  caption: '全部活动',
  codeName: 'task_all_maneuver_grid_view',
  appDataEntityId: 'crmweb.task',
  appViewNavContexts: [
    {
      key: 'N_OWNER_EQ',
      value: 'user',
      name: 'N_OWNER_EQ',
      id: 'n_owner_eq',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_eq',
      value: 'user',
      id: 'n_owner_eq',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'crmweb.task_the_maneuver_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.task_the_maneuver_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'crmweb.task_maneuver_main_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'crmweb.task_maneuver_main_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '活动编辑视图',
        refAppViewId: 'crmweb.task_the_maneuver_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '活动信息',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.TASK.MAIN_VIEW',
        },
        refAppViewId: 'crmweb.task_maneuver_main_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'create_new_maneuver@task',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '创建活动',
            itemType: 'DEUIACTION',
            tooltip: '创建活动',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_refreshaction',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '刷新',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-refresh',
              glyph: 'xf021@FontAwesome',
            },
            tooltip: '刷新',
            showIcon: true,
            id: 'deuiaction7',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'all_maneuver_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '全部活动_工具栏',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          ctrlParams: {
            TELEPORTTAG: '#task_all_maneuver_tab_search_view-tabtoolbar',
          },
          id: 'toolbar',
        },
        modelId: 'c9155093d24b8da01f89a383ac29c6f6',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'all_maneuver_grid_view_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        minorSortDir: 'DESC',
        minorSortAppDEFieldId: 'start_time',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'start_time',
            excelCaption: '活动时间',
            appDEFieldId: 'start_time',
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.START_TIME',
            },
            caption: '活动时间',
            codeName: 'start_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'start_time',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'subject',
            excelCaption: '主题',
            appDEFieldId: 'subject',
            deuiactionGroup: {
              uiactionGroupDetails: [
                {
                  actionLevel: 200,
                  afterItemType: 'NONE',
                  beforeItemType: 'NONE',
                  buttonStyle: 'DEFAULT',
                  detailType: 'DEUIACTION',
                  uiactionId: 'maneuver_open_edit_view@task',
                  showIcon: true,
                  sysImage: {
                    cssClass: 'fa fa-edit',
                    glyph: 'xf044@FontAwesome',
                  },
                  id: 'uc8e3995',
                },
              ],
              appDataEntityId: 'crmweb.task',
              uniqueTag: 'task__Usr0625432311',
              name: '活动敏捷操作列',
              id: 'usr0625432311',
            },
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.SUBJECT',
            },
            caption: '主题',
            codeName: 'subject',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'subject',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '状态',
            appCodeListId: 'crmweb.crm__task_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'CENTER',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.STATUS',
            },
            caption: '状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'owner',
            excelCaption: '所有者',
            appCodeListId: 'crmweb.crm__owner',
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.OWNER',
            },
            caption: '所有者',
            codeName: 'owner',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'PX',
            enableSort: true,
            id: 'owner',
          },
        ],
        degridDataItems: [
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'start_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'start_time',
          },
          {
            appDEFieldId: 'subject',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'subject',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'status',
          },
          {
            appDEFieldId: 'owner',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'owner',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'subject',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_all_maneuver',
          appDataEntityId: 'crmweb.task',
          id: 'fetch',
        },
        dedataImportId: 'dataimport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.task',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        controls: [
          {
            detoolbarItems: [
              {
                actionLevel: 100,
                noPrivDisplayMode: 2,
                uiactionId: 'remove@task',
                uiactionTarget: 'MULTIKEY',
                valid: true,
                caption: '删除',
                itemType: 'DEUIACTION',
                tooltip: '删除',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction5',
              },
            ],
            codeName: 'all_maneuver_grid_view_grid_batchtoolbar',
            controlType: 'TOOLBAR',
            logicName: '批操作_工具栏',
            appDataEntityId: 'crmweb.task',
            controlParam: {
              id: 'grid_batchtoolbar',
            },
            modelId: '7f60d400c60441a72abfaca9b2495ba7',
            modelType: 'PSDETOOLBAR',
            name: 'grid_batchtoolbar',
            id: 'all_maneuver_grid_view_grid_batchtoolbar',
          },
        ],
        codeName: 'all_maneuver_grid_view_grid',
        controlStyle: 'NUMBER_GRID',
        controlType: 'GRID',
        logicName: '全部活动_表格',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'grid',
        },
        sysPFPluginId: 'number_grid',
        modelId: '09f04043c05edf61018f0269ded73030',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'crmweb.task.all_maneuver_grid_view_grid',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'all_maneuver_grid_view_search_form',
        controlType: 'SEARCHFORM',
        logicName: '全部活动_搜索表单',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'searchform',
        },
        modelId: 'c3eb1563f6bade8cb431bb19111d7992',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'crmweb.task.all_maneuver_grid_view_search_form',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '全部活动',
        codeName: 'all_maneuver_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.task',
        controlParam: {},
        name: 'captionbar',
        id: 'all_maneuver_grid_view_captionbar',
      },
    ],
    codeName: 'usr0415540230',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '分页搜索内表格视图通用布局',
    appDataEntityId: 'crmweb.task',
    controlParam: {},
    modelId: '539d683107e4178ee9be6197d342453c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0415540230',
  },
  title: '全部活动',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '126d4de25ef630838490e19959c0e34b',
  modelType: 'PSAPPDEVIEW',
  name: 'taskall_maneuver_grid_view',
  id: 'crmweb.task_all_maneuver_grid_view',
};
