export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'info_edit_view',
  deviewId: 'dd494adddc77f07f8b737f21919951cb',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.USER',
  },
  caption: '个人信息编辑',
  codeName: 'user_info_edit_view',
  appDataEntityId: 'crmweb.user',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      key: 'USER',
      value: 'userid',
      name: 'USER',
      id: 'user',
    },
  ],
  appViewNavParams: [
    {
      key: 'user',
      value: 'userid',
      id: 'user',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'info_edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '个人信息编辑_工具栏',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '24bc26ac021f82c9567406250c7eddc9',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'info_edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.user',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.user',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.user',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.user',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.user',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.user',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'first_name',
                      editor: {
                        maxLength: 50,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'first_name',
                      },
                      caption: '姓名',
                      codeName: 'first_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'first_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 1,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'user_name',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'user_name',
                      },
                      allowEmpty: true,
                      caption: '账号',
                      codeName: 'user_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'user_name',
                    },
                    {
                      dataType: 25,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'email',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'email',
                      },
                      allowEmpty: true,
                      caption: '电子邮件',
                      codeName: 'email',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'email',
                    },
                    {
                      dataType: 25,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'role',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'role',
                      },
                      allowEmpty: true,
                      caption: '职位',
                      codeName: 'role',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'role',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'alias',
                      editor: {
                        maxLength: 50,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'alias',
                      },
                      allowEmpty: true,
                      caption: '别名',
                      codeName: 'alias',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'alias',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'phone',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'phone',
                      },
                      allowEmpty: true,
                      caption: '电话',
                      codeName: 'phone',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'phone',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'mobile',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'mobile',
                      },
                      allowEmpty: true,
                      caption: '手机',
                      codeName: 'mobile',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'mobile',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'website',
                      editor: {
                        maxLength: 200,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'website',
                      },
                      allowEmpty: true,
                      caption: '网站',
                      codeName: 'website',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'website',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'fax',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'fax',
                      },
                      allowEmpty: true,
                      caption: '传真',
                      codeName: 'fax',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'fax',
                    },
                    {
                      dataType: 5,
                      enableCond: 3,
                      itemWidth: 230,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'dob',
                      editor: {
                        dateTimeFormat: 'YYYY-MM-DD',
                        editorParams: {
                          TIMEFMT: 'YYYY-MM-DD',
                        },
                        editorType: 'DATEPICKEREX_NOTIME',
                        editorWidth: 100,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'dob',
                      },
                      valueFormat: 'YYYY-MM-DD',
                      allowEmpty: true,
                      caption: '生日',
                      codeName: 'dob',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'dob',
                    },
                  ],
                  caption: '用户信息',
                  codeName: 'group1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'group1',
                },
              ],
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'street',
                      editor: {
                        maxLength: 250,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'street',
                      },
                      allowEmpty: true,
                      caption: '街道',
                      codeName: 'street',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'street',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'city',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'city',
                      },
                      allowEmpty: true,
                      caption: '城市',
                      codeName: 'city',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'city',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'state',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'state',
                      },
                      allowEmpty: true,
                      caption: '省/市',
                      codeName: 'state',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'state',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'zip',
                      editor: {
                        maxLength: 30,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'zip',
                      },
                      allowEmpty: true,
                      caption: '邮编',
                      codeName: 'zip',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'zip',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'country',
                      editor: {
                        maxLength: 100,
                        editorType: 'TEXTBOX',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'country',
                      },
                      allowEmpty: true,
                      caption: '国家/地区',
                      codeName: 'country',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'country',
                    },
                  ],
                  caption: '地址信息',
                  codeName: 'grouppanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 12,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel1',
                },
              ],
              codeName: 'grouppanel4',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'grouppanel4',
            },
            {
              layout: {
                align: 'center',
                dir: 'row',
                layout: 'FLEX',
              },
              deformDetails: [
                {
                  actionType: 'UIACTION',
                  buttonStyle: 'DEFAULT',
                  uiactionId: 'editview_saveaction',
                  tooltip: '确定',
                  capLanguageRes: {
                    lanResTag: 'TBB.TEXT.*.SAVE',
                  },
                  caption: '确定',
                  codeName: 'button1',
                  detailStyle: 'DEFAULT',
                  detailType: 'BUTTON',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                    width: 120,
                    widthMode: 'PX',
                  },
                  sysImage: {
                    cssClass: 'fa fa-save',
                    glyph: 'xf0c7@FontAwesome',
                  },
                  showCaption: true,
                  id: 'button1',
                },
              ],
              codeName: 'grouppanel5',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colLG: 8,
                colMD: 12,
                layout: 'TABLE_24COL',
              },
              id: 'grouppanel5',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'edit_view_form',
      controlType: 'FORM',
      logicName: '个人信息编辑_表单',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'form',
      },
      modelId: '80b8e3d3d739f264da9d65bc021004bb',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.user.edit_view_form',
    },
    {
      codeName: 'info_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'info_edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.USER',
      },
      caption: '个人信息编辑',
      codeName: 'info_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {},
      name: 'captionbar',
      id: 'info_edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.user',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '个人信息编辑',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '80f61c22d6c92fa59c0b93f46c16b853',
  modelType: 'PSAPPDEVIEW',
  name: 'userinfo_edit_view',
  id: 'crmweb.user_info_edit_view',
};
