export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_relation',
  deviewId: '020eb53d80fc43153508774b2f789c7c',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.USER',
  },
  caption: '关联销售人员',
  codeName: 'user_grid_view_relation',
  appDataEntityId: 'crmweb.user',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.user_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.user_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.user_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.user_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '用户数据重定向视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.USER.REDIRECTVIEW',
      },
      refAppViewId: 'crmweb.user_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '用户编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.USER.EDITVIEW',
      },
      refAppViewId: 'crmweb.user_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'add_account_reluser@user',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '添加关联销售',
          itemType: 'DEUIACTION',
          tooltip: '添加关联销售',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'unlink@user',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          caption: '取消关联',
          itemType: 'DEUIACTION',
          tooltip: '取消关联',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_relation_toolbar',
      controlType: 'TOOLBAR',
      logicName: '关联销售_工具栏',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'dca33af7def3cb34850e82add9142ba8',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_relation_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'first_name',
          excelCaption: '姓名',
          appDEFieldId: 'first_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '姓名',
          codeName: 'first_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'first_name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'phone',
          excelCaption: '电话',
          appDEFieldId: 'phone',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '电话',
          codeName: 'phone',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'phone',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'mobile',
          excelCaption: '手机',
          appDEFieldId: 'mobile',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '手机',
          codeName: 'mobile',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'mobile',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'status',
          excelCaption: '状态',
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '状态',
          codeName: 'status',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'status',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'first_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'first_name',
        },
        {
          appDEFieldId: 'phone',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'phone',
        },
        {
          appDEFieldId: 'mobile',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'mobile',
        },
        {
          appDEFieldId: 'status',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'status',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'first_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_account_reluser',
        appDataEntityId: 'crmweb.user',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.user',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_relation_grid',
      controlType: 'GRID',
      logicName: '关联销售_表格',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        ctrlParams: {
          SHOWMODE: 'MIXIN',
        },
        id: 'grid',
      },
      modelId: '9159e6ebba6d3bafb6af503a80c4ef27',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.user.grid_view_relation_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_relation_search_form',
      controlType: 'SEARCHFORM',
      logicName: '关联销售_搜索表单',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'c2edae0fa7fed6a185ab662168f4a834',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.user.grid_view_relation_search_form',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.USER',
      },
      caption: '关联销售人员',
      codeName: 'grid_view_relation_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_relation_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.user',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '关联销售人员',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '4f33f94087bd77c255a3b2c53501a2e0',
  modelType: 'PSAPPDEVIEW',
  name: 'usergrid_view_relation',
  id: 'crmweb.user_grid_view_relation',
};
