export default {
  sideBarLayout: 'LEFT',
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'list_exp_view',
  deviewId: '771bb847e117ce0b0167fc22322eb73c',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.USER',
  },
  caption: '用户管理',
  codeName: 'user_list_exp_view',
  appDataEntityId: 'crmweb.user',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      title: '用户',
      xdataControlName: 'listexpbar_list',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '个人详情信息',
          refAppViewId: 'crmweb.user_info_view',
          name: 'EXPITEM:DEFAULT',
          id: 'expitem:default',
        },
      ],
      controls: [
        {
          groupMode: 'NONE',
          groupStyle: 'DEFAULT',
          itemLayoutPanel: {
            layoutMode: 'TABLE_24COL',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            fieldStates: 1,
                            editor: {
                              maxFileCount: 1,
                              editorParams: {
                                MAXCOUNT: '1',
                                READONLY: 'TRUE',
                              },
                              editorType: 'PICTURE_ONE',
                              predefinedType: 'FIELD_IMAGE',
                              valueType: 'SIMPLE',
                              editable: true,
                              readOnly: true,
                              id: 'image_link',
                            },
                            viewFieldName: 'IMAGE_LINK',
                            allowEmpty: true,
                            caption: '图片(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'image_link',
                          },
                        ],
                        layout: {
                          align: 'center',
                          dir: 'column',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container1',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'first_name',
                            },
                            viewFieldName: 'FIRST_NAME',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'first_name',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'role',
                            },
                            viewFieldName: 'ROLE',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'role',
                          },
                          {
                            editor: {
                              halign: 'LEFT',
                              renderMode: 'TEXT_DYNAMIC',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              editorType: 'SPAN',
                              predefinedType: 'FIELD_TEXT_DYNAMIC',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'email',
                            },
                            viewFieldName: 'EMAIL',
                            allowEmpty: true,
                            caption: '文本(动态)',
                            itemStyle: 'DEFAULT',
                            itemType: 'FIELD',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            id: 'email',
                          },
                        ],
                        layout: {
                          align: 'center',
                          dir: 'column',
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container2',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'page_container',
              },
            ],
            codeName: 'usr0506869406',
            controlType: 'PANEL',
            logicName: 'List_列表项面板',
            appDataEntityId: 'crmweb.user',
            controlParam: {},
            modelId: '8aa28bfbede28bead5a52bb7f152ed5e',
            modelType: 'PSSYSVIEWPANEL',
            name: 'listexpbar_list_itempanel',
            id: 'crmweb.user.usr0506869406',
          },
          delistDataItems: [
            {
              appDEFieldId: 'image_link',
              dataType: 25,
              id: 'image_link',
            },
            {
              appDEFieldId: 'first_name',
              dataType: 25,
              id: 'first_name',
            },
            {
              appDEFieldId: 'role',
              dataType: 25,
              id: 'role',
            },
            {
              appDEFieldId: 'id',
              dataType: 25,
              id: 'id',
            },
            {
              appDEFieldId: 'email',
              dataType: 25,
              id: 'email',
            },
            {
              appDEFieldId: 'id',
              dataType: 25,
              id: 'srfkey',
            },
            {
              appDEFieldId: 'first_name',
              dataType: 25,
              id: 'srfmajortext',
            },
          ],
          pagingSize: 1000,
          showHeader: true,
          navAppViewId: 'crmweb.user_info_view',
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'crmweb.user',
            id: 'create',
          },
          fetchControlAction: {
            appDEMethodId: 'fetch_default',
            appDataEntityId: 'crmweb.user',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'crmweb.user',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'crmweb.user',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'crmweb.user',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'list_exp_view_list',
          controlType: 'LIST',
          logicName: 'List',
          appDataEntityId: 'crmweb.user',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'listexpbar_list',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'listexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'listexpbar_list',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'listexpbar_load',
            },
          ],
          controlParam: {
            id: 'listexpbar_list',
          },
          modelId: '8af1b69a46a3fe393606845214328e3c',
          modelType: 'PSDELIST',
          name: 'listexpbar_list',
          id: 'crmweb.user.list_exp_view_list',
        },
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'new_user@user',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '新建',
              itemType: 'DEUIACTION',
              tooltip: '新建',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'change_password',
              uiactionTarget: 'NONE',
              hiddenItem: true,
              valid: true,
              caption: '修改密码',
              itemType: 'DEUIACTION',
              tooltip: '修改密码',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction2',
            },
          ],
          codeName: 'list_exp_view_listexpbar_toolbar',
          controlType: 'TOOLBAR',
          logicName: '用户管理_工具栏',
          appDataEntityId: 'crmweb.user',
          controlParam: {
            id: 'listexpbar_toolbar',
          },
          modelId: 'b1b30d58d1241bbcf1212c530388563b',
          modelType: 'PSDETOOLBAR',
          name: 'listexpbar_toolbar',
          id: 'list_exp_view_listexpbar_toolbar',
        },
      ],
      codeName: 'list_exp_view_listexpbar',
      controlType: 'LISTEXPBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'listexpbar',
      },
      modelId: '74ec017db0acf6d5de245fa8165cf726_listexpbar',
      modelType: 'PSEXPBAR',
      name: 'listexpbar',
      id: 'list_exp_view_listexpbar',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem5',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_editaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.EDIT',
          },
          caption: '编辑',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-edit',
            glyph: 'xf044@FontAwesome',
          },
          tooltip: '编辑',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.EDIT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem2',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_copyaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.COPY',
          },
          caption: '拷贝',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-copy',
            glyph: 'xf0c5@FontAwesome',
          },
          tooltip: '拷贝',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.COPY',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem15',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_removeaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.REMOVE',
          },
          caption: '删除',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.REMOVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem8',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem16',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'gridview_exportxmlaction',
              valid: true,
              capLanguageRes: {
                lanResTag: 'MENUITEM.CAPTION.*.EXPORTSRF',
              },
              caption: '导出数据模型',
              itemType: 'DEUIACTION',
              sysImage: {
                cssClass: 'fa fa-download',
                glyph: 'xf019@FontAwesome',
              },
              tooltip: '导出数据模型',
              showCaption: true,
              showIcon: true,
              id: 'tbitem24',
            },
          ],
          valid: true,
          caption: '其它',
          itemType: 'ITEMS',
          tooltip: '其它',
          showCaption: true,
          showIcon: true,
          id: 'tbitem20',
        },
        {
          itemType: 'SEPERATOR',
          id: 'tbitem21',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_helpaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.HELP',
          },
          caption: '帮助',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-question',
            glyph: 'xf128@FontAwesome',
          },
          tooltip: '帮助',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.HELP',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem4',
        },
      ],
      xdataControlName: 'LISTEXPBAR',
      codeName: 'list_exp_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认表格界面）',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'ec6fbb681f5e3e6783c2af57e5eefaaa',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'list_exp_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.USER',
      },
      caption: '用户管理',
      codeName: 'list_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {},
      name: 'captionbar',
      id: 'list_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.user',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '用户管理',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '74ec017db0acf6d5de245fa8165cf726',
  modelType: 'PSAPPDEVIEW',
  name: 'userlist_exp_view',
  id: 'crmweb.user_list_exp_view',
};
