export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'setting_view',
  deviewId: '0263af161528a95bfc5a8bae544f013b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.USER',
  },
  caption: '个人信息设置',
  codeName: 'user_setting_view',
  appDataEntityId: 'crmweb.user',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView2',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      key: 'USER',
      value: 'userid',
      name: 'USER',
      id: 'user',
    },
  ],
  appViewNavParams: [
    {
      key: 'user',
      value: 'userid',
      id: 'user',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'crmweb.user',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'crmweb.user',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'crmweb.user',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'crmweb.user',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.user',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'crmweb.user',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
              ],
              caption: '用户基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'create_man',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'crmweb.crm__sysoperator',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'create_man',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.CREATE_MAN',
                  },
                  caption: '建立人',
                  codeName: 'create_man',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'create_man',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'create_time',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'create_time',
                  },
                  valueFormat: 'YYYY-MM-DD HH:mm:ss',
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.CREATE_TIME',
                  },
                  caption: '建立时间',
                  codeName: 'create_time',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'create_time',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'update_man',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    appCodeListId: 'crmweb.crm__sysoperator',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'update_man',
                  },
                  allowEmpty: true,
                  convertToCodeItemText: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.UPDATE_MAN',
                  },
                  caption: '更新人',
                  codeName: 'update_man',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'update_man',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  ignoreInput: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'update_time',
                  editor: {
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    editorType: 'SPAN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'update_time',
                  },
                  valueFormat: 'YYYY-MM-DD HH:mm:ss',
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.UPDATE_TIME',
                  },
                  caption: '更新时间',
                  codeName: 'update_time',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'update_time',
                },
              ],
              caption: '操作信息',
              codeName: 'group2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group2',
            },
          ],
          caption: '其它',
          codeName: 'formpage2',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage2',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'setting_view_form',
      controlType: 'FORM',
      logicName: '个人信息设置_表单',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'form',
      },
      modelId: 'd1ae595e0884498218aa9d883be6b711',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'crmweb.user.setting_view_form',
    },
    {
      dedrbarGroups: [
        {
          caption: '详细信息',
          name: '详细信息',
          id: 'drgroup',
        },
      ],
      title: '设置',
      showTitle: true,
      dataRelationTag: 'setting_view_DR',
      editItemCapLanguageRes: {
        lanResTag: 'DE.LNAME.USER',
      },
      editItemCaption: '用户',
      dedrctrlItems: [
        {
          dedrbarGroupId: 'drgroup',
          caption: '基本信息',
          appViewId: 'crmweb.user_info_edit_view',
          id: 'info',
        },
        {
          dedrbarGroupId: 'drgroup',
          caption: '密码修改',
          appViewId: 'crmweb.user_password_edit_view',
          id: 'password',
        },
      ],
      uniqueTag: 'user_setting_view__drbar',
      hideEditItem: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'setting_view_dr',
      controlType: 'DRBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'drbar',
      },
      modelId: 'faf179e01c9fd1af46ae40138c926f16',
      modelType: 'PSDEDRBAR',
      name: 'drbar',
      id: 'setting_view_dr',
    },
    {
      codeName: 'setting_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'setting_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.USER',
      },
      caption: '个人信息设置',
      codeName: 'setting_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.user',
      controlParam: {},
      name: 'captionbar',
      id: 'setting_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW2',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.user',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '个人信息设置',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW2',
  enableDP: true,
  showCaptionBar: true,
  modelId: '539ceab118f3ba1bc235fd872c6af284',
  modelType: 'PSAPPDEVIEW',
  name: 'usersetting_view',
  id: 'crmweb.user_setting_view',
};
