export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_multimode',
  deviewId: 'd9a93829ddb335b3c2b38f62a88dfd75',
  accUserMode: 2,
  caption: '供应商',
  codeName: 'vendor_grid_view_multimode',
  appDataEntityId: 'crmweb.vendor',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.vendor_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.vendor_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.vendor_main_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.vendor_main_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '供应商信息',
      refAppViewId: 'crmweb.vendor_main_view',
      name: 'OPENDATA',
      id: 'opendata',
    },
    {
      realTitle: '供应商信息',
      refAppViewId: 'crmweb.vendor_main_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '供应商编辑视图',
      refAppViewId: 'crmweb.vendor_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.NEW',
          },
          caption: '创建供应商',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '创建供应商',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.NEW',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'importdata@vendor',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入供应商',
              itemType: 'DEUIACTION',
              tooltip: '导入供应商',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_importdata',
            },
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'import@note_attach',
              uiactionTarget: 'NONE',
              valid: true,
              caption: '导入备注',
              itemType: 'DEUIACTION',
              tooltip: '导入备注',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction5_import',
            },
          ],
          valid: true,
          itemType: 'ITEMS',
          sysCss: {
            cssName: 'toolbar_group',
          },
          sysImage: {
            cssClass: 'fa fa-chevron-down',
            glyph: 'xf078@FontAwesome',
          },
          showIcon: true,
          id: 'items2',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_multimode_toolbar',
      controlType: 'TOOLBAR',
      logicName: '供应商多模式表格视图_工具栏',
      appDataEntityId: 'crmweb.vendor',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '86e3f0b333545474f5ab73bf1098e027',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_multimode_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'crmweb.vendor',
        id: 'fetch',
      },
      dedataImportId: 'dataimport',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.vendor',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detoolbarItems: [
            {
              actionLevel: 100,
              noPrivDisplayMode: 2,
              uiactionId: 'create_task@vendor',
              uiactionTarget: 'MULTIKEY',
              valid: true,
              caption: '创建任务',
              itemType: 'DEUIACTION',
              tooltip: '创建任务',
              showCaption: true,
              showIcon: true,
              id: 'deuiaction1',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'add_tags@vendor',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '添加标签',
                  itemType: 'DEUIACTION',
                  tooltip: '添加标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction2',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'delete_tags@vendor',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '移除标签',
                  itemType: 'DEUIACTION',
                  tooltip: '移除标签',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction3',
                },
              ],
              valid: true,
              caption: '标签',
              itemType: 'ITEMS',
              tooltip: '标签',
              showCaption: true,
              showIcon: true,
              id: 'items1',
            },
            {
              actionLevel: 100,
              detoolbarItems: [
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'batch_update@vendor',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '批量更新',
                  itemType: 'DEUIACTION',
                  tooltip: '批量更新',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction4',
                },
                {
                  actionLevel: 100,
                  noPrivDisplayMode: 2,
                  uiactionId: 'remove@vendor',
                  uiactionTarget: 'MULTIKEY',
                  valid: true,
                  caption: '删除',
                  itemType: 'DEUIACTION',
                  tooltip: '删除',
                  showCaption: true,
                  showIcon: true,
                  id: 'deuiaction5',
                },
              ],
              valid: true,
              caption: '操作',
              itemType: 'ITEMS',
              tooltip: '操作',
              showCaption: true,
              showIcon: true,
              id: 'items2',
            },
          ],
          codeName: 'grid_view_multimode_grid_batchtoolbar',
          controlType: 'TOOLBAR',
          logicName: '批操作_工具栏',
          appDataEntityId: 'crmweb.vendor',
          controlParam: {
            id: 'grid_batchtoolbar',
          },
          modelId: '1442ea76b6cd47d148b6ede657ff719e',
          modelType: 'PSDETOOLBAR',
          name: 'grid_batchtoolbar',
          id: 'grid_view_multimode_grid_batchtoolbar',
        },
      ],
      codeName: 'grid_view_multimode_grid',
      controlType: 'GRID',
      logicName: '供应商多模式表格视图_表格',
      appDataEntityId: 'crmweb.vendor',
      controlParam: {
        id: 'grid',
      },
      modelId: '29f7390808ee2d857f3c2192ae5bd635',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.vendor.grid_view_multimode_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'grid_view_multimode_search_form',
      controlType: 'SEARCHFORM',
      logicName: '供应商多模式表格视图_搜索表单',
      appDataEntityId: 'crmweb.vendor',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'fe8e906e6a7aa5612b12baa480990cd9',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.vendor.grid_view_multimode_search_form',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.vendor',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '供应商',
      codeName: 'grid_view_multimode_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.vendor',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_multimode_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.vendor',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '供应商',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '65649d153194db232a37798fdf820fd4',
  modelType: 'PSAPPDEVIEW',
  name: 'vendorgrid_view_multimode',
  id: 'crmweb.vendor_grid_view_multimode',
};
