export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'quick_create_view',
  deviewId: '41414baaac07dbf0326e7429670b3d1d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WEEKLIES',
  },
  caption: '新建周报',
  codeName: 'weeklies_quick_create_view',
  height: 320,
  appDataEntityId: 'crmweb.weeklies',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionType: 'UIACTION',
            buttonStyle: 'PRIMARY',
            buttonType: 'PANELBUTTON',
            uiactionId: 'close_cur_view@weeklies',
            renderMode: 'BUTTON',
            tooltip: '确定',
            uiactionTarget: 'SINGLEDATA',
            caption: '确定',
            itemStyle: 'PRIMARY',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'button_okaction',
          },
          {
            actionType: 'UIACTION',
            buttonStyle: 'INFO',
            buttonType: 'PANELBUTTON',
            uiactionId: 'view_cancelaction',
            renderMode: 'BUTTON',
            tooltip: '取消',
            caption: '取消',
            itemStyle: 'INFO',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'button_cancelaction',
          },
        ],
        layout: {
          dir: 'row-reverse',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_footer',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'OptionView',
        id: 'engine',
      },
    ],
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'nothing',
          appDataEntityId: 'crmweb.weeklies',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'crmweb.weeklies',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'crmweb.weeklies',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'crmweb.weeklies',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'crmweb.weeklies',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'crmweb.weeklies',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    createDV: 'userid',
                    createDVT: 'SESSION',
                    dataType: 25,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'owner',
                    editor: {
                      singleSelect: true,
                      appCodeListId: 'crmweb.crm__owner',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'owner',
                    },
                    needCodeListConfig: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.OWNER',
                    },
                    caption: '所有者',
                    codeName: 'owner',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'owner',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    itemWidth: 131,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      editorParams: {
                        TIMEFMT: 'YYYY-MM-DD',
                      },
                      editorType: 'DATERANGE_NOTIME',
                      editorWidth: 1,
                      editorItems: [
                        {
                          id: 'start_date',
                        },
                        {
                          id: 'end_date',
                        },
                      ],
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'date_scope',
                    },
                    caption: '统计范围',
                    codeName: 'date_scope',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'date_scope',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'start_date',
                    editor: {
                      editorParams: {
                        format: 'YYYY-MM-DD',
                      },
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'start_date',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    hidden: true,
                    caption: '开始时间',
                    codeName: 'start_date',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'start_date',
                  },
                  {
                    dataType: 5,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'end_date',
                    editor: {
                      editorParams: {
                        format: 'YYYY-MM-DD',
                      },
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'end_date',
                    },
                    valueFormat: 'YYYY-MM-DD',
                    hidden: true,
                    caption: '结束时间',
                    codeName: 'end_date',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'end_date',
                  },
                ],
                caption: '周报基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'quick_create_form',
        controlType: 'FORM',
        logicName: '新建周报_表单',
        appDataEntityId: 'crmweb.weeklies',
        controlLogics: [
          {
            eventNames: 'onChange',
            itemName: 'date_scope',
            logicTag: 'form',
            logicType: 'SCRIPT',
            scriptCode:
              "var start_date = ctrl.details.start_date.value;\r\nvar end_date = ctrl.details.end_date.value;\r\nctrl.details.name.setDataValue(context.srfusername + start_date + '至' + end_date + '周报');\r\n",
            triggerType: 'CTRLEVENT',
            id: 'date_onchange',
          },
        ],
        controlParam: {
          id: 'form',
        },
        modelId: '9225d9a3b99387beaf8be7f3c880eabb',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'crmweb.weeklies.quick_create_form',
      },
      {
        codeName: 'quick_create_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'crmweb.weeklies',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'quick_create_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WEEKLIES',
        },
        caption: '新建周报',
        codeName: 'quick_create_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'crmweb.weeklies',
        controlParam: {},
        name: 'captionbar',
        id: 'quick_create_view_captionbar',
      },
    ],
    codeName: 'usr0718904488',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'quick_create_view选项操作视图布局面',
    appDataEntityId: 'crmweb.weeklies',
    controlParam: {},
    modelId: '56d7f571af19e0f17f8ed52f38199fce',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0718904488',
  },
  title: '新建周报',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 600,
  enableDP: true,
  showCaptionBar: true,
  modelId: '21b786322b69d71eff8cff4904ef2f1e',
  modelType: 'PSAPPDEVIEW',
  name: 'weekliesquick_create_view',
  id: 'crmweb.weeklies_quick_create_view',
};
