export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: '9dfa96c9a7f610f571613ce321012f70',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WEEKLIES',
  },
  caption: '周报',
  codeName: 'weeklies_grid_view',
  appDataEntityId: 'crmweb.weeklies',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'crmweb.weeklies_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.weeklies_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'crmweb.weeklies_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'crmweb.weeklies_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '周报编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.WEEKLIES.EDITVIEW',
      },
      refAppViewId: 'crmweb.weeklies_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '周报编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.WEEKLIES.EDITVIEW',
      },
      refAppViewId: 'crmweb.weeklies_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      minorSortDir: 'DESC',
      minorSortAppDEFieldId: 'start_date',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 350,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'start_date',
          excelCaption: '开始时间',
          appDEFieldId: 'start_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '开始时间',
          codeName: 'start_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'start_date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'end_date',
          excelCaption: '结束时间',
          appDEFieldId: 'end_date',
          valueFormat: 'YYYY-MM-DD',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '结束时间',
          codeName: 'end_date',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'end_date',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'start_date_sort',
          excelCaption: '开始时间',
          appDEFieldId: 'start_date_sort',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '开始时间',
          codeName: 'start_date_sort',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'start_date_sort',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'statistical_period',
          excelCaption: '统计期间',
          appCodeListId: 'crmweb.crm__weeklies_period',
          appDEFieldId: 'statistical_period',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '统计期间',
          codeName: 'statistical_period',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'statistical_period',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'id',
          excelCaption: '标识',
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          codeName: 'id',
          columnType: 'DEFGRIDCOLUMN',
          hideMode: 1,
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          hideDefault: true,
          id: 'id',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'start_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'start_date',
        },
        {
          format: 'YYYY-MM-DD',
          appDEFieldId: 'end_date',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'end_date',
        },
        {
          appDEFieldId: 'start_date_sort',
          valueType: 'SIMPLE',
          dataType: 9,
          id: 'start_date_sort',
        },
        {
          appDEFieldId: 'statistical_period',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'statistical_period',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_all',
        appDataEntityId: 'crmweb.weeklies',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'crmweb.weeklies',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlStyle: 'NUMBER_GRID',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'crmweb.weeklies',
      controlParam: {
        id: 'grid',
      },
      sysPFPluginId: 'number_grid',
      modelId: 'a276143524e32709f789ea3b17d75354',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'crmweb.weeklies.main',
    },
    {
      searchButtonStyle: 'NONE',
      enableAutoSearch: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'owner',
              editor: {
                singleSelect: true,
                appCodeListId: 'crmweb.crm__owner',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_owner_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '销售人员',
              codeName: 'n_owner_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 8,
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'n_owner_eq',
            },
          ],
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.WEEKLIES.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'crmweb.weeklies',
      controlParam: {
        id: 'searchform',
      },
      modelId: '46d5154b0f912c9959cc9839ccb7ab7f',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'crmweb.weeklies.default',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'new@weeklies',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '新建周报',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-file-text-o',
            glyph: 'xf0f6@FontAwesome',
          },
          tooltip: '新建周报',
          showCaption: true,
          showIcon: true,
          id: 'tbitem5',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_printaction',
          uiactionTarget: 'SINGLEKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.PRINT',
          },
          caption: '打印',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-print',
            glyph: 'xf02f@FontAwesome',
          },
          tooltip: '打印',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.PRINT',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem8',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_removeaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.REMOVE',
          },
          caption: '删除',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.REMOVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem9',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '周报表格工具栏',
      appDataEntityId: 'crmweb.weeklies',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '4b408afcbe942361dabc95290f59f62e',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'crmweb.weeklies',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.WEEKLIES',
      },
      caption: '周报',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'crmweb.weeklies',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'crmweb.weeklies',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '周报表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.WEEKLIES.GRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '5e8a206f01bc5c8c9eb0e679936d56ca',
  modelType: 'PSAPPDEVIEW',
  name: 'weekliesGridView',
  id: 'crmweb.weeklies_grid_view',
};
