export default {
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'DataImport',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '所属数据标识',
          appDEFieldId: 'owner_id',
          name: 'OWNER_ID',
          id: 'owner_id',
        },
        {
          caption: '所属数据对象',
          appDEFieldId: 'owner_type',
          name: 'OWNER_TYPE',
          id: 'owner_type',
        },
        {
          caption: '所属对象子类型',
          appDEFieldId: 'owner_subtype',
          name: 'OWNER_SUBTYPE',
          id: 'owner_subtype',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          appDEFieldId: 'update_time',
          name: 'UPDATE_TIME',
          id: 'update_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'create_man',
          name: 'CREATE_MAN',
          id: 'create_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          appDEFieldId: 'create_time',
          name: 'CREATE_TIME',
          id: 'create_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          appDEFieldId: 'name',
          name: 'NAME',
          id: 'name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'update_man',
          name: 'UPDATE_MAN',
          id: 'update_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          appDEFieldId: 'id',
          name: 'ID',
          id: 'id',
        },
        {
          caption: '通话类型',
          appDEFieldId: 'call_type',
          name: 'CALL_TYPE',
          id: 'call_type',
        },
        {
          caption: '去电通话状态',
          codeListId: 'crmweb.crm__outgoing_call_status',
          appDEFieldId: 'outgoing_call_status',
          name: 'OUTGOING_CALL_STATUS',
          id: 'outgoing_call_status',
        },
        {
          caption: '描述',
          appDEFieldId: 'description',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          caption: '通话结果',
          appDEFieldId: 'call_result',
          name: 'CALL_RESULT',
          id: 'call_result',
        },
        {
          caption: '通话议程',
          appDEFieldId: 'call_agenda',
          name: 'CALL_AGENDA',
          id: 'call_agenda',
        },
        {
          caption: '通话开始时间',
          appDEFieldId: 'call_start_time',
          name: 'CALL_START_TIME',
          id: 'call_start_time',
        },
        {
          caption: '通话目的',
          appDEFieldId: 'call_purpose',
          name: 'CALL_PURPOSE',
          id: 'call_purpose',
        },
        {
          caption: '呼叫者ID',
          appDEFieldId: 'caller_id',
          name: 'CALLER_ID',
          id: 'caller_id',
        },
        {
          caption: '语音录音',
          appDEFieldId: 'voice_recording_s',
          name: 'VOICE_RECORDING__S',
          id: 'voice_recording__s',
        },
        {
          caption: '主题',
          appDEFieldId: 'subject',
          name: 'SUBJECT',
          id: 'subject',
        },
        {
          caption: '通话持续时间',
          appDEFieldId: 'call_duration',
          name: 'CALL_DURATION',
          id: 'call_duration',
        },
        {
          caption: '拨打的号码',
          appDEFieldId: 'dialled_number',
          name: 'DIALLED_NUMBER',
          id: 'dialled_number',
        },
        {
          caption: '提醒',
          appDEFieldId: 'reminder',
          name: 'REMINDER',
          id: 'reminder',
        },
        {
          caption: '通话持续时间(秒)',
          appDEFieldId: 'call_duration_in_seconds',
          name: 'CALL_DURATION_IN_SECONDS',
          id: 'call_duration_in_seconds',
        },
        {
          caption: '在CRM中已预定',
          appDEFieldId: 'scheduled_in_crm',
          name: 'SCHEDULED_IN_CRM',
          id: 'scheduled_in_crm',
        },
        {
          caption: 'CTI条目',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'cti_entry',
          name: 'CTI_ENTRY',
          id: 'cti_entry',
        },
        {
          caption: '标签',
          appDEFieldId: 'tag',
          name: 'TAG',
          id: 'tag',
        },
        {
          caption: '附件',
          appDEFieldId: 'attachments',
          name: 'ATTACHMENTS',
          id: 'attachments',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '导入通话',
      id: 'dataimport',
    },
  ],
  appDEFields: [
    {
      codeName: 'owner_id',
      logicName: '所属数据标识',
      predefinedType: 'PARENTID',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      codeName: 'owner_type',
      logicName: '所属数据对象',
      predefinedType: 'PARENTTYPE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      codeName: 'owner_subtype',
      logicName: '所属对象子类型',
      predefinedType: 'PARENTSUBTYPE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_SUBTYPE',
      id: 'owner_subtype',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'call_type',
      logicName: '通话类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CALL_TYPE',
      id: 'call_type',
    },
    {
      codeName: 'outgoing_call_status',
      logicName: '去电通话状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'OUTGOING_CALL_STATUS',
      id: 'outgoing_call_status',
    },
    {
      codeName: 'description',
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'call_result',
      logicName: '通话结果',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CALL_RESULT',
      id: 'call_result',
    },
    {
      codeName: 'call_agenda',
      logicName: '通话议程',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'CALL_AGENDA',
      id: 'call_agenda',
    },
    {
      codeName: 'call_start_time',
      logicName: '通话开始时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CALL_START_TIME',
      id: 'call_start_time',
    },
    {
      codeName: 'call_purpose',
      logicName: '通话目的',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CALL_PURPOSE',
      id: 'call_purpose',
    },
    {
      codeName: 'caller_id',
      logicName: '呼叫者ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'CALLER_ID',
      id: 'caller_id',
    },
    {
      codeName: 'voice_recording_s',
      logicName: '语音录音',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'VOICE_RECORDING__S',
      id: 'voice_recording_s',
    },
    {
      codeName: 'subject',
      logicName: '主题',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'SUBJECT',
      id: 'subject',
    },
    {
      codeName: 'call_duration',
      logicName: '通话持续时间',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'CALL_DURATION',
      id: 'call_duration',
    },
    {
      codeName: 'dialled_number',
      logicName: '拨打的号码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'DIALLED_NUMBER',
      id: 'dialled_number',
    },
    {
      codeName: 'reminder',
      logicName: '提醒',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'REMINDER',
      id: 'reminder',
    },
    {
      codeName: 'call_duration_in_seconds',
      logicName: '通话持续时间(秒)',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CALL_DURATION_IN_SECONDS',
      id: 'call_duration_in_seconds',
    },
    {
      codeName: 'scheduled_in_crm',
      logicName: '在CRM中已预定',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SCHEDULED_IN_CRM',
      id: 'scheduled_in_crm',
    },
    {
      codeName: 'cti_entry',
      logicName: 'CTI条目',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CTI_ENTRY',
      id: 'cti_entry',
    },
    {
      codeName: 'tag',
      logicName: '标签',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'TAG',
      id: 'tag',
    },
    {
      codeName: 'attachments',
      logicName: '附件',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'call_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'owner_id',
          logicName: '所属数据标识',
          appDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_id',
        },
        {
          codeName: 'owner_type',
          logicName: '所属数据对象',
          appDEFieldId: 'owner_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_type',
        },
        {
          codeName: 'owner_subtype',
          logicName: '所属对象子类型',
          appDEFieldId: 'owner_subtype',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_subtype',
        },
        {
          codeName: 'attachments',
          logicName: '附件',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'attachment_dto',
          refAppDataEntityId: 'crmweb.attachment',
          refPickupAppDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'call_agenda',
          logicName: '通话议程',
          appDEFieldId: 'call_agenda',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'call_agenda',
        },
        {
          codeName: 'call_duration',
          logicName: '通话持续时间',
          appDEFieldId: 'call_duration',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'call_duration',
        },
        {
          codeName: 'call_duration_in_seconds',
          logicName: '通话持续时间(秒)',
          appDEFieldId: 'call_duration_in_seconds',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'call_duration_in_seconds',
        },
        {
          codeName: 'call_purpose',
          logicName: '通话目的',
          appDEFieldId: 'call_purpose',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'call_purpose',
        },
        {
          codeName: 'call_result',
          logicName: '通话结果',
          appDEFieldId: 'call_result',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'call_result',
        },
        {
          codeName: 'call_start_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '通话开始时间',
          appDEFieldId: 'call_start_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'call_start_time',
        },
        {
          codeName: 'call_type',
          logicName: '通话类型',
          appDEFieldId: 'call_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'call_type',
        },
        {
          codeName: 'caller_id',
          logicName: '呼叫者ID',
          appDEFieldId: 'caller_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'caller_id',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'cti_entry',
          logicName: 'CTI条目',
          appDEFieldId: 'cti_entry',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'cti_entry',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'dialled_number',
          logicName: '拨打的号码',
          appDEFieldId: 'dialled_number',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'dialled_number',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'outgoing_call_status',
          logicName: '去电通话状态',
          appDEFieldId: 'outgoing_call_status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'outgoing_call_status',
        },
        {
          codeName: 'reminder',
          logicName: '提醒',
          appDEFieldId: 'reminder',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'reminder',
        },
        {
          codeName: 'scheduled_in_crm',
          logicName: '在CRM中已预定',
          appDEFieldId: 'scheduled_in_crm',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'scheduled_in_crm',
        },
        {
          codeName: 'subject',
          logicName: '主题',
          appDEFieldId: 'subject',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'subject',
        },
        {
          codeName: 'tag',
          logicName: '标签',
          appDEFieldId: 'tag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'tag',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
        {
          codeName: 'voice_recording_s',
          logicName: '语音录音',
          appDEFieldId: 'voice_recording_s',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'voice_recording_s',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'call_dto',
    },
    {
      codeName: 'call_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_call_duration_eq',
          logicName: '通话持续时间',
          appDEFieldId: 'call_duration',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_call_duration_eq',
        },
        {
          codeName: 'n_call_purpose_eq',
          logicName: '通话目的',
          appDEFieldId: 'call_purpose',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_call_purpose_eq',
        },
        {
          codeName: 'n_call_result_eq',
          logicName: '通话结果',
          appDEFieldId: 'call_result',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_call_result_eq',
        },
        {
          codeName: 'n_call_type_eq',
          logicName: '通话类型',
          appDEFieldId: 'call_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_call_type_eq',
        },
        {
          codeName: 'n_caller_id_eq',
          logicName: '呼叫者ID',
          appDEFieldId: 'caller_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_caller_id_eq',
        },
        {
          codeName: 'n_dialled_number_eq',
          logicName: '拨打的号码',
          appDEFieldId: 'dialled_number',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_dialled_number_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_outgoing_call_status_eq',
          logicName: '去电通话状态',
          appDEFieldId: 'outgoing_call_status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_outgoing_call_status_eq',
        },
        {
          codeName: 'n_owner_id_eq',
          logicName: '所属数据标识',
          appDEFieldId: 'owner_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_owner_id_eq',
        },
        {
          codeName: 'n_reminder_eq',
          logicName: '提醒',
          appDEFieldId: 'reminder',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_reminder_eq',
        },
        {
          codeName: 'n_scheduled_in_crm_eq',
          logicName: '在CRM中已预定',
          appDEFieldId: 'scheduled_in_crm',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_scheduled_in_crm_eq',
        },
        {
          codeName: 'n_subject_eq',
          logicName: '主题',
          appDEFieldId: 'subject',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_subject_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'call_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_tags',
    },
    {
      codeName: 'batch_update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/batch_update',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'batch_update',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_task',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_task',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_task',
    },
    {
      codeName: 'delete_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete_tags',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'main_view_dr_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/main_view_dr_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'main_view_dr_count',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_close',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_close',
      actionType: 'REMOTE',
      dataSetName: 'close',
      dataSetTag: 'close',
      dataSetType: 'REMOTE',
      id: 'fetch_close',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_not_close',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'call_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'call_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_not_close',
      actionType: 'REMOTE',
      dataSetName: 'not_close',
      dataSetTag: 'not_close',
      dataSetType: 'REMOTE',
      id: 'fetch_not_close',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '预约通话',
      codeName: 'book',
      frontAppViewId: 'crmweb.call_simple_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'call_book',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'book',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.call',
      name: '（通用）预约通话',
      id: 'book@call',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '记录通话',
      codeName: 'record',
      frontAppViewId: 'crmweb.call_simple_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'call_record',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'record',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.call',
      name: '（通用）记录通话',
      id: 'record@call',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'call',
  deapicodeName: 'call',
  deapicodeName2: 'calls',
  deapitag: 'CALL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'dataimport',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '通话',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'CALL',
  id: 'crmweb.call',
  codeName2: 'calls',
  requestPaths: [],
};
