export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'full_name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'crmweb.contact',
      textAppDEFieldId: 'full_name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'DataImport',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '客户名称',
          appDEFieldId: 'account_name',
          name: 'ACCOUNT_NAME',
          id: 'account_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          appDEFieldId: 'update_time',
          name: 'UPDATE_TIME',
          id: 'update_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'create_man',
          name: 'CREATE_MAN',
          id: 'create_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          appDEFieldId: 'name',
          name: 'NAME',
          id: 'name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          appDEFieldId: 'create_time',
          name: 'CREATE_TIME',
          id: 'create_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'update_man',
          name: 'UPDATE_MAN',
          id: 'update_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DESCRIPTION',
          },
          caption: '描述',
          appDEFieldId: 'description',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RECORD_IMAGE',
          },
          caption: '联系人图片',
          appDEFieldId: 'record_image',
          name: 'RECORD_IMAGE',
          id: 'record_image',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAILING_STREET',
          },
          caption: '邮寄地址-街道',
          appDEFieldId: 'mailing_street',
          name: 'MAILING_STREET',
          id: 'mailing_street',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.OTHER_STREET',
          },
          caption: '其它街道',
          appDEFieldId: 'other_street',
          name: 'OTHER_STREET',
          id: 'other_street',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.FULL_NAME',
          },
          caption: '全名',
          appDEFieldId: 'full_name',
          name: 'FULL_NAME',
          id: 'full_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.FIRST_NAME',
          },
          caption: '名字',
          appDEFieldId: 'first_name',
          name: 'FIRST_NAME',
          id: 'first_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.OTHER_CITY',
          },
          caption: '其它城市',
          appDEFieldId: 'other_city',
          name: 'OTHER_CITY',
          id: 'other_city',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LEAD_SOURCE',
          },
          caption: '线索来源',
          codeListId: 'crmweb.crm__lead_source',
          appDEFieldId: 'lead_source',
          name: 'LEAD_SOURCE',
          id: 'lead_source',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAILING_STATE',
          },
          caption: '邮寄地址-省/市',
          appDEFieldId: 'mailing_state',
          name: 'MAILING_STATE',
          id: 'mailing_state',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAILING_CITY',
          },
          caption: '邮寄地址-城市',
          appDEFieldId: 'mailing_city',
          name: 'MAILING_CITY',
          id: 'mailing_city',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LAST_NAME',
          },
          caption: '姓氏',
          appDEFieldId: 'last_name',
          name: 'LAST_NAME',
          id: 'last_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DEPARTMENT',
          },
          caption: '部门',
          appDEFieldId: 'department',
          name: 'DEPARTMENT',
          id: 'department',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.OTHER_STATE',
          },
          caption: '其它省/市',
          appDEFieldId: 'other_state',
          name: 'OTHER_STATE',
          id: 'other_state',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.OTHER_ZIP',
          },
          caption: '其他邮编',
          appDEFieldId: 'other_zip',
          name: 'OTHER_ZIP',
          id: 'other_zip',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.OTHER_COUNTRY',
          },
          caption: '其它国家/地区',
          appDEFieldId: 'other_country',
          name: 'OTHER_COUNTRY',
          id: 'other_country',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.EMAIL',
          },
          caption: '电子邮件',
          appDEFieldId: 'email',
          name: 'EMAIL',
          id: 'email',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAILING_ZIP',
          },
          caption: '邮寄地址-邮编',
          appDEFieldId: 'mailing_zip',
          name: 'MAILING_ZIP',
          id: 'mailing_zip',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.TITLE',
          },
          caption: '职位/职称',
          appDEFieldId: 'title',
          name: 'TITLE',
          id: 'title',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MAILING_COUNTRY',
          },
          caption: '邮寄地址-国家/地',
          appDEFieldId: 'mailing_country',
          name: 'MAILING_COUNTRY',
          id: 'mailing_country',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ASST_PHONE',
          },
          caption: '助理电话',
          appDEFieldId: 'asst_phone',
          name: 'ASST_PHONE',
          id: 'asst_phone',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DATE_OF_BIRTH',
          },
          caption: '生日',
          appDEFieldId: 'date_of_birth',
          name: 'DATE_OF_BIRTH',
          id: 'date_of_birth',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.HOME_PHONE',
          },
          caption: '住宅电话',
          appDEFieldId: 'home_phone',
          name: 'HOME_PHONE',
          id: 'home_phone',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MOBILE',
          },
          caption: '手机',
          appDEFieldId: 'mobile',
          name: 'MOBILE',
          id: 'mobile',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ASSISTANT',
          },
          caption: '助理',
          appDEFieldId: 'assistant',
          name: 'ASSISTANT',
          id: 'assistant',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.FAX',
          },
          caption: '传真',
          appDEFieldId: 'fax',
          name: 'FAX',
          id: 'fax',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PHONE',
          },
          caption: '电话',
          appDEFieldId: 'phone',
          name: 'PHONE',
          id: 'phone',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.TAG',
          },
          caption: '标签',
          appDEFieldId: 'tag',
          name: 'TAG',
          id: 'tag',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.EMAIL_OPT_OUT',
          },
          caption: '不发营销邮件',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'email_opt_out',
          name: 'EMAIL_OPT_OUT',
          id: 'email_opt_out',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SALUTATION',
          },
          caption: '称呼',
          appDEFieldId: 'salutation',
          name: 'SALUTATION',
          id: 'salutation',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CONTACT.SKYPE_ID',
          },
          caption: 'Skype_ID',
          appDEFieldId: 'skype_id',
          name: 'SKYPE_ID',
          id: 'skype_id',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SECONDARY_EMAIL',
          },
          caption: '备用邮箱',
          appDEFieldId: 'secondary_email',
          name: 'SECONDARY_EMAIL',
          id: 'secondary_email',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UNSUBSCRIBED_MODE',
          },
          caption: '退订的方式',
          appDEFieldId: 'unsubscribed_mode',
          name: 'UNSUBSCRIBED_MODE',
          id: 'unsubscribed_mode',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UNSUBSCRIBED_TIME',
          },
          caption: '退订的时间',
          appDEFieldId: 'unsubscribed_time',
          name: 'UNSUBSCRIBED_TIME',
          id: 'unsubscribed_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CHANGE_LOG_TIME__S',
          },
          caption: 'Change_Log_Time',
          appDEFieldId: 'change_log_time_s',
          name: 'CHANGE_LOG_TIME__S',
          id: 'change_log_time__s',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LAST_ACTIVITY_TIME',
          },
          caption: '最近操作时间',
          appDEFieldId: 'last_activity_time',
          name: 'LAST_ACTIVITY_TIME',
          id: 'last_activity_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LAST_ENRICHED_TIME__S',
          },
          caption: '最后充实时间',
          appDEFieldId: 'last_enriched_time_s',
          name: 'LAST_ENRICHED_TIME__S',
          id: 'last_enriched_time__s',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LOCKED__S',
          },
          caption: 'Locked',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'locked_s',
          name: 'LOCKED__S',
          id: 'locked__s',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ENRICH_STATUS__S',
          },
          caption: '充实状态',
          appDEFieldId: 'enrich_status_s',
          name: 'ENRICH_STATUS__S',
          id: 'enrich_status__s',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          appDEFieldId: 'id',
          name: 'ID',
          id: 'id',
        },
        {
          caption: '附件',
          appDEFieldId: 'attachments',
          name: 'ATTACHMENTS',
          id: 'attachments',
        },
        {
          caption: '客户ID',
          appDEFieldId: 'account_id',
          name: 'ACCOUNT_ID',
          id: 'account_id',
        },
        {
          caption: '所有者',
          codeListId: 'crmweb.crm__owner',
          appDEFieldId: 'owner',
          name: 'OWNER',
          id: 'owner',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '导入联系人',
      id: 'dataimport',
    },
  ],
  appDEFields: [
    {
      codeName: 'account_name',
      logicName: '客户名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACCOUNT_NAME',
      id: 'account_name',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'description',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DESCRIPTION',
      },
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'record_image',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RECORD_IMAGE',
      },
      logicName: '联系人图片',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RECORD_IMAGE',
      id: 'record_image',
    },
    {
      codeName: 'mailing_street',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAILING_STREET',
      },
      logicName: '邮寄地址-街道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'MAILING_STREET',
      id: 'mailing_street',
    },
    {
      codeName: 'other_street',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.OTHER_STREET',
      },
      logicName: '其它街道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'OTHER_STREET',
      id: 'other_street',
    },
    {
      codeName: 'full_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FULL_NAME',
      },
      logicName: '全名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 120,
      enableQuickSearch: true,
      name: 'FULL_NAME',
      id: 'full_name',
    },
    {
      codeName: 'first_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FIRST_NAME',
      },
      logicName: '名字',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 40,
      name: 'FIRST_NAME',
      id: 'first_name',
    },
    {
      codeName: 'other_city',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.OTHER_CITY',
      },
      logicName: '其它城市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OTHER_CITY',
      id: 'other_city',
    },
    {
      codeName: 'lead_source',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LEAD_SOURCE',
      },
      logicName: '线索来源',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'LEAD_SOURCE',
      id: 'lead_source',
    },
    {
      codeName: 'mailing_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAILING_STATE',
      },
      logicName: '邮寄地址-省/市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MAILING_STATE',
      id: 'mailing_state',
    },
    {
      codeName: 'mailing_city',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAILING_CITY',
      },
      logicName: '邮寄地址-城市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MAILING_CITY',
      id: 'mailing_city',
    },
    {
      codeName: 'last_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LAST_NAME',
      },
      logicName: '姓氏',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 80,
      name: 'LAST_NAME',
      id: 'last_name',
    },
    {
      codeName: 'department',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DEPARTMENT',
      },
      logicName: '部门',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'DEPARTMENT',
      id: 'department',
    },
    {
      codeName: 'other_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.OTHER_STATE',
      },
      logicName: '其它省/市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OTHER_STATE',
      id: 'other_state',
    },
    {
      codeName: 'other_zip',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.OTHER_ZIP',
      },
      logicName: '其他邮编',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'OTHER_ZIP',
      id: 'other_zip',
    },
    {
      codeName: 'other_country',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.OTHER_COUNTRY',
      },
      logicName: '其它国家/地区',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OTHER_COUNTRY',
      id: 'other_country',
    },
    {
      codeName: 'email',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.EMAIL',
      },
      logicName: '电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EMAIL',
      id: 'email',
    },
    {
      codeName: 'mailing_zip',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAILING_ZIP',
      },
      logicName: '邮寄地址-邮编',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'MAILING_ZIP',
      id: 'mailing_zip',
    },
    {
      codeName: 'title',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.TITLE',
      },
      logicName: '职位/职称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TITLE',
      id: 'title',
    },
    {
      codeName: 'mailing_country',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAILING_COUNTRY',
      },
      logicName: '邮寄地址-国家/地',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MAILING_COUNTRY',
      id: 'mailing_country',
    },
    {
      codeName: 'asst_phone',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ASST_PHONE',
      },
      logicName: '助理电话',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ASST_PHONE',
      id: 'asst_phone',
    },
    {
      codeName: 'date_of_birth',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DATE_OF_BIRTH',
      },
      logicName: '生日',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'DATE_OF_BIRTH',
      id: 'date_of_birth',
    },
    {
      codeName: 'home_phone',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.HOME_PHONE',
      },
      logicName: '住宅电话',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'HOME_PHONE',
      id: 'home_phone',
    },
    {
      codeName: 'mobile',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MOBILE',
      },
      logicName: '手机',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MOBILE',
      id: 'mobile',
    },
    {
      codeName: 'assistant',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ASSISTANT',
      },
      logicName: '助理',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'ASSISTANT',
      id: 'assistant',
    },
    {
      codeName: 'fax',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FAX',
      },
      logicName: '传真',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'FAX',
      id: 'fax',
    },
    {
      codeName: 'phone',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PHONE',
      },
      logicName: '电话',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PHONE',
      id: 'phone',
    },
    {
      codeName: 'tag',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.TAG',
      },
      logicName: '标签',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'TAG',
      id: 'tag',
    },
    {
      codeName: 'email_opt_out',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.EMAIL_OPT_OUT',
      },
      logicName: '不发营销邮件',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'EMAIL_OPT_OUT',
      id: 'email_opt_out',
    },
    {
      codeName: 'salutation',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SALUTATION',
      },
      logicName: '称呼',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SALUTATION',
      id: 'salutation',
    },
    {
      codeName: 'skype_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CONTACT.SKYPE_ID',
      },
      logicName: 'Skype_ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'SKYPE_ID',
      id: 'skype_id',
    },
    {
      codeName: 'secondary_email',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SECONDARY_EMAIL',
      },
      logicName: '备用邮箱',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SECONDARY_EMAIL',
      id: 'secondary_email',
    },
    {
      codeName: 'unsubscribed_mode',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UNSUBSCRIBED_MODE',
      },
      logicName: '退订的方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'UNSUBSCRIBED_MODE',
      id: 'unsubscribed_mode',
    },
    {
      codeName: 'unsubscribed_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UNSUBSCRIBED_TIME',
      },
      logicName: '退订的时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UNSUBSCRIBED_TIME',
      id: 'unsubscribed_time',
    },
    {
      codeName: 'change_log_time_s',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CHANGE_LOG_TIME__S',
      },
      logicName: 'Change_Log_Time',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CHANGE_LOG_TIME__S',
      id: 'change_log_time_s',
    },
    {
      codeName: 'last_activity_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LAST_ACTIVITY_TIME',
      },
      logicName: '最近操作时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_ACTIVITY_TIME',
      id: 'last_activity_time',
    },
    {
      codeName: 'last_enriched_time_s',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LAST_ENRICHED_TIME__S',
      },
      logicName: '最后充实时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_ENRICHED_TIME__S',
      id: 'last_enriched_time_s',
    },
    {
      codeName: 'locked_s',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LOCKED__S',
      },
      logicName: 'Locked',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LOCKED__S',
      id: 'locked_s',
    },
    {
      codeName: 'enrich_status_s',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ENRICH_STATUS__S',
      },
      logicName: '充实状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ENRICH_STATUS__S',
      id: 'enrich_status_s',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'attachments',
      logicName: '附件',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'account_id',
      logicName: '客户ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACCOUNT_ID',
      id: 'account_id',
    },
    {
      codeName: 'owner',
      logicName: '所有者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'OWNER',
      id: 'owner',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'contact_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'account_name',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_name',
        },
        {
          codeName: 'account_id',
          logicName: '客户ID',
          appDEFieldId: 'account_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_id',
        },
        {
          codeName: 'assistant',
          logicName: '助理',
          appDEFieldId: 'assistant',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'assistant',
        },
        {
          codeName: 'asst_phone',
          logicName: '助理电话',
          appDEFieldId: 'asst_phone',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'asst_phone',
        },
        {
          codeName: 'attachments',
          logicName: '附件',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'attachment_dto',
          refAppDataEntityId: 'crmweb.attachment',
          refPickupAppDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'change_log_time_s',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: 'Change_Log_Time',
          appDEFieldId: 'change_log_time_s',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'change_log_time_s',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'date_of_birth',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '生日',
          appDEFieldId: 'date_of_birth',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_of_birth',
        },
        {
          codeName: 'department',
          logicName: '部门',
          appDEFieldId: 'department',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'department',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'email',
          logicName: '电子邮件',
          appDEFieldId: 'email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email',
        },
        {
          codeName: 'email_opt_out',
          logicName: '不发营销邮件',
          appDEFieldId: 'email_opt_out',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_opt_out',
        },
        {
          codeName: 'enrich_status_s',
          logicName: '充实状态',
          appDEFieldId: 'enrich_status_s',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'enrich_status_s',
        },
        {
          codeName: 'fax',
          logicName: '传真',
          appDEFieldId: 'fax',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'fax',
        },
        {
          codeName: 'first_name',
          logicName: '名字',
          appDEFieldId: 'first_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'first_name',
        },
        {
          codeName: 'full_name',
          logicName: '全名',
          appDEFieldId: 'full_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'full_name',
        },
        {
          codeName: 'home_phone',
          logicName: '住宅电话',
          appDEFieldId: 'home_phone',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'home_phone',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'last_activity_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最近操作时间',
          appDEFieldId: 'last_activity_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_activity_time',
        },
        {
          codeName: 'last_enriched_time_s',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最后充实时间',
          appDEFieldId: 'last_enriched_time_s',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_enriched_time_s',
        },
        {
          codeName: 'last_name',
          logicName: '姓氏',
          appDEFieldId: 'last_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_name',
        },
        {
          codeName: 'lead_source',
          logicName: '线索来源',
          appDEFieldId: 'lead_source',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lead_source',
        },
        {
          codeName: 'locked_s',
          logicName: 'Locked',
          appDEFieldId: 'locked_s',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'locked_s',
        },
        {
          codeName: 'mailing_city',
          logicName: '邮寄地址-城市',
          appDEFieldId: 'mailing_city',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mailing_city',
        },
        {
          codeName: 'mailing_country',
          logicName: '邮寄地址-国家/地',
          appDEFieldId: 'mailing_country',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mailing_country',
        },
        {
          codeName: 'mailing_state',
          logicName: '邮寄地址-省/市',
          appDEFieldId: 'mailing_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mailing_state',
        },
        {
          codeName: 'mailing_street',
          logicName: '邮寄地址-街道',
          appDEFieldId: 'mailing_street',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mailing_street',
        },
        {
          codeName: 'mailing_zip',
          logicName: '邮寄地址-邮编',
          appDEFieldId: 'mailing_zip',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mailing_zip',
        },
        {
          codeName: 'mobile',
          logicName: '手机',
          appDEFieldId: 'mobile',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mobile',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'other_city',
          logicName: '其它城市',
          appDEFieldId: 'other_city',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'other_city',
        },
        {
          codeName: 'other_country',
          logicName: '其它国家/地区',
          appDEFieldId: 'other_country',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'other_country',
        },
        {
          codeName: 'other_state',
          logicName: '其它省/市',
          appDEFieldId: 'other_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'other_state',
        },
        {
          codeName: 'other_street',
          logicName: '其它街道',
          appDEFieldId: 'other_street',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'other_street',
        },
        {
          codeName: 'other_zip',
          logicName: '其他邮编',
          appDEFieldId: 'other_zip',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'other_zip',
        },
        {
          codeName: 'owner',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner',
        },
        {
          codeName: 'phone',
          logicName: '电话',
          appDEFieldId: 'phone',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone',
        },
        {
          codeName: 'record_image',
          logicName: '联系人图片',
          appDEFieldId: 'record_image',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'record_image',
        },
        {
          codeName: 'salutation',
          logicName: '称呼',
          appDEFieldId: 'salutation',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'salutation',
        },
        {
          codeName: 'secondary_email',
          logicName: '备用邮箱',
          appDEFieldId: 'secondary_email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'secondary_email',
        },
        {
          codeName: 'skype_id',
          logicName: 'Skype_ID',
          appDEFieldId: 'skype_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'skype_id',
        },
        {
          codeName: 'tag',
          logicName: '标签',
          appDEFieldId: 'tag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'tag',
        },
        {
          codeName: 'title',
          logicName: '职位/职称',
          appDEFieldId: 'title',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'title',
        },
        {
          codeName: 'unsubscribed_mode',
          logicName: '退订的方式',
          appDEFieldId: 'unsubscribed_mode',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'unsubscribed_mode',
        },
        {
          codeName: 'unsubscribed_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '退订的时间',
          appDEFieldId: 'unsubscribed_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'unsubscribed_time',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'contact_dto',
    },
    {
      codeName: 'contact_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_account_id_eq',
          logicName: '客户ID',
          appDEFieldId: 'account_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_id_eq',
        },
        {
          codeName: 'n_account_name_eq',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_name_eq',
        },
        {
          codeName: 'n_account_name_like',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_name_like',
        },
        {
          codeName: 'n_enrich_status_s_eq',
          logicName: '充实状态',
          appDEFieldId: 'enrich_status_s',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_enrich_status_s_eq',
        },
        {
          codeName: 'n_first_name_like',
          logicName: '名字',
          appDEFieldId: 'first_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_first_name_like',
        },
        {
          codeName: 'n_full_name_like',
          logicName: '全名',
          appDEFieldId: 'full_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_full_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_lead_source_eq',
          logicName: '线索来源',
          appDEFieldId: 'lead_source',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lead_source_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_owner_eq',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_owner_eq',
        },
        {
          codeName: 'n_salutation_eq',
          logicName: '称呼',
          appDEFieldId: 'salutation',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_salutation_eq',
        },
        {
          codeName: 'n_unsubscribed_mode_eq',
          logicName: '退订的方式',
          appDEFieldId: 'unsubscribed_mode',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_unsubscribed_mode_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'contact_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_tags',
    },
    {
      codeName: 'batch_update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/batch_update',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'batch_update',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_task',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_task',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_task',
    },
    {
      codeName: 'delete_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete_tags',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'main_view_dr_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/main_view_dr_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'main_view_dr_count',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_createman',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_createman',
      actionType: 'REMOTE',
      dataSetName: 'createman',
      dataSetTag: 'createman',
      dataSetType: 'REMOTE',
      id: 'fetch_createman',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_owner',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'contact_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'contact_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_owner',
      actionType: 'REMOTE',
      dataSetName: 'owner',
      dataSetTag: 'owner',
      dataSetType: 'REMOTE',
      id: 'fetch_owner',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导入联系人',
      codeName: 'ImportData',
      frontProcessType: 'DATAIMP',
      fullCodeName: 'contact_ImportData',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'ImportData',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEDataImportId: 'dataimport',
      appDataEntityId: 'crmweb.contact',
      name: '导入数据',
      id: 'importdata@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加附件',
      codeName: 'add_attachments',
      frontProcessType: 'OTHER',
      fullCodeName: 'contact_add_attachments',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'add_attachments',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'add_attachment',
      appDataEntityId: 'crmweb.contact',
      name: '添加附件',
      id: 'add_attachments@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '添加标签',
      codeName: 'add_tags',
      frontAppViewId: 'crmweb.tag_add_tag',
      fullCodeName: 'contact_add_tags',
      appDEMethodId: 'add_tags',
      refreshMode: 1,
      successMsg: '已成功添加标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '添加标签',
      id: 'add_tags@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '批量更新',
      codeName: 'batch_update',
      fullCodeName: 'contact_batch_update',
      appDEMethodId: 'batch_update',
      refreshMode: 1,
      successMsg: '更新完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'batch_update',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '批量更新',
      id: 'batch_update@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '创建任务',
      codeName: 'create_task',
      frontAppViewId: 'crmweb.task_batch_create_view',
      fullCodeName: 'contact_create_task',
      appDEMethodId: 'create_task',
      successMsg: '创建完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'create_task',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '创建任务',
      id: 'create_task@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移除标签',
      codeName: 'delete_tags',
      frontAppViewId: 'crmweb.tag_remove_tag',
      fullCodeName: 'contact_delete_tags',
      appDEMethodId: 'delete_tags',
      refreshMode: 1,
      successMsg: '已成功移除标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '移除标签',
      id: 'delete_tags@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '管理标签',
      codeName: 'mgr_tags',
      frontAppViewId: 'crmweb.tag_mgr_grid_view',
      frontProcessType: 'TOP',
      fullCodeName: 'contact_mgr_tags',
      navigateContexts: [
        {
          key: 'OWNER_TYPE',
          value: 'CONTACT',
          rawValue: true,
          name: 'OWNER_TYPE',
          id: 'owner_type',
        },
      ],
      navigateParams: [
        {
          key: 'owner_type',
          value: 'CONTACT',
          rawValue: true,
          id: 'owner_type',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'mgr_tags',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '管理标签',
      id: 'mgr_tags@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '联系人',
      codeName: 'openContactZsjView',
      frontAppViewId: 'crmweb.contact_main_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'contact_openContactZsjView',
      uiactionMode: 'FRONT',
      uiactionTag: 'openContactZsjView',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '打开联系人主数据页面',
      id: 'opencontactzsjview@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'open_edit_view',
      frontAppViewId: 'crmweb.contact_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'contact_open_edit_view',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit_view',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '编辑',
      id: 'open_edit_view@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '联系人层级',
      codeName: 'panel_usr0422974089_button_openview_click',
      frontAppViewId: 'crmweb.contact_tree_view_level',
      frontProcessType: 'WIZARD',
      fullCodeName: 'contact_panel_usr0422974089_button_openview_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_usr0422974089_button_openview_click',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '层级视图',
      id: 'panel_usr0422974089_button_openview_click@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'remove',
      confirmMsg: '确定要删除所选的记录吗？',
      fullCodeName: 'contact_remove',
      appDEMethodId: 'remove',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '删除',
      id: 'remove@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '保存并打开联系人主数据页面',
      codeName: 'saveAndOpenContact',
      dialogResult: 'OK',
      fullCodeName: 'contact_saveAndOpenContact',
      nextId: 'opencontactzsjview@contact',
      appDEMethodId: 'create',
      refreshMode: 1,
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'saveAndOpenContact',
      uiactionType: 'DEUIACTION',
      closeEditView: true,
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '保存并打开联系人主数据页面',
      id: 'saveandopencontact@contact',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '上传',
      codeName: 'upload_attachment',
      frontProcessType: 'OTHER',
      fullCodeName: 'contact_upload_attachment',
      sysPFPluginId: 'file_upload',
      uiactionMode: 'FRONT',
      uiactionTag: 'upload_attachment',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.contact',
      name: '上传附件',
      id: 'upload_attachment@contact',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'add_attachment',
      defaultParamName: 'Default',
      logicName: '添加附件',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          dstAppDEUIActionId: 'upload_attachment@contact',
          dstAppDataEntityId: 'crmweb.contact',
          codeName: 'DEUIACTION1',
          dstDEUILogicParamId: 'files',
          leftPos: 309,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'deuiaction1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '界面行为',
          id: 'deuiaction1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 553,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode4',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'grid',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'details.attachments.mdController',
              srcDEUILogicParamId: 'form',
              srcValueType: 'SRCDLPARAM',
              name: 'form[details.attachments.mdController] ==> grid',
              id: 'form[details.attachments.mdcontroller] ==> grid',
            },
          ],
          topPos: 208,
          name: '绑定表格部件',
          id: 'preparejsparam1',
        },
        {
          invokeCtrlId: 'grid',
          invokeMethod: 'addAttachMent',
          invokeParamId: 'attach',
          codeName: 'VIEWCTRLINVOKE2',
          leftPos: 989,
          logicNodeType: 'VIEWCTRLINVOKE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlinvoke2',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '视图部件调用',
          id: 'viewctrlinvoke2',
        },
        {
          codeName: 'END1',
          leftPos: 1167,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
        {
          code: '// 计算新建默认值\r\nconst defaultData = uiLogic.grid.calcDefaultValue({}, true);\r\nuiLogic.attach = uiLogic.files.map(item => \r\n    {\r\n        return {\r\n            name: item.name,\r\n            file_id: item.id,\r\n            id: item.uuid,\r\n            ...defaultData,\r\n        }\r\n    }\r\n)',
          codeName: 'RAWJSCODE4',
          leftPos: 780,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke2',
              srcDEUILogicNodeId: 'rawjscode4',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '设置附件参数',
          id: 'rawjscode4',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'files',
          entityListParam: true,
          name: '上传文件',
          id: 'files',
        },
        {
          codeName: 'attach',
          entityListParam: true,
          name: '附件',
          id: 'attach',
        },
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '重复器表格',
          id: 'grid',
        },
        {
          codeName: 'form',
          ctrlParam: true,
          name: '表单',
          id: 'form',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '添加附件',
      id: 'add_attachment',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'contact',
  deapicodeName: 'contact',
  deapicodeName2: 'contacts',
  deapitag: 'CONTACT',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'dataimport',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '联系人',
  majorAppDEFieldId: 'full_name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'contacts',
      majorAppDataEntityId: 'crmweb.account',
      parentAppDEFieldId: 'account_id',
      parentTextAppDEFieldId: 'account_name',
      rsmode: 2,
      name: 'DER1N_CONTACT_ACCOUNT_ACCOUNT_ID',
      id: 'contacts',
    },
  ],
  quickSearchAppDEFieldIds: ['full_name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'CONTACT',
  id: 'crmweb.contact',
  codeName2: 'contacts',
  requestPaths: ['accounts/${account}/contacts/${contact}'],
};
