export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'deal_name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'crmweb.deal',
      textAppDEFieldId: 'deal_name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'DataImport',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '客户名称',
          appDEFieldId: 'account_name',
          name: 'ACCOUNT_NAME',
          id: 'account_name',
        },
        {
          caption: '执行人',
          appDEFieldId: 'executors',
          name: 'EXECUTORS',
          id: 'executors',
        },
        {
          caption: '是否有效',
          appDEFieldId: 'validity',
          name: 'VALIDITY',
          id: 'validity',
        },
        {
          caption: '业务条线',
          codeListId: 'crmweb.crm__industry',
          appDEFieldId: 'business_line',
          name: 'BUSINESS_LINE',
          id: 'business_line',
        },
        {
          caption: '商机阶段概率',
          appDEFieldId: 'stage_probability',
          name: 'STAGE_PROBABILITY',
          id: 'stage_probability',
        },
        {
          caption: '最近评估时间',
          appDEFieldId: 'last_assess_time',
          name: 'LAST_ASSESS_TIME',
          id: 'last_assess_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          appDEFieldId: 'create_time',
          name: 'CREATE_TIME',
          id: 'create_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'create_man',
          name: 'CREATE_MAN',
          id: 'create_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          appDEFieldId: 'name',
          name: 'NAME',
          id: 'name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          appDEFieldId: 'update_time',
          name: 'UPDATE_TIME',
          id: 'update_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'update_man',
          name: 'UPDATE_MAN',
          id: 'update_man',
        },
        {
          caption: '金额',
          appDEFieldId: 'amount',
          name: 'AMOUNT',
          id: 'amount',
        },
        {
          caption: '商机名称',
          appDEFieldId: 'deal_name',
          name: 'DEAL_NAME',
          id: 'deal_name',
        },
        {
          caption: '描述',
          appDEFieldId: 'description',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          caption: '预期收益',
          appDEFieldId: 'expected_revenue',
          name: 'EXPECTED_REVENUE',
          id: 'expected_revenue',
        },
        {
          caption: '标签',
          appDEFieldId: 'tag',
          name: 'TAG',
          id: 'tag',
        },
        {
          caption: '下一步',
          appDEFieldId: 'next_step',
          name: 'NEXT_STEP',
          id: 'next_step',
        },
        {
          caption: '预计成交日期',
          appDEFieldId: 'closing_date',
          name: 'CLOSING_DATE',
          id: 'closing_date',
        },
        {
          caption: '可能性',
          appDEFieldId: 'probability',
          name: 'PROBABILITY',
          id: 'probability',
        },
        {
          caption: '线索来源',
          codeListId: 'crmweb.crm__lead_source',
          appDEFieldId: 'lead_source',
          name: 'LEAD_SOURCE',
          id: 'lead_source',
        },
        {
          caption: '丢单原因',
          appDEFieldId: 'reason_for_loss_s',
          name: 'REASON_FOR_LOSS__S',
          id: 'reason_for_loss__s',
        },
        {
          caption: '类型',
          codeListId: 'crmweb.crm__type',
          appDEFieldId: 'type',
          name: 'TYPE',
          id: 'type',
        },
        {
          caption: '阶段标识',
          appDEFieldId: 'stage',
          name: 'STAGE',
          id: 'stage',
        },
        {
          caption: '最近操作时间',
          appDEFieldId: 'last_activity_time',
          name: 'LAST_ACTIVITY_TIME',
          id: 'last_activity_time',
        },
        {
          caption: 'Locked',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'locked_s',
          name: 'LOCKED__S',
          id: 'locked__s',
        },
        {
          caption: 'Change Log Time',
          appDEFieldId: 'change_log_time_s',
          name: 'CHANGE_LOG_TIME__S',
          id: 'change_log_time__s',
        },
        {
          caption: '线索转换用时',
          appDEFieldId: 'lead_conversion_time',
          name: 'LEAD_CONVERSIONTIME',
          id: 'lead_conversiontime',
        },
        {
          caption: '销售周期的持续时间',
          appDEFieldId: 'sales_cycle_duration',
          name: 'SALES_CYCLE_DURATION',
          id: 'sales_cycle_duration',
        },
        {
          caption: '总销售时间',
          appDEFieldId: 'overall_sales_duration',
          name: 'OVERALL_SALES_DURATION',
          id: 'overall_sales_duration',
        },
        {
          caption: '附件',
          appDEFieldId: 'attachments',
          name: 'ATTACHMENTS',
          id: 'attachments',
        },
        {
          caption: '客户ID',
          appDEFieldId: 'account_id',
          name: 'ACCOUNT_ID',
          id: 'account_id',
        },
        {
          caption: '联系人标识',
          appDEFieldId: 'contact_id',
          name: 'CONTACT_ID',
          id: 'contact_id',
        },
        {
          caption: '联系人名称',
          appDEFieldId: 'contact_name',
          name: 'CONTACT_NAME',
          id: 'contact_name',
        },
        {
          caption: '所有者',
          codeListId: 'crmweb.crm__owner',
          appDEFieldId: 'owner',
          name: 'OWNER',
          id: 'owner',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          appDEFieldId: 'id',
          name: 'ID',
          id: 'id',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '导入商机',
      id: 'dataimport',
    },
  ],
  appDEFields: [
    {
      codeName: 'account_name',
      logicName: '客户名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACCOUNT_NAME',
      id: 'account_name',
    },
    {
      codeName: 'executors',
      logicName: '执行人',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'EXECUTORS',
      id: 'executors',
    },
    {
      codeName: 'validity',
      logicName: '是否有效',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'VALIDITY',
      id: 'validity',
    },
    {
      codeName: 'business_line',
      logicName: '业务条线',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'BUSINESS_LINE',
      id: 'business_line',
    },
    {
      codeName: 'stage_probability',
      logicName: '商机阶段概率',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'STAGE_PROBABILITY',
      id: 'stage_probability',
    },
    {
      codeName: 'last_assess_time',
      logicName: '最近评估时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_ASSESS_TIME',
      id: 'last_assess_time',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'amount',
      logicName: '金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'AMOUNT',
      id: 'amount',
    },
    {
      codeName: 'deal_name',
      logicName: '商机名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 120,
      enableQuickSearch: true,
      name: 'DEAL_NAME',
      id: 'deal_name',
    },
    {
      codeName: 'description',
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'expected_revenue',
      logicName: '预期收益',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'EXPECTED_REVENUE',
      id: 'expected_revenue',
    },
    {
      codeName: 'tag',
      logicName: '标签',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'TAG',
      id: 'tag',
    },
    {
      codeName: 'next_step',
      logicName: '下一步',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'NEXT_STEP',
      id: 'next_step',
    },
    {
      codeName: 'closing_date',
      logicName: '预计成交日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'CLOSING_DATE',
      id: 'closing_date',
    },
    {
      codeName: 'probability',
      logicName: '可能性',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'PROBABILITY',
      id: 'probability',
    },
    {
      codeName: 'lead_source',
      logicName: '线索来源',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'LEAD_SOURCE',
      id: 'lead_source',
    },
    {
      codeName: 'reason_for_loss_s',
      logicName: '丢单原因',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'REASON_FOR_LOSS__S',
      id: 'reason_for_loss_s',
    },
    {
      codeName: 'type',
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'TYPE',
      id: 'type',
    },
    {
      codeName: 'stage',
      logicName: '阶段标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STAGE',
      id: 'stage',
    },
    {
      codeName: 'last_activity_time',
      logicName: '最近操作时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_ACTIVITY_TIME',
      id: 'last_activity_time',
    },
    {
      codeName: 'locked_s',
      logicName: 'Locked',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LOCKED__S',
      id: 'locked_s',
    },
    {
      codeName: 'change_log_time_s',
      logicName: 'Change Log Time',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CHANGE_LOG_TIME__S',
      id: 'change_log_time_s',
    },
    {
      codeName: 'lead_conversion_time',
      logicName: '线索转换用时',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LEAD_CONVERSIONTIME',
      id: 'lead_conversion_time',
    },
    {
      codeName: 'sales_cycle_duration',
      logicName: '销售周期的持续时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SALES_CYCLE_DURATION',
      id: 'sales_cycle_duration',
    },
    {
      codeName: 'overall_sales_duration',
      logicName: '总销售时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OVERALL_SALES_DURATION',
      id: 'overall_sales_duration',
    },
    {
      codeName: 'attachments',
      logicName: '附件',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'account_id',
      logicName: '客户ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACCOUNT_ID',
      id: 'account_id',
    },
    {
      codeName: 'contact_id',
      logicName: '联系人标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CONTACT_ID',
      id: 'contact_id',
    },
    {
      codeName: 'contact_name',
      logicName: '联系人名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'CONTACT_NAME',
      id: 'contact_name',
    },
    {
      codeName: 'owner',
      logicName: '所有者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'OWNER',
      id: 'owner',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'deal_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'account_name',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_name',
        },
        {
          codeName: 'executors',
          logicName: '执行人',
          appDEFieldId: 'executors',
          refAppDEMethodDTOId: 'executor_dto',
          refAppDataEntityId: 'crmweb.executor',
          refPickupAppDEFieldId: 'principal_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'executors',
        },
        {
          codeName: 'validity',
          logicName: '是否有效',
          appDEFieldId: 'validity',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'validity',
        },
        {
          codeName: 'business_line',
          logicName: '业务条线',
          appDEFieldId: 'business_line',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'business_line',
        },
        {
          codeName: 'last_assess_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最近评估时间',
          appDEFieldId: 'last_assess_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_assess_time',
        },
        {
          codeName: 'stage_probability',
          logicName: '商机阶段概率',
          appDEFieldId: 'stage_probability',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'stage_probability',
        },
        {
          codeName: 'account_id',
          logicName: '客户ID',
          appDEFieldId: 'account_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_id',
        },
        {
          codeName: 'amount',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'amount',
        },
        {
          codeName: 'attachments',
          logicName: '附件',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'attachment_dto',
          refAppDataEntityId: 'crmweb.attachment',
          refPickupAppDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'change_log_time_s',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: 'Change Log Time',
          appDEFieldId: 'change_log_time_s',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'change_log_time_s',
        },
        {
          codeName: 'closing_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '预计成交日期',
          appDEFieldId: 'closing_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'closing_date',
        },
        {
          codeName: 'contact_id',
          logicName: '联系人标识',
          appDEFieldId: 'contact_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'contact_id',
        },
        {
          codeName: 'contact_name',
          logicName: '联系人名称',
          appDEFieldId: 'contact_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'contact_name',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'deal_name',
          logicName: '商机名称',
          appDEFieldId: 'deal_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'deal_name',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'expected_revenue',
          logicName: '预期收益',
          appDEFieldId: 'expected_revenue',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'expected_revenue',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'last_activity_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最近操作时间',
          appDEFieldId: 'last_activity_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_activity_time',
        },
        {
          codeName: 'lead_conversion_time',
          logicName: '线索转换用时',
          appDEFieldId: 'lead_conversion_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lead_conversion_time',
        },
        {
          codeName: 'lead_source',
          logicName: '线索来源',
          appDEFieldId: 'lead_source',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lead_source',
        },
        {
          codeName: 'locked_s',
          logicName: 'Locked',
          appDEFieldId: 'locked_s',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'locked_s',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'next_step',
          logicName: '下一步',
          appDEFieldId: 'next_step',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'next_step',
        },
        {
          codeName: 'overall_sales_duration',
          logicName: '总销售时间',
          appDEFieldId: 'overall_sales_duration',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overall_sales_duration',
        },
        {
          codeName: 'owner',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner',
        },
        {
          codeName: 'probability',
          logicName: '可能性',
          appDEFieldId: 'probability',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'probability',
        },
        {
          codeName: 'reason_for_loss_s',
          logicName: '丢单原因',
          appDEFieldId: 'reason_for_loss_s',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'reason_for_loss_s',
        },
        {
          codeName: 'sales_cycle_duration',
          logicName: '销售周期的持续时间',
          appDEFieldId: 'sales_cycle_duration',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sales_cycle_duration',
        },
        {
          codeName: 'stage',
          logicName: '阶段标识',
          appDEFieldId: 'stage',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'stage',
        },
        {
          codeName: 'tag',
          logicName: '标签',
          appDEFieldId: 'tag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'tag',
        },
        {
          codeName: 'type',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'type',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'deal_dto',
    },
    {
      codeName: 'deal_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_account_id_eq',
          logicName: '客户ID',
          appDEFieldId: 'account_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_id_eq',
        },
        {
          codeName: 'n_account_name_eq',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_name_eq',
        },
        {
          codeName: 'n_account_name_like',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_name_like',
        },
        {
          codeName: 'n_amount_gt',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_amount_gt',
        },
        {
          codeName: 'n_amount_gtandeq',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_amount_gtandeq',
        },
        {
          codeName: 'n_amount_lt',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_amount_lt',
        },
        {
          codeName: 'n_amount_ltandeq',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_amount_ltandeq',
        },
        {
          codeName: 'n_business_line_eq',
          logicName: '业务条线',
          appDEFieldId: 'business_line',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_business_line_eq',
        },
        {
          codeName: 'n_closing_date_gtandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '预计成交日期',
          appDEFieldId: 'closing_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_closing_date_gtandeq',
        },
        {
          codeName: 'n_closing_date_in',
          logicName: '预计成交日期',
          appDEFieldId: 'closing_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLES',
          allowEmpty: true,
          id: 'n_closing_date_in',
        },
        {
          codeName: 'n_closing_date_ltandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '预计成交日期',
          appDEFieldId: 'closing_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_closing_date_ltandeq',
        },
        {
          codeName: 'n_contact_id_eq',
          logicName: '联系人标识',
          appDEFieldId: 'contact_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_contact_id_eq',
        },
        {
          codeName: 'n_contact_name_eq',
          logicName: '联系人名称',
          appDEFieldId: 'contact_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_contact_name_eq',
        },
        {
          codeName: 'n_contact_name_like',
          logicName: '联系人名称',
          appDEFieldId: 'contact_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_contact_name_like',
        },
        {
          codeName: 'n_deal_name_like',
          logicName: '商机名称',
          appDEFieldId: 'deal_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_deal_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_lead_source_eq',
          logicName: '线索来源',
          appDEFieldId: 'lead_source',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lead_source_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_owner_eq',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_owner_eq',
        },
        {
          codeName: 'n_reason_for_loss_s_eq',
          logicName: '丢单原因',
          appDEFieldId: 'reason_for_loss_s',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_reason_for_loss_s_eq',
        },
        {
          codeName: 'n_stage_eq',
          logicName: '阶段标识',
          appDEFieldId: 'stage',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_stage_eq',
        },
        {
          codeName: 'n_stage_probability_eq',
          logicName: '商机阶段概率',
          appDEFieldId: 'stage_probability',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_stage_probability_eq',
        },
        {
          codeName: 'n_stage_probability_like',
          logicName: '商机阶段概率',
          appDEFieldId: 'stage_probability',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_stage_probability_like',
        },
        {
          codeName: 'n_type_eq',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'deal_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_deal',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_deal',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_deal',
    },
    {
      codeName: 'add_deal_to_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_deal_to_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'addDealToWorkProgress',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'addDealToWorkProgress',
      id: 'add_deal_to_work_progress',
    },
    {
      codeName: 'add_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_tags',
    },
    {
      codeName: 'async_add_deal_to_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'ASYNCACTION',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/async_add_deal_to_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'Async_addDealToWorkProgress',
      actionType: 'REMOTE',
      asyncAction: true,
      dataSetType: 'REMOTE',
      name: 'Async_addDealToWorkProgress',
      id: 'async_add_deal_to_work_progress',
    },
    {
      codeName: 'batch_update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/batch_update',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'batch_update',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_task',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_task',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_task',
    },
    {
      codeName: 'delete_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete_tags',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'main_view_dr_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/main_view_dr_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'main_view_dr_count',
    },
    {
      codeName: 'relate_task_and_maneuver',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/relate_task_and_maneuver',
      needResourceKey: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'relate_task_and_maneuver',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'stage_probability',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/stage_probability',
      actionMode: 'GETDRAFT',
      actionTag: 'stageProbability',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'stageProbability',
      id: 'stage_probability',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'All',
      dataSetTag: 'All',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_by_account',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_by_account',
      actionType: 'REMOTE',
      dataSetName: 'ByAccount',
      dataSetTag: 'ByAccount',
      dataSetType: 'REMOTE',
      id: 'fetch_by_account',
    },
    {
      codeName: 'fetch_chart',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_chart',
      actionType: 'REMOTE',
      dataSetName: 'chart',
      dataSetTag: 'chart',
      dataSetType: 'REMOTE',
      id: 'fetch_chart',
    },
    {
      codeName: 'fetch_createman',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_createman',
      actionType: 'REMOTE',
      dataSetName: 'createman',
      dataSetTag: 'createman',
      dataSetType: 'REMOTE',
      id: 'fetch_createman',
    },
    {
      codeName: 'fetch_deal_relation_task',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_deal_relation_task',
      actionType: 'REMOTE',
      dataSetName: 'deal_relation_task',
      dataSetTag: 'deal_relation_task',
      dataSetType: 'REMOTE',
      id: 'fetch_deal_relation_task',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_executor',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_executor',
      actionType: 'REMOTE',
      dataSetName: 'executor',
      dataSetTag: 'executor',
      dataSetType: 'REMOTE',
      id: 'fetch_executor',
    },
    {
      codeName: 'fetch_owner',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_owner',
      actionType: 'REMOTE',
      dataSetName: 'owner',
      dataSetTag: 'owner',
      dataSetType: 'REMOTE',
      id: 'fetch_owner',
    },
    {
      codeName: 'fetch_relation',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_relation',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'TARGET_TYPE',
          fieldName: 'TARGET_TYPE',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(TARGET_TYPE) 等于(=) 数据上下文 TARGET_TYPE',
          id: '(target_type) 等于(=) 数据上下文 target_type',
        },
        {
          condOp: 'EQ',
          condValue: 'PRINCIPAL_ID',
          fieldName: 'PRINCIPAL_ID',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(PRINCIPAL_ID) 等于(=) 数据上下文 PRINCIPAL_ID',
          id: '(principal_id) 等于(=) 数据上下文 principal_id',
        },
      ],
      dataSetName: 'relation',
      dataSetTag: 'relation',
      dataSetType: 'REMOTE',
      id: 'fetch_relation',
    },
    {
      codeName: 'fetch_sum',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_sum',
      actionType: 'REMOTE',
      dataSetName: 'sum',
      dataSetTag: 'sum',
      dataSetType: 'REMOTE',
      id: 'fetch_sum',
    },
    {
      codeName: 'fetch_target_relation',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'deal_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'deal_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_target_relation',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'principal_type',
          fieldName: 'TARGET_TYPE',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(TARGET_TYPE) 等于(=) 数据上下文 principal_type',
          id: '(target_type) 等于(=) 数据上下文 principal_type',
        },
        {
          condOp: 'EQ',
          condValue: 'principal_id',
          fieldName: 'TARGET_ID',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(TARGET_ID) 等于(=) 数据上下文 principal_id',
          id: '(target_id) 等于(=) 数据上下文 principal_id',
        },
      ],
      dataSetName: 'target_relation',
      dataSetTag: 'target_relation',
      dataSetType: 'REMOTE',
      id: 'fetch_target_relation',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导入商机',
      codeName: 'ImportData',
      frontProcessType: 'DATAIMP',
      fullCodeName: 'deal_ImportData',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'ImportData',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEDataImportId: 'dataimport',
      appDataEntityId: 'crmweb.deal',
      name: '导入数据',
      id: 'importdata@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加附件',
      codeName: 'add_attachments',
      frontProcessType: 'OTHER',
      fullCodeName: 'deal_add_attachments',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'add_attachments',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'add_attachment',
      appDataEntityId: 'crmweb.deal',
      name: '添加附件',
      id: 'add_attachments@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '添加标签',
      codeName: 'add_tags',
      frontAppViewId: 'crmweb.tag_add_tag',
      fullCodeName: 'deal_add_tags',
      appDEMethodId: 'add_tags',
      refreshMode: 1,
      successMsg: '已成功添加标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '添加标签',
      id: 'add_tags@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '批量更新',
      codeName: 'batch_update',
      fullCodeName: 'deal_batch_update',
      appDEMethodId: 'batch_update',
      refreshMode: 1,
      successMsg: '更新完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'batch_update',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '批量更新',
      id: 'batch_update@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '保存并打开商机主数据视图',
      codeName: 'createAndOpenDeal',
      dialogResult: 'OK',
      fullCodeName: 'deal_createAndOpenDeal',
      nextId: 'opendealzsjview@deal',
      appDEMethodId: 'create',
      refreshMode: 1,
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'createAndOpenDeal',
      uiactionType: 'DEUIACTION',
      closeEditView: true,
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '保存并打开商机主数据视图',
      id: 'createandopendeal@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '创建商机',
      codeName: 'createDeal',
      frontAppViewId: 'crmweb.deal_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'deal_createDeal',
      uiactionMode: 'FRONT',
      uiactionTag: 'createDeal',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '创建商机',
      id: 'createdeal@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '创建任务',
      codeName: 'create_task',
      frontAppViewId: 'crmweb.task_batch_create_view',
      fullCodeName: 'deal_create_task',
      appDEMethodId: 'create_task',
      successMsg: '创建完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'create_task',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '创建任务',
      id: 'create_task@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移除标签',
      codeName: 'delete_tags',
      frontAppViewId: 'crmweb.tag_remove_tag',
      fullCodeName: 'deal_delete_tags',
      appDEMethodId: 'delete_tags',
      refreshMode: 1,
      successMsg: '已成功移除标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '移除标签',
      id: 'delete_tags@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '管理标签',
      codeName: 'mgr_tags',
      frontAppViewId: 'crmweb.tag_mgr_grid_view',
      frontProcessType: 'TOP',
      fullCodeName: 'deal_mgr_tags',
      navigateContexts: [
        {
          key: 'OWNER_TYPE',
          value: 'DEAL',
          rawValue: true,
          name: 'OWNER_TYPE',
          id: 'owner_type',
        },
      ],
      navigateParams: [
        {
          key: 'owner_type',
          value: 'DEAL',
          rawValue: true,
          id: 'owner_type',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'mgr_tags',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '管理标签',
      id: 'mgr_tags@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '商机',
      codeName: 'openDealZsjView',
      frontAppViewId: 'crmweb.deal_main_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'deal_openDealZsjView',
      uiactionMode: 'FRONT',
      uiactionTag: 'openDealZsjView',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '打开商机主数据视图',
      id: 'opendealzsjview@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'open_edit_view',
      dataAccessAction: 'UPDATE',
      frontAppViewId: 'crmweb.deal_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'deal_open_edit_view',
      deopprivId: 'update',
      sysImage: {
        cssClass: 'fa fa-pencil',
        glyph: 'xf040@FontAwesome',
      },
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit_view',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '编辑',
      id: 'open_edit_view@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加',
      codeName: 'open_relation_view',
      frontAppViewId: 'crmweb.task_deal_re_mpick_up_view',
      fullCodeName: 'deal_open_relation_view',
      appDEMethodId: 'relate_task_and_maneuver',
      sysImage: {
        cssClass: 'fa fa-link',
        glyph: 'xf0c1@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '关联成功',
      timeout: 60000,
      tooltip: '添加',
      uiactionMode: 'BACKEND',
      uiactionTag: 'open_relation_view',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '打开关联活动任务视图',
      id: 'open_relation_view@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'remove',
      confirmMsg: '确定要删除所选的记录吗？',
      dataAccessAction: 'DELETE',
      fullCodeName: 'deal_remove',
      appDEMethodId: 'remove',
      deopprivId: 'delete',
      sysImage: {
        cssClass: 'fa fa-remove',
        glyph: 'xf00d@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 1,
      appDataEntityId: 'crmweb.deal',
      name: '删除',
      id: 'remove@deal',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '上传',
      codeName: 'upload_attachment',
      frontProcessType: 'OTHER',
      fullCodeName: 'deal_upload_attachment',
      sysPFPluginId: 'file_upload',
      uiactionMode: 'FRONT',
      uiactionTag: 'upload_attachment',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.deal',
      name: '上传附件',
      id: 'upload_attachment@deal',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'add_attachment',
      defaultParamName: 'Default',
      logicName: '添加附件',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: '// 计算新建默认值\r\nconst defaultData = uiLogic.grid.calcDefaultValue({}, true);\r\nuiLogic.attach = uiLogic.files.map(item => \r\n    {\r\n        return {\r\n            name: item.name,\r\n            file_id: item.id,\r\n            id: item.uuid,\r\n            ...defaultData,\r\n        }\r\n    }\r\n)',
          codeName: 'RAWJSCODE4',
          leftPos: 780,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke2',
              srcDEUILogicNodeId: 'rawjscode4',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '设置附件参数',
          id: 'rawjscode4',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 553,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode4',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'grid',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'details.attachments.mdController',
              srcDEUILogicParamId: 'form',
              srcValueType: 'SRCDLPARAM',
              name: 'form[details.attachments.mdController] ==> grid',
              id: 'form[details.attachments.mdcontroller] ==> grid',
            },
          ],
          topPos: 208,
          name: '绑定表格部件',
          id: 'preparejsparam1',
        },
        {
          invokeCtrlId: 'grid',
          invokeMethod: 'addAttachMent',
          invokeParamId: 'attach',
          codeName: 'VIEWCTRLINVOKE2',
          leftPos: 989,
          logicNodeType: 'VIEWCTRLINVOKE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlinvoke2',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '视图部件调用',
          id: 'viewctrlinvoke2',
        },
        {
          codeName: 'END1',
          leftPos: 1167,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
        {
          dstAppDEUIActionId: 'upload_attachment@deal',
          dstAppDataEntityId: 'crmweb.deal',
          codeName: 'DEUIACTION1',
          dstDEUILogicParamId: 'files',
          leftPos: 309,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'deuiaction1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '界面行为',
          id: 'deuiaction1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'form',
          ctrlParam: true,
          name: '表单',
          id: 'form',
        },
        {
          codeName: 'files',
          entityListParam: true,
          name: '上传文件',
          id: 'files',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '重复器表格',
          id: 'grid',
        },
        {
          codeName: 'attach',
          entityListParam: true,
          name: '附件',
          id: 'attach',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '添加附件',
      id: 'add_attachment',
    },
    {
      codeName: 'all_deal_with_query',
      defaultParamName: 'Default',
      logicName: '导航（全部商机含查询条件）',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 60,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '全部数据',
            },
          ],
          topPos: 12,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'END1',
          leftPos: 1091,
          logicNodeType: 'END',
          topPos: 12,
          name: '结束',
          id: 'end1',
        },
        {
          eventName: 'onNavViewChange',
          eventParamId: 'viewmsg',
          fireCtrlId: 'chartexpbar',
          codeName: 'VIEWCTRLFIREEVENT1',
          leftPos: 468,
          logicNodeType: 'VIEWCTRLFIREEVENT',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlfireevent1',
              id: '连接名称',
            },
          ],
          topPos: 20,
          name: '视图部件事件触发',
          id: 'viewctrlfireevent1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 230,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlfireevent1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'viewId',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'crmweb.deal_exp_grid_view',
              srcValueType: 'SRCVALUE',
              name: '直接值[crmweb.deal_exp_grid...] ==> viewmsg[viewId]',
              id: '直接值[crmweb.deal_exp_grid...] ==> viewmsg[viewid]',
            },
            {
              dstFieldName: 'key',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[id] ==> viewmsg[key]',
            },
            {
              dstFieldName: 'context',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'context',
              srcDEUILogicParamId: 'chartexpbar_chart',
              srcValueType: 'SRCDLPARAM',
              id: 'chartexpbar_chart[context] ==> viewmsg[context]',
            },
            {
              dstFieldName: 'params',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'params',
              srcDEUILogicParamId: 'chartexpbar_chart',
              srcValueType: 'SRCDLPARAM',
              id: 'chartexpbar_chart[params] ==> viewmsg[params]',
            },
            {
              dstFieldName: 'isCache',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'false',
              srcValueType: 'SRCVALUE',
              name: '直接值[false] ==> viewmsg[isCache]',
              id: '直接值[false] ==> viewmsg[iscache]',
            },
            {
              dstFieldName: 'navViewMsg',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcDEUILogicParamId: 'viewmsg',
              srcValueType: 'SRCDLPARAM',
              name: 'viewmsg ==> viewmsg[navViewMsg]',
              id: 'viewmsg ==> viewmsg[navviewmsg]',
            },
          ],
          topPos: 20,
          name: '准备视图参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'chartexpbar',
          ctrlParam: true,
          name: '图表导航栏',
          id: 'chartexpbar',
        },
        {
          codeName: 'chartexpbar_chart',
          ctrlParam: true,
          name: '图表',
          id: 'chartexpbar_chart',
        },
        {
          codeName: 'viewmsg',
          entityParam: true,
          name: '视图信息',
          id: 'viewmsg',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '导航（全部商机含查询条件）',
      id: 'all_deal_with_query',
    },
    {
      codeName: 'exp_to_gridview',
      defaultParamName: 'Default',
      logicName: '导航到表格视图（图表导航）',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 50,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'state.items',
                    dstLogicParamId: 'chartexpbar_chart',
                    logicType: 'SINGLE',
                    name: 'chartexpbar_chart[state.items] 值为空(Nil)',
                    id: 'chartexpbar_chart[state.items] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '无数据时导航',
            },
          ],
          topPos: 20,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          eventName: 'onNavViewChange',
          eventParamId: 'viewmsg',
          fireCtrlId: 'chartexpbar',
          codeName: 'VIEWCTRLFIREEVENT1',
          leftPos: 468,
          logicNodeType: 'VIEWCTRLFIREEVENT',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlfireevent1',
              id: '连接名称',
            },
          ],
          topPos: 20,
          name: '视图部件事件触发',
          id: 'viewctrlfireevent1',
        },
        {
          codeName: 'END1',
          leftPos: 1091,
          logicNodeType: 'END',
          topPos: 12,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 230,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlfireevent1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'viewId',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'crmweb.deal_exp_grid_view',
              srcValueType: 'SRCVALUE',
              name: '直接值[crmweb.deal_exp_grid...] ==> viewmsg[viewId]',
              id: '直接值[crmweb.deal_exp_grid...] ==> viewmsg[viewid]',
            },
            {
              dstFieldName: 'key',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[id] ==> viewmsg[key]',
            },
            {
              dstFieldName: 'context',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'context',
              srcDEUILogicParamId: 'chartexpbar_chart',
              srcValueType: 'SRCDLPARAM',
              id: 'chartexpbar_chart[context] ==> viewmsg[context]',
            },
            {
              dstFieldName: 'params',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'params',
              srcDEUILogicParamId: 'chartexpbar_chart',
              srcValueType: 'SRCDLPARAM',
              id: 'chartexpbar_chart[params] ==> viewmsg[params]',
            },
            {
              dstFieldName: 'isCache',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'false',
              srcValueType: 'SRCVALUE',
              name: '直接值[false] ==> viewmsg[isCache]',
              id: '直接值[false] ==> viewmsg[iscache]',
            },
            {
              dstFieldName: 'navViewMsg',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcDEUILogicParamId: 'viewmsg',
              srcValueType: 'SRCDLPARAM',
              name: 'viewmsg ==> viewmsg[navViewMsg]',
              id: 'viewmsg ==> viewmsg[navviewmsg]',
            },
          ],
          topPos: 20,
          name: '准备视图参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'chartexpbar',
          ctrlParam: true,
          name: '图表导航栏',
          id: 'chartexpbar',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'viewmsg',
          entityParam: true,
          name: '视图信息',
          id: 'viewmsg',
        },
        {
          codeName: 'chartexpbar_chart',
          ctrlParam: true,
          name: '图表',
          id: 'chartexpbar_chart',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '导航到表格视图（图表导航）',
      id: 'exp_to_gridview',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'deal',
  deapicodeName: 'deal',
  deapicodeName2: 'deals',
  deapitag: 'DEAL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'dataimport',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '商机',
  majorAppDEFieldId: 'deal_name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'deals',
      majorAppDataEntityId: 'crmweb.account',
      parentAppDEFieldId: 'account_id',
      parentTextAppDEFieldId: 'account_name',
      rsmode: 2,
      name: 'DER1N_DEAL_ACCOUNT_ACCOUNT_ID',
      id: 'deals',
    },
  ],
  quickSearchAppDEFieldIds: ['deal_name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'DEAL',
  id: 'crmweb.deal',
  codeName2: 'deals',
  requestPaths: ['accounts/${account}/deals/${deal}'],
};
