export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'subject',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'crmweb.lead',
      textAppDEFieldId: 'subject',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'DataImport',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '跟踪人',
          appDEFieldId: 'executors',
          name: 'EXECUTORS',
          id: 'executors',
        },
        {
          caption: '客户名称',
          appDEFieldId: 'account_name',
          name: 'ACCOUNT_NAME',
          id: 'account_name',
        },
        {
          caption: '父线索',
          appDEFieldId: 'pname',
          name: 'PNAME',
          id: 'pname',
        },
        {
          caption: '是否已删除',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'is_deleted',
          name: 'IS_DELETED',
          id: 'is_deleted',
        },
        {
          caption: '最近评估时间',
          appDEFieldId: 'last_assess_time',
          name: 'LAST_ASSESS_TIME',
          id: 'last_assess_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'create_man',
          name: 'CREATE_MAN',
          id: 'create_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          appDEFieldId: 'name',
          name: 'NAME',
          id: 'name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'update_man',
          name: 'UPDATE_MAN',
          id: 'update_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          appDEFieldId: 'create_time',
          name: 'CREATE_TIME',
          id: 'create_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          appDEFieldId: 'update_time',
          name: 'UPDATE_TIME',
          id: 'update_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CITY',
          },
          caption: '城市',
          appDEFieldId: 'city',
          name: 'CITY',
          id: 'city',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.STATE',
          },
          caption: '省/市',
          appDEFieldId: 'state',
          name: 'STATE',
          id: 'state',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.COMPANY',
          },
          caption: '公司',
          appDEFieldId: 'company',
          name: 'COMPANY',
          id: 'company',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.FIRST_NAME',
          },
          caption: '名字',
          appDEFieldId: 'first_name',
          name: 'FIRST_NAME',
          id: 'first_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.STREET',
          },
          caption: '街道',
          appDEFieldId: 'street',
          name: 'STREET',
          id: 'street',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.FULL_NAME',
          },
          caption: '联系人姓名',
          appDEFieldId: 'full_name',
          name: 'FULL_NAME',
          id: 'full_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DESIGNATION',
          },
          caption: '职位/职称',
          appDEFieldId: 'designation',
          name: 'DESIGNATION',
          id: 'designation',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LAST_NAME',
          },
          caption: '姓氏',
          appDEFieldId: 'last_name',
          name: 'LAST_NAME',
          id: 'last_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.COUNTRY',
          },
          caption: '国家/地区',
          appDEFieldId: 'country',
          name: 'COUNTRY',
          id: 'country',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.EMAIL',
          },
          caption: '电子邮件',
          appDEFieldId: 'email',
          name: 'EMAIL',
          id: 'email',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ZIP_CODE',
          },
          caption: '邮编',
          appDEFieldId: 'zip_code',
          name: 'ZIP_CODE',
          id: 'zip_code',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.MOBILE',
          },
          caption: '手机',
          appDEFieldId: 'mobile',
          name: 'MOBILE',
          id: 'mobile',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ANNUALREVENUE',
          },
          caption: '年收入',
          appDEFieldId: 'annual_revenue',
          name: 'ANNUALREVENUE',
          id: 'annualrevenue',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LEAD_STATUS',
          },
          caption: '线索状态',
          codeListId: 'crmweb.crm__lead_status',
          appDEFieldId: 'lead_status',
          name: 'LEAD_STATUS',
          id: 'lead_status',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NO_OF_EMPLOYEES',
          },
          caption: '员工数',
          appDEFieldId: 'no_of_employees',
          name: 'NO_OF_EMPLOYEES',
          id: 'no_of_employees',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LEAD_SOURCE',
          },
          caption: '线索来源',
          codeListId: 'crmweb.crm__lead_source',
          appDEFieldId: 'lead_source',
          name: 'LEAD_SOURCE',
          id: 'lead_source',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.LEAD_CONVERSION_TIME',
          },
          caption: '线索转换用时',
          appDEFieldId: 'lead_conversion_time',
          name: 'LEAD_CONVERSION_TIME',
          id: 'lead_conversion_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SECONDARY_EMAIL',
          },
          caption: '备用邮箱',
          appDEFieldId: 'secondary_email',
          name: 'SECONDARY_EMAIL',
          id: 'secondary_email',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.EMAIL_OPT_OUT',
          },
          caption: '不发营销邮件',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'email_opt_out',
          name: 'EMAIL_OPT_OUT',
          id: 'email_opt_out',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UNSUBSCRIBED_MODE',
          },
          caption: '退订的方式',
          appDEFieldId: 'unsubscribed_mode',
          name: 'UNSUBSCRIBED_MODE',
          id: 'unsubscribed_mode',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SALUTATION',
          },
          caption: '称呼',
          appDEFieldId: 'salutation',
          name: 'SALUTATION',
          id: 'salutation',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CONVERTED_DATE_TIME',
          },
          caption: '转换的日期时间',
          appDEFieldId: 'converted_date_time',
          name: 'CONVERTED_DATE_TIME',
          id: 'converted_date_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UNSUBSCRIBED_TIME',
          },
          caption: '退订的时间',
          appDEFieldId: 'unsubscribed_time',
          name: 'UNSUBSCRIBED_TIME',
          id: 'unsubscribed_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SKYPE_ID',
          },
          caption: 'Skype lD',
          appDEFieldId: 'skype_id',
          name: 'SKYPE_ID',
          id: 'skype_id',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ENRICH_STATUS_S',
          },
          caption: '充实状态',
          appDEFieldId: 'enrich_status_s',
          name: 'ENRICH_STATUS_S',
          id: 'enrich_status_s',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CONVERTED__S',
          },
          caption: '为“已转换”',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'converted_s',
          name: 'CONVERTED__S',
          id: 'converted__s',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          appDEFieldId: 'id',
          name: 'ID',
          id: 'id',
        },
        {
          caption: '附件',
          appDEFieldId: 'attachments',
          name: 'ATTACHMENTS',
          id: 'attachments',
        },
        {
          caption: '所有者',
          codeListId: 'crmweb.crm__owner',
          appDEFieldId: 'owner',
          name: 'OWNER',
          id: 'owner',
        },
        {
          caption: '描述',
          appDEFieldId: 'description',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.SUBJECT',
          },
          caption: '主题',
          appDEFieldId: 'subject',
          name: 'SUBJECT',
          id: 'subject',
        },
        {
          caption: '客户标识',
          appDEFieldId: 'account_id',
          name: 'ACCOUNT_ID',
          id: 'account_id',
        },
        {
          caption: '父线索标识',
          appDEFieldId: 'pid',
          name: 'PID',
          id: 'pid',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '导入线索',
      id: 'dataimport',
    },
  ],
  appDEFields: [
    {
      codeName: 'executors',
      logicName: '跟踪人',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'EXECUTORS',
      id: 'executors',
    },
    {
      codeName: 'account_name',
      logicName: '客户名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACCOUNT_NAME',
      id: 'account_name',
    },
    {
      codeName: 'pname',
      logicName: '父线索',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'PNAME',
      id: 'pname',
    },
    {
      codeName: 'is_deleted',
      logicName: '是否已删除',
      predefinedType: 'LOGICVALID',
      stdDataType: 9,
      name: 'IS_DELETED',
      id: 'is_deleted',
    },
    {
      codeName: 'last_assess_time',
      logicName: '最近评估时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'LAST_ASSESS_TIME',
      id: 'last_assess_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'city',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CITY',
      },
      logicName: '城市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CITY',
      id: 'city',
    },
    {
      codeName: 'state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.STATE',
      },
      logicName: '省/市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'company',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.COMPANY',
      },
      logicName: '公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'COMPANY',
      id: 'company',
    },
    {
      codeName: 'first_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FIRST_NAME',
      },
      logicName: '名字',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 40,
      name: 'FIRST_NAME',
      id: 'first_name',
    },
    {
      codeName: 'street',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.STREET',
      },
      logicName: '街道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'STREET',
      id: 'street',
    },
    {
      codeName: 'full_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.FULL_NAME',
      },
      logicName: '联系人姓名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 120,
      name: 'FULL_NAME',
      id: 'full_name',
    },
    {
      codeName: 'designation',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DESIGNATION',
      },
      logicName: '职位/职称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'DESIGNATION',
      id: 'designation',
    },
    {
      codeName: 'last_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LAST_NAME',
      },
      logicName: '姓氏',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 80,
      name: 'LAST_NAME',
      id: 'last_name',
    },
    {
      codeName: 'country',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.COUNTRY',
      },
      logicName: '国家/地区',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COUNTRY',
      id: 'country',
    },
    {
      codeName: 'email',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.EMAIL',
      },
      logicName: '电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EMAIL',
      id: 'email',
    },
    {
      codeName: 'zip_code',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ZIP_CODE',
      },
      logicName: '邮编',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'ZIP_CODE',
      id: 'zip_code',
    },
    {
      codeName: 'mobile',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MOBILE',
      },
      logicName: '手机',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MOBILE',
      id: 'mobile',
    },
    {
      codeName: 'annual_revenue',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ANNUALREVENUE',
      },
      logicName: '年收入',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ANNUALREVENUE',
      id: 'annual_revenue',
    },
    {
      codeName: 'lead_status',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LEAD_STATUS',
      },
      logicName: '线索状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'LEAD_STATUS',
      id: 'lead_status',
    },
    {
      codeName: 'no_of_employees',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NO_OF_EMPLOYEES',
      },
      logicName: '员工数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'NO_OF_EMPLOYEES',
      id: 'no_of_employees',
    },
    {
      codeName: 'lead_source',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LEAD_SOURCE',
      },
      logicName: '线索来源',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'LEAD_SOURCE',
      id: 'lead_source',
    },
    {
      codeName: 'lead_conversion_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.LEAD_CONVERSION_TIME',
      },
      logicName: '线索转换用时',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LEAD_CONVERSION_TIME',
      id: 'lead_conversion_time',
    },
    {
      codeName: 'secondary_email',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SECONDARY_EMAIL',
      },
      logicName: '备用邮箱',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SECONDARY_EMAIL',
      id: 'secondary_email',
    },
    {
      codeName: 'email_opt_out',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.EMAIL_OPT_OUT',
      },
      logicName: '不发营销邮件',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'EMAIL_OPT_OUT',
      id: 'email_opt_out',
    },
    {
      codeName: 'unsubscribed_mode',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UNSUBSCRIBED_MODE',
      },
      logicName: '退订的方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'UNSUBSCRIBED_MODE',
      id: 'unsubscribed_mode',
    },
    {
      codeName: 'salutation',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SALUTATION',
      },
      logicName: '称呼',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SALUTATION',
      id: 'salutation',
    },
    {
      codeName: 'converted_date_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CONVERTED_DATE_TIME',
      },
      logicName: '转换的日期时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CONVERTED_DATE_TIME',
      id: 'converted_date_time',
    },
    {
      codeName: 'unsubscribed_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UNSUBSCRIBED_TIME',
      },
      logicName: '退订的时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UNSUBSCRIBED_TIME',
      id: 'unsubscribed_time',
    },
    {
      codeName: 'skype_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SKYPE_ID',
      },
      logicName: 'Skype lD',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'SKYPE_ID',
      id: 'skype_id',
    },
    {
      codeName: 'enrich_status_s',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ENRICH_STATUS_S',
      },
      logicName: '充实状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ENRICH_STATUS_S',
      id: 'enrich_status_s',
    },
    {
      codeName: 'converted_s',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CONVERTED__S',
      },
      logicName: '为“已转换”',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CONVERTED__S',
      id: 'converted_s',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'attachments',
      logicName: '附件',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'owner',
      logicName: '所有者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'OWNER',
      id: 'owner',
    },
    {
      codeName: 'description',
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'subject',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SUBJECT',
      },
      logicName: '主题',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      enableQuickSearch: true,
      name: 'SUBJECT',
      id: 'subject',
    },
    {
      codeName: 'account_id',
      logicName: '客户标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACCOUNT_ID',
      id: 'account_id',
    },
    {
      codeName: 'pid',
      logicName: '父线索标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PID',
      id: 'pid',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'lead_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'executors',
          logicName: '跟踪人',
          appDEFieldId: 'executors',
          refAppDEMethodDTOId: 'executor_dto',
          refAppDataEntityId: 'crmweb.executor',
          refPickupAppDEFieldId: 'principal_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'executors',
        },
        {
          codeName: 'account_name',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'account_name',
        },
        {
          codeName: 'pname',
          logicName: '父线索',
          appDEFieldId: 'pname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'pname',
        },
        {
          codeName: 'last_assess_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '最近评估时间',
          appDEFieldId: 'last_assess_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_assess_time',
        },
        {
          codeName: 'account_id',
          logicName: '客户标识',
          appDEFieldId: 'account_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'account_id',
        },
        {
          codeName: 'annual_revenue',
          logicName: '年收入',
          appDEFieldId: 'annual_revenue',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'annual_revenue',
        },
        {
          codeName: 'attachments',
          logicName: '附件',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'attachment_dto',
          refAppDataEntityId: 'crmweb.attachment',
          refPickupAppDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'city',
          logicName: '城市',
          appDEFieldId: 'city',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'city',
        },
        {
          codeName: 'company',
          logicName: '公司',
          appDEFieldId: 'company',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company',
        },
        {
          codeName: 'converted_date_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '转换的日期时间',
          appDEFieldId: 'converted_date_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'converted_date_time',
        },
        {
          codeName: 'converted_s',
          logicName: '为“已转换”',
          appDEFieldId: 'converted_s',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'converted_s',
        },
        {
          codeName: 'country',
          logicName: '国家/地区',
          appDEFieldId: 'country',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'country',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'designation',
          logicName: '职位/职称',
          appDEFieldId: 'designation',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'designation',
        },
        {
          codeName: 'email',
          logicName: '电子邮件',
          appDEFieldId: 'email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email',
        },
        {
          codeName: 'email_opt_out',
          logicName: '不发营销邮件',
          appDEFieldId: 'email_opt_out',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_opt_out',
        },
        {
          codeName: 'enrich_status_s',
          logicName: '充实状态',
          appDEFieldId: 'enrich_status_s',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'enrich_status_s',
        },
        {
          codeName: 'first_name',
          logicName: '名字',
          appDEFieldId: 'first_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'first_name',
        },
        {
          codeName: 'full_name',
          logicName: '联系人姓名',
          appDEFieldId: 'full_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'full_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'last_name',
          logicName: '姓氏',
          appDEFieldId: 'last_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_name',
        },
        {
          codeName: 'lead_conversion_time',
          logicName: '线索转换用时',
          appDEFieldId: 'lead_conversion_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lead_conversion_time',
        },
        {
          codeName: 'lead_source',
          logicName: '线索来源',
          appDEFieldId: 'lead_source',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lead_source',
        },
        {
          codeName: 'lead_status',
          logicName: '线索状态',
          appDEFieldId: 'lead_status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'lead_status',
        },
        {
          codeName: 'mobile',
          logicName: '手机',
          appDEFieldId: 'mobile',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mobile',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'no_of_employees',
          logicName: '员工数',
          appDEFieldId: 'no_of_employees',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'no_of_employees',
        },
        {
          codeName: 'owner',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner',
        },
        {
          codeName: 'pid',
          logicName: '父线索标识',
          appDEFieldId: 'pid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'pid',
        },
        {
          codeName: 'salutation',
          logicName: '称呼',
          appDEFieldId: 'salutation',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'salutation',
        },
        {
          codeName: 'secondary_email',
          logicName: '备用邮箱',
          appDEFieldId: 'secondary_email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'secondary_email',
        },
        {
          codeName: 'skype_id',
          logicName: 'Skype lD',
          appDEFieldId: 'skype_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'skype_id',
        },
        {
          codeName: 'state',
          logicName: '省/市',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'street',
          logicName: '街道',
          appDEFieldId: 'street',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'street',
        },
        {
          codeName: 'subject',
          logicName: '主题',
          appDEFieldId: 'subject',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'subject',
        },
        {
          codeName: 'unsubscribed_mode',
          logicName: '退订的方式',
          appDEFieldId: 'unsubscribed_mode',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'unsubscribed_mode',
        },
        {
          codeName: 'unsubscribed_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '退订的时间',
          appDEFieldId: 'unsubscribed_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'unsubscribed_time',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
        {
          codeName: 'zip_code',
          logicName: '邮编',
          appDEFieldId: 'zip_code',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'zip_code',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'lead_dto',
    },
    {
      codeName: 'lead_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_account_id_eq',
          logicName: '客户标识',
          appDEFieldId: 'account_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_id_eq',
        },
        {
          codeName: 'n_account_name_eq',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_name_eq',
        },
        {
          codeName: 'n_account_name_like',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_name_like',
        },
        {
          codeName: 'n_company_like',
          logicName: '公司',
          appDEFieldId: 'company',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_like',
        },
        {
          codeName: 'n_enrich_status_s_eq',
          logicName: '充实状态',
          appDEFieldId: 'enrich_status_s',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_enrich_status_s_eq',
        },
        {
          codeName: 'n_executors_exists_n_user_id_eq',
          logicName: '跟踪人',
          appDEFieldId: 'executors',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_executors_exists_n_user_id_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_last_name_like',
          logicName: '姓氏',
          appDEFieldId: 'last_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_last_name_like',
        },
        {
          codeName: 'n_lead_source_eq',
          logicName: '线索来源',
          appDEFieldId: 'lead_source',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lead_source_eq',
        },
        {
          codeName: 'n_lead_status_eq',
          logicName: '线索状态',
          appDEFieldId: 'lead_status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lead_status_eq',
        },
        {
          codeName: 'n_lead_status_noteq',
          logicName: '线索状态',
          appDEFieldId: 'lead_status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_lead_status_noteq',
        },
        {
          codeName: 'n_mobile_like',
          logicName: '手机',
          appDEFieldId: 'mobile',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mobile_like',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_owner_eq',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_owner_eq',
        },
        {
          codeName: 'n_pid_eq',
          logicName: '父线索标识',
          appDEFieldId: 'pid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_pid_eq',
        },
        {
          codeName: 'n_pname_eq',
          logicName: '父线索',
          appDEFieldId: 'pname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_pname_eq',
        },
        {
          codeName: 'n_pname_like',
          logicName: '父线索',
          appDEFieldId: 'pname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_pname_like',
        },
        {
          codeName: 'n_salutation_eq',
          logicName: '称呼',
          appDEFieldId: 'salutation',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_salutation_eq',
        },
        {
          codeName: 'n_subject_like',
          logicName: '主题',
          appDEFieldId: 'subject',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_subject_like',
        },
        {
          codeName: 'n_unsubscribed_mode_eq',
          logicName: '退订的方式',
          appDEFieldId: 'unsubscribed_mode',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_unsubscribed_mode_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'lead_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_leadto_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_leadto_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'addLeadtoWorkProgress',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'addLeadtoWorkProgress',
      id: 'add_leadto_work_progress',
    },
    {
      codeName: 'add_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_tags',
    },
    {
      codeName: 'async_add_leadto_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'ASYNCACTION',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/async_add_leadto_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'Async_addLeadtoWorkProgress',
      actionType: 'REMOTE',
      asyncAction: true,
      dataSetType: 'REMOTE',
      name: 'Async_addLeadtoWorkProgress',
      id: 'async_add_leadto_work_progress',
    },
    {
      codeName: 'batch_update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/batch_update',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'batch_update',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_task',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_task',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_task',
    },
    {
      codeName: 'delete_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete_tags',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'lead_to_be_deal',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/lead_to_be_deal',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'leadToBeDeal',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'leadToBeDeal',
      id: 'lead_to_be_deal',
    },
    {
      codeName: 'lead_to_deal',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/lead_to_deal',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'leadToDeal',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'leadToDeal',
      id: 'lead_to_deal',
    },
    {
      codeName: 'main_view_dr_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/main_view_dr_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'main_view_dr_count',
    },
    {
      codeName: 'relate_task_and_maneuver',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/relate_task_and_maneuver',
      needResourceKey: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'relate_task_and_maneuver',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_createman',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_createman',
      actionType: 'REMOTE',
      dataSetName: 'createman',
      dataSetTag: 'createman',
      dataSetType: 'REMOTE',
      id: 'fetch_createman',
    },
    {
      codeName: 'fetch_data_set2',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_data_set2',
      actionType: 'REMOTE',
      dataSetName: 'tree',
      dataSetTag: 'DataSet2',
      dataSetType: 'REMOTE',
      id: 'fetch_data_set2',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_executor',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_executor',
      actionType: 'REMOTE',
      dataSetName: 'executor',
      dataSetTag: 'executor',
      dataSetType: 'REMOTE',
      id: 'fetch_executor',
    },
    {
      codeName: 'fetch_lead_relation_task',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_lead_relation_task',
      actionType: 'REMOTE',
      dataSetName: 'lead_relation_task',
      dataSetTag: 'lead_relation_task',
      dataSetType: 'REMOTE',
      id: 'fetch_lead_relation_task',
    },
    {
      codeName: 'fetch_owner',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_owner',
      actionType: 'REMOTE',
      dataSetName: 'owner',
      dataSetTag: 'owner',
      dataSetType: 'REMOTE',
      id: 'fetch_owner',
    },
    {
      codeName: 'fetch_target_relation',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'lead_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'lead_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_target_relation',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'principal_id',
          fieldName: 'TARGET_ID',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(TARGET_ID) 等于(=) 数据上下文 principal_id',
          id: '(target_id) 等于(=) 数据上下文 principal_id',
        },
      ],
      dataSetName: 'target_relation',
      dataSetTag: 'target_relation',
      dataSetType: 'REMOTE',
      id: 'fetch_target_relation',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导入线索',
      codeName: 'ImportData',
      frontProcessType: 'DATAIMP',
      fullCodeName: 'lead_ImportData',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'ImportData',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEDataImportId: 'dataimport',
      appDataEntityId: 'crmweb.lead',
      name: '导入数据',
      id: 'importdata@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.SAVE',
      },
      caption: '保存',
      codeName: 'SaveAndOpenLead',
      dialogResult: 'OK',
      fullCodeName: 'lead_SaveAndOpenLead',
      nextId: 'openleadveiw@lead',
      appDEMethodId: 'create',
      sysImage: {
        cssClass: 'fa fa-save',
        glyph: 'xf0c7@FontAwesome',
      },
      refreshMode: 1,
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.SAVE',
      },
      uiactionMode: 'BACKEND',
      uiactionTag: 'SaveAndOpenLead',
      uiactionType: 'DEUIACTION',
      closeEditView: true,
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '保存并打开线索主信息界面',
      id: 'saveandopenlead@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加附件',
      codeName: 'add_attachments',
      frontProcessType: 'OTHER',
      fullCodeName: 'lead_add_attachments',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'add_attachments',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'add_attachment',
      appDataEntityId: 'crmweb.lead',
      name: '添加附件',
      id: 'add_attachments@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '添加标签',
      codeName: 'add_tags',
      frontAppViewId: 'crmweb.tag_add_tag',
      fullCodeName: 'lead_add_tags',
      appDEMethodId: 'add_tags',
      refreshMode: 1,
      successMsg: '已成功添加标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '添加标签',
      id: 'add_tags@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '批量更新',
      codeName: 'batch_update',
      fullCodeName: 'lead_batch_update',
      appDEMethodId: 'batch_update',
      refreshMode: 1,
      successMsg: '更新完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'batch_update',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '批量更新',
      id: 'batch_update@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '创建子线索',
      codeName: 'createSubLead',
      frontAppViewId: 'crmweb.lead_lead_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'lead_createSubLead',
      navigateContexts: [
        {
          key: 'ID',
          rawValue: true,
          name: 'ID',
          id: 'id',
        },
        {
          key: 'PNAME',
          value: 'subject',
          name: 'PNAME',
          id: 'pname',
        },
        {
          key: 'ACCOUNTID',
          value: 'account_id',
          name: 'ACCOUNTID',
          id: 'accountid',
        },
        {
          key: 'LEAD',
          rawValue: true,
          name: 'LEAD',
          id: 'lead',
        },
        {
          key: 'PID',
          value: 'id',
          name: 'PID',
          id: 'pid',
        },
        {
          key: 'ACCOUNTNAME',
          value: 'account_name',
          name: 'ACCOUNTNAME',
          id: 'accountname',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'createSubLead',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '创建子线索',
      id: 'createsublead@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '创建任务',
      codeName: 'create_task',
      frontAppViewId: 'crmweb.task_batch_create_view',
      fullCodeName: 'lead_create_task',
      appDEMethodId: 'create_task',
      successMsg: '创建完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'create_task',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '创建任务',
      id: 'create_task@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移除标签',
      codeName: 'delete_tags',
      frontAppViewId: 'crmweb.tag_remove_tag',
      fullCodeName: 'lead_delete_tags',
      appDEMethodId: 'delete_tags',
      refreshMode: 1,
      successMsg: '已成功移除标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '移除标签',
      id: 'delete_tags@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '商机主数据视图',
      codeName: 'leadOpenDealZsj',
      frontAppViewId: 'crmweb.deal_main_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'lead_leadOpenDealZsj',
      uiactionMode: 'FRONT',
      uiactionTag: 'leadOpenDealZsj',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '打开商机主数据视图',
      id: 'leadopendealzsj@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '派生商机',
      codeName: 'leadToBeDeal',
      frontAppViewId: 'crmweb.deal_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'lead_leadToBeDeal',
      appDEMethodId: 'lead_to_be_deal',
      navigateContexts: [
        {
          key: 'LEAD_SOURCE',
          value: 'LEAD_SOURCE',
          name: 'LEAD_SOURCE',
          id: 'lead_source',
        },
        {
          key: 'ACCOUNT_NAME',
          value: 'ACCOUNT_NAME',
          name: 'ACCOUNT_NAME',
          id: 'account_name',
        },
        {
          key: 'DEALNAME',
          value: 'SUBJECT',
          name: 'DEALNAME',
          id: 'dealname',
        },
        {
          key: 'DESCRIPTION',
          value: 'DESCRIPTION',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          key: 'ACCOUNT_ID',
          value: 'ACCOUNT_ID',
          name: 'ACCOUNT_ID',
          id: 'account_id',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-send-o',
        glyph: 'xf1d9@FontAwesome',
      },
      successMsg: '生成商机成功!',
      uiactionMode: 'FRONT',
      uiactionTag: 'leadToBeDeal',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '派生商机',
      id: 'leadtobedeal@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '线索转为商机',
      codeName: 'leadToDeal',
      confirmMsg: '是否确认将制定线索转为商机？一旦转换将无法回退！',
      dialogResult: 'OK',
      fullCodeName: 'lead_leadToDeal',
      nextId: 'leadopendealzsj@lead',
      appDEMethodId: 'lead_to_deal',
      navigateContexts: [
        {
          key: 'DEAL',
          value: 'id',
          name: 'DEAL',
          id: 'deal',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-retweet',
        glyph: 'xf079@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '转换为商机成功!',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'leadToDeal',
      uiactionType: 'DEUIACTION',
      closeEditView: true,
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '线索转为商机',
      id: 'leadtodeal@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '管理标签',
      codeName: 'mgr_tags',
      frontAppViewId: 'crmweb.tag_mgr_grid_view',
      frontProcessType: 'TOP',
      fullCodeName: 'lead_mgr_tags',
      navigateContexts: [
        {
          key: 'OWNER_TYPE',
          value: 'LEAD',
          rawValue: true,
          name: 'OWNER_TYPE',
          id: 'owner_type',
        },
      ],
      navigateParams: [
        {
          key: 'owner_type',
          value: 'LEAD',
          rawValue: true,
          id: 'owner_type',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'mgr_tags',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '管理标签',
      id: 'mgr_tags@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '线索详情',
      codeName: 'openLeadVeiw',
      frontAppViewId: 'crmweb.lead_main_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'lead_openLeadVeiw',
      uiactionMode: 'FRONT',
      uiactionTag: 'openLeadVeiw',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '打开线索主数据视图',
      id: 'openleadveiw@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'open_edit_view',
      frontAppViewId: 'crmweb.lead_lead_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'lead_open_edit_view',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit_view',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '编辑',
      id: 'open_edit_view@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加',
      codeName: 'open_relation_view',
      frontAppViewId: 'crmweb.task_lead_re_mpick_up_view',
      fullCodeName: 'lead_open_relation_view',
      appDEMethodId: 'relate_task_and_maneuver',
      sysImage: {
        cssClass: 'fa fa-link',
        glyph: 'xf0c1@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '关联成功',
      timeout: 60000,
      tooltip: '添加',
      uiactionMode: 'BACKEND',
      uiactionTag: 'open_relation_view',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '打开关联活动任务视图',
      id: 'open_relation_view@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'remove',
      confirmMsg: '确定要删除所选的记录吗？',
      fullCodeName: 'lead_remove',
      appDEMethodId: 'remove',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '删除',
      id: 'remove@lead',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '上传',
      codeName: 'upload_attachment',
      frontProcessType: 'OTHER',
      fullCodeName: 'lead_upload_attachment',
      sysPFPluginId: 'file_upload',
      uiactionMode: 'FRONT',
      uiactionTag: 'upload_attachment',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.lead',
      name: '上传附件',
      id: 'upload_attachment@lead',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'add_attachment',
      defaultParamName: 'Default',
      logicName: '添加附件',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          dstAppDEUIActionId: 'upload_attachment@lead',
          dstAppDataEntityId: 'crmweb.lead',
          codeName: 'DEUIACTION1',
          dstDEUILogicParamId: 'files',
          leftPos: 309,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'deuiaction1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '界面行为',
          id: 'deuiaction1',
        },
        {
          codeName: 'END1',
          leftPos: 1167,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
        {
          invokeCtrlId: 'grid',
          invokeMethod: 'addAttachMent',
          invokeParamId: 'attach',
          codeName: 'VIEWCTRLINVOKE2',
          leftPos: 989,
          logicNodeType: 'VIEWCTRLINVOKE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlinvoke2',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '视图部件调用',
          id: 'viewctrlinvoke2',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 553,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode4',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'grid',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'details.attachments.mdController',
              srcDEUILogicParamId: 'form',
              srcValueType: 'SRCDLPARAM',
              name: 'form[details.attachments.mdController] ==> grid',
              id: 'form[details.attachments.mdcontroller] ==> grid',
            },
          ],
          topPos: 208,
          name: '绑定表格部件',
          id: 'preparejsparam1',
        },
        {
          code: '// 计算新建默认值\r\nconst defaultData = uiLogic.grid.calcDefaultValue({}, true);\r\nuiLogic.attach = uiLogic.files.map(item => \r\n    {\r\n        return {\r\n            name: item.name,\r\n            file_id: item.id,\r\n            id: item.uuid,\r\n            ...defaultData,\r\n        }\r\n    }\r\n)',
          codeName: 'RAWJSCODE4',
          leftPos: 780,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke2',
              srcDEUILogicNodeId: 'rawjscode4',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '设置附件参数',
          id: 'rawjscode4',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'form',
          ctrlParam: true,
          name: '表单',
          id: 'form',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'files',
          entityListParam: true,
          name: '上传文件',
          id: 'files',
        },
        {
          codeName: 'attach',
          entityListParam: true,
          name: '附件',
          id: 'attach',
        },
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '重复器表格',
          id: 'grid',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '添加附件',
      id: 'add_attachment',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'lead',
  deapicodeName: 'lead',
  deapicodeName2: 'leads',
  deapitag: 'LEAD',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'dataimport',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '线索',
  majorAppDEFieldId: 'subject',
  quickSearchAppDEFieldIds: ['subject'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'LEAD',
  id: 'crmweb.lead',
  codeName2: 'leads',
  requestPaths: [],
};
