export default {
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'Default',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '内容',
          appDEFieldId: 'content',
          name: 'CONTENT',
          id: 'content',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '跟随主数据导入',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'principal_id',
      logicName: '备注主体标识',
      predefinedType: 'PARENTID',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      codeName: 'principal_name',
      logicName: '备注主体名称',
      predefinedType: 'PARENTNAME',
      stdDataType: 25,
      stringLength: 200,
      name: 'PRINCIPAL_NAME',
      id: 'principal_name',
    },
    {
      codeName: 'owner_type',
      logicName: '所属数据对象',
      predefinedType: 'PARENTTYPE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      codeName: 'principal_type',
      logicName: '备注主体类型',
      predefinedType: 'PARENTSUBTYPE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
    {
      codeName: 'content',
      logicName: '内容',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CONTENT',
      id: 'content',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'note_attach_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'principal_id',
          logicName: '备注主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_id',
        },
        {
          codeName: 'principal_name',
          logicName: '备注主体名称',
          appDEFieldId: 'principal_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_name',
        },
        {
          codeName: 'owner_type',
          logicName: '所属数据对象',
          appDEFieldId: 'owner_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_type',
        },
        {
          codeName: 'principal_type',
          logicName: '备注主体类型',
          appDEFieldId: 'principal_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_type',
        },
        {
          codeName: 'content',
          logicName: '内容',
          appDEFieldId: 'content',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'content',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'note_attach_dto',
    },
    {
      codeName: 'note_attach_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_owner_type_eq',
          logicName: '所属数据对象',
          appDEFieldId: 'owner_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_owner_type_eq',
        },
        {
          codeName: 'n_principal_id_eq',
          logicName: '备注主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_principal_id_eq',
        },
        {
          codeName: 'n_principal_type_eq',
          logicName: '备注主体类型',
          appDEFieldId: 'principal_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_principal_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'note_attach_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'async_evaluate_to_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'ASYNCACTION',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/async_evaluate_to_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'Async_evaluateToWorkProgress',
      actionType: 'REMOTE',
      asyncAction: true,
      dataSetType: 'REMOTE',
      name: 'Async_evaluateToWorkProgress',
      id: 'async_evaluate_to_work_progress',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'evaluate_to_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/evaluate_to_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'evaluateToWorkProgress',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'evaluateToWorkProgress',
      id: 'evaluate_to_work_progress',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_by_owner',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_by_owner',
      actionType: 'REMOTE',
      dataSetName: 'ByOwner',
      dataSetTag: 'ByOwner',
      dataSetType: 'REMOTE',
      id: 'fetch_by_owner',
    },
    {
      codeName: 'fetch_createman',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_createman',
      actionType: 'REMOTE',
      dataSetName: 'createman',
      dataSetTag: 'createman',
      dataSetType: 'REMOTE',
      id: 'fetch_createman',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'note_attach_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'note_attach_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '清空',
      codeName: 'clear_comment',
      frontProcessType: 'OTHER',
      fullCodeName: 'note_attach_clear_comment',
      scriptCode: "console.log('清空评论')",
      uiactionMode: 'FRONT',
      uiactionTag: 'clear_comment',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'clear_comment',
      appDataEntityId: 'crmweb.note_attach',
      name: '清空评论',
      id: 'clear_comment@note_attach',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除评论',
      codeName: 'del_comment',
      confirmMsg: '确认删除该评论？',
      fullCodeName: 'note_attach_del_comment',
      appDEMethodId: 'remove',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'del_comment',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.note_attach',
      name: '删除评论',
      id: 'del_comment@note_attach',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导入备注',
      codeName: 'import',
      frontProcessType: 'DATAIMP',
      fullCodeName: 'note_attach_import',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'import',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEDataImportId: 'default',
      appDataEntityId: 'crmweb.note_attach',
      name: '导入备注',
      id: 'import@note_attach',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'panel_note_attach_list_button_calluilogic1_click',
      frontProcessType: 'OTHER',
      fullCodeName:
        'note_attach_panel_note_attach_list_button_calluilogic1_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_note_attach_list_button_calluilogic1_click',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      uilogicType: 'DELOGIC',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'edit_note',
      appDataEntityId: 'crmweb.note_attach',
      name: '编辑',
      id: 'panel_note_attach_list_button_calluilogic1_click@note_attach',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '发送评论',
      codeName: 'send_comment',
      frontProcessType: 'OTHER',
      fullCodeName: 'note_attach_send_comment',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'send_comment',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'send_comment',
      appDataEntityId: 'crmweb.note_attach',
      name: '发送评论',
      id: 'send_comment@note_attach',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'clear_comment',
      defaultParamName: 'Default',
      logicName: '清空评论',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 230,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 260,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'uiLogic.view.layoutPanel.panelItems.field_textbox.editor.clear();\r\nuiLogic.view.edit_comment_id = null;\r\nuiLogic.view.reply_comment_id = null;',
          codeName: 'RAWJSCODE1',
          leftPos: 190,
          logicNodeType: 'RAWJSCODE',
          topPos: 470,
          name: '注入脚本代码',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '清空评论',
      id: 'clear_comment',
    },
    {
      codeName: 'edit_note',
      defaultParamName: 'Default',
      logicName: '编辑备注',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'content',
                    dstLogicParamId: 'default',
                    logicType: 'SINGLE',
                    name: 'Default[content] 值不为空(NotNil)',
                    id: 'default[content] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '无评论内容时不执行',
            },
          ],
          topPos: 200,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'parentview',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'parentView',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[parentView] ==> parentView',
              id: 'view[parentview] ==> parentview',
            },
            {
              dstFieldName: 'reply_comment_id',
              dstDEUILogicParamId: 'parentview',
              paramAction: 'SETPARAMVALUE',
              srcValueType: 'NULLVALUE',
              name: '空值（NULL） ==> parentView[reply_comment_id]',
              id: '空值（null） ==> parentview[reply_comment_id]',
            },
            {
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.field_textbox.editor',
              srcDEUILogicParamId: 'parentview',
              srcValueType: 'SRCDLPARAM',
              name: 'parentView[layoutPanel.panelItems.field_textbox.editor] ==> comment',
              id: 'parentview[layoutpanel.panelitems.field_textbox.editor] ==> comment',
            },
            {
              dstFieldName: 'edit_comment_id',
              dstDEUILogicParamId: 'parentview',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'id',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default[id] ==> parentView[edit_comment_id]',
              id: 'default[id] ==> parentview[edit_comment_id]',
            },
          ],
          topPos: 340,
          name: '设置评论id',
          id: 'preparejsparam1',
        },
        {
          code: 'uiLogic.comment.toggleCollapse(true);\r\nuiLogic.comment.setValue(uiLogic.default.content);\r\nuiLogic.comment.reply.value = null;',
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          topPos: 480,
          name: '展开评论输入框并设值',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'parentView',
          entityParam: true,
          name: '父视图对象',
          id: 'parentview',
        },
        {
          codeName: 'comment',
          entityParam: true,
          name: '评论对象',
          id: 'comment',
        },
        {
          codeName: 'comment_id',
          entityParam: true,
          name: '评论id存储对象',
          id: 'comment_id',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '编辑备注',
      id: 'edit_note',
    },
    {
      codeName: 'note_icon_hidden',
      defaultParamName: 'Default',
      logicName: '控制备注按钮隐藏',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: -30,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'view',
          leftPos: 72,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 8,
          name: '隐藏按钮的逻辑',
          id: 'debugparam1',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 500,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicNodeParams: [
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'send',
              expression: 'view.layoutPanel.panelItems.field_textbox.value',
              paramAction: 'SETPARAMVALUE',
              srcFieldName:
                'layoutPanel.panelItems.field_textbox.value?true:false',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.value?true:false] ==> send[visible]',
              id: 'view[layoutpanel.panelitems.field_textbox.value?true:false] ==> send[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'reset',
              expression: 'view.layoutPanel.panelItems.field_textbox.value',
              paramAction: 'SETPARAMVALUE',
              srcFieldName:
                'layoutPanel.panelItems.field_textbox.value?true:false',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.value?true:false] ==> reset[visible]',
              id: 'view[layoutpanel.panelitems.field_textbox.value?true:false] ==> reset[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'icon',
              expression: '!view.layoutPanel.panelItems.field_textbox.value',
              paramAction: 'SETPARAMVALUE',
              srcFieldName:
                'layoutPanel.panelItems.field_textbox.value?false:true',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.value?false:true] ==> icon[visible]',
              id: 'view[layoutpanel.panelitems.field_textbox.value?false:true] ==> icon[visible]',
            },
          ],
          topPos: 8,
          name: '准备参数',
          id: 'preparejsparam2',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 260,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'send',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_send.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_send.state] ==> send',
              id: 'view[layoutpanel.panelitems.comment_send.state] ==> send',
            },
            {
              dstDEUILogicParamId: 'reset',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_cancel.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_cancel.state] ==> reset',
              id: 'view[layoutpanel.panelitems.comment_cancel.state] ==> reset',
            },
            {
              dstDEUILogicParamId: 'icon',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_icon.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_icon.state] ==> icon',
              id: 'view[layoutpanel.panelitems.comment_icon.state] ==> icon',
            },
          ],
          topPos: 8,
          name: '准备参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'reset',
          entityParam: true,
          name: '清空',
          id: 'reset',
        },
        {
          codeName: 'send',
          entityParam: true,
          name: '评论',
          id: 'send',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'icon',
          entityParam: true,
          name: '图标',
          id: 'icon',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '控制备注按钮隐藏',
      id: 'note_icon_hidden',
    },
    {
      codeName: 'note_icon_show',
      defaultParamName: 'Default',
      logicName: '控制备注按钮显示',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 140,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 378,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'send',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_send.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_send.state] ==> send',
              id: 'view[layoutpanel.panelitems.comment_send.state] ==> send',
            },
            {
              dstDEUILogicParamId: 'reset',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_cancel.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_cancel.state] ==> reset',
              id: 'view[layoutpanel.panelitems.comment_cancel.state] ==> reset',
            },
            {
              dstDEUILogicParamId: 'icon',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_icon.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_icon.state] ==> icon',
              id: 'view[layoutpanel.panelitems.comment_icon.state] ==> icon',
            },
          ],
          topPos: 208,
          name: '准备参数',
          id: 'preparejsparam1',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 582,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicNodeParams: [
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'send',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'true',
              srcValueType: 'SRCVALUE',
              id: '直接值[true] ==> send[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'reset',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'true',
              srcValueType: 'SRCVALUE',
              id: '直接值[true] ==> reset[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'icon',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'false',
              srcValueType: 'SRCVALUE',
              id: '直接值[false] ==> icon[visible]',
            },
          ],
          topPos: 208,
          name: '准备参数',
          id: 'preparejsparam2',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'view',
          leftPos: 206,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '按钮显示逻辑',
          id: 'debugparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'icon',
          entityParam: true,
          name: '图标',
          id: 'icon',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'send',
          entityParam: true,
          name: '评论',
          id: 'send',
        },
        {
          codeName: 'reset',
          entityParam: true,
          name: '清空',
          id: 'reset',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '控制备注按钮显示',
      id: 'note_icon_show',
    },
    {
      codeName: 'send_comment',
      defaultParamName: 'Default',
      logicName: '发送评论',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam2',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 100,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'END1',
          leftPos: 220,
          logicNodeType: 'END',
          topPos: 1030,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'PREPAREJSPARAM3',
          leftPos: 310,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction3',
              srcDEUILogicNodeId: 'preparejsparam3',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'id',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'edit_comment_id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[edit_comment_id] ==> comment[id]',
            },
            {
              dstFieldName: 'comment',
              dstDEUILogicParamId: 'ctx',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'edit_comment_id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[edit_comment_id] ==> ctx[comment]',
            },
          ],
          topPos: 690,
          name: '设置评论id',
          id: 'preparejsparam3',
        },
        {
          dstAppDEActionId: 'save',
          dstAppDataEntityId: 'crmweb.note_attach',
          codeName: 'DEACTION3',
          dstDEUILogicParamId: 'comment',
          leftPos: 310,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'deaction3',
              id: '连接名称',
            },
          ],
          topPos: 830,
          name: 'Save',
          id: 'deaction3',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'view',
          leftPos: 320,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction2',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'edit_comment_id',
                    dstLogicParamId: 'view',
                    logicType: 'SINGLE',
                    name: 'view[edit_comment_id] 值为空(Nil)',
                    id: 'view[edit_comment_id] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '无存在评论id',
            },
            {
              dstDEUILogicNodeId: 'preparejsparam3',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'edit_comment_id',
                    dstLogicParamId: 'view',
                    logicType: 'SINGLE',
                    name: 'view[edit_comment_id] 值不为空(NotNil)',
                    id: 'view[edit_comment_id] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '存在评论id',
            },
          ],
          topPos: 550,
          name: '查看view里面参数',
          id: 'debugparam1',
        },
        {
          code: 'uiLogic.comment.content = uiLogic.view.layoutPanel.panelItems.field_textbox.value;',
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'content',
                    dstLogicParamId: 'comment',
                    logicType: 'SINGLE',
                    name: 'comment[content] 值不为空(NotNil)',
                    id: 'comment[content] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'rawjscode3',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'content',
                    dstLogicParamId: 'comment',
                    logicType: 'SINGLE',
                    name: 'comment[content] 值为空(Nil)',
                    id: 'comment[content] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 340,
          name: '获取评论框内容',
          id: 'rawjscode1',
        },
        {
          codeName: 'DEBUGPARAM2',
          dstDEUILogicParamId: 'view',
          leftPos: 160,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'debugparam2',
              id: '连接名称',
            },
          ],
          topPos: 220,
          name: '查看view参数',
          id: 'debugparam2',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 640,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction2',
              srcDEUILogicNodeId: 'preparejsparam2',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'pid',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'reply_comment_id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[reply_comment_id] ==> comment[pid]',
            },
          ],
          topPos: 550,
          name: '回复标识',
          id: 'preparejsparam2',
        },
        {
          code: 'console.log("ceSsasasa")',
          codeName: 'RAWJSCODE3',
          leftPos: 180,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode3',
              id: '连接名称',
            },
          ],
          topPos: 916,
          name: '注入脚本代码',
          id: 'rawjscode3',
        },
        {
          codeName: 'DEBUGPARAM3',
          dstDEUILogicParamId: 'view',
          leftPos: 706,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'debugparam3',
              id: '连接名称',
            },
          ],
          topPos: 410,
          name: '查看view',
          id: 'debugparam3',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 430,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'reply.value',
                    dstLogicParamId: 'editor',
                    logicType: 'SINGLE',
                    name: 'editor[reply.value] 值为空(Nil)',
                    id: 'editor[reply.value] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'debugparam3',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'reply.value',
                    dstLogicParamId: 'editor',
                    logicType: 'SINGLE',
                    name: 'editor[reply.value] 值不为空(NotNil)',
                    id: 'editor[reply.value] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'principal_id',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'principal_id',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[principal_id] ==> comment[principal_id]',
            },
            {
              dstFieldName: 'principal_name',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'principal_name',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[principal_name] ==> comment[principal_name]',
            },
            {
              dstFieldName: 'principal_type',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'principal_type',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[principal_type] ==> comment[principal_type]',
            },
            {
              dstDEUILogicParamId: 'editor',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.field_textbox.editor',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.editor] ==> editor',
              id: 'view[layoutpanel.panelitems.field_textbox.editor] ==> editor',
            },
            {
              dstFieldName: 'owner_type',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'principal_type',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[principal_type] ==> comment[owner_type]',
            },
          ],
          topPos: 350,
          name: '设置评论principal_id与principal_type',
          id: 'preparejsparam1',
        },
        {
          code: "uiLogic.view.layoutPanel.panelItems.field_textbox.value = '';\r\nuiLogic.view.layoutPanel.panelItems.field_textbox.data.field_textbox = '';\r\nuiLogic.view.edit_comment_id = null;\r\nuiLogic.view.reply_comment_id = null;\r\nuiLogic.editor.reply.value = null;",
          codeName: 'RAWJSCODE2',
          leftPos: 580,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode3',
              srcDEUILogicNodeId: 'rawjscode2',
              id: '连接名称',
            },
          ],
          topPos: 986,
          name: '清空评论框与评论id',
          id: 'rawjscode2',
        },
        {
          dstAppDEActionId: 'create',
          dstAppDataEntityId: 'crmweb.note_attach',
          codeName: 'DEACTION2',
          dstDEUILogicParamId: 'comment',
          leftPos: 640,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'deaction2',
              id: '连接名称',
            },
          ],
          topPos: 690,
          name: 'Create',
          id: 'deaction2',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '应用上下文变量',
          id: 'ctx',
        },
        {
          codeName: 'editor',
          entityParam: true,
          name: '编辑器',
          id: 'editor',
        },
        {
          codeName: 'comment',
          entityParam: true,
          name: '评论对象',
          id: 'comment',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '发送评论',
      id: 'send_comment',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'note_attach',
  deapicodeName: 'note_attach',
  deapicodeName2: 'note_attaches',
  deapitag: 'NOTE_ATTACH',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'default',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '备注',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'NOTE_ATTACH',
  id: 'crmweb.note_attach',
  codeName2: 'note_attaches',
  requestPaths: [],
};
