export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'plan_name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'crmweb.payee_plan',
      textAppDEFieldId: 'plan_name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'DataImport',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '序号',
          appDEFieldId: 'sequence',
          name: 'SEQUENCE',
          id: 'sequence',
        },
        {
          caption: '计划收款时间',
          appDEFieldId: 'planned_time',
          name: 'PLANNED_TIME',
          id: 'planned_time',
        },
        {
          caption: '未纳入结算计划款',
          codeListId: 'crmweb.crm__yesno',
          appDEFieldId: 'is_not_in_plan',
          name: 'IS_NOT_IN_PLAN',
          id: 'is_not_in_plan',
        },
        {
          caption: '订单编号',
          appDEFieldId: 'o_number',
          name: 'O_NUMBER',
          id: 'o_number',
        },
        {
          caption: '所有者',
          codeListId: 'crmweb.crm__owner',
          appDEFieldId: 'owner',
          name: 'OWNER',
          id: 'owner',
        },
        {
          caption: '父订单标识',
          appDEFieldId: 'pproject_id',
          name: 'PPROJECT_ID',
          id: 'pproject_id',
        },
        {
          caption: '计划状态',
          codeListId: 'crmweb.runtime__usrcodelist0618913512',
          appDEFieldId: 'plan_status',
          name: 'PLAN_STATUS',
          id: 'plan_status',
        },
        {
          caption: '计划名称',
          appDEFieldId: 'plan_name',
          name: 'PLAN_NAME',
          id: 'plan_name',
        },
        {
          caption: '订单金额',
          appDEFieldId: 'project_amount',
          name: 'PROJECT_AMOUNT',
          id: 'project_amount',
        },
        {
          caption: '业绩结算金额',
          appDEFieldId: 'settlement_amount',
          name: 'SETTLEMENT_AMOUNT',
          id: 'settlement_amount',
        },
        {
          caption: '订单客户',
          appDEFieldId: 'account_name',
          name: 'ACCOUNT_NAME',
          id: 'account_name',
        },
        {
          caption: '订单日期',
          appDEFieldId: 'order_date',
          name: 'ORDER_DATE',
          id: 'order_date',
        },
        {
          caption: '业务条线',
          codeListId: 'crmweb.crm__industry',
          appDEFieldId: 'business_line',
          name: 'BUSINESS_LINE',
          id: 'business_line',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          appDEFieldId: 'create_time',
          name: 'CREATE_TIME',
          id: 'create_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'create_man',
          name: 'CREATE_MAN',
          id: 'create_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'update_man',
          name: 'UPDATE_MAN',
          id: 'update_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          appDEFieldId: 'name',
          name: 'NAME',
          id: 'name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          appDEFieldId: 'id',
          name: 'ID',
          id: 'id',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          appDEFieldId: 'update_time',
          name: 'UPDATE_TIME',
          id: 'update_time',
        },
        {
          caption: '订单名称',
          appDEFieldId: 'project_id',
          name: 'PROJECT_ID',
          id: 'project_id',
        },
        {
          caption: '款项说明',
          appDEFieldId: 'description',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          caption: '金额',
          appDEFieldId: 'amount',
          name: 'AMOUNT',
          id: 'amount',
        },
        {
          caption: '附件',
          appDEFieldId: 'attachments',
          name: 'ATTACHMENTS',
          id: 'attachments',
        },
        {
          caption: '订单名称',
          appDEFieldId: 'project_name',
          name: 'PROJECT_NAME',
          id: 'project_name',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '导入收款计划',
      id: 'dataimport',
    },
  ],
  appDEFields: [
    {
      codeName: 'sequence',
      logicName: '序号',
      predefinedType: 'ORDERVALUE',
      stdDataType: 6,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'planned_time',
      logicName: '计划收款时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'PLANNED_TIME',
      id: 'planned_time',
    },
    {
      codeName: 'is_not_in_plan',
      logicName: '未纳入结算计划款',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_NOT_IN_PLAN',
      id: 'is_not_in_plan',
    },
    {
      codeName: 'o_number',
      logicName: '订单编号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 120,
      name: 'O_NUMBER',
      id: 'o_number',
    },
    {
      codeName: 'owner',
      logicName: '所有者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'OWNER',
      id: 'owner',
    },
    {
      codeName: 'pproject_id',
      logicName: '父订单标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PPROJECT_ID',
      id: 'pproject_id',
    },
    {
      codeName: 'plan_status',
      logicName: '计划状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PLAN_STATUS',
      id: 'plan_status',
    },
    {
      codeName: 'plan_name',
      logicName: '计划名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'PLAN_NAME',
      id: 'plan_name',
    },
    {
      codeName: 'project_amount',
      logicName: '订单金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'PROJECT_AMOUNT',
      id: 'project_amount',
    },
    {
      codeName: 'settlement_amount',
      logicName: '业绩结算金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'SETTLEMENT_AMOUNT',
      id: 'settlement_amount',
    },
    {
      codeName: 'account_name',
      logicName: '订单客户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACCOUNT_NAME',
      id: 'account_name',
    },
    {
      codeName: 'order_date',
      logicName: '订单日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'ORDER_DATE',
      id: 'order_date',
    },
    {
      codeName: 'business_line',
      logicName: '业务条线',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'BUSINESS_LINE',
      id: 'business_line',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'project_id',
      logicName: '订单名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PROJECT_ID',
      id: 'project_id',
    },
    {
      codeName: 'description',
      logicName: '款项说明',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'amount',
      logicName: '金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'AMOUNT',
      id: 'amount',
    },
    {
      codeName: 'attachments',
      logicName: '附件',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'project_name',
      logicName: '订单名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PROJECT_NAME',
      id: 'project_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'payee_plan_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'sequence',
          logicName: '序号',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'planned_time',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '计划收款时间',
          appDEFieldId: 'planned_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'planned_time',
        },
        {
          codeName: 'is_not_in_plan',
          logicName: '未纳入结算计划款',
          appDEFieldId: 'is_not_in_plan',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_not_in_plan',
        },
        {
          codeName: 'o_number',
          logicName: '订单编号',
          appDEFieldId: 'o_number',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'o_number',
        },
        {
          codeName: 'owner',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner',
        },
        {
          codeName: 'pproject_id',
          logicName: '父订单标识',
          appDEFieldId: 'pproject_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'pproject_id',
        },
        {
          codeName: 'plan_status',
          logicName: '计划状态',
          appDEFieldId: 'plan_status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'plan_status',
        },
        {
          codeName: 'plan_name',
          logicName: '计划名称',
          appDEFieldId: 'plan_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'plan_name',
        },
        {
          codeName: 'project_amount',
          logicName: '订单金额',
          appDEFieldId: 'project_amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'project_amount',
        },
        {
          codeName: 'settlement_amount',
          logicName: '业绩结算金额',
          appDEFieldId: 'settlement_amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'settlement_amount',
        },
        {
          codeName: 'account_name',
          logicName: '订单客户',
          appDEFieldId: 'account_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_name',
        },
        {
          codeName: 'order_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '订单日期',
          appDEFieldId: 'order_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'order_date',
        },
        {
          codeName: 'business_line',
          logicName: '业务条线',
          appDEFieldId: 'business_line',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'business_line',
        },
        {
          codeName: 'amount',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'amount',
        },
        {
          codeName: 'attachments',
          logicName: '附件',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'attachment_dto',
          refAppDataEntityId: 'crmweb.attachment',
          refPickupAppDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'description',
          logicName: '款项说明',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'project_id',
          logicName: '订单名称',
          appDEFieldId: 'project_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'project_id',
        },
        {
          codeName: 'project_name',
          logicName: '订单名称',
          appDEFieldId: 'project_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'project_name',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'payee_plan_dto',
    },
    {
      codeName: 'payee_plan_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_amount_gtandeq',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_amount_gtandeq',
        },
        {
          codeName: 'n_amount_in',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLES',
          allowEmpty: true,
          id: 'n_amount_in',
        },
        {
          codeName: 'n_amount_ltandeq',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_amount_ltandeq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_o_number_like',
          logicName: '订单编号',
          appDEFieldId: 'o_number',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_o_number_like',
        },
        {
          codeName: 'n_plan_name_like',
          logicName: '计划名称',
          appDEFieldId: 'plan_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_plan_name_like',
        },
        {
          codeName: 'n_plan_status_eq',
          logicName: '计划状态',
          appDEFieldId: 'plan_status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_plan_status_eq',
        },
        {
          codeName: 'n_planned_time_gt',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '计划收款时间',
          appDEFieldId: 'planned_time',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_planned_time_gt',
        },
        {
          codeName: 'n_planned_time_gtandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '计划收款时间',
          appDEFieldId: 'planned_time',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_planned_time_gtandeq',
        },
        {
          codeName: 'n_planned_time_in',
          logicName: '计划收款时间',
          appDEFieldId: 'planned_time',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLES',
          allowEmpty: true,
          id: 'n_planned_time_in',
        },
        {
          codeName: 'n_planned_time_ltandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '计划收款时间',
          appDEFieldId: 'planned_time',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_planned_time_ltandeq',
        },
        {
          codeName: 'n_project_id_eq',
          logicName: '订单名称',
          appDEFieldId: 'project_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_project_id_eq',
        },
        {
          codeName: 'n_project_name_eq',
          logicName: '订单名称',
          appDEFieldId: 'project_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_project_name_eq',
        },
        {
          codeName: 'n_project_name_like',
          logicName: '订单名称',
          appDEFieldId: 'project_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_project_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'payee_plan_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_project',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_project',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_project',
    },
    {
      codeName: 'add_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_tags',
    },
    {
      codeName: 'batch_update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/batch_update',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'batch_update',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_task',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_task',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_task',
    },
    {
      codeName: 'delete_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete_tags',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'main_view_dr_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/main_view_dr_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'main_view_dr_count',
    },
    {
      codeName: 'move_order',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTOS',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/move_order',
      needResourceKey: true,
      actionMode: 'MOVEORDER',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'move_order',
    },
    {
      codeName: 'plan_to_payee',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/plan_to_payee',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'plan_to_payee',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_createman',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_createman',
      actionType: 'REMOTE',
      dataSetName: 'createman',
      dataSetTag: 'createman',
      dataSetType: 'REMOTE',
      id: 'fetch_createman',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_executor',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_executor',
      actionType: 'REMOTE',
      dataSetName: 'executor',
      dataSetTag: 'executor',
      dataSetType: 'REMOTE',
      id: 'fetch_executor',
    },
    {
      codeName: 'fetch_sum',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_sum',
      actionType: 'REMOTE',
      dataSetName: 'sum',
      dataSetTag: 'sum',
      dataSetType: 'REMOTE',
      id: 'fetch_sum',
    },
    {
      codeName: 'fetch_toward',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_toward',
      actionType: 'REMOTE',
      dataSetName: 'toward',
      dataSetTag: 'toward',
      dataSetType: 'REMOTE',
      id: 'fetch_toward',
    },
    {
      codeName: 'fetch_tree',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_plan_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_plan_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_tree',
      actionType: 'REMOTE',
      dataSetName: 'tree',
      dataSetTag: 'tree',
      dataSetType: 'REMOTE',
      id: 'fetch_tree',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导入收款计划',
      codeName: 'ImportData',
      frontProcessType: 'DATAIMP',
      fullCodeName: 'payee_plan_ImportData',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'ImportData',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEDataImportId: 'dataimport',
      appDataEntityId: 'crmweb.payee_plan',
      name: '导入数据',
      id: 'importdata@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '添加标签',
      codeName: 'add_tags',
      frontAppViewId: 'crmweb.tag_add_tag',
      fullCodeName: 'payee_plan_add_tags',
      appDEMethodId: 'add_tags',
      refreshMode: 1,
      successMsg: '已成功添加标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '添加标签',
      id: 'add_tags@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '批量更新',
      codeName: 'batch_update',
      fullCodeName: 'payee_plan_batch_update',
      appDEMethodId: 'batch_update',
      refreshMode: 1,
      successMsg: '更新完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'batch_update',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '批量更新',
      id: 'batch_update@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '关闭计划',
      codeName: 'close_plan',
      confirmMsg: '是否确认关闭当前计划？',
      fullCodeName: 'payee_plan_close_plan',
      appDEMethodId: 'update',
      navigateParams: [
        {
          key: 'plan_status',
          value: '50',
          rawValue: true,
          id: 'plan_status',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-close',
        glyph: 'xf00d@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '已关闭！',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'close_plan',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '关闭计划',
      id: 'close_plan@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '生成收款记录',
      codeName: 'create_payee',
      frontAppViewId: 'crmweb.payee_payee_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_plan_create_payee',
      navigateParams: [
        {
          key: 'planned_amount',
          value: 'amount',
          id: 'planned_amount',
        },
        {
          key: 'projectid',
          value: 'project',
          id: 'projectid',
        },
        {
          key: 'amount',
          value: 'amount',
          id: 'amount',
        },
        {
          key: 'planid',
          value: 'id',
          id: 'planid',
        },
        {
          key: 'plan_description',
          value: 'description',
          id: 'plan_description',
        },
        {
          key: 'description',
          value: 'description',
          id: 'description',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-share-square-o',
        glyph: 'xf045@FontAwesome',
      },
      tooltip: '生成收款记录',
      uiactionMode: 'FRONT',
      uiactionTag: 'create_payee',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '生成收款记录',
      id: 'create_payee@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '创建任务',
      codeName: 'create_task',
      frontAppViewId: 'crmweb.task_batch_create_view',
      fullCodeName: 'payee_plan_create_task',
      appDEMethodId: 'create_task',
      successMsg: '创建完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'create_task',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '创建任务',
      id: 'create_task@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '计划拆分保存',
      codeName: 'cut_save',
      dialogResult: 'OK',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_plan_cut_save',
      uiactionMode: 'FRONT',
      uiactionTag: 'cut_save',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      closeEditView: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'cut_and_save',
      appDataEntityId: 'crmweb.payee_plan',
      name: '计划拆分保存',
      id: 'cut_save@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移除标签',
      codeName: 'delete_tags',
      frontAppViewId: 'crmweb.tag_remove_tag',
      fullCodeName: 'payee_plan_delete_tags',
      appDEMethodId: 'delete_tags',
      refreshMode: 1,
      successMsg: '已成功移除标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '移除标签',
      id: 'delete_tags@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '打开计划编辑视图',
      codeName: 'open_edit',
      frontAppViewId: 'crmweb.payee_plan_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_plan_open_edit',
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '打开计划编辑视图',
      id: 'open_edit@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'remove',
      confirmMsg: '确定要删除所选的记录吗？',
      fullCodeName: 'payee_plan_remove',
      appDEMethodId: 'remove',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '删除',
      id: 'remove@payee_plan',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '拆分计划',
      codeName: 'split_plan',
      frontAppViewId: 'crmweb.payee_plan_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_plan_split_plan',
      navigateContexts: [
        {
          key: 'AMOUNT',
          rawValue: true,
          name: 'AMOUNT',
          id: 'amount',
        },
        {
          key: 'PAYEE_PLAN',
          rawValue: true,
          name: 'PAYEE_PLAN',
          id: 'payee_plan',
        },
        {
          key: 'ID',
          rawValue: true,
          name: 'ID',
          id: 'id',
        },
      ],
      navigateParams: [
        {
          key: 'plan_status',
          value: '10',
          rawValue: true,
          id: 'plan_status',
        },
        {
          key: 'view_mode',
          value: 'cut',
          rawValue: true,
          id: 'view_mode',
        },
        {
          key: 'last_id',
          value: 'id',
          id: 'last_id',
        },
        {
          key: 'last_amount',
          value: 'amount',
          id: 'last_amount',
        },
        {
          key: 'description',
          value: 'description',
          id: 'description',
        },
        {
          key: 'project_id',
          value: 'project_id',
          id: 'project_id',
        },
        {
          key: 'id',
          rawValue: true,
          id: 'id',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-cut',
        glyph: 'xf0c4@FontAwesome',
      },
      tooltip: '拆分计划',
      uiactionMode: 'FRONT',
      uiactionTag: 'split_plan',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_plan',
      name: '拆分计划',
      id: 'split_plan@payee_plan',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'cut_and_save',
      defaultParamName: 'Default',
      logicName: '拆分前保存检测',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: -160,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 674,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'LTANDEQ',
                    dstFieldName: 'amount',
                    dstLogicParamId: 'default',
                    paramType: 'SRCENTITYFIELD',
                    paramValue: 'last_amount',
                    srcLogicParamId: 'default',
                    value: 'last_amount',
                    logicType: 'SINGLE',
                    name: 'Default[amount] 小于等于(<=) last_amount',
                    id: 'default[amount] 小于等于(<=) last_amount',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam2',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'throwexception1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'GT',
                    dstFieldName: 'amount',
                    dstLogicParamId: 'default',
                    paramType: 'SRCENTITYFIELD',
                    paramValue: 'last_amount',
                    srcLogicParamId: 'default',
                    value: 'last_amount',
                    logicType: 'SINGLE',
                    name: 'Default[amount] 大于(>) last_amount',
                    id: 'default[amount] 大于(>) last_amount',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam2',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'amount',
              dstDEUILogicParamId: 'last_plan',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'last_result_amount',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default[last_result_amount] ==> last_plan[amount]',
              id: 'default[last_result_amount] ==> last_plan[amount]',
            },
            {
              dstFieldName: 'id',
              dstDEUILogicParamId: 'last_plan',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'last_id',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default[last_id] ==> last_plan[id]',
              id: 'default[last_id] ==> last_plan[id]',
            },
          ],
          topPos: 130,
          name: '准备参数',
          id: 'preparejsparam2',
        },
        {
          dstAppDEActionId: 'save',
          dstAppDataEntityId: 'crmweb.payee_plan',
          codeName: 'DEACTION1',
          dstDEUILogicParamId: 'last_plan',
          leftPos: 710,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              srcDEUILogicNodeId: 'deaction1',
              id: '连接名称',
            },
          ],
          topPos: 490,
          name: '实体行为',
          id: 'deaction1',
        },
        {
          dstAppDEUIActionId: 'save',
          dstAppDataEntityId: 'crmweb.payee_plan',
          codeName: 'DEUIACTION1',
          dstDEUILogicParamId: 'default',
          leftPos: 170,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'deuiaction1',
              id: '连接名称',
            },
          ],
          topPos: 480,
          name: '界面行为',
          id: 'deuiaction1',
        },
        {
          codeName: 'PREPAREJSPARAM3',
          leftPos: -20,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              srcDEUILogicNodeId: 'preparejsparam3',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'plan_status',
              dstDEUILogicParamId: 'default',
              paramAction: 'SETPARAMVALUE',
              srcValue: '10',
              srcValueType: 'SRCVALUE',
              name: '直接值[10] ==> Default[plan_status]',
              id: '直接值[10] ==> default[plan_status]',
            },
          ],
          topPos: 290,
          name: '准备参数',
          id: 'preparejsparam3',
        },
        {
          errorInfo: '金额大于上一记录的金额',
          codeName: 'THROWEXCEPTION1',
          leftPos: 820,
          logicNodeType: 'THROWEXCEPTION',
          topPos: -60,
          name: '抛出异常',
          id: 'throwexception1',
        },
        {
          codeName: 'END1',
          leftPos: 210,
          logicNodeType: 'END',
          topPos: 770,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'default',
          leftPos: 150,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam3',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'NOTEQ',
                    dstFieldName: 'view_mode',
                    dstLogicParamId: 'default',
                    paramValue: 'cut',
                    value: 'cut',
                    logicType: 'SINGLE',
                    name: 'Default[view_mode] 不等于(<>) cut',
                    id: 'default[view_mode] 不等于(<>) cut',
                  },
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'plan_status',
                    dstLogicParamId: 'default',
                    logicType: 'SINGLE',
                    name: 'Default[plan_status] 值为空(Nil)',
                    id: 'default[plan_status] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'EQ',
                    dstFieldName: 'view_mode',
                    dstLogicParamId: 'default',
                    paramValue: 'cut',
                    value: 'cut',
                    logicType: 'SINGLE',
                    name: 'Default[view_mode] 等于(=) cut',
                    id: 'default[view_mode] 等于(=) cut',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'deuiaction1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'NOTEQ',
                    dstFieldName: 'view_mode',
                    dstLogicParamId: 'default',
                    paramValue: 'cut',
                    value: 'cut',
                    logicType: 'SINGLE',
                    name: 'Default[view_mode] 不等于(<>) cut',
                    id: 'default[view_mode] 不等于(<>) cut',
                  },
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'plan_status',
                    dstLogicParamId: 'default',
                    logicType: 'SINGLE',
                    name: 'Default[plan_status] 值不为空(NotNil)',
                    id: 'default[plan_status] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 130,
          name: '调试逻辑参数',
          id: 'debugparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'last_plan',
          entityParam: true,
          name: '上一计划参数',
          id: 'last_plan',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '拆分前保存检测',
      id: 'cut_and_save',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'payee_plan',
  deapicodeName: 'payee_plan',
  deapicodeName2: 'payee_plans',
  deapitag: 'PAYEE_PLAN',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'dataimport',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PAYEE_PLAN',
  },
  logicName: '收款计划',
  majorAppDEFieldId: 'plan_name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'payee_plans',
      majorAppDataEntityId: 'crmweb.project',
      parentAppDEFieldId: 'project_id',
      parentTextAppDEFieldId: 'project_name',
      rsmode: 2,
      name: 'DER1N_PAYEE_PLAN_PROJECT_PROJECT_ID',
      id: 'payee_plans',
    },
  ],
  quickSearchAppDEFieldIds: ['plan_name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PAYEE_PLAN',
  id: 'crmweb.payee_plan',
  codeName2: 'payee_plans',
  requestPaths: ['projects/${project}/payee_plans/${payee_plan}'],
};
