export default {
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'DataImport',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '序号',
          appDEFieldId: 'sequence',
          name: 'SEQUENCE',
          id: 'sequence',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.METHOD',
          },
          caption: '收款方式',
          appDEFieldId: 'method',
          name: 'METHOD',
          id: 'method',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PAYEE_DATE',
          },
          caption: '收款日期',
          appDEFieldId: 'payee_date',
          name: 'PAYEE_DATE',
          id: 'payee_date',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PLAN_AMOUNT',
          },
          caption: '原计划金额',
          appDEFieldId: 'plan_amount',
          name: 'PLAN_AMOUNT',
          id: 'plan_amount',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PLANNED_TIME',
          },
          caption: '原计划时间',
          appDEFieldId: 'planned_time',
          name: 'PLANNED_TIME',
          id: 'planned_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PLAN_DESCRIPTION',
          },
          caption: '原计划说明',
          appDEFieldId: 'plan_description',
          name: 'PLAN_DESCRIPTION',
          id: 'plan_description',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PAYEE_ALLOCATES',
          },
          caption: '回款分配',
          appDEFieldId: 'payee_allocates',
          name: 'PAYEE_ALLOCATES',
          id: 'payee_allocates',
        },
        {
          caption: '所属年度',
          appDEFieldId: 'year',
          name: 'YEAR',
          id: 'year',
        },
        {
          caption: '订单编号',
          appDEFieldId: 'o_number',
          name: 'O_NUMBER',
          id: 'o_number',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ALLOCATE_MODEL',
          },
          caption: '分配模式',
          codeListId: 'crmweb.crm__distribution_model',
          appDEFieldId: 'allocate_model',
          name: 'ALLOCATE_MODEL',
          id: 'allocate_model',
        },
        {
          caption: '所有者',
          codeListId: 'crmweb.crm__owner',
          appDEFieldId: 'owner',
          name: 'OWNER',
          id: 'owner',
        },
        {
          caption: '父标识',
          appDEFieldId: 'pproject_id',
          name: 'PPROJECT_ID',
          id: 'pproject_id',
        },
        {
          caption: '订单名称',
          appDEFieldId: 'project_name',
          name: 'PROJECT_NAME',
          id: 'project_name',
        },
        {
          caption: '客户名称',
          appDEFieldId: 'account_name',
          name: 'ACCOUNT_NAME',
          id: 'account_name',
        },
        {
          caption: '业绩结算金额',
          appDEFieldId: 'settlement_amount',
          name: 'SETTLEMENT_AMOUNT',
          id: 'settlement_amount',
        },
        {
          caption: '业务条线',
          codeListId: 'crmweb.crm__industry',
          appDEFieldId: 'business_line',
          name: 'BUSINESS_LINE',
          id: 'business_line',
        },
        {
          caption: '订单日期',
          appDEFieldId: 'order_date',
          name: 'ORDER_DATE',
          id: 'order_date',
        },
        {
          caption: '计划名称',
          appDEFieldId: 'plan_name',
          name: 'PLAN_NAME',
          id: 'plan_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'create_man',
          name: 'CREATE_MAN',
          id: 'create_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '名称',
          appDEFieldId: 'name',
          name: 'NAME',
          id: 'name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          appDEFieldId: 'create_time',
          name: 'CREATE_TIME',
          id: 'create_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'update_man',
          name: 'UPDATE_MAN',
          id: 'update_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          appDEFieldId: 'update_time',
          name: 'UPDATE_TIME',
          id: 'update_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          appDEFieldId: 'id',
          name: 'ID',
          id: 'id',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTACHMENTS',
          },
          caption: '附件',
          appDEFieldId: 'attachments',
          name: 'ATTACHMENTS',
          id: 'attachments',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PAYEE_NUMBER',
          },
          caption: '编号',
          appDEFieldId: 'payee_number',
          name: 'PAYEE_NUMBER',
          id: 'payee_number',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.AMOUNT',
          },
          caption: '金额',
          appDEFieldId: 'amount',
          name: 'AMOUNT',
          id: 'amount',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.STATUS',
          },
          caption: '状态',
          codeListId: 'crmweb.crm__payee_status',
          appDEFieldId: 'status',
          name: 'STATUS',
          id: 'status',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.DESCRIPTION',
          },
          caption: '款项说明',
          appDEFieldId: 'description',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PROJECT_ID',
          },
          caption: '订单标识',
          appDEFieldId: 'project_id',
          name: 'PROJECT_ID',
          id: 'project_id',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PAYEE_PLAN_ID',
          },
          caption: '收款计划标识',
          appDEFieldId: 'payee_plan_id',
          name: 'PAYEE_PLAN_ID',
          id: 'payee_plan_id',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '导入收付款',
      id: 'dataimport',
    },
  ],
  appDEFields: [
    {
      codeName: 'sequence',
      logicName: '序号',
      predefinedType: 'ORDERVALUE',
      stdDataType: 6,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'method',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.METHOD',
      },
      logicName: '收款方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'METHOD',
      id: 'method',
    },
    {
      codeName: 'payee_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PAYEE_DATE',
      },
      logicName: '收款日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'PAYEE_DATE',
      id: 'payee_date',
    },
    {
      codeName: 'plan_amount',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PLAN_AMOUNT',
      },
      logicName: '原计划金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'PLAN_AMOUNT',
      id: 'plan_amount',
    },
    {
      codeName: 'planned_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PLANNED_TIME',
      },
      logicName: '原计划时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'PLANNED_TIME',
      id: 'planned_time',
    },
    {
      codeName: 'plan_description',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PLAN_DESCRIPTION',
      },
      logicName: '原计划说明',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'PLAN_DESCRIPTION',
      id: 'plan_description',
    },
    {
      codeName: 'payee_allocates',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PAYEE_ALLOCATES',
      },
      logicName: '回款分配',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'PAYEE_ALLOCATES',
      id: 'payee_allocates',
    },
    {
      codeName: 'year',
      logicName: '所属年度',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'YEAR',
      id: 'year',
    },
    {
      codeName: 'o_number',
      logicName: '订单编号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 120,
      name: 'O_NUMBER',
      id: 'o_number',
    },
    {
      codeName: 'allocate_model',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ALLOCATE_MODEL',
      },
      logicName: '分配模式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ALLOCATE_MODEL',
      id: 'allocate_model',
    },
    {
      codeName: 'owner',
      logicName: '所有者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'OWNER',
      id: 'owner',
    },
    {
      codeName: 'pproject_id',
      logicName: '父标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PPROJECT_ID',
      id: 'pproject_id',
    },
    {
      codeName: 'project_name',
      logicName: '订单名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PROJECT_NAME',
      id: 'project_name',
    },
    {
      codeName: 'account_name',
      logicName: '客户名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACCOUNT_NAME',
      id: 'account_name',
    },
    {
      codeName: 'settlement_amount',
      logicName: '业绩结算金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'SETTLEMENT_AMOUNT',
      id: 'settlement_amount',
    },
    {
      codeName: 'business_line',
      logicName: '业务条线',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'BUSINESS_LINE',
      id: 'business_line',
    },
    {
      codeName: 'order_date',
      logicName: '订单日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'ORDER_DATE',
      id: 'order_date',
    },
    {
      codeName: 'plan_name',
      logicName: '计划名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PLAN_NAME',
      id: 'plan_name',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'attachments',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTACHMENTS',
      },
      logicName: '附件',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'payee_number',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PAYEE_NUMBER',
      },
      logicName: '编号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 120,
      name: 'PAYEE_NUMBER',
      id: 'payee_number',
    },
    {
      codeName: 'amount',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.AMOUNT',
      },
      logicName: '金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'AMOUNT',
      id: 'amount',
    },
    {
      codeName: 'status',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.STATUS',
      },
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATUS',
      id: 'status',
    },
    {
      codeName: 'description',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.DESCRIPTION',
      },
      logicName: '款项说明',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'project_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PROJECT_ID',
      },
      logicName: '订单标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PROJECT_ID',
      id: 'project_id',
    },
    {
      codeName: 'payee_plan_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.PAYEE_PLAN_ID',
      },
      logicName: '收款计划标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PAYEE_PLAN_ID',
      id: 'payee_plan_id',
    },
  ],
  appDELogics: [
    {
      codeName: 'get_project_id',
      defaultParamName: 'Default',
      logicName: '传递订单id给向导视图',
      logicSubType: 'NONE',
      delogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          links: [
            {
              thenId: 'prepareparam1',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          returnParamId: 'default',
          returnType: 'LOGICPARAM',
          codeName: 'END1',
          leftPos: 623,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'PREPAREPARAM1',
          leftPos: 343,
          logicNodeType: 'PREPAREPARAM',
          links: [
            {
              thenId: 'end1',
              id: '连接名称',
            },
          ],
          delogicNodeParams: [
            {
              dstFieldName: 'PROJECT_ID',
              dstDELogicParamId: 'default',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'project',
              srcValueType: 'VIEWPARAM',
              name: '当前视图参数[project] ==> Default[PROJECT_ID]',
              id: '当前视图参数[project] ==> default[project_id]',
            },
          ],
          topPos: 208,
          name: '准备参数',
          id: 'prepareparam1',
        },
      ],
      delogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          paramAppDataEntityId: 'crmweb.payee',
          name: '传入变量',
          id: 'default',
        },
      ],
      startDELogicNodeId: 'begin',
      enableFront: true,
      valid: true,
      name: '传递订单id给向导视图',
      id: 'get_project_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'payee_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'sequence',
          logicName: '序号',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'method',
          logicName: '收款方式',
          appDEFieldId: 'method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'method',
        },
        {
          codeName: 'payee_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '收款日期',
          appDEFieldId: 'payee_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'payee_date',
        },
        {
          codeName: 'plan_amount',
          logicName: '原计划金额',
          appDEFieldId: 'plan_amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'plan_amount',
        },
        {
          codeName: 'planned_time',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '原计划时间',
          appDEFieldId: 'planned_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'planned_time',
        },
        {
          codeName: 'plan_description',
          logicName: '原计划说明',
          appDEFieldId: 'plan_description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'plan_description',
        },
        {
          codeName: 'payee_allocates',
          logicName: '回款分配',
          appDEFieldId: 'payee_allocates',
          refAppDEMethodDTOId: 'payee_allocate_dto',
          refAppDataEntityId: 'crmweb.payee_allocate',
          refPickupAppDEFieldId: 'payee_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'payee_allocates',
        },
        {
          codeName: 'year',
          logicName: '所属年度',
          appDEFieldId: 'year',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'year',
        },
        {
          codeName: 'o_number',
          logicName: '订单编号',
          appDEFieldId: 'o_number',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'o_number',
        },
        {
          codeName: 'allocate_model',
          logicName: '分配模式',
          appDEFieldId: 'allocate_model',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'allocate_model',
        },
        {
          codeName: 'owner',
          logicName: '所有者',
          appDEFieldId: 'owner',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner',
        },
        {
          codeName: 'pproject_id',
          logicName: '父标识',
          appDEFieldId: 'pproject_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'pproject_id',
        },
        {
          codeName: 'project_name',
          logicName: '订单名称',
          appDEFieldId: 'project_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'project_name',
        },
        {
          codeName: 'account_name',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_name',
        },
        {
          codeName: 'settlement_amount',
          logicName: '业绩结算金额',
          appDEFieldId: 'settlement_amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'settlement_amount',
        },
        {
          codeName: 'business_line',
          logicName: '业务条线',
          appDEFieldId: 'business_line',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'business_line',
        },
        {
          codeName: 'order_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '订单日期',
          appDEFieldId: 'order_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'order_date',
        },
        {
          codeName: 'plan_name',
          logicName: '计划名称',
          appDEFieldId: 'plan_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'plan_name',
        },
        {
          codeName: 'amount',
          logicName: '金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'amount',
        },
        {
          codeName: 'attachments',
          logicName: '附件',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'attachment_dto',
          refAppDataEntityId: 'crmweb.attachment',
          refPickupAppDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'description',
          logicName: '款项说明',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'payee_number',
          logicName: '编号',
          appDEFieldId: 'payee_number',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'payee_number',
        },
        {
          codeName: 'payee_plan_id',
          logicName: '收款计划标识',
          appDEFieldId: 'payee_plan_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'payee_plan_id',
        },
        {
          codeName: 'project_id',
          logicName: '订单标识',
          appDEFieldId: 'project_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'project_id',
        },
        {
          codeName: 'status',
          logicName: '状态',
          appDEFieldId: 'status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'status',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'payee_dto',
    },
    {
      codeName: 'payee_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_payee_date_gt',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '收款日期',
          appDEFieldId: 'payee_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_payee_date_gt',
        },
        {
          codeName: 'n_payee_date_gtandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '收款日期',
          appDEFieldId: 'payee_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_payee_date_gtandeq',
        },
        {
          codeName: 'n_payee_date_in',
          logicName: '收款日期',
          appDEFieldId: 'payee_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLES',
          allowEmpty: true,
          id: 'n_payee_date_in',
        },
        {
          codeName: 'n_payee_date_ltandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '收款日期',
          appDEFieldId: 'payee_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_payee_date_ltandeq',
        },
        {
          codeName: 'n_payee_plan_id_eq',
          logicName: '收款计划标识',
          appDEFieldId: 'payee_plan_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_payee_plan_id_eq',
        },
        {
          codeName: 'n_plan_name_eq',
          logicName: '计划名称',
          appDEFieldId: 'plan_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_plan_name_eq',
        },
        {
          codeName: 'n_plan_name_like',
          logicName: '计划名称',
          appDEFieldId: 'plan_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_plan_name_like',
        },
        {
          codeName: 'n_project_id_eq',
          logicName: '订单标识',
          appDEFieldId: 'project_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_project_id_eq',
        },
        {
          codeName: 'n_project_name_eq',
          logicName: '订单名称',
          appDEFieldId: 'project_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_project_name_eq',
        },
        {
          codeName: 'n_project_name_like',
          logicName: '订单名称',
          appDEFieldId: 'project_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_project_name_like',
        },
        {
          codeName: 'n_status_eq',
          logicName: '状态',
          appDEFieldId: 'status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_status_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'payee_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CreateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempInput',
        id: 'createtempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempResult',
        id: 'createtempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTemp',
      id: 'createtemp',
    },
    {
      codeName: 'CreateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempMajorInput',
        id: 'createtempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempMajorResult',
        id: 'createtempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTempMajor',
      id: 'createtempmajor',
    },
    {
      codeName: 'GetDraftTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        name: 'GetDraftTempInput',
        id: 'getdrafttempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        name: 'GetDraftTempResult',
        id: 'getdrafttempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTemp',
      id: 'getdrafttemp',
    },
    {
      codeName: 'GetDraftTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorInput',
        id: 'getdrafttempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorResult',
        id: 'getdrafttempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTempMajor',
      id: 'getdrafttempmajor',
    },
    {
      codeName: 'GetTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempInput',
        id: 'gettempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        name: 'GetTempResult',
        id: 'gettempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTemp',
      id: 'gettemp',
    },
    {
      codeName: 'GetTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempMajorInput',
        id: 'gettempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        name: 'GetTempMajorResult',
        id: 'gettempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTempMajor',
      id: 'gettempmajor',
    },
    {
      codeName: 'RemoveTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempInput',
        id: 'removetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempResult',
        id: 'removetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTemp',
      id: 'removetemp',
    },
    {
      codeName: 'RemoveTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempMajorInput',
        id: 'removetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempMajorResult',
        id: 'removetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTempMajor',
      id: 'removetempmajor',
    },
    {
      codeName: 'UpdateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempInput',
        id: 'updatetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempResult',
        id: 'updatetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTemp',
      id: 'updatetemp',
    },
    {
      codeName: 'UpdateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempMajorInput',
        id: 'updatetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempMajorResult',
        id: 'updatetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTempMajor',
      id: 'updatetempmajor',
    },
    {
      codeName: 'account_from_plan',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/account_from_plan',
      actionMode: 'GETDRAFT',
      actionTag: 'AccountFromPlan',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'AccountFromPlan',
      id: 'account_from_plan',
    },
    {
      codeName: 'add_payee_to_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_payee_to_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'addPayeeToWorkProgress',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'addPayeeToWorkProgress',
      id: 'add_payee_to_work_progress',
    },
    {
      codeName: 'add_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_tags',
    },
    {
      codeName: 'allocate_from_project',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/allocate_from_project',
      actionMode: 'GETDRAFT',
      actionTag: 'AllocateFromProject',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'AllocateFromProject',
      id: 'allocate_from_project',
    },
    {
      codeName: 'async_add_payee_to_work_progress',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'ASYNCACTION',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/async_add_payee_to_work_progress',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'Async_addPayeeToWorkProgress',
      actionType: 'REMOTE',
      asyncAction: true,
      dataSetType: 'REMOTE',
      name: 'Async_addPayeeToWorkProgress',
      id: 'async_add_payee_to_work_progress',
    },
    {
      codeName: 'batch_update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/batch_update',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'batch_update',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_task',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_task',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_task',
    },
    {
      codeName: 'delete_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete_tags',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'main_view_dr_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/main_view_dr_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'main_view_dr_count',
    },
    {
      codeName: 'move_order',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTOS',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/move_order',
      needResourceKey: true,
      actionMode: 'MOVEORDER',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'move_order',
    },
    {
      codeName: 'plan_info_by_project',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/plan_info_by_project',
      actionMode: 'GETDRAFT',
      actionName: 'PlanInfoByProject',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'plan_info_by_project',
    },
    {
      codeName: 'project_info',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/project_info',
      actionMode: 'GETDRAFT',
      actionName: 'ProjectInfo',
      actionTag: 'Project_Info',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Project_Info',
      id: 'project_info',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_createman',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_createman',
      actionType: 'REMOTE',
      dataSetName: 'createman',
      dataSetTag: 'createman',
      dataSetType: 'REMOTE',
      id: 'fetch_createman',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_executor',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_executor',
      actionType: 'REMOTE',
      dataSetName: 'executor',
      dataSetTag: 'executor',
      dataSetType: 'REMOTE',
      id: 'fetch_executor',
    },
    {
      codeName: 'fetch_sum',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_sum',
      actionType: 'REMOTE',
      dataSetName: 'sum',
      dataSetTag: 'sum',
      dataSetType: 'REMOTE',
      id: 'fetch_sum',
    },
    {
      codeName: 'fetch_tree',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_tree',
      actionType: 'REMOTE',
      dataSetName: 'tree',
      dataSetTag: 'tree',
      dataSetType: 'REMOTE',
      id: 'fetch_tree',
    },
    {
      codeName: 'FetchTempAll',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        name: 'AllInput',
        id: 'allinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        name: 'AllResult',
        id: 'allresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'all',
      dataSetType: 'DATAQUERY',
      name: 'all',
      id: 'fetchtempall',
    },
    {
      codeName: 'FetchTempCreateman',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        name: 'CreatemanInput',
        id: 'createmaninput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        name: 'CreatemanResult',
        id: 'createmanresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'createman',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condOp: 'EQ',
              condValue: 'srfpersonid',
              fieldName: 'CREATE_MAN',
              vartypeId: 'SESSIONCONTEXT',
              condType: 'SINGLE',
              name: '(CREATE_MAN) 等于(=) 用户上下文 srfpersonid',
              id: '(create_man) 等于(=) 用户上下文 srfpersonid',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'createman',
      id: 'fetchtempcreateman',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FetchTempExecutor',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        name: 'ExecutorInput',
        id: 'executorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        name: 'ExecutorResult',
        id: 'executorresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'executor',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condition:
                'EXISTS(SELECT * FROM `EXECUTOR` t31 \n WHERE \n t21.`ID` = t31.`PRINCIPAL_ID`  AND  ( t31.`USER_ID` = #{ctx.sessioncontext.userid} ) )',
              condType: 'CUSTOM',
              id: '执行人',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'executor',
      id: 'fetchtempexecutor',
    },
    {
      codeName: 'FetchTempSum',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        name: 'SumInput',
        id: 'suminput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        name: 'SumResult',
        id: 'sumresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'sum',
      dataSetType: 'DATAQUERY',
      name: 'sum',
      id: 'fetchtempsum',
    },
    {
      codeName: 'FetchTempTree',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_filter_dto',
        type: 'DTO',
        name: 'TreeInput',
        id: 'treeinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_dto',
        type: 'PAGE',
        name: 'TreeResult',
        id: 'treeresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'tree',
      dataSetType: 'DATAQUERY',
      name: 'tree',
      id: 'fetchtemptree',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导入收付款',
      codeName: 'ImportData',
      frontProcessType: 'DATAIMP',
      fullCodeName: 'payee_ImportData',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'ImportData',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEDataImportId: 'dataimport',
      appDataEntityId: 'crmweb.payee',
      name: '导入数据',
      id: 'importdata@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '添加标签',
      codeName: 'add_tags',
      frontAppViewId: 'crmweb.tag_add_tag',
      fullCodeName: 'payee_add_tags',
      appDEMethodId: 'add_tags',
      refreshMode: 1,
      successMsg: '已成功添加标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '添加标签',
      id: 'add_tags@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '获取订单分配配置',
      codeName: 'allocate_from_project',
      fullCodeName: 'payee_allocate_from_project',
      appDEMethodId: 'allocate_from_project',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'allocate_from_project',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '获取订单分配配置',
      id: 'allocate_from_project@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '批量更新',
      codeName: 'batch_update',
      fullCodeName: 'payee_batch_update',
      appDEMethodId: 'batch_update',
      refreshMode: 1,
      successMsg: '更新完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'batch_update',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '批量更新',
      id: 'batch_update@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '创建任务',
      codeName: 'create_task',
      frontAppViewId: 'crmweb.task_batch_create_view',
      fullCodeName: 'payee_create_task',
      appDEMethodId: 'create_task',
      successMsg: '创建完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'create_task',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '创建任务',
      id: 'create_task@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移除标签',
      codeName: 'delete_tags',
      frontAppViewId: 'crmweb.tag_remove_tag',
      fullCodeName: 'payee_delete_tags',
      appDEMethodId: 'delete_tags',
      refreshMode: 1,
      successMsg: '已成功移除标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '移除标签',
      id: 'delete_tags@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '收款记录',
      codeName: 'openPayeeView',
      frontAppViewId: 'crmweb.payee_multimode_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_openPayeeView',
      uiactionMode: 'FRONT',
      uiactionTag: 'openPayeeView',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '打开收款记录详情页',
      id: 'openpayeeview@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '打开记录编辑视图',
      codeName: 'open_edit',
      frontAppViewId: 'crmweb.payee_payee_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_open_edit',
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '打开记录编辑视图',
      id: 'open_edit@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '向导',
      codeName: 'open_wizard',
      frontAppViewId: 'crmweb.payee_wizard_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_open_wizard',
      uiactionMode: 'FRONT',
      uiactionTag: 'open_wizard',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '打开收款记录向导视图',
      id: 'open_wizard@payee',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'remove',
      confirmMsg: '确定要删除所选的记录吗？',
      fullCodeName: 'payee_remove',
      appDEMethodId: 'remove',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee',
      name: '删除',
      id: 'remove@payee',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'before_save_payee',
      defaultParamName: 'Default',
      logicName: '收款记录保存之前',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'form_data',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.form.control.data',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.form.control.data] ==> form_data',
              id: 'view[layoutpanel.panelitems.form.control.data] ==> form_data',
            },
          ],
          topPos: 394,
          name: '绑定表单数据对象',
          id: 'preparejsparam1',
        },
        {
          code: "var form_data = view.layoutPanel.panelItems.form.control.data;\r\nvar planned_amount = form_data.planned_amount; // 收款计划金额 \r\nvar amount = form_data.amount; // 收款记录金额 \r\nif (planned_amount != undefined  && planned_amount != null) {\r\n    if( amount < planned_amount ){\r\n        util.message.warning('收款金额小于计划金额，请降低原收款计划金额！');\r\n    }\r\n}",
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          topPos: 550,
          name: '判断金额，是否提示',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'ctrl',
          activeCtrlParam: true,
          ctrlParam: true,
          name: '当前部件对象',
          id: 'ctrl',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'form_data',
          entityParam: true,
          name: '表单数据对象',
          id: 'form_data',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '收款记录保存之前',
      id: 'before_save_payee',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'payee',
  deapicodeName: 'payee',
  deapicodeName2: 'payees',
  deapitag: 'PAYEE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'dataimport',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PAYEE',
  },
  logicName: '收款记录',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'payees',
      majorAppDataEntityId: 'crmweb.project',
      parentAppDEFieldId: 'project_id',
      parentTextAppDEFieldId: 'project_name',
      rsmode: 2,
      name: 'DER1N_PAYEE_PROJECT_PROJECT_ID',
      id: 'payees',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  major: true,
  name: 'PAYEE',
  id: 'crmweb.payee',
  codeName2: 'payees',
  requestPaths: ['projects/${project}/payees/${payee}'],
};
