export default {
  appDEFields: [
    {
      codeName: 'type',
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TYPE',
      id: 'type',
    },
    {
      codeName: 'owner',
      logicName: '销售人员',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER',
      id: 'owner',
    },
    {
      codeName: 'sector',
      logicName: '行业',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SECTOR',
      id: 'sector',
    },
    {
      codeName: 'statistic_date',
      logicName: '统计时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'STATISTIC_DATE',
      id: 'statistic_date',
    },
    {
      codeName: 'type_date',
      logicName: '计划/记录时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'TYPE_DATE',
      id: 'type_date',
    },
    {
      codeName: 'o_number',
      logicName: '订单编号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'O_NUMBER',
      id: 'o_number',
    },
    {
      codeName: 'account_name',
      logicName: '客户名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACCOUNT_NAME',
      id: 'account_name',
    },
    {
      codeName: 'project_name',
      logicName: '订单名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PROJECT_NAME',
      id: 'project_name',
    },
    {
      codeName: 'project_id',
      logicName: '订单标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PROJECT_ID',
      id: 'project_id',
    },
    {
      codeName: 'description',
      logicName: '款项说明',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'business_line',
      logicName: '业务条线',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'BUSINESS_LINE',
      id: 'business_line',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'amount',
      logicName: '收款金额',
      precision: 2,
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'AMOUNT',
      id: 'amount',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'payee_statistic_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'type',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'type',
        },
        {
          codeName: 'owner',
          logicName: '销售人员',
          appDEFieldId: 'owner',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner',
        },
        {
          codeName: 'sector',
          logicName: '行业',
          appDEFieldId: 'sector',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sector',
        },
        {
          codeName: 'statistic_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '统计时间',
          appDEFieldId: 'statistic_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'statistic_date',
        },
        {
          codeName: 'type_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '计划/记录时间',
          appDEFieldId: 'type_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'type_date',
        },
        {
          codeName: 'o_number',
          logicName: '订单编号',
          appDEFieldId: 'o_number',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'o_number',
        },
        {
          codeName: 'account_name',
          logicName: '客户名称',
          appDEFieldId: 'account_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_name',
        },
        {
          codeName: 'project_id',
          logicName: '订单标识',
          appDEFieldId: 'project_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'project_id',
        },
        {
          codeName: 'project_name',
          logicName: '订单名称',
          appDEFieldId: 'project_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'project_name',
        },
        {
          codeName: 'description',
          logicName: '款项说明',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'business_line',
          logicName: '业务条线',
          appDEFieldId: 'business_line',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'business_line',
        },
        {
          codeName: 'amount',
          logicName: '收款金额',
          appDEFieldId: 'amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'amount',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'payee_statistic_dto',
    },
    {
      codeName: 'payee_statistic_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_business_line_eq',
          logicName: '业务条线',
          appDEFieldId: 'business_line',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_business_line_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_eq',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_owner_eq',
          logicName: '销售人员',
          appDEFieldId: 'owner',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_owner_eq',
        },
        {
          codeName: 'n_statistic_date_gt',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '统计时间',
          appDEFieldId: 'statistic_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_statistic_date_gt',
        },
        {
          codeName: 'n_statistic_date_gtandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '统计时间',
          appDEFieldId: 'statistic_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_statistic_date_gtandeq',
        },
        {
          codeName: 'n_statistic_date_ltandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '统计时间',
          appDEFieldId: 'statistic_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_statistic_date_ltandeq',
        },
        {
          codeName: 'n_type_eq',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'payee_statistic_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'all_statistic',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/all_statistic',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'all_statistic',
    },
    {
      codeName: 'async_calculation',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'ASYNCACTION',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/async_calculation',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'Async_Calculation',
      actionType: 'REMOTE',
      asyncAction: true,
      dataSetType: 'REMOTE',
      name: 'Async_Calculation',
      id: 'async_calculation',
    },
    {
      codeName: 'calculation',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/calculation',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionTag: 'Calculation',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Calculation',
      id: 'calculation',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_findplan_payee',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_findplan_payee',
      actionType: 'REMOTE',
      dataSetName: 'findplan_payee',
      dataSetTag: 'findplan_payee',
      dataSetType: 'REMOTE',
      id: 'fetch_findplan_payee',
    },
    {
      codeName: 'fetch_owner',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_owner',
      actionType: 'REMOTE',
      dataSetName: 'owner',
      dataSetTag: 'owner',
      dataSetType: 'REMOTE',
      id: 'fetch_owner',
    },
    {
      codeName: 'fetch_sortby_name',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_sortby_name',
      actionType: 'REMOTE',
      dataSetName: 'SortbyName',
      dataSetTag: 'SortbyName',
      dataSetType: 'REMOTE',
      id: 'fetch_sortby_name',
    },
    {
      codeName: 'fetch_statistic',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'payee_statistic_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'payee_statistic_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_statistic',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'GTANDEQ',
          condValue: 'gt',
          fieldName: 'STATISTIC_DATE',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(STATISTIC_DATE) 大于等于(>=) 数据上下文 gt',
          id: '(statistic_date) 大于等于(>=) 数据上下文 gt',
        },
        {
          condOp: 'LT',
          condValue: 'lt',
          fieldName: 'STATISTIC_DATE',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(STATISTIC_DATE) 小于(<) 数据上下文 lt',
          id: '(statistic_date) 小于(<) 数据上下文 lt',
        },
        {
          condOp: 'GTANDEQ',
          condValue: 'gt',
          fieldName: 'STATISTIC_DATE',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(STATISTIC_DATE) 大于等于(>=) 数据上下文 gt',
          id: '(statistic_date) 大于等于(>=) 数据上下文 gt',
        },
        {
          condOp: 'LT',
          condValue: 'lt',
          fieldName: 'STATISTIC_DATE',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(STATISTIC_DATE) 小于(<) 数据上下文 lt',
          id: '(statistic_date) 小于(<) 数据上下文 lt',
        },
        {
          condOp: 'GTANDEQ',
          condValue: 'lt',
          fieldName: 'STATISTIC_DATE',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(STATISTIC_DATE) 大于等于(>=) 数据上下文 lt',
          id: '(statistic_date) 大于等于(>=) 数据上下文 lt',
        },
      ],
      dataSetName: 'statistic',
      dataSetTag: 'statistic',
      dataSetType: 'REMOTE',
      id: 'fetch_statistic',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导航收款统计表格视图',
      codeName: 'nav_statistic_grid',
      frontProcessType: 'OTHER',
      fullCodeName: 'payee_statistic_nav_statistic_grid',
      uiactionMode: 'FRONT',
      uiactionTag: 'nav_statistic_grid',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'exp_to_gridview3',
      appDataEntityId: 'crmweb.payee_statistic',
      name: '导航收款统计表格视图(只传搜索表单参数)',
      id: 'nav_statistic_grid@payee_statistic',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'open_edit',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_statistic_open_edit',
      sysImage: {
        cssClass: 'fa fa-pencil-square-o',
        glyph: 'xf044@FontAwesome',
      },
      refreshMode: 2,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'redirect',
      appDataEntityId: 'crmweb.payee_statistic',
      name: '反查数据打开编辑视图',
      id: 'open_edit@payee_statistic',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '查看',
      codeName: 'open_project',
      frontAppViewId: 'crmweb.project_main_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'payee_statistic_open_project',
      navigateContexts: [
        {
          key: 'PROJECT',
          value: 'project_id',
          name: 'PROJECT',
          id: 'project',
        },
      ],
      sysImage: {
        cssClass: 'fa fa-share-alt',
        glyph: 'xf1e0@FontAwesome',
      },
      refreshMode: 2,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_project',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_statistic',
      name: '订单号反查',
      id: 'open_project@payee_statistic',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '生成收款情况统计',
      codeName: 'save_statistic_ALLOCATE',
      fullCodeName: 'payee_statistic_save_statistic_ALLOCATE',
      appDEMethodId: 'calculation',
      successMsg: '更新成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'save_statistic_ALLOCATE',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.payee_statistic',
      name: '生成收款情况统计',
      id: 'save_statistic_allocate@payee_statistic',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'exp_to_gridview',
      defaultParamName: 'Default',
      logicName: '导航到表格视图（统计图表导航）',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 60,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'state.items',
                    dstLogicParamId: 'chartexpbar_chart',
                    logicType: 'SINGLE',
                    name: 'chartexpbar_chart[state.items] 值为空(Nil)',
                    id: 'chartexpbar_chart[state.items] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '无数据时导航',
            },
          ],
          topPos: 12,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'console.log("在这停顿")',
          codeName: 'RAWJSCODE1',
          leftPos: 180,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 160,
          name: '注入脚本代码',
          id: 'rawjscode1',
        },
        {
          eventName: 'onNavViewChange',
          eventParamId: 'viewmsg',
          fireCtrlId: 'chartexpbar',
          codeName: 'VIEWCTRLFIREEVENT1',
          leftPos: 728,
          logicNodeType: 'VIEWCTRLFIREEVENT',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlfireevent1',
              id: '连接名称',
            },
          ],
          topPos: 20,
          name: '视图部件事件触发',
          id: 'viewctrlfireevent1',
        },
        {
          codeName: 'END1',
          leftPos: 1091,
          logicNodeType: 'END',
          topPos: 12,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 280,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlfireevent1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'viewId',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'crmweb.deal_grid_view_multimode',
              srcValueType: 'SRCVALUE',
              name: '直接值[crmweb.deal_grid_vie...] ==> viewmsg[viewId]',
              id: '直接值[crmweb.deal_grid_vie...] ==> viewmsg[viewid]',
            },
            {
              dstFieldName: 'key',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[id] ==> viewmsg[key]',
            },
            {
              dstFieldName: 'context',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'context',
              srcDEUILogicParamId: 'chartexpbar_chart',
              srcValueType: 'SRCDLPARAM',
              id: 'chartexpbar_chart[context] ==> viewmsg[context]',
            },
            {
              dstFieldName: 'params',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'params',
              srcDEUILogicParamId: 'chartexpbar_chart',
              srcValueType: 'SRCDLPARAM',
              id: 'chartexpbar_chart[params] ==> viewmsg[params]',
            },
            {
              dstFieldName: 'isCache',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'false',
              srcValueType: 'SRCVALUE',
              name: '直接值[false] ==> viewmsg[isCache]',
              id: '直接值[false] ==> viewmsg[iscache]',
            },
            {
              dstFieldName: 'navViewMsg',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcDEUILogicParamId: 'viewmsg',
              srcValueType: 'SRCDLPARAM',
              name: 'viewmsg ==> viewmsg[navViewMsg]',
              id: 'viewmsg ==> viewmsg[navviewmsg]',
            },
          ],
          topPos: 20,
          name: '准备视图参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'chartexpbar',
          ctrlParam: true,
          name: '图表导航栏',
          id: 'chartexpbar',
        },
        {
          codeName: 'chartexpbar_chart',
          ctrlParam: true,
          name: '图表',
          id: 'chartexpbar_chart',
        },
        {
          codeName: 'viewmsg',
          entityParam: true,
          name: '视图信息',
          id: 'viewmsg',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '导航到表格视图（统计图表导航）',
      id: 'exp_to_gridview',
    },
    {
      codeName: 'exp_to_gridview3',
      defaultParamName: 'Default',
      logicName: '导航到表格视图(只传搜索表单参数)',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 60,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 12,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 410,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlfireevent1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'viewId',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'crmweb.payee_statistic_chart_grid_view',
              srcValueType: 'SRCVALUE',
              name: '直接值[crmweb.payee_statist...] ==> viewmsg[viewId]',
              id: '直接值[crmweb.payee_statist...] ==> viewmsg[viewid]',
            },
            {
              dstFieldName: 'key',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[id] ==> viewmsg[key]',
            },
            {
              dstFieldName: 'context',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'context',
              srcDEUILogicParamId: 'chartexpbar_chart',
              srcValueType: 'SRCDLPARAM',
              id: 'chartexpbar_chart[context] ==> viewmsg[context]',
            },
            {
              dstFieldName: 'params',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'state.data',
              srcDEUILogicParamId: 'searchform',
              srcValueType: 'SRCDLPARAM',
              id: 'searchform[state.data] ==> viewmsg[params]',
            },
            {
              dstFieldName: 'isCache',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'false',
              srcValueType: 'SRCVALUE',
              name: '直接值[false] ==> viewmsg[isCache]',
              id: '直接值[false] ==> viewmsg[iscache]',
            },
            {
              dstFieldName: 'navViewMsg',
              dstDEUILogicParamId: 'viewmsg',
              paramAction: 'SETPARAMVALUE',
              srcDEUILogicParamId: 'viewmsg',
              srcValueType: 'SRCDLPARAM',
              name: 'viewmsg ==> viewmsg[navViewMsg]',
              id: 'viewmsg ==> viewmsg[navviewmsg]',
            },
          ],
          topPos: 20,
          name: '准备视图参数',
          id: 'preparejsparam1',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'ctrl',
          leftPos: 170,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 20,
          name: '调试逻辑参数',
          id: 'debugparam1',
        },
        {
          codeName: 'END1',
          leftPos: 1091,
          logicNodeType: 'END',
          topPos: 12,
          name: '结束',
          id: 'end1',
        },
        {
          eventName: 'onNavViewChange',
          eventParamId: 'viewmsg',
          fireCtrlId: 'chartexpbar',
          codeName: 'VIEWCTRLFIREEVENT1',
          leftPos: 728,
          logicNodeType: 'VIEWCTRLFIREEVENT',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlfireevent1',
              id: '连接名称',
            },
          ],
          topPos: 20,
          name: '视图部件事件触发',
          id: 'viewctrlfireevent1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'ctrl',
          activeCtrlParam: true,
          ctrlParam: true,
          name: '当前部件对象',
          id: 'ctrl',
        },
        {
          codeName: 'viewmsg',
          entityParam: true,
          name: '视图信息',
          id: 'viewmsg',
        },
        {
          codeName: 'chartexpbar_chart',
          ctrlParam: true,
          name: '图表',
          id: 'chartexpbar_chart',
        },
        {
          codeName: 'searchform',
          ctrlParam: true,
          name: '搜索表单',
          id: 'searchform',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'chartexpbar',
          ctrlParam: true,
          name: '图表导航栏',
          id: 'chartexpbar',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '导航到表格视图(只传搜索表单参数)',
      id: 'exp_to_gridview3',
    },
    {
      codeName: 'redirect',
      defaultParamName: 'Default',
      logicName: '界面跳转至记录/计划',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 550,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    groupOP: 'OR',
                    deuilogicLinkConds: [
                      {
                        condOP: 'EQ',
                        dstFieldName: 'type',
                        dstLogicParamId: 'default',
                        paramValue: '0',
                        value: '0',
                        logicType: 'SINGLE',
                        name: 'Default[type] 等于(=) 0',
                        id: 'default[type] 等于(=) 0',
                      },
                      {
                        condOP: 'EQ',
                        dstFieldName: 'type',
                        dstLogicParamId: 'default',
                        paramValue: '2',
                        value: '2',
                        logicType: 'SINGLE',
                        name: 'Default[type] 等于(=) 2',
                        id: 'default[type] 等于(=) 2',
                      },
                      {
                        condOP: 'EQ',
                        dstFieldName: 'type',
                        dstLogicParamId: 'default',
                        paramValue: '3',
                        value: '3',
                        logicType: 'SINGLE',
                        name: 'Default[type] 等于(=) 3',
                        id: 'default[type] 等于(=) 3',
                      },
                    ],
                    logicType: 'GROUP',
                    name: 'OR',
                    id: 'or',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '收款计划',
            },
            {
              dstDEUILogicNodeId: 'deuiaction2',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'EQ',
                    dstFieldName: 'type',
                    dstLogicParamId: 'default',
                    paramValue: '1',
                    value: '1',
                    logicType: 'SINGLE',
                    name: 'Default[type] 等于(=) 1',
                    id: 'default[type] 等于(=) 1',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '收款记录',
            },
          ],
          topPos: 150,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'END1',
          leftPos: 514,
          logicNodeType: 'END',
          topPos: 642,
          name: '结束',
          id: 'end1',
        },
        {
          dstAppDEUIActionId: 'open_edit@payee',
          dstAppDataEntityId: 'crmweb.payee',
          codeName: 'DEUIACTION2',
          dstDEUILogicParamId: 'default',
          leftPos: 810,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'deuiaction2',
              id: '连接名称',
            },
          ],
          topPos: 370,
          name: '打开记录编辑视图',
          id: 'deuiaction2',
        },
        {
          dstAppDEUIActionId: 'open_edit@payee_plan',
          dstAppDataEntityId: 'crmweb.payee_plan',
          codeName: 'DEUIACTION1',
          dstDEUILogicParamId: 'default',
          leftPos: 220,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'deuiaction1',
              id: '连接名称',
            },
          ],
          topPos: 380,
          name: '打开计划编辑视图',
          id: 'deuiaction1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '界面跳转至记录/计划',
      id: 'redirect',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'payee_statistic',
  deapicodeName: 'payee_statistic',
  deapicodeName2: 'payee_statistics',
  deapitag: 'PAYEE_STATISTIC',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PAYEE_STATISTIC',
  },
  logicName: '收款情况统计',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PAYEE_STATISTIC',
  id: 'crmweb.payee_statistic',
  codeName2: 'payee_statistics',
  requestPaths: [],
};
