export default {
  appDEDataImports: [
    {
      batchSize: 1000,
      codeName: 'DataImport',
      createDataAccessAction: 'CREATE',
      dedataImportItems: [
        {
          caption: '证书编号',
          appDEFieldId: 'pc_number',
          name: 'PC_NUMBER',
          id: 'pc_number',
        },
        {
          caption: '颁证机构',
          appDEFieldId: 'awarding_organization',
          name: 'AWARDING_ORGANIZATION',
          id: 'awarding_organization',
        },
        {
          caption: '受证单位',
          appDEFieldId: 'accredited_organization',
          name: 'ACCREDITED_ORGANIZATION',
          id: 'accredited_organization',
        },
        {
          caption: '认证范围',
          appDEFieldId: 'scope',
          name: 'SCOPE',
          id: 'scope',
        },
        {
          caption: '有效期起',
          appDEFieldId: 'start_date',
          name: 'START_DATE',
          id: 'start_date',
        },
        {
          caption: '有效期止',
          appDEFieldId: 'end_date',
          name: 'END_DATE',
          id: 'end_date',
        },
        {
          caption: '签发日期',
          appDEFieldId: 'issue_date',
          name: 'ISSUE_DATE',
          id: 'issue_date',
        },
        {
          caption: '签发人',
          appDEFieldId: 'issue_man',
          name: 'ISSUE_MAN',
          id: 'issue_man',
        },
        {
          caption: '产品/服务名称及型号',
          appDEFieldId: 'service_name',
          name: 'SERVICE_NAME',
          id: 'service_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ID',
          },
          caption: '标识',
          appDEFieldId: 'id',
          name: 'ID',
          id: 'id',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '证书名称',
          appDEFieldId: 'name',
          name: 'NAME',
          id: 'name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_TIME',
          },
          caption: '更新时间',
          appDEFieldId: 'update_time',
          name: 'UPDATE_TIME',
          id: 'update_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_MAN',
          },
          caption: '建立人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'create_man',
          name: 'CREATE_MAN',
          id: 'create_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.UPDATE_MAN',
          },
          caption: '更新人',
          codeListId: 'crmweb.crm__sysoperator',
          appDEFieldId: 'update_man',
          name: 'UPDATE_MAN',
          id: 'update_man',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.CREATE_TIME',
          },
          caption: '建立时间',
          appDEFieldId: 'create_time',
          name: 'CREATE_TIME',
          id: 'create_time',
        },
        {
          caption: '描述',
          appDEFieldId: 'description',
          name: 'DESCRIPTION',
          id: 'description',
        },
        {
          caption: '产品标识',
          appDEFieldId: 'product_id',
          name: 'PRODUCT_ID',
          id: 'product_id',
        },
        {
          caption: '附件',
          appDEFieldId: 'attachments',
          name: 'ATTACHMENTS',
          id: 'attachments',
        },
      ],
      updateDataAccessAction: 'UPDATE',
      defaultMode: true,
      enableBackend: true,
      enableFront: true,
      valid: true,
      createAppDEActionId: 'create',
      updateAppDEActionId: 'update',
      name: '导入产品证书',
      id: 'dataimport',
    },
  ],
  appDEFields: [
    {
      codeName: 'pc_number',
      logicName: '证书编号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PC_NUMBER',
      id: 'pc_number',
    },
    {
      codeName: 'awarding_organization',
      logicName: '颁证机构',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'AWARDING_ORGANIZATION',
      id: 'awarding_organization',
    },
    {
      codeName: 'accredited_organization',
      logicName: '受证单位',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACCREDITED_ORGANIZATION',
      id: 'accredited_organization',
    },
    {
      codeName: 'scope',
      logicName: '认证范围',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'SCOPE',
      id: 'scope',
    },
    {
      codeName: 'start_date',
      logicName: '有效期起',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'START_DATE',
      id: 'start_date',
    },
    {
      codeName: 'end_date',
      logicName: '有效期止',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'END_DATE',
      id: 'end_date',
    },
    {
      codeName: 'issue_date',
      logicName: '签发日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'ISSUE_DATE',
      id: 'issue_date',
    },
    {
      codeName: 'issue_man',
      logicName: '签发人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ISSUE_MAN',
      id: 'issue_man',
    },
    {
      codeName: 'service_name',
      logicName: '产品/服务名称及型号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'SERVICE_NAME',
      id: 'service_name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '证书名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'description',
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 32000,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'product_id',
      logicName: '产品标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRODUCT_ID',
      id: 'product_id',
    },
    {
      codeName: 'attachments',
      logicName: '附件',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'product_certificate_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'pc_number',
          logicName: '证书编号',
          appDEFieldId: 'pc_number',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'pc_number',
        },
        {
          codeName: 'awarding_organization',
          logicName: '颁证机构',
          appDEFieldId: 'awarding_organization',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'awarding_organization',
        },
        {
          codeName: 'accredited_organization',
          logicName: '受证单位',
          appDEFieldId: 'accredited_organization',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'accredited_organization',
        },
        {
          codeName: 'scope',
          logicName: '认证范围',
          appDEFieldId: 'scope',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'scope',
        },
        {
          codeName: 'start_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '有效期起',
          appDEFieldId: 'start_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'start_date',
        },
        {
          codeName: 'end_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '有效期止',
          appDEFieldId: 'end_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'end_date',
        },
        {
          codeName: 'issue_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '签发日期',
          appDEFieldId: 'issue_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'issue_date',
        },
        {
          codeName: 'issue_man',
          logicName: '签发人',
          appDEFieldId: 'issue_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'issue_man',
        },
        {
          codeName: 'service_name',
          logicName: '产品/服务名称及型号',
          appDEFieldId: 'service_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'service_name',
        },
        {
          codeName: 'attachments',
          logicName: '附件',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'attachment_dto',
          refAppDataEntityId: 'crmweb.attachment',
          refPickupAppDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'description',
          logicName: '描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '证书名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'product_id',
          logicName: '产品标识',
          appDEFieldId: 'product_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'product_id',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'product_certificate_dto',
    },
    {
      codeName: 'product_certificate_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '证书名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_product_id_eq',
          logicName: '产品标识',
          appDEFieldId: 'product_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_product_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'product_certificate_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_tags',
    },
    {
      codeName: 'batch_update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/batch_update',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'batch_update',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_task',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_task',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_task',
    },
    {
      codeName: 'delete_tags',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete_tags',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete_tags',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'main_view_dr_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/main_view_dr_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'main_view_dr_count',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'product_certificate_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'product_certificate_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加附件',
      codeName: 'add_attachments',
      frontProcessType: 'OTHER',
      fullCodeName: 'product_certificate_add_attachments',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      uiactionMode: 'FRONT',
      uiactionTag: 'add_attachments',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'add_attachment',
      appDataEntityId: 'crmweb.product_certificate',
      name: '添加附件',
      id: 'add_attachments@product_certificate',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '添加标签',
      codeName: 'add_tags',
      frontAppViewId: 'crmweb.tag_add_tag',
      fullCodeName: 'product_certificate_add_tags',
      appDEMethodId: 'add_tags',
      refreshMode: 1,
      successMsg: '已成功添加标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.product_certificate',
      name: '添加标签',
      id: 'add_tags@product_certificate',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '批量更新',
      codeName: 'batch_update',
      fullCodeName: 'product_certificate_batch_update',
      appDEMethodId: 'batch_update',
      refreshMode: 1,
      successMsg: '更新完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'batch_update',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.product_certificate',
      name: '批量更新',
      id: 'batch_update@product_certificate',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '创建任务',
      codeName: 'create_task',
      frontAppViewId: 'crmweb.task_batch_create_view',
      fullCodeName: 'product_certificate_create_task',
      appDEMethodId: 'create_task',
      successMsg: '创建完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'create_task',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.product_certificate',
      name: '创建任务',
      id: 'create_task@product_certificate',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移除标签',
      codeName: 'delete_tags',
      frontAppViewId: 'crmweb.tag_remove_tag',
      fullCodeName: 'product_certificate_delete_tags',
      appDEMethodId: 'delete_tags',
      refreshMode: 1,
      successMsg: '已成功移除标签',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_tags',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.product_certificate',
      name: '移除标签',
      id: 'delete_tags@product_certificate',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'open_edit_view',
      frontAppViewId: 'crmweb.product_certificate_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'product_certificate_open_edit_view',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit_view',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.product_certificate',
      name: '编辑',
      id: 'open_edit_view@product_certificate',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'remove',
      confirmMsg: '确定要删除所选的记录吗？',
      fullCodeName: 'product_certificate_remove',
      appDEMethodId: 'remove',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.product_certificate',
      name: '删除',
      id: 'remove@product_certificate',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '上传',
      codeName: 'upload_attachment',
      frontProcessType: 'OTHER',
      fullCodeName: 'product_certificate_upload_attachment',
      sysPFPluginId: 'file_upload',
      uiactionMode: 'FRONT',
      uiactionTag: 'upload_attachment',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.product_certificate',
      name: '上传附件',
      id: 'upload_attachment@product_certificate',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'add_attachment',
      defaultParamName: 'Default',
      logicName: '添加附件',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          invokeCtrlId: 'grid',
          invokeMethod: 'addAttachMent',
          invokeParamId: 'attach',
          codeName: 'VIEWCTRLINVOKE2',
          leftPos: 989,
          logicNodeType: 'VIEWCTRLINVOKE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'viewctrlinvoke2',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '视图部件调用',
          id: 'viewctrlinvoke2',
        },
        {
          dstAppDEUIActionId: 'upload_attachment@product_certificate',
          dstAppDataEntityId: 'crmweb.product_certificate',
          codeName: 'DEUIACTION1',
          dstDEUILogicParamId: 'files',
          leftPos: 309,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'deuiaction1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '界面行为',
          id: 'deuiaction1',
        },
        {
          code: '// 计算新建默认值\r\nconst defaultData = uiLogic.grid.calcDefaultValue({}, true);\r\nuiLogic.attach = uiLogic.files.map(item => \r\n    {\r\n        return {\r\n            name: item.name,\r\n            file_id: item.id,\r\n            id: item.uuid,\r\n            ...defaultData,\r\n        }\r\n    }\r\n)',
          codeName: 'RAWJSCODE4',
          leftPos: 780,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke2',
              srcDEUILogicNodeId: 'rawjscode4',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '设置附件参数',
          id: 'rawjscode4',
        },
        {
          codeName: 'END1',
          leftPos: 1167,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 553,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode4',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'grid',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'details.attachments.mdController',
              srcDEUILogicParamId: 'form',
              srcValueType: 'SRCDLPARAM',
              name: 'form[details.attachments.mdController] ==> grid',
              id: 'form[details.attachments.mdcontroller] ==> grid',
            },
          ],
          topPos: 208,
          name: '绑定表格部件',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'form',
          ctrlParam: true,
          name: '表单',
          id: 'form',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '重复器表格',
          id: 'grid',
        },
        {
          codeName: 'files',
          entityListParam: true,
          name: '上传文件',
          id: 'files',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'attach',
          entityListParam: true,
          name: '附件',
          id: 'attach',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '添加附件',
      id: 'add_attachment',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'product_certificate',
  deapicodeName: 'product_certificate',
  deapicodeName2: 'product_certificates',
  deapitag: 'PRODUCT_CERTIFICATE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  defaultAppDEDataImportId: 'dataimport',
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PRODUCT_CERTIFICATE',
  },
  logicName: '产品证书',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'product_certificates',
      majorAppDataEntityId: 'crmweb.product',
      parentAppDEFieldId: 'product_id',
      rsmode: 2,
      name: 'DER1N_PRODUCT_CERTIFICATE_PRODUCT_PRODUCT_ID',
      id: 'product_certificates',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PRODUCT_CERTIFICATE',
  id: 'crmweb.product_certificate',
  codeName2: 'product_certificates',
  requestPaths: [
    'products/${product}/product_certificates/${product_certificate}',
  ],
};
