export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'first_name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'crmweb.user',
      textAppDEFieldId: 'first_name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'first_name',
      logicName: '姓名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      enableQuickSearch: true,
      name: 'FIRST_NAME',
      id: 'first_name',
    },
    {
      codeName: 'locale',
      logicName: '语言',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LOCALE',
      id: 'locale',
    },
    {
      codeName: 'street',
      logicName: '街道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'STREET',
      id: 'street',
    },
    {
      codeName: 'last_name',
      logicName: '姓氏',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'LAST_NAME',
      id: 'last_name',
    },
    {
      codeName: 'country_locale',
      logicName: '国家/地区设置',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COUNTRY_LOCALE',
      id: 'country_locale',
    },
    {
      codeName: 'city',
      logicName: '城市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CITY',
      id: 'city',
    },
    {
      codeName: 'email',
      logicName: '电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EMAIL',
      id: 'email',
    },
    {
      codeName: 'state',
      logicName: '省/市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'STATE',
      id: 'state',
    },
    {
      codeName: 'zip',
      logicName: '邮编',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'ZIP',
      id: 'zip',
    },
    {
      codeName: 'country',
      logicName: '国家/地区',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COUNTRY',
      id: 'country',
    },
    {
      codeName: 'alias',
      logicName: '别名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'ALIAS',
      id: 'alias',
    },
    {
      codeName: 'role',
      logicName: '职位',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ROLE',
      id: 'role',
    },
    {
      codeName: 'phone',
      logicName: '电话',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PHONE',
      id: 'phone',
    },
    {
      codeName: 'mobile',
      logicName: '手机',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MOBILE',
      id: 'mobile',
    },
    {
      codeName: 'website',
      logicName: '网站',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'WEBSITE',
      id: 'website',
    },
    {
      codeName: 'fax',
      logicName: '传真',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'FAX',
      id: 'fax',
    },
    {
      codeName: 'sysuser_id',
      logicName: 'rt用户标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SYSUSERID',
      id: 'sysuser_id',
    },
    {
      codeName: 'dob',
      logicName: '生日',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'DOB',
      id: 'dob',
    },
    {
      codeName: 'status',
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATUS',
      id: 'status',
    },
    {
      codeName: 'full_name',
      logicName: '全名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 120,
      name: 'FULL_NAME',
      id: 'full_name',
    },
    {
      codeName: 'image_link',
      logicName: '头像',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'IMAGE_LINK',
      id: 'image_link',
    },
    {
      codeName: 'user_name',
      logicName: '账号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USER_NAME',
      id: 'user_name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'enable',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ENABLE',
      },
      logicName: '逻辑有效标志',
      predefinedType: 'LOGICVALID',
      stdDataType: 9,
      name: 'ENABLE',
      id: 'enable',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'user_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'first_name',
          logicName: '姓名',
          appDEFieldId: 'first_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'first_name',
        },
        {
          codeName: 'locale',
          logicName: '语言',
          appDEFieldId: 'locale',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'locale',
        },
        {
          codeName: 'street',
          logicName: '街道',
          appDEFieldId: 'street',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'street',
        },
        {
          codeName: 'last_name',
          logicName: '姓氏',
          appDEFieldId: 'last_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_name',
        },
        {
          codeName: 'country_locale',
          logicName: '国家/地区设置',
          appDEFieldId: 'country_locale',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'country_locale',
        },
        {
          codeName: 'city',
          logicName: '城市',
          appDEFieldId: 'city',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'city',
        },
        {
          codeName: 'email',
          logicName: '电子邮件',
          appDEFieldId: 'email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email',
        },
        {
          codeName: 'state',
          logicName: '省/市',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'zip',
          logicName: '邮编',
          appDEFieldId: 'zip',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'zip',
        },
        {
          codeName: 'country',
          logicName: '国家/地区',
          appDEFieldId: 'country',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'country',
        },
        {
          codeName: 'alias',
          logicName: '别名',
          appDEFieldId: 'alias',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias',
        },
        {
          codeName: 'role',
          logicName: '职位',
          appDEFieldId: 'role',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'role',
        },
        {
          codeName: 'phone',
          logicName: '电话',
          appDEFieldId: 'phone',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone',
        },
        {
          codeName: 'mobile',
          logicName: '手机',
          appDEFieldId: 'mobile',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mobile',
        },
        {
          codeName: 'website',
          logicName: '网站',
          appDEFieldId: 'website',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'website',
        },
        {
          codeName: 'fax',
          logicName: '传真',
          appDEFieldId: 'fax',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'fax',
        },
        {
          codeName: 'sysuser_id',
          logicName: 'rt用户标识',
          appDEFieldId: 'sysuser_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sysuser_id',
        },
        {
          codeName: 'dob',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '生日',
          appDEFieldId: 'dob',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'dob',
        },
        {
          codeName: 'status',
          logicName: '状态',
          appDEFieldId: 'status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'status',
        },
        {
          codeName: 'full_name',
          logicName: '全名',
          appDEFieldId: 'full_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'full_name',
        },
        {
          codeName: 'image_link',
          logicName: '头像',
          appDEFieldId: 'image_link',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'image_link',
        },
        {
          codeName: 'user_name',
          logicName: '账号',
          appDEFieldId: 'user_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_name',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'user_dto',
    },
    {
      codeName: 'user_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_first_name_like',
          logicName: '姓名',
          appDEFieldId: 'first_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_first_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_status_eq',
          logicName: '状态',
          appDEFieldId: 'status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_status_eq',
        },
        {
          codeName: 'n_sysuserid_eq',
          logicName: 'rt用户标识',
          appDEFieldId: 'sysuser_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_sysuserid_eq',
        },
        {
          codeName: 'n_sysuserid_noteq',
          logicName: 'rt用户标识',
          appDEFieldId: 'sysuser_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_sysuserid_noteq',
        },
        {
          codeName: 'n_user_name_like',
          logicName: '账号',
          appDEFieldId: 'user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'user_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_account_reluser',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_account_reluser',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_account_reluser',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_sys_person',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_sys_person',
      actionMode: 'CREATE',
      actionTag: 'createSysPerson',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'createSysPerson',
      id: 'create_sys_person',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'unlink',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/unlink',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'unlink',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_account_reluser',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_account_reluser',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'principal_id',
          fieldName: 'PRINCIPAL_ID',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(PRINCIPAL_ID) 等于(=) 数据上下文 principal_id',
          id: '(principal_id) 等于(=) 数据上下文 principal_id',
        },
      ],
      dataSetName: 'account_reluser',
      dataSetTag: 'account_reluser',
      dataSetType: 'REMOTE',
      id: 'fetch_account_reluser',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_curuser',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_curuser',
      actionType: 'REMOTE',
      dataSetName: 'curuser',
      dataSetTag: 'curuser',
      dataSetType: 'REMOTE',
      id: 'fetch_curuser',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_sales_leader',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'user_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'user_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_sales_leader',
      actionType: 'REMOTE',
      dataSetName: 'SalesLeader',
      dataSetTag: 'SalesLeader',
      dataSetType: 'REMOTE',
      id: 'fetch_sales_leader',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加关联销售',
      codeName: 'add_account_reluser',
      dataAccessAction: 'SRFUR__ASSIGNRELATEDSALES',
      frontAppViewId: 'crmweb.user_m_pickup_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'user_add_account_reluser',
      appDEMethodId: 'add_account_reluser',
      deopprivId: 'srfur__assignrelatedsales',
      navigateParams: [
        {
          key: 'pickupname',
          value: '选取的销售人员',
          rawValue: true,
          id: 'pickupname',
        },
        {
          key: 'principal_type',
          value: 'ACCOUNT',
          rawValue: true,
          id: 'principal_type',
        },
        {
          key: 'principal_id',
          value: 'account',
          id: 'principal_id',
        },
      ],
      refreshMode: 1,
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'add_account_reluser',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.user',
      name: '添加关联销售',
      id: 'add_account_reluser@user',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '确认',
      codeName: 'change_password',
      frontProcessType: 'OTHER',
      fullCodeName: 'user_change_password',
      uiactionMode: 'FRONT',
      uiactionTag: 'change_password',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'change_pas',
      appDataEntityId: 'crmweb.user',
      name: '修改密码（表单）',
      id: 'change_password@user',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'edit_personal_info',
      frontAppViewId: 'crmweb.user_option_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'user_edit_personal_info',
      uiactionMode: 'FRONT',
      uiactionTag: 'edit_personal_info',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.user',
      name: '编辑个人信息',
      id: 'edit_personal_info@user',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '新建',
      codeName: 'new_user',
      frontAppViewId: 'crmweb.user_quick_new_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'user_new_user',
      uiactionMode: 'FRONT',
      uiactionTag: 'new_user',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.user',
      name: '新建用户',
      id: 'new_user@user',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '取消关联',
      codeName: 'unlink',
      confirmMsg: '是否确认取消关联销售人员？',
      dataAccessAction: 'SRFUR__ASSIGNRELATEDSALES',
      fullCodeName: 'user_unlink',
      appDEMethodId: 'unlink',
      deopprivId: 'srfur__assignrelatedsales',
      refreshMode: 1,
      successMsg: '已完成！',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'unlink',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.user',
      name: '取消关联',
      id: 'unlink@user',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'work_user_edit_personal_info',
      frontAppViewId: 'crmweb.user_work_user_option_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'user_work_user_edit_personal_info',
      uiactionMode: 'FRONT',
      uiactionTag: 'work_user_edit_personal_info',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.user',
      name: '编辑个人信息（工作用户）',
      id: 'work_user_edit_personal_info@user',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'change_pas',
      defaultParamName: 'Default',
      logicName: '修改密码（表单）',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: "(async function() { \r\nconst bol = await uiLogic.form.validate();\r\nif (bol) {\r\n    ibiz.util.action.execAndResolved(\r\n      'change_password',\r\n      {\r\n        context: uiLogic.form.context,\r\n        params: uiLogic.form.params,\r\n        data: [uiLogic.default],\r\n        view: uiLogic.view,\r\n      },\r\n      uiLogic.form.model.appId,\r\n    );\r\n} else {\r\n    ibiz.message.error('请检查表单填写！');\r\n}\r\n} )();",
          codeName: 'RAWJSCODE1',
          leftPos: 367,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '校验表单',
          id: 'rawjscode1',
        },
        {
          codeName: 'END1',
          leftPos: 633,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'form',
          ctrlParam: true,
          name: '表单',
          id: 'form',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '修改密码（表单）',
      id: 'change_pas',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'user',
  deapicodeName: 'user',
  deapicodeName2: 'users',
  deapitag: 'USER',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.USER',
  },
  logicName: '用户',
  majorAppDEFieldId: 'first_name',
  quickSearchAppDEFieldIds: ['first_name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'USER',
  id: 'crmweb.user',
  codeName2: 'users',
  requestPaths: [],
};
