package cn.ibizlab.crm.crm.logic.productlogic.add_product;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.product productadd_productdefault;
                global cn.ibizlab.crm.core.crm.domain.product productadd_productitem;
                global cn.ibizlab.crm.core.crm.domain.relation productadd_productrelation;
                global java.util.Map productadd_productsrfactionparam;
                global java.util.Map productadd_productsub;
                    global cn.ibizlab.crm.core.crm.service.IrelationService relationservice;
        global cn.ibizlab.crm.core.crm.service.IproductService iBzSysProductDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "productadd_productbegin"
            when
            then
            end

            //逻辑处理节点[获取选择产品集合]
            rule "prepareparam1"
            ruleflow-group "productadd_productprepareparam1"
            when
            then
                            productadd_productsrfactionparam.set("",productadd_productdefault.get("srfactionparam"));
                        update(productadd_productdefault);//更新fact中变量值
                        update(productadd_productitem);//更新fact中变量值
                        update(productadd_productrelation);//更新fact中变量值
                        update(productadd_productsrfactionparam);//更新fact中变量值
                        update(productadd_productsub);//更新fact中变量值
            end

            //逻辑处理节点[循环获取产品数据集]
            rule "loopsubcall1"
            ruleflow-group "productadd_productloopsubcall1"
            when
            then
                        update(productadd_productdefault);//更新fact中变量值
                        update(productadd_productitem);//更新fact中变量值
                        update(productadd_productrelation);//更新fact中变量值
                        update(productadd_productsrfactionparam);//更新fact中变量值
                        update(productadd_productsub);//更新fact中变量值
            end

            //逻辑处理节点[拷贝产品数据至中间对象]
            rule "copyparam1"
            ruleflow-group "productadd_productcopyparam1"
            when
            then
                        update(productadd_productdefault);//更新fact中变量值
                        update(productadd_productitem);//更新fact中变量值
                        update(productadd_productrelation);//更新fact中变量值
                        update(productadd_productsrfactionparam);//更新fact中变量值
                        update(productadd_productsub);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "productadd_productend1"
            when
            then
                        update(productadd_productdefault);//更新fact中变量值
                        update(productadd_productitem);//更新fact中变量值
                        update(productadd_productrelation);//更新fact中变量值
                        update(productadd_productsrfactionparam);//更新fact中变量值
                        update(productadd_productsub);//更新fact中变量值
            end

            //逻辑处理节点[设置关联数据]
            rule "prepareparam2"
            ruleflow-group "productadd_productprepareparam2"
            when
            then
                            productadd_productrelation.set("principalid",productadd_productdefault.get("principal_id"));
                            productadd_productrelation.set("principaltype",productadd_productdefault.get("principal_type"));
                            productadd_productrelation.set("targetid",productadd_productitem.get("id"));
                            productadd_productrelation.set("targettype","PRODUCT");
                                productadd_productrelation.set("id",null);
                        update(productadd_productdefault);//更新fact中变量值
                        update(productadd_productitem);//更新fact中变量值
                        update(productadd_productrelation);//更新fact中变量值
                        update(productadd_productsrfactionparam);//更新fact中变量值
                        update(productadd_productsub);//更新fact中变量值
            end

            //逻辑处理节点[创建关联数据]
            rule "deaction1"
            ruleflow-group "productadd_productdeaction1"
            when
            then
                        relationservice.save(productadd_productrelation);
                        update(productadd_productdefault);//更新fact中变量值
                        update(productadd_productitem);//更新fact中变量值
                        update(productadd_productrelation);//更新fact中变量值
                        update(productadd_productsrfactionparam);//更新fact中变量值
                        update(productadd_productsub);//更新fact中变量值
            end