package cn.ibizlab.crm.crm.logic.accountlogic.delete_marge;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.account accountdelete_margedefault;
                    global cn.ibizlab.crm.core.crm.service.IaccountService accountservice;
        global cn.ibizlab.crm.core.crm.service.IaccountService iBzSysAccountDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "accountdelete_margebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "accountdelete_margeend1"
            when
            then
                        update(accountdelete_margedefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "accountdelete_margedeaction1"
            when
            then
                        accountservice.remove(accountdelete_margedefault.getId());
                        update(accountdelete_margedefault);//更新fact中变量值
            end