package cn.ibizlab.crm.crm.logic.accountlogic.findaccount;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.account accountfindaccountdefault;
                global cn.ibizlab.crm.core.crm.domain.account accountfindaccountaccount;
                global java.util.Map accountfindaccountprobability;
                    global cn.ibizlab.crm.core.crm.service.IaccountService accountservice;
        global cn.ibizlab.crm.core.crm.service.IaccountService iBzSysAccountDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "accountfindaccountbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "accountfindaccountend1"
            when
            then
                        update(accountfindaccountdefault);//更新fact中变量值
                        update(accountfindaccountaccount);//更新fact中变量值
                        update(accountfindaccountprobability);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "accountfindaccountprepareparam2"
            when
            then
                            accountfindaccountaccount.set("id",accountfindaccountdefault.get("id"));
                        update(accountfindaccountdefault);//更新fact中变量值
                        update(accountfindaccountaccount);//更新fact中变量值
                        update(accountfindaccountprobability);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "accountfindaccountdeaction1"
            when
            then
                            cn.ibizlab.crm.util.helper.CachedBeanCopier.copy(accountservice.get(accountfindaccountaccount.getId()),accountfindaccountaccount);
                        update(accountfindaccountdefault);//更新fact中变量值
                        update(accountfindaccountaccount);//更新fact中变量值
                        update(accountfindaccountprobability);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "accountfindaccountdebugparam1"
            when
            then
                        update(accountfindaccountdefault);//更新fact中变量值
                        update(accountfindaccountaccount);//更新fact中变量值
                        update(accountfindaccountprobability);//更新fact中变量值
            end