package cn.ibizlab.crm.crm.logic.accountlogic.marge_account;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.account accountmarge_accountdefault;
                global cn.ibizlab.crm.core.crm.domain.attachment accountmarge_accountattachment_filter;
                global cn.ibizlab.crm.core.crm.domain.attachment accountmarge_accountattachment_list;
                global cn.ibizlab.crm.core.crm.domain.attachment accountmarge_accountattachment_sub;
                global cn.ibizlab.crm.core.crm.domain.contact accountmarge_accountcontact_filter;
                global cn.ibizlab.crm.core.crm.domain.contact accountmarge_accountcontact_list;
                global cn.ibizlab.crm.core.crm.domain.contact accountmarge_accountcontact_sub;
                global cn.ibizlab.crm.core.crm.domain.custom_button accountmarge_accountcustom_buttom_sub;
                global cn.ibizlab.crm.core.crm.domain.custom_button accountmarge_accountcustom_button_filter;
                global cn.ibizlab.crm.core.crm.domain.custom_button accountmarge_accountcustom_button_list;
                global cn.ibizlab.crm.core.crm.domain.deal accountmarge_accountdeal_filter;
                global cn.ibizlab.crm.core.crm.domain.deal accountmarge_accountdeal_list;
                global cn.ibizlab.crm.core.crm.domain.deal accountmarge_accountdeal_sub;
                global cn.ibizlab.crm.core.crm.domain.account accountmarge_accountdel_account;
                global cn.ibizlab.crm.core.crm.domain.lead accountmarge_accountlead;
                global cn.ibizlab.crm.core.crm.domain.lead accountmarge_accountlead_filter;
                global cn.ibizlab.crm.core.crm.domain.lead accountmarge_accountlead_list;
                global cn.ibizlab.crm.core.crm.domain.lead accountmarge_accountlead_sub;
                global cn.ibizlab.crm.core.crm.domain.note_attach accountmarge_accountnote_attach_filter;
                global cn.ibizlab.crm.core.crm.domain.note_attach accountmarge_accountnote_attach_list;
                global cn.ibizlab.crm.core.crm.domain.note_attach accountmarge_accountnote_attach_sub;
                global cn.ibizlab.crm.core.crm.domain.project accountmarge_accountproject_filter;
                global cn.ibizlab.crm.core.crm.domain.project accountmarge_accountproject_list;
                global cn.ibizlab.crm.core.crm.domain.project accountmarge_accountproject_sub;
                global cn.ibizlab.crm.core.crm.domain.relation accountmarge_accountrelation_filter;
                global cn.ibizlab.crm.core.crm.domain.relation accountmarge_accountrelation_list;
                global cn.ibizlab.crm.core.crm.domain.relation accountmarge_accountrelation_sub;
                    global cn.ibizlab.crm.core.crm.service.IdealService dealservice;
                    global cn.ibizlab.crm.core.crm.service.IprojectService projectservice;
                    global cn.ibizlab.crm.core.crm.service.IcontactService contactservice;
                    global cn.ibizlab.crm.core.crm.service.IleadService leadservice;
                    global cn.ibizlab.crm.core.crm.service.IrelationService relationservice;
                    global cn.ibizlab.crm.core.crm.service.Icustom_buttonService custom_buttonservice;
                    global cn.ibizlab.crm.core.crm.service.Inote_attachService note_attachservice;
                    global cn.ibizlab.crm.core.crm.service.IattachmentService attachmentservice;
        global cn.ibizlab.crm.core.crm.service.IaccountService iBzSysAccountDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "accountmarge_accountbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "accountmarge_accountprepareparam1"
            when
            then
                            accountmarge_accountdeal_filter.set("n_account_id_eq",accountmarge_accountdefault.get("id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam3"
            ruleflow-group "accountmarge_accountprepareparam3"
            when
            then
                            accountmarge_accountproject_filter.set("n_account_id_eq",accountmarge_accountdefault.get("id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam4"
            ruleflow-group "accountmarge_accountprepareparam4"
            when
            then
                            accountmarge_accountcontact_filter.set("n_account_id_eq",accountmarge_accountdefault.get("id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam6"
            ruleflow-group "accountmarge_accountprepareparam6"
            when
            then
                            accountmarge_accountrelation_filter.set("n_principal_id_eq",accountmarge_accountdefault.get("id"));
                            accountmarge_accountrelation_filter.set("n_principal_type_eq","ACCOUNT");
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "accountmarge_accountdedataset1"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset3"
            ruleflow-group "accountmarge_accountdedataset3"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset4"
            ruleflow-group "accountmarge_accountdedataset4"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall3"
            ruleflow-group "accountmarge_accountloopsubcall3"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "accountmarge_accountprepareparam2"
            when
            then
                            accountmarge_accountlead_filter.set("n_account_id_eq",accountmarge_accountdefault.get("id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam5"
            ruleflow-group "accountmarge_accountprepareparam5"
            when
            then
                            accountmarge_accountcustom_button_filter.set("n_owner_id_eq",accountmarge_accountdefault.get("id"));
                            accountmarge_accountcustom_button_filter.set("n_owner_type_eq","ACCOUNT");
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam7"
            ruleflow-group "accountmarge_accountprepareparam7"
            when
            then
                            accountmarge_accountnote_attach_filter.set("n_principal_id_eq",accountmarge_accountdefault.get("id"));
                            accountmarge_accountnote_attach_filter.set("n_principal_type_eq","ACCOUNT");
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam8"
            ruleflow-group "accountmarge_accountprepareparam8"
            when
            then
                            accountmarge_accountattachment_filter.set("n_owner_id_eq",accountmarge_accountdefault.get("id"));
                            accountmarge_accountattachment_filter.set("n_owner_type_eq","ACCOUNT");
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset2"
            ruleflow-group "accountmarge_accountdedataset2"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset5"
            ruleflow-group "accountmarge_accountdedataset5"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset6"
            ruleflow-group "accountmarge_accountdedataset6"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset7"
            ruleflow-group "accountmarge_accountdedataset7"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset8"
            ruleflow-group "accountmarge_accountdedataset8"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "accountmarge_accountloopsubcall1"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall2"
            ruleflow-group "accountmarge_accountloopsubcall2"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall4"
            ruleflow-group "accountmarge_accountloopsubcall4"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall5"
            ruleflow-group "accountmarge_accountloopsubcall5"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall6"
            ruleflow-group "accountmarge_accountloopsubcall6"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall7"
            ruleflow-group "accountmarge_accountloopsubcall7"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall8"
            ruleflow-group "accountmarge_accountloopsubcall8"
            when
            then
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam16"
            ruleflow-group "accountmarge_accountprepareparam16"
            when
            then
                            accountmarge_accountnote_attach_sub.set("principalid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam10"
            ruleflow-group "accountmarge_accountprepareparam10"
            when
            then
                            accountmarge_accountlead_sub.set("accountid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam11"
            ruleflow-group "accountmarge_accountprepareparam11"
            when
            then
                            accountmarge_accountdeal_sub.set("accountid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam12"
            ruleflow-group "accountmarge_accountprepareparam12"
            when
            then
                            accountmarge_accountproject_sub.set("accountid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam13"
            ruleflow-group "accountmarge_accountprepareparam13"
            when
            then
                            accountmarge_accountcontact_sub.set("accountid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam14"
            ruleflow-group "accountmarge_accountprepareparam14"
            when
            then
                            accountmarge_accountrelation_sub.set("principalid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam15"
            ruleflow-group "accountmarge_accountprepareparam15"
            when
            then
                            accountmarge_accountcustom_buttom_sub.set("ownerid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam17"
            ruleflow-group "accountmarge_accountprepareparam17"
            when
            then
                            accountmarge_accountattachment_sub.set("ownerid",accountmarge_accountdefault.get("last_id"));
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction2"
            ruleflow-group "accountmarge_accountdeaction2"
            when
            then
                        leadservice.update(accountmarge_accountlead_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction3"
            ruleflow-group "accountmarge_accountdeaction3"
            when
            then
                        dealservice.update(accountmarge_accountdeal_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction4"
            ruleflow-group "accountmarge_accountdeaction4"
            when
            then
                        projectservice.update(accountmarge_accountproject_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction5"
            ruleflow-group "accountmarge_accountdeaction5"
            when
            then
                        contactservice.update(accountmarge_accountcontact_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction6"
            ruleflow-group "accountmarge_accountdeaction6"
            when
            then
                        relationservice.update(accountmarge_accountrelation_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction7"
            ruleflow-group "accountmarge_accountdeaction7"
            when
            then
                        custom_buttonservice.update(accountmarge_accountcustom_buttom_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction8"
            ruleflow-group "accountmarge_accountdeaction8"
            when
            then
                        note_attachservice.update(accountmarge_accountnote_attach_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction9"
            ruleflow-group "accountmarge_accountdeaction9"
            when
            then
                        attachmentservice.update(accountmarge_accountattachment_sub);
                        update(accountmarge_accountdefault);//更新fact中变量值
                        update(accountmarge_accountattachment_filter);//更新fact中变量值
                        update(accountmarge_accountattachment_list);//更新fact中变量值
                        update(accountmarge_accountattachment_sub);//更新fact中变量值
                        update(accountmarge_accountcontact_filter);//更新fact中变量值
                        update(accountmarge_accountcontact_list);//更新fact中变量值
                        update(accountmarge_accountcontact_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_buttom_sub);//更新fact中变量值
                        update(accountmarge_accountcustom_button_filter);//更新fact中变量值
                        update(accountmarge_accountcustom_button_list);//更新fact中变量值
                        update(accountmarge_accountdeal_filter);//更新fact中变量值
                        update(accountmarge_accountdeal_list);//更新fact中变量值
                        update(accountmarge_accountdeal_sub);//更新fact中变量值
                        update(accountmarge_accountdel_account);//更新fact中变量值
                        update(accountmarge_accountlead);//更新fact中变量值
                        update(accountmarge_accountlead_filter);//更新fact中变量值
                        update(accountmarge_accountlead_list);//更新fact中变量值
                        update(accountmarge_accountlead_sub);//更新fact中变量值
                        update(accountmarge_accountnote_attach_filter);//更新fact中变量值
                        update(accountmarge_accountnote_attach_list);//更新fact中变量值
                        update(accountmarge_accountnote_attach_sub);//更新fact中变量值
                        update(accountmarge_accountproject_filter);//更新fact中变量值
                        update(accountmarge_accountproject_list);//更新fact中变量值
                        update(accountmarge_accountproject_sub);//更新fact中变量值
                        update(accountmarge_accountrelation_filter);//更新fact中变量值
                        update(accountmarge_accountrelation_list);//更新fact中变量值
                        update(accountmarge_accountrelation_sub);//更新fact中变量值
            end