package cn.ibizlab.crm.crm.logic.userlogic.add_account_reluser;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.user useradd_account_reluserdefault;
                global cn.ibizlab.crm.core.crm.domain.user useradd_account_reluseritem;
                global cn.ibizlab.crm.core.crm.domain.relation useradd_account_reluserrelation;
                global java.util.Map useradd_account_relusersrfactionparam;
                global java.util.Map useradd_account_relusersub;
                    global cn.ibizlab.crm.core.crm.service.IrelationService relationservice;
        global cn.ibizlab.crm.core.crm.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "useradd_account_reluserbegin"
            when
            then
            end

            //逻辑处理节点[获取选择用户集合]
            rule "prepareparam1"
            ruleflow-group "useradd_account_reluserprepareparam1"
            when
            then
                            useradd_account_relusersrfactionparam.set("",useradd_account_reluserdefault.get("srfactionparam"));
                        update(useradd_account_reluserdefault);//更新fact中变量值
                        update(useradd_account_reluseritem);//更新fact中变量值
                        update(useradd_account_reluserrelation);//更新fact中变量值
                        update(useradd_account_relusersrfactionparam);//更新fact中变量值
                        update(useradd_account_relusersub);//更新fact中变量值
            end

            //逻辑处理节点[循环获取用户数据集]
            rule "loopsubcall1"
            ruleflow-group "useradd_account_reluserloopsubcall1"
            when
            then
                        update(useradd_account_reluserdefault);//更新fact中变量值
                        update(useradd_account_reluseritem);//更新fact中变量值
                        update(useradd_account_reluserrelation);//更新fact中变量值
                        update(useradd_account_relusersrfactionparam);//更新fact中变量值
                        update(useradd_account_relusersub);//更新fact中变量值
            end

            //逻辑处理节点[拷贝用户数据至中间对象]
            rule "copyparam1"
            ruleflow-group "useradd_account_relusercopyparam1"
            when
            then
                        update(useradd_account_reluserdefault);//更新fact中变量值
                        update(useradd_account_reluseritem);//更新fact中变量值
                        update(useradd_account_reluserrelation);//更新fact中变量值
                        update(useradd_account_relusersrfactionparam);//更新fact中变量值
                        update(useradd_account_relusersub);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "useradd_account_reluserend1"
            when
            then
                        update(useradd_account_reluserdefault);//更新fact中变量值
                        update(useradd_account_reluseritem);//更新fact中变量值
                        update(useradd_account_reluserrelation);//更新fact中变量值
                        update(useradd_account_relusersrfactionparam);//更新fact中变量值
                        update(useradd_account_relusersub);//更新fact中变量值
            end

            //逻辑处理节点[设置关联数据]
            rule "prepareparam2"
            ruleflow-group "useradd_account_reluserprepareparam2"
            when
            then
                            useradd_account_reluserrelation.set("principalid",useradd_account_reluserdefault.get("principal_id"));
                            useradd_account_reluserrelation.set("principaltype",useradd_account_reluserdefault.get("principal_type"));
                            useradd_account_reluserrelation.set("targetid",useradd_account_reluseritem.get("id"));
                            useradd_account_reluserrelation.set("targettype","USER");
                                useradd_account_reluserrelation.set("id",null);
                        update(useradd_account_reluserdefault);//更新fact中变量值
                        update(useradd_account_reluseritem);//更新fact中变量值
                        update(useradd_account_reluserrelation);//更新fact中变量值
                        update(useradd_account_relusersrfactionparam);//更新fact中变量值
                        update(useradd_account_relusersub);//更新fact中变量值
            end

            //逻辑处理节点[创建关联数据]
            rule "deaction1"
            ruleflow-group "useradd_account_reluserdeaction1"
            when
            then
                        relationservice.save(useradd_account_reluserrelation);
                        update(useradd_account_reluserdefault);//更新fact中变量值
                        update(useradd_account_reluseritem);//更新fact中变量值
                        update(useradd_account_reluserrelation);//更新fact中变量值
                        update(useradd_account_relusersrfactionparam);//更新fact中变量值
                        update(useradd_account_relusersub);//更新fact中变量值
            end