package cn.ibizlab.crm.crm.logic.userlogic.createsysperson;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.user usercreatesyspersondefault;
                global cn.ibizlab.crm.core.runtime.domain.sys_person usercreatesyspersonperson;
                global cn.ibizlab.crm.core.runtime.domain.sys_role usercreatesyspersonrole;
                global cn.ibizlab.crm.core.runtime.domain.sys_role usercreatesyspersonrolelist;
                global cn.ibizlab.crm.core.runtime.domain.sys_role_member usercreatesyspersonrole_member;
                global cn.ibizlab.crm.core.runtime.domain.sys_role usercreatesyspersonrolefilter;
                    global cn.ibizlab.crm.core.crm.service.IuserService userservice;
                    global cn.ibizlab.crm.core.runtime.service.Isys_role_memberService sys_role_memberservice;
                    global cn.ibizlab.crm.core.runtime.service.Isys_personService sys_personservice;
                    global cn.ibizlab.crm.core.runtime.service.Isys_roleService sys_roleservice;
        global cn.ibizlab.crm.core.crm.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "usercreatesyspersonbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "usercreatesyspersonend1"
            when
            then
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[创建用户]
            rule "deaction1"
            ruleflow-group "usercreatesyspersondeaction1"
            when
            then
                        userservice.create(usercreatesyspersondefault);
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[设置rt用户信息]
            rule "prepareparam1"
            ruleflow-group "usercreatesyspersonprepareparam1"
            when
            then
                            usercreatesyspersonperson.set("uid",usercreatesyspersondefault.get("username"));
                                usercreatesyspersonperson.set("organizationid",curuser.getSessionParams().get("srforgid"));
                            usercreatesyspersonperson.set("displayname",usercreatesyspersondefault.get("firstname"));
                            usercreatesyspersonperson.set("employeenumber",usercreatesyspersondefault.get("username"));
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[绑定管理员角色]
            rule "deaction4"
            ruleflow-group "usercreatesyspersondeaction4"
            when
            then
                        sys_role_memberservice.create(usercreatesyspersonrole_member);
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[创建rt用户]
            rule "deaction2"
            ruleflow-group "usercreatesyspersondeaction2"
            when
            then
                        sys_personservice.create(usercreatesyspersonperson);
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[设置管理员角色]
            rule "prepareparam4"
            ruleflow-group "usercreatesyspersonprepareparam4"
            when
            then
                            usercreatesyspersonrole_member.set("roleid",usercreatesyspersonrole.get("id"));
                            usercreatesyspersonrole_member.set("memberuid",usercreatesyspersonperson.get("id"));
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[获取rt标识]
            rule "prepareparam2"
            ruleflow-group "usercreatesyspersonprepareparam2"
            when
            then
                            usercreatesyspersondefault.set("sysuserid",usercreatesyspersonperson.get("id"));
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[获取查询角色]
            rule "bindparam1"
            ruleflow-group "usercreatesyspersonbindparam1"
            when
            then
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[更新用户的关联标识]
            rule "deaction3"
            ruleflow-group "usercreatesyspersondeaction3"
            when
            then
                        userservice.update(usercreatesyspersondefault);
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[设置角色查询条件]
            rule "prepareparam3"
            ruleflow-group "usercreatesyspersonprepareparam3"
            when
            then
                                usercreatesyspersonrolefilter.set("n_deploy_system_id_eq",curuser.getSessionParams().get("srfsystemid"));
                            usercreatesyspersonrolefilter.set("n_authority_eq","SalesStaff");
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end

            //逻辑处理节点[查询角色数据]
            rule "dedataset1"
            ruleflow-group "usercreatesyspersondedataset1"
            when
            then
                        update(usercreatesyspersondefault);//更新fact中变量值
                        update(usercreatesyspersonperson);//更新fact中变量值
                        update(usercreatesyspersonrole);//更新fact中变量值
                        update(usercreatesyspersonrolelist);//更新fact中变量值
                        update(usercreatesyspersonrole_member);//更新fact中变量值
                        update(usercreatesyspersonrolefilter);//更新fact中变量值
            end