package cn.ibizlab.crm.crm.logic.userlogic.unlink;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.user userunlinkdefault;
                global cn.ibizlab.crm.core.crm.domain.relation userunlinkrelation;
                global cn.ibizlab.crm.core.crm.domain.relation userunlinkrelationfilter;
                global cn.ibizlab.crm.core.crm.domain.relation userunlinkrelationlist;
                    global cn.ibizlab.crm.core.crm.service.IrelationService relationservice;
        global cn.ibizlab.crm.core.crm.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "userunlinkbegin"
            when
            then
            end

            //逻辑处理节点[设置查询条件]
            rule "prepareparam2"
            ruleflow-group "userunlinkprepareparam2"
            when
            then
                            userunlinkrelationfilter.set("n_target_id_eq",userunlinkdefault.get("id"));
                            userunlinkrelationfilter.set("n_target_type_eq","USER");
                            userunlinkrelationfilter.set("n_principal_id_eq",userunlinkdefault.get("principal_id"));
                        update(userunlinkdefault);//更新fact中变量值
                        update(userunlinkrelation);//更新fact中变量值
                        update(userunlinkrelationfilter);//更新fact中变量值
                        update(userunlinkrelationlist);//更新fact中变量值
            end

            //逻辑处理节点[查询管理数据]
            rule "dedataquery1"
            ruleflow-group "userunlinkdedataquery1"
            when
            then
                        update(userunlinkdefault);//更新fact中变量值
                        update(userunlinkrelation);//更新fact中变量值
                        update(userunlinkrelationfilter);//更新fact中变量值
                        update(userunlinkrelationlist);//更新fact中变量值
            end

            //逻辑处理节点[获取关联数据]
            rule "bindparam1"
            ruleflow-group "userunlinkbindparam1"
            when
            then
                        update(userunlinkdefault);//更新fact中变量值
                        update(userunlinkrelation);//更新fact中变量值
                        update(userunlinkrelationfilter);//更新fact中变量值
                        update(userunlinkrelationlist);//更新fact中变量值
            end

            //逻辑处理节点[删除关联数据]
            rule "deaction1"
            ruleflow-group "userunlinkdeaction1"
            when
            then
                        relationservice.remove(userunlinkrelation.getId());
                        update(userunlinkdefault);//更新fact中变量值
                        update(userunlinkrelation);//更新fact中变量值
                        update(userunlinkrelationfilter);//更新fact中变量值
                        update(userunlinkrelationlist);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "userunlinkend1"
            when
            then
                        update(userunlinkdefault);//更新fact中变量值
                        update(userunlinkrelation);//更新fact中变量值
                        update(userunlinkrelationfilter);//更新fact中变量值
                        update(userunlinkrelationlist);//更新fact中变量值
            end