package cn.ibizlab.crm.crm.logic.tasklogic.asyncmaneuvertoworkprogres;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.task taskasyncmaneuvertoworkprogresdefault;
                    global cn.ibizlab.crm.core.crm.service.ItaskService taskservice;
        global cn.ibizlab.crm.core.crm.service.ItaskService iBzSysTaskDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "taskasyncmaneuvertoworkprogresbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "taskasyncmaneuvertoworkprogresend1"
            when
            then
                        update(taskasyncmaneuvertoworkprogresdefault);//更新fact中变量值
            end

            //逻辑处理节点[异步添加活动到工作进展]
            rule "deaction1"
            ruleflow-group "taskasyncmaneuvertoworkprogresdeaction1"
            when
            then
                        taskservice.async_maneuverToWorkProgress(taskasyncmaneuvertoworkprogresdefault);
                        update(taskasyncmaneuvertoworkprogresdefault);//更新fact中变量值
            end