package cn.ibizlab.crm.crm.logic.tasklogic.closed_taskormaneuver;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.task taskclosed_taskormaneuverdefault;
                    global cn.ibizlab.crm.core.crm.service.ItaskService taskservice;
        global cn.ibizlab.crm.core.crm.service.ItaskService iBzSysTaskDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "taskclosed_taskormaneuverbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "taskclosed_taskormaneuverend1"
            when
            then
                        update(taskclosed_taskormaneuverdefault);//更新fact中变量值
            end

            //逻辑处理节点[将状态变为完成]
            rule "prepareparam1"
            ruleflow-group "taskclosed_taskormaneuverprepareparam1"
            when
            then
                            taskclosed_taskormaneuverdefault.set("status","40");
                        update(taskclosed_taskormaneuverdefault);//更新fact中变量值
            end

            //逻辑处理节点[更新任务/活动]
            rule "deaction1"
            ruleflow-group "taskclosed_taskormaneuverdeaction1"
            when
            then
                        taskservice.update(taskclosed_taskormaneuverdefault);
                        update(taskclosed_taskormaneuverdefault);//更新fact中变量值
            end