package cn.ibizlab.crm.crm.logic.tasklogic.deal_cancel_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.task taskdeal_cancel_relationdefault;
                global cn.ibizlab.crm.core.crm.domain.relation taskdeal_cancel_relationrelation_obj;
                    global cn.ibizlab.crm.core.crm.service.IrelationService relationservice;
        global cn.ibizlab.crm.core.crm.service.ItaskService iBzSysTaskDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "taskdeal_cancel_relationbegin"
            when
            then
            end

            //逻辑处理节点[拼接关系主键]
            rule "rawsfcode1"
            ruleflow-group "taskdeal_cancel_relationrawsfcode1"
            when
            then
                        update(taskdeal_cancel_relationdefault);//更新fact中变量值
                        update(taskdeal_cancel_relationrelation_obj);//更新fact中变量值
            end

            //逻辑处理节点[删除关联]
            rule "deaction1"
            ruleflow-group "taskdeal_cancel_relationdeaction1"
            when
            then
                        relationservice.remove(taskdeal_cancel_relationrelation_obj.getId());
                        update(taskdeal_cancel_relationdefault);//更新fact中变量值
                        update(taskdeal_cancel_relationrelation_obj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "taskdeal_cancel_relationend1"
            when
            then
                        update(taskdeal_cancel_relationdefault);//更新fact中变量值
                        update(taskdeal_cancel_relationrelation_obj);//更新fact中变量值
            end