package cn.ibizlab.crm.crm.logic.tasklogic.defaultexecutor;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.task taskdefaultexecutordefault;
                global cn.ibizlab.crm.core.crm.domain.task_executor taskdefaultexecutoritem;
                global cn.ibizlab.crm.core.crm.domain.task_executor taskdefaultexecutorlist;
        global cn.ibizlab.crm.core.crm.service.ItaskService iBzSysTaskDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "taskdefaultexecutorbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "taskdefaultexecutorend1"
            when
            then
                        update(taskdefaultexecutordefault);//更新fact中变量值
                        update(taskdefaultexecutoritem);//更新fact中变量值
                        update(taskdefaultexecutorlist);//更新fact中变量值
            end

            //逻辑处理节点[默认执行人]
            rule "prepareparam1"
            ruleflow-group "taskdefaultexecutorprepareparam1"
            when
            then
                                taskdefaultexecutoritem.set("userid",curuser.getSessionParams().get("userid"));
                            taskdefaultexecutorlist.set("0",taskdefaultexecutoritem.get(""));
                        update(taskdefaultexecutordefault);//更新fact中变量值
                        update(taskdefaultexecutoritem);//更新fact中变量值
                        update(taskdefaultexecutorlist);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "taskdefaultexecutorprepareparam2"
            when
            then
                            taskdefaultexecutordefault.set("executors",taskdefaultexecutorlist.get(""));
                        update(taskdefaultexecutordefault);//更新fact中变量值
                        update(taskdefaultexecutoritem);//更新fact中变量值
                        update(taskdefaultexecutorlist);//更新fact中变量值
            end