package cn.ibizlab.crm.crm.logic.tasklogic.notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.task tasknotifydefault;
                    global cn.ibizlab.crm.core.crm.service.ItaskService taskservice;
        global cn.ibizlab.crm.core.crm.service.ItaskService iBzSysTaskDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "tasknotifybegin"
            when
            then
            end

            //逻辑处理节点[推送任务新建、更新通知]
            rule "denotify1"
            ruleflow-group "tasknotifydenotify1"
            when
            then
                        update(tasknotifydefault);//更新fact中变量值
            end

            //逻辑处理节点[推送活动新建、更新通知]
            rule "denotify2"
            ruleflow-group "tasknotifydenotify2"
            when
            then
                        update(tasknotifydefault);//更新fact中变量值
            end