package cn.ibizlab.crm.crm.logic.projectlogic.addprojecttoworkprogress;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.project projectaddprojecttoworkprogressdefault;
                global cn.ibizlab.crm.core.crm.domain.work_progress projectaddprojecttoworkprogresswork_progress;
                    global cn.ibizlab.crm.core.crm.service.Iwork_progressService work_progressservice;
        global cn.ibizlab.crm.core.crm.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectaddprojecttoworkprogressbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectaddprojecttoworkprogressend1"
            when
            then
                        update(projectaddprojecttoworkprogressdefault);//更新fact中变量值
                        update(projectaddprojecttoworkprogresswork_progress);//更新fact中变量值
            end

            //逻辑处理节点[准备工作进展参数]
            rule "prepareparam1"
            ruleflow-group "projectaddprojecttoworkprogressprepareparam1"
            when
            then
                            projectaddprojecttoworkprogresswork_progress.set("actiontype","create");
                            projectaddprojecttoworkprogresswork_progress.set("targetid",projectaddprojecttoworkprogressdefault.get("id"));
                            projectaddprojecttoworkprogresswork_progress.set("targettype","PROJECT");
                            projectaddprojecttoworkprogresswork_progress.set("targetname",projectaddprojecttoworkprogressdefault.get("name"));
                            projectaddprojecttoworkprogresswork_progress.set("description",projectaddprojecttoworkprogressdefault.get("description"));
                        update(projectaddprojecttoworkprogressdefault);//更新fact中变量值
                        update(projectaddprojecttoworkprogresswork_progress);//更新fact中变量值
            end

            //逻辑处理节点[创建工作进展]
            rule "deaction1"
            ruleflow-group "projectaddprojecttoworkprogressdeaction1"
            when
            then
                        work_progressservice.create(projectaddprojecttoworkprogresswork_progress);
                        update(projectaddprojecttoworkprogressdefault);//更新fact中变量值
                        update(projectaddprojecttoworkprogresswork_progress);//更新fact中变量值
            end