package cn.ibizlab.crm.crm.logic.projectlogic.asyncprojecttoworkprogres;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.project projectasyncprojecttoworkprogresdefault;
                    global cn.ibizlab.crm.core.crm.service.IprojectService projectservice;
        global cn.ibizlab.crm.core.crm.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectasyncprojecttoworkprogresbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectasyncprojecttoworkprogresend1"
            when
            then
                        update(projectasyncprojecttoworkprogresdefault);//更新fact中变量值
            end

            //逻辑处理节点[异步将线索更新到工作进展]
            rule "deaction1"
            ruleflow-group "projectasyncprojecttoworkprogresdeaction1"
            when
            then
                        projectservice.async_addProjectToWorkProgress(projectasyncprojecttoworkprogresdefault);
                        update(projectasyncprojecttoworkprogresdefault);//更新fact中变量值
            end