package cn.ibizlab.crm.crm.logic.projectlogic.defaultexecutor;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.project projectdefaultexecutordefault;
                global cn.ibizlab.crm.core.crm.domain.executor projectdefaultexecutoritem;
                global cn.ibizlab.crm.core.crm.domain.executor projectdefaultexecutorlist;
        global cn.ibizlab.crm.core.crm.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectdefaultexecutorbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectdefaultexecutorend1"
            when
            then
                        update(projectdefaultexecutordefault);//更新fact中变量值
                        update(projectdefaultexecutoritem);//更新fact中变量值
                        update(projectdefaultexecutorlist);//更新fact中变量值
            end

            //逻辑处理节点[默认执行人]
            rule "prepareparam1"
            ruleflow-group "projectdefaultexecutorprepareparam1"
            when
            then
                                projectdefaultexecutoritem.set("userid",curuser.getSessionParams().get("userid"));
                            projectdefaultexecutorlist.set("0",projectdefaultexecutoritem.get(""));
                        update(projectdefaultexecutordefault);//更新fact中变量值
                        update(projectdefaultexecutoritem);//更新fact中变量值
                        update(projectdefaultexecutorlist);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "projectdefaultexecutorprepareparam2"
            when
            then
                            projectdefaultexecutordefault.set("executors",projectdefaultexecutorlist.get(""));
                        update(projectdefaultexecutordefault);//更新fact中变量值
                        update(projectdefaultexecutoritem);//更新fact中变量值
                        update(projectdefaultexecutorlist);//更新fact中变量值
            end