package cn.ibizlab.crm.crm.logic.projectlogic.getaccount;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.project projectgetaccountdefault;
                global cn.ibizlab.crm.core.crm.domain.project projectgetaccountparent_project;
                    global cn.ibizlab.crm.core.crm.service.IprojectService projectservice;
        global cn.ibizlab.crm.core.crm.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectgetaccountbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "projectgetaccountprepareparam1"
            when
            then
                            projectgetaccountparent_project.set("id",projectgetaccountdefault.get("pid"));
                        update(projectgetaccountdefault);//更新fact中变量值
                        update(projectgetaccountparent_project);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "projectgetaccountdeaction1"
            when
            then
                            cn.ibizlab.crm.util.helper.CachedBeanCopier.copy(projectservice.get(projectgetaccountparent_project.getId()),projectgetaccountparent_project);
                        update(projectgetaccountdefault);//更新fact中变量值
                        update(projectgetaccountparent_project);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectgetaccountend1"
            when
            then
                        update(projectgetaccountdefault);//更新fact中变量值
                        update(projectgetaccountparent_project);//更新fact中变量值
            end