package cn.ibizlab.crm.crm.logic.projectlogic.loop_son_project;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.project projectloop_son_projectdefault;
                global cn.ibizlab.crm.core.crm.domain.project projectloop_son_projectproject_info;
                global cn.ibizlab.crm.core.crm.domain.project projectloop_son_projectproject_pid_filter;
                global cn.ibizlab.crm.core.crm.domain.project projectloop_son_projectproject_sub;
                    global cn.ibizlab.crm.core.crm.service.IprojectService projectservice;
        global cn.ibizlab.crm.core.crm.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectloop_son_projectbegin"
            when
            then
            end

            //逻辑处理节点[查看订单详细内容]
            rule "debugparam3"
            ruleflow-group "projectloop_son_projectdebugparam3"
            when
            then
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "projectloop_son_projectprepareparam1"
            when
            then
                            projectloop_son_projectproject_pid_filter.set("n_pid_eq",projectloop_son_projectdefault.get("id"));
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end

            //逻辑处理节点[查询下级订单]
            rule "dedataset1"
            ruleflow-group "projectloop_son_projectdedataset1"
            when
            then
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end

            //逻辑处理节点[查看子订单列表数据]
            rule "debugparam2"
            ruleflow-group "projectloop_son_projectdebugparam2"
            when
            then
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "projectloop_son_projectend1"
            when
            then
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end

            //逻辑处理节点[抛出异常]
            rule "throwexception1"
            ruleflow-group "projectloop_son_projectthrowexception1"
            when
            then
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "projectloop_son_projectloopsubcall1"
            when
            then
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end

            //逻辑处理节点[实体处理逻辑]
            rule "delogic1"
            ruleflow-group "projectloop_son_projectdelogic1"
            when
            then
                        update(projectloop_son_projectdefault);//更新fact中变量值
                        update(projectloop_son_projectproject_info);//更新fact中变量值
                        update(projectloop_son_projectproject_pid_filter);//更新fact中变量值
                        update(projectloop_son_projectproject_sub);//更新fact中变量值
            end