package cn.ibizlab.crm.crm.logic.projectlogic.project_change_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.project projectproject_change_notifydefault;
                    global cn.ibizlab.crm.core.crm.service.IprojectService projectservice;
        global cn.ibizlab.crm.core.crm.service.IprojectService iBzSysProjectDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "projectproject_change_notifybegin"
            when
            then
            end

            //逻辑处理节点[实体通知]
            rule "denotify1"
            ruleflow-group "projectproject_change_notifydenotify1"
            when
            then
                        update(projectproject_change_notifydefault);//更新fact中变量值
            end