package cn.ibizlab.crm.crm.logic.leadlogic.addleadtoworkprogress;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.lead leadaddleadtoworkprogressdefault;
                global cn.ibizlab.crm.core.crm.domain.work_progress leadaddleadtoworkprogresswork_progress;
                    global cn.ibizlab.crm.core.crm.service.Iwork_progressService work_progressservice;
        global cn.ibizlab.crm.core.crm.service.IleadService iBzSysLeadDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "leadaddleadtoworkprogressbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "leadaddleadtoworkprogressend1"
            when
            then
                        update(leadaddleadtoworkprogressdefault);//更新fact中变量值
                        update(leadaddleadtoworkprogresswork_progress);//更新fact中变量值
            end

            //逻辑处理节点[准备工作进展参数]
            rule "prepareparam1"
            ruleflow-group "leadaddleadtoworkprogressprepareparam1"
            when
            then
                            leadaddleadtoworkprogresswork_progress.set("actiontype","create");
                            leadaddleadtoworkprogresswork_progress.set("targetid",leadaddleadtoworkprogressdefault.get("id"));
                            leadaddleadtoworkprogresswork_progress.set("targettype","LEAD");
                            leadaddleadtoworkprogresswork_progress.set("targetname",leadaddleadtoworkprogressdefault.get("subject"));
                            leadaddleadtoworkprogresswork_progress.set("description",leadaddleadtoworkprogressdefault.get("description"));
                        update(leadaddleadtoworkprogressdefault);//更新fact中变量值
                        update(leadaddleadtoworkprogresswork_progress);//更新fact中变量值
            end

            //逻辑处理节点[创建工作进展]
            rule "deaction1"
            ruleflow-group "leadaddleadtoworkprogressdeaction1"
            when
            then
                        work_progressservice.create(leadaddleadtoworkprogresswork_progress);
                        update(leadaddleadtoworkprogressdefault);//更新fact中变量值
                        update(leadaddleadtoworkprogresswork_progress);//更新fact中变量值
            end