package cn.ibizlab.crm.crm.logic.leadlogic.leadtobedeal;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.lead leadleadtobedealdefault;
                global cn.ibizlab.crm.core.crm.domain.lead leadleadtobedealleadback;
                    global cn.ibizlab.crm.core.crm.service.IleadService leadservice;
        global cn.ibizlab.crm.core.crm.service.IleadService iBzSysLeadDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "leadleadtobedealbegin"
            when
            then
            end

            //逻辑处理节点[根据线索id查询线索]
            rule "deaction2"
            ruleflow-group "leadleadtobedealdeaction2"
            when
            then
                            cn.ibizlab.crm.util.helper.CachedBeanCopier.copy(leadservice.get(leadleadtobedealdefault.getId()),leadleadtobedealdefault);
                        update(leadleadtobedealdefault);//更新fact中变量值
                        update(leadleadtobedealleadback);//更新fact中变量值
            end

            //逻辑处理节点[线索属性值转换为商机属性值]
            rule "prepareparam1"
            ruleflow-group "leadleadtobedealprepareparam1"
            when
            then
                            leadleadtobedealdefault.set("deal_name",leadleadtobedealleadback.get("subject"));
                            leadleadtobedealdefault.set("owner",leadleadtobedealleadback.get("owner"));
                            leadleadtobedealdefault.set("accountid",leadleadtobedealleadback.get("accountid"));
                            leadleadtobedealdefault.set("leadsource",leadleadtobedealleadback.get("leadsource"));
                            leadleadtobedealdefault.set("description",leadleadtobedealleadback.get("description"));
                        update(leadleadtobedealdefault);//更新fact中变量值
                        update(leadleadtobedealleadback);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "leadleadtobedealend1"
            when
            then
                        update(leadleadtobedealdefault);//更新fact中变量值
                        update(leadleadtobedealleadback);//更新fact中变量值
            end