package cn.ibizlab.crm.crm.logic.leadlogic.relate_task_and_maneuver;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.lead leadrelate_task_and_maneuverdefault;
                global cn.ibizlab.crm.core.crm.domain.lead leadrelate_task_and_maneuverfor_temp_obj;
                global cn.ibizlab.crm.core.crm.domain.relation leadrelate_task_and_maneuverrelation_obj;
                global cn.ibizlab.crm.core.crm.domain.lead leadrelate_task_and_maneuverselectdate;
                    global cn.ibizlab.crm.core.crm.service.IrelationService relationservice;
        global cn.ibizlab.crm.core.crm.service.IleadService iBzSysLeadDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "leadrelate_task_and_maneuverbegin"
            when
            then
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam1"
            ruleflow-group "leadrelate_task_and_maneuverbindparam1"
            when
            then
                        update(leadrelate_task_and_maneuverdefault);//更新fact中变量值
                        update(leadrelate_task_and_maneuverfor_temp_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverrelation_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverselectdate);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "leadrelate_task_and_maneuverloopsubcall1"
            when
            then
                        update(leadrelate_task_and_maneuverdefault);//更新fact中变量值
                        update(leadrelate_task_and_maneuverfor_temp_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverrelation_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverselectdate);//更新fact中变量值
            end

            //逻辑处理节点[重置关联对象]
            rule "resetparam1"
            ruleflow-group "leadrelate_task_and_maneuverresetparam1"
            when
            then
                        update(leadrelate_task_and_maneuverdefault);//更新fact中变量值
                        update(leadrelate_task_and_maneuverfor_temp_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverrelation_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverselectdate);//更新fact中变量值
            end

            //逻辑处理节点[活动填充关联对象属性]
            rule "prepareparam1"
            ruleflow-group "leadrelate_task_and_maneuverprepareparam1"
            when
            then
                            leadrelate_task_and_maneuverrelation_obj.set("targetid",leadrelate_task_and_maneuverfor_temp_obj.get("id"));
                            leadrelate_task_and_maneuverrelation_obj.set("principaltype","LEAD");
                            leadrelate_task_and_maneuverrelation_obj.set("principalid",leadrelate_task_and_maneuverdefault.get("id"));
                        update(leadrelate_task_and_maneuverdefault);//更新fact中变量值
                        update(leadrelate_task_and_maneuverfor_temp_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverrelation_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverselectdate);//更新fact中变量值
            end

            //逻辑处理节点[建立关联关系]
            rule "deaction1"
            ruleflow-group "leadrelate_task_and_maneuverdeaction1"
            when
            then
                        relationservice.save(leadrelate_task_and_maneuverrelation_obj);
                        update(leadrelate_task_and_maneuverdefault);//更新fact中变量值
                        update(leadrelate_task_and_maneuverfor_temp_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverrelation_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverselectdate);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "leadrelate_task_and_maneuverend1"
            when
            then
                        update(leadrelate_task_and_maneuverdefault);//更新fact中变量值
                        update(leadrelate_task_and_maneuverfor_temp_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverrelation_obj);//更新fact中变量值
                        update(leadrelate_task_and_maneuverselectdate);//更新fact中变量值
            end