package cn.ibizlab.crm.crm.logic.weeklieslogic.get_link_type;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.weeklies weekliesget_link_typedefault;
        global cn.ibizlab.crm.core.crm.service.IweekliesService iBzSysWeekliesDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "weekliesget_link_typebegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "weekliesget_link_typeend1"
            when
            then
                        update(weekliesget_link_typedefault);//更新fact中变量值
            end