export default {
  appDEUIActions: [
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '添加全部',
      codeName: 'AddAll',
      fullCodeName: 'AddAll',
      predefinedType: 'UTIL_ADDALL',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'AddAll',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '添加全部数据（数据选择）',
      id: 'util_addall',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '添加选中',
      codeName: 'AddSelection',
      fullCodeName: 'AddSelection',
      predefinedType: 'UTIL_ADDSELECTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'AddSelection',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '添加选中数据（数据选择）',
      id: 'util_addselection',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '取消',
      codeName: 'Cancel',
      fullCodeName: 'Cancel',
      predefinedType: 'VIEW_CANCELACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Cancel',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_取消',
      id: 'view_cancelaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '取消变更',
      codeName: 'CancelChanges',
      fullCodeName: 'CancelChanges',
      predefinedType: 'DATA_CANCELCHANGES',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'CancelChanges',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '取消变更',
      id: 'data_cancelchanges',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.COPY',
      },
      caption: '拷贝',
      codeName: 'Copy',
      fullCodeName: 'Copy',
      sysImage: {
        cssClass: 'fa fa-copy',
        glyph: 'xf0c5@FontAwesome',
      },
      predefinedType: 'EDITVIEW_COPYACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.COPY',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Copy',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_拷贝操作',
      id: 'editview_copyaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.COPY',
      },
      caption: '拷贝',
      codeName: 'Copy',
      fullCodeName: 'Copy',
      sysImage: {
        cssClass: 'fa fa-copy',
        glyph: 'xf0c5@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_COPYACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.COPY',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Copy',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_拷贝操作',
      id: 'gridview_copyaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '建立数据',
      codeName: 'CreateObject',
      fullCodeName: 'CreateObject',
      predefinedType: 'DATA_CREATEOBJECT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'CreateObject',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '建立数据',
      id: 'data_createobject',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.EDIT',
      },
      caption: '编辑',
      codeName: 'Edit',
      fullCodeName: 'Edit',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_EDITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.EDIT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Edit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_编辑操作',
      id: 'gridview_editaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
      },
      caption: '关闭',
      codeName: 'Exit',
      fullCodeName: 'Exit',
      sysImage: {
        cssClass: 'fa fa-sign-out',
        glyph: 'xf08b@FontAwesome',
      },
      predefinedType: 'EDITVIEW_EXITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.CLOSE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Exit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_退出操作',
      id: 'editview_exitaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.EXPORT',
      },
      caption: '导出',
      codeName: 'ExportExcel',
      fullCodeName: 'ExportExcel',
      sysImage: {
        cssClass: 'fa fa-file-excel-o',
        glyph: 'xf1c3@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_EXPORTACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.EXPORT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'ExportExcel',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_导出操作（Excel）',
      id: 'gridview_exportaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'MENUITEM.CAPTION.*.EXPORTSRF',
      },
      caption: '导出数据模型',
      codeName: 'ExportModel',
      fullCodeName: 'ExportModel',
      sysImage: {
        cssClass: 'fa fa-download',
        glyph: 'xf019@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_EXPORTXMLACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'ExportModel',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_导出数据模型',
      id: 'gridview_exportxmlaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '完成',
      codeName: 'Finish',
      fullCodeName: 'Finish',
      predefinedType: 'UTIL_FINISH',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Finish',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '完成（向导）',
      id: 'util_finish',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '第一个记录',
      codeName: 'FirstRecord',
      fullCodeName: 'FirstRecord',
      sysImage: {
        cssClass: 'fa fa-fast-backward',
        glyph: 'xf049@FontAwesome',
      },
      predefinedType: 'EDITVIEW_FIRSTRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'FirstRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_第一个记录',
      id: 'editview_firstrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.HELP',
      },
      caption: '帮助',
      codeName: 'Help',
      fullCodeName: 'Help',
      sysImage: {
        cssClass: 'fa fa-question',
        glyph: 'xf128@FontAwesome',
      },
      predefinedType: 'EDITVIEW_HELPACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.HELP',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Help',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_帮助操作',
      id: 'editview_helpaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.HELP',
      },
      caption: '帮助',
      codeName: 'Help',
      fullCodeName: 'Help',
      sysImage: {
        cssClass: 'fa fa-question',
        glyph: 'xf128@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_HELPACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.HELP',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Help',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_帮助操作',
      id: 'gridview_helpaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '数据导入',
      codeName: 'Import',
      fullCodeName: 'Import',
      sysImage: {
        cssClass: 'fa fa-upload',
        glyph: 'xf093@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_IMPORTBAR',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Import',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_数据导入栏',
      id: 'gridview_importbar',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '最后一个记录',
      codeName: 'LastRecord',
      fullCodeName: 'LastRecord',
      sysImage: {
        cssClass: 'fa fa-fast-forward',
        glyph: 'xf050@FontAwesome',
      },
      predefinedType: 'EDITVIEW_LASTRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'LastRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_最后一个记录',
      id: 'editview_lastrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '登录',
      codeName: 'Login',
      fullCodeName: 'Login',
      predefinedType: 'APP_LOGIN',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Login',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '应用登录',
      id: 'app_login',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '登出',
      codeName: 'Logout',
      fullCodeName: 'Logout',
      predefinedType: 'APP_LOGOUT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Logout',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '应用登出',
      id: 'app_logout',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.NEW',
      },
      caption: '新建',
      codeName: 'New',
      fullCodeName: 'New',
      sysImage: {
        cssClass: 'fa fa-file-text-o',
        glyph: 'xf0f6@FontAwesome',
      },
      predefinedType: 'EDITVIEW_NEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.NEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'New',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_新建操作',
      id: 'editview_newaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.NEW',
      },
      caption: '新建',
      codeName: 'New',
      fullCodeName: 'New',
      sysImage: {
        cssClass: 'fa fa-file-text-o',
        glyph: 'xf0f6@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_NEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.NEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'New',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_新建操作',
      id: 'gridview_newaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '新建行',
      codeName: 'NewRow',
      fullCodeName: 'NewRow',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_NEWROWACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NewRow',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_新建行',
      id: 'gridview_newrowaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '下一个记录',
      codeName: 'NextRecord',
      fullCodeName: 'NextRecord',
      sysImage: {
        cssClass: 'fa fa-step-forward',
        glyph: 'xf051@FontAwesome',
      },
      predefinedType: 'EDITVIEW_NEXTRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NextRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_下一个记录',
      id: 'editview_nextrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '下一步',
      codeName: 'NextStep',
      fullCodeName: 'NextStep',
      predefinedType: 'UTIL_NEXTSTEP',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NextStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '下一步（向导）',
      id: 'util_nextstep',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '否',
      codeName: 'No',
      fullCodeName: 'No',
      predefinedType: 'VIEW_NOACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'No',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_否',
      id: 'view_noaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '确定',
      codeName: 'Ok',
      fullCodeName: 'Ok',
      predefinedType: 'VIEW_OKACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Ok',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_确定',
      id: 'view_okaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '上一个记录',
      codeName: 'PrevRecord',
      fullCodeName: 'PrevRecord',
      sysImage: {
        cssClass: 'fa fa-step-backward',
        glyph: 'xf048@FontAwesome',
      },
      predefinedType: 'EDITVIEW_PREVRECORDACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'PrevRecord',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_上一个记录',
      id: 'editview_prevrecordaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '上一步',
      codeName: 'PrevStep',
      fullCodeName: 'PrevStep',
      predefinedType: 'UTIL_PREVSTEP',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'PrevStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '上一步（向导）',
      id: 'util_prevstep',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.PRINT',
      },
      caption: '打印',
      codeName: 'Print',
      fullCodeName: 'Print',
      sysImage: {
        cssClass: 'fa fa-print',
        glyph: 'xf02f@FontAwesome',
      },
      predefinedType: 'EDITVIEW_PRINTACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.PRINT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Print',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_打印操作',
      id: 'editview_printaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.PRINT',
      },
      caption: '打印',
      codeName: 'Print',
      fullCodeName: 'Print',
      sysImage: {
        cssClass: 'fa fa-print',
        glyph: 'xf02f@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_PRINTACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.PRINT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Print',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_打印操作',
      id: 'gridview_printaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '刷新',
      codeName: 'Refresh',
      fullCodeName: 'Refresh',
      sysImage: {
        cssClass: 'fa fa-refresh',
        glyph: 'xf021@FontAwesome',
      },
      predefinedType: 'EDITVIEW_REFRESHACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Refresh',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_刷新操作',
      id: 'editview_refreshaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '刷新',
      codeName: 'Refresh',
      fullCodeName: 'Refresh',
      sysImage: {
        cssClass: 'fa fa-refresh',
        glyph: 'xf021@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_REFRESHACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Refresh',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_刷新操作',
      id: 'gridview_refreshaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.REMOVE',
      },
      caption: '删除',
      codeName: 'Remove',
      fullCodeName: 'Remove',
      sysImage: {
        cssClass: 'fa fa-remove',
        glyph: 'xf00d@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_REMOVEACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.REMOVE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Remove',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_删除操作',
      id: 'gridview_removeaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '移除全部',
      codeName: 'RemoveAll',
      fullCodeName: 'RemoveAll',
      predefinedType: 'UTIL_REMOVEALL',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveAll',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '移除全部数据（数据选择）',
      id: 'util_removeall',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
      },
      caption: '删除并关闭',
      codeName: 'RemoveAndExit',
      fullCodeName: 'RemoveAndExit',
      sysImage: {
        cssClass: 'fa fa-remove',
        glyph: 'xf00d@FontAwesome',
      },
      predefinedType: 'EDITVIEW_REMOVEANDEXITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveAndExit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_删除并退出操作',
      id: 'editview_removeandexitaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '删除数据',
      codeName: 'RemoveObject',
      fullCodeName: 'RemoveObject',
      predefinedType: 'DATA_REMOVEOBJECT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveObject',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '删除数据',
      id: 'data_removeobject',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '移除选中',
      codeName: 'RemoveSelection',
      fullCodeName: 'RemoveSelection',
      predefinedType: 'UTIL_REMOVESELECTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveSelection',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '移除选中数据（数据选择）',
      id: 'util_removeselection',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '重置',
      codeName: 'Reset',
      fullCodeName: 'Reset',
      predefinedType: 'UTIL_RESET',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Reset',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '重置（搜索栏）',
      id: 'util_reset',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.SAVE',
      },
      caption: '保存',
      codeName: 'Save',
      fullCodeName: 'Save',
      sysImage: {
        cssClass: 'fa fa-save',
        glyph: 'xf0c7@FontAwesome',
      },
      predefinedType: 'EDITVIEW_SAVEACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.SAVE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Save',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存操作',
      id: 'editview_saveaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDCLOSE',
      },
      caption: '保存并关闭',
      codeName: 'SaveAndExit',
      fullCodeName: 'SaveAndExit',
      sysImage: {
        cssClass: 'sx-tb-saveandclose',
      },
      predefinedType: 'EDITVIEW_SAVEANDEXITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDCLOSE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'SaveAndExit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存并退出操作',
      id: 'editview_saveandexitaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
      },
      caption: '保存并新建',
      codeName: 'SaveAndNew',
      fullCodeName: 'SaveAndNew',
      sysImage: {
        cssClass: 'sx-tb-saveandnew',
      },
      predefinedType: 'EDITVIEW_SAVEANDNEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'SaveAndNew',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存并新建操作',
      id: 'editview_saveandnewaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.STARTWF',
      },
      caption: '开始流程',
      codeName: 'SaveAndStart',
      fullCodeName: 'SaveAndStart',
      sysImage: {
        cssClass: 'fa fa-play',
        glyph: 'xf04b@FontAwesome',
      },
      predefinedType: 'EDITVIEW_SAVEANDSTARTWFACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.STARTWF',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'SaveAndStart',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存并开始流程操作',
      id: 'editview_saveandstartwfaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '保存变更',
      codeName: 'SaveChanges',
      fullCodeName: 'SaveChanges',
      predefinedType: 'DATA_SAVECHANGES',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'SaveChanges',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '保存变更',
      id: 'data_savechanges',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '搜索',
      codeName: 'Search',
      fullCodeName: 'Search',
      predefinedType: 'UTIL_SEARCH',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Search',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '搜索（搜索栏）',
      id: 'util_search',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '同步数据',
      codeName: 'Synchronize',
      fullCodeName: 'Synchronize',
      predefinedType: 'DATA_SYNCHRONIZE',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Synchronize',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '同步数据',
      id: 'data_synchronize',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.FILTER',
      },
      caption: '过滤',
      codeName: 'ToggleFilter',
      fullCodeName: 'ToggleFilter',
      sysImage: {
        cssClass: 'fa fa-filter',
        glyph: 'xf0b0@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_SEARCHBAR',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.FILTER',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'ToggleFilter',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_搜索栏',
      id: 'gridview_searchbar',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '行编辑',
      codeName: 'ToggleRowEdit',
      fullCodeName: 'ToggleRowEdit',
      sysImage: {
        cssClass: 'fa fa-table',
        glyph: 'xf0ce@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_ROWEDITACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'ToggleRowEdit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_行编辑开关操作',
      id: 'gridview_roweditaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.VIEW',
      },
      caption: '查看',
      codeName: 'View',
      fullCodeName: 'View',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_VIEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.VIEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'View',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_查看操作',
      id: 'gridview_viewaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.VIEWWFSTEP',
      },
      caption: '当前流程步骤',
      codeName: 'ViewWFStep',
      fullCodeName: 'ViewWFStep',
      sysImage: {
        cssClass: 'sx-tb-stepactor',
      },
      predefinedType: 'EDITVIEW_VIEWWFSTEPACTORACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'ViewWFStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_查看当前流程步骤用户操作',
      id: 'editview_viewwfstepactoraction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '是',
      codeName: 'Yes',
      fullCodeName: 'Yes',
      predefinedType: 'VIEW_YESACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Yes',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_是',
      id: 'view_yesaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '预约通话',
      codeName: 'book',
      frontAppViewId: 'crmweb.call_simple_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'call_book',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'book',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.call',
      name: '（通用）预约通话',
      id: 'book@call',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '修改密码',
      codeName: 'change_password',
      dataAccessAction: 'SRFUR__SPECIAL',
      frontProcessType: 'OTHER',
      fullCodeName: 'change_password',
      deopprivId: 'srfur__special',
      navigateParams: [
        {
          key: 'surepassword',
          value: 'sure_password',
          id: 'surepassword',
        },
        {
          key: 'oldpassword',
          value: 'old_password',
          id: 'oldpassword',
        },
        {
          key: 'newpassword',
          value: 'new_password',
          id: 'newpassword',
        },
      ],
      sysPFPluginId: 'change_password',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'change_password',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '修改密码',
      id: 'change_password',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '任务',
      codeName: 'create',
      frontAppViewId: 'crmweb.task_simple_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'task_create',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'create',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.task',
      name: '（通用）创建任务',
      id: 'create@task',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '会议',
      codeName: 'create',
      frontAppViewId: 'crmweb.event_simple_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'event_create',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'create',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.event',
      name: '（通用）创建会议',
      id: 'create@event',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导入备注',
      codeName: 'import',
      frontProcessType: 'DATAIMP',
      fullCodeName: 'note_attach_import',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'import',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEDataImportId: 'default',
      appDataEntityId: 'crmweb.note_attach',
      name: '导入备注',
      id: 'import@note_attach',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '记录通话',
      codeName: 'record',
      frontAppViewId: 'crmweb.call_simple_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'call_record',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'record',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'crmweb.call',
      name: '（通用）记录通话',
      id: 'record@call',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组1',
      codeName: '实体界面行为组1',
      fullCodeName: '实体界面行为组1',
      predefinedType: 'VIEW_DEBHGROUP001',
      uiactionMode: 'SYS',
      uiactionTag: 'ae6d784c04f360d59200ca287aec8f01',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组1',
      id: 'ae6d784c04f360d59200ca287aec8f01',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组2',
      codeName: '实体界面行为组2',
      fullCodeName: '实体界面行为组2',
      predefinedType: 'VIEW_DEBHGROUP002',
      uiactionMode: 'SYS',
      uiactionTag: 'd25a9e58be16f27e8e61f784a1c74ea5',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组2',
      id: 'd25a9e58be16f27e8e61f784a1c74ea5',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组3',
      codeName: '实体界面行为组3',
      fullCodeName: '实体界面行为组3',
      predefinedType: 'VIEW_DEBHGROUP003',
      uiactionMode: 'SYS',
      uiactionTag: '756758c15b45c9cfa60a87492b52f269',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组3',
      id: '756758c15b45c9cfa60a87492b52f269',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '实体界面行为组4',
      codeName: '实体界面行为组4',
      fullCodeName: '实体界面行为组4',
      predefinedType: 'VIEW_DEBHGROUP004',
      uiactionMode: 'SYS',
      uiactionTag: '41f7e84590b7e0c8ff3c13e08cef9947',
      uiactionType: 'DEUIACTION',
      group: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '实体界面行为组4',
      id: '41f7e84590b7e0c8ff3c13e08cef9947',
    },
  ],
  appFuncs: [
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0705657690',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.weeklies_grid_view_leader',
      name: '销售工作报告（领导）',
      id: 'usrappfunc0705657690',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325010771',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.invoice_tab_search_view',
      name: '发货单',
      id: 'usrappfunc0325010771',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0705789517',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.project_chart_exp_view',
      name: '签单分析',
      id: 'usrappfunc0705789517',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528517037',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.app_portal_view',
      name: '我的工作台',
      id: 'usrappfunc0528517037',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0616862932',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.payee_statistic_chart_view',
      name: '收款情况统计（按钮）',
      id: 'usrappfunc0616862932',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0612324026',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_maneuver_tab_search_view',
      name: '我的活动',
      id: 'usrappfunc0612324026',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0612581180',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_all_tab_search_view',
      name: '我的全部任务',
      id: 'usrappfunc0612581180',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528093606',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_todo_tab_search_view',
      name: '待办任务',
      id: 'usrappfunc0528093606',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0516027669',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.call_tab_search_view',
      name: '通话',
      id: 'usrappfunc0516027669',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0616788184',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_task_tree_exp_view',
      name: '全部任务',
      id: 'usrappfunc0616788184',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0612754829',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_done_tab_search_view',
      name: '已完成任务',
      id: 'usrappfunc0612754829',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325205901',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.price_book_tab_search_view',
      name: '价格表',
      id: 'usrappfunc0325205901',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0705056529',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.work_progress_menu_grid_view',
      name: '工作进展',
      id: 'usrappfunc0705056529',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528918425',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_tracing_grid_view',
      name: '追踪中的任务',
      id: 'usrappfunc0528918425',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528450525',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_task_tree_exp_view',
      name: '全部任务',
      id: 'usrappfunc0528450525',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325157131',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.purchase_order_tab_search_view',
      name: '采购订单',
      id: 'usrappfunc0325157131',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0612391645',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_maneuver_tree_exp_view',
      name: '全部活动',
      id: 'usrappfunc0612391645',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0430419046',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.user_setting_view',
      name: '个人设置',
      id: 'usrappfunc0430419046',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0607811956',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.payee_statistic_chart_exp_view',
      name: '收款情况统计（销售）',
      id: 'usrappfunc0607811956',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0322638087',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.lead_tab_search_view',
      name: '线索',
      id: 'usrappfunc0322638087',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0516117389',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_maneuver_tree_exp_view',
      name: '任务&活动',
      id: 'usrappfunc0516117389',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0612430806',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_todo_tab_search_view',
      name: '待办任务',
      id: 'usrappfunc0612430806',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325822439',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.sales_order_tab_search_view',
      name: '销售订单',
      id: 'usrappfunc0325822439',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0506888872',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.user_list_exp_view',
      name: '用户管理',
      id: 'usrappfunc0506888872',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0516431991',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.event_tab_search_view',
      name: '会议',
      id: 'usrappfunc0516431991',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0531732306',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.note_attach_option_view',
      name: '进展评估',
      id: 'usrappfunc0531732306',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325673850',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.solution_tab_search_view',
      name: '解决方案',
      id: 'usrappfunc0325673850',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325502888',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.campaign_tab_search_view',
      name: '市场活动',
      id: 'usrappfunc0325502888',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325474316',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.quote_tab_search_view',
      name: '报价',
      id: 'usrappfunc0325474316',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325605066',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.service_case_tab_search_view',
      name: '服务支持',
      id: 'usrappfunc0325605066',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528893181',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_the_maneuver_edit_view',
      navigateContexts: [
        {
          key: 'TYPE',
          value: 'MANEUVER',
          rawValue: true,
          name: 'TYPE',
          id: 'type',
        },
        {
          key: 'STATUS',
          value: '40',
          rawValue: true,
          name: 'STATUS',
          id: 'status',
        },
      ],
      navigateParams: [
        {
          key: 'type',
          value: 'MANEUVER',
          rawValue: true,
          id: 'type',
        },
        {
          key: 'status',
          value: '40',
          rawValue: true,
          id: 'status',
        },
      ],
      name: '填报活动',
      id: 'usrappfunc0528893181',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0618068589',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.deal_stage_grid_view',
      name: '阶段管理',
      id: 'usrappfunc0618068589',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0527039179',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.project_tab_search_view',
      name: '订单',
      id: 'usrappfunc0527039179',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0615004587',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.payee_plan_tab_search_view',
      name: '收款计划',
      id: 'usrappfunc0615004587',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0322577200',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.contact_tab_search_view',
      name: '联系人',
      id: 'usrappfunc0322577200',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0625511235',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.weeklies_grid_view',
      name: '销售工作报告（销售）',
      id: 'usrappfunc0625511235',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325697093',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.deal_tab_search_view',
      name: '商机',
      id: 'usrappfunc0325697093',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0615194100',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.payee_tab_search_view',
      name: '收款记录',
      id: 'usrappfunc0615194100',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325399993',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.product_tab_search_view',
      name: '产品',
      id: 'usrappfunc0325399993',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0325928262',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.vendor_tab_search_view',
      name: '供应商',
      id: 'usrappfunc0325928262',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528092584',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_cancelled_grid_view',
      name: '已取消任务',
      id: 'usrappfunc0528092584',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0407210749',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.account_test_tab_search_view',
      name: '客户',
      id: 'usrappfunc0407210749',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528941694',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_my_done_grid_view',
      name: '已完成任务',
      id: 'usrappfunc0528941694',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0625377314',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_weekly_custom_view',
      name: '功能名称',
      id: 'usrappfunc0625377314',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0712405429',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.payee_statistic_chart_exp_view_leader',
      name: '收款情况统计（领导）',
      id: 'usrappfunc0712405429',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0614992269',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.payee_statistic_chart_exp_view',
      name: '功能名称',
      id: 'usrappfunc0614992269',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0319371604',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.account_tab_search_view',
      name: '客户',
      id: 'usrappfunc0319371604',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528287391',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_task_edit_view',
      navigateContexts: [
        {
          key: 'TYPE',
          value: 'TASK',
          rawValue: true,
          name: 'TYPE',
          id: 'type',
        },
      ],
      navigateParams: [
        {
          key: 'type',
          value: 'TASK',
          rawValue: true,
          id: 'type',
        },
      ],
      name: '制定任务',
      id: 'usrappfunc0528287391',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0528417954',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'crmweb.task_portal_calendar_view',
      name: '测试',
      id: 'usrappfunc0528417954',
    },
  ],
  appPFPluginRefs: [
    {
      pluginCode: 'CRM_IMAGE_UPLOAD',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'CrmImageUpload',
      rtobjectRepo: '@ibiz-template-crm/anchor-point-nav@0.0.2-dev.18',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      name: 'CRM图片上传',
      id: 'crm图片上传',
    },
    {
      pluginCode: 'COMMENT',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizHtmlComment',
      rtobjectRepo: '@ibiz-template-plm/html-comment@0.0.2-dev.138',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      name: 'HTML（评论）',
      id: 'html（评论）',
    },
    {
      pluginCode: 'DRBAR_ANCHOR_STYLE',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizDRBarExControl',
      rtobjectRepo: '@ibiz-template-crm/anchor-point-nav@0.0.2-dev.18',
      refMode: 'CONTROL',
      refTag: 'DRBAR',
      runtimeObject: true,
      id: 'dabar(锚点)',
    },
    {
      pluginCode: 'DRBAR_ANCHOR_STYLE',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizDRBarExControl',
      rtobjectRepo: '@ibiz-template-crm/anchor-point-nav@0.0.2-dev.18',
      refMode: 'CONTROL',
      refTag: 'TABEXPPANEL',
      runtimeObject: true,
      id: 'dabar(锚点)',
    },
    {
      pluginCode: 'ANCHOR_STYLE',
      pluginType: 'EDITFORM_RENDER',
      rtobjectName: 'IBizFromAnchorPointControl',
      rtobjectRepo: '@ibiz-template-crm/anchor-point-nav@0.0.2-dev.18',
      refMode: 'CONTROL',
      refTag: 'FORM',
      runtimeObject: true,
      id: 'form(锚点)',
    },
    {
      pluginCode: 'PERSONNEL_INFO',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizPersonnelInfo',
      rtobjectRepo: '@ibiz-template-plm/personnel-info@0.0.2-dev.79',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '人员信息',
    },
    {
      pluginCode: 'CHANGE_PASSWORD',
      pluginType: 'DEUIACTION',
      rtobjectName: 'registerChangePasswordProvider',
      rtobjectRepo: '@ibiz-template-plugin/change-password@0.0.3-dev.60',
      refMode: 'UIACTION',
      refTag: 'FRONT',
      runtimeObject: true,
      id: '修改密码',
    },
    {
      pluginCode: 'TABEXPPANEL_DROPDOWN',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizTabExpPanelDropdownControl',
      rtobjectRepo: '@ibiz-template-crm/tab-search-bar@0.0.2-dev.15',
      refMode: 'CONTROL',
      refTag: 'TABEXPPANEL',
      runtimeObject: true,
      id: '关系分页部件（下拉）',
    },
    {
      pluginCode: 'GROUP_SEARCHBAR',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizGroupSearch',
      rtobjectRepo: '@ibiz-template-crm/tab-search-bar@0.0.2-dev.15',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'RAWITEM',
      runtimeObject: true,
      id: '分组搜索栏',
    },
    {
      pluginCode: 'NUMBER_GRID',
      pluginType: 'GRID_RENDER',
      rtobjectName: 'IBizNumberGridControl',
      rtobjectRepo: '@ibiz-template-plugin/number-grid@0.0.3-dev.190',
      refMode: 'CONTROL',
      refTag: 'GRID',
      runtimeObject: true,
      id: '序号表格',
    },
    {
      pluginCode: 'NUMBER_GRID',
      pluginType: 'GRID_RENDER',
      rtobjectName: 'IBizNumberGridControl',
      rtobjectRepo: '@ibiz-template-plugin/number-grid@0.0.3-dev.190',
      refMode: 'CONTROL',
      refTag: 'TREEGRID',
      runtimeObject: true,
      id: '序号表格',
    },
    {
      pluginCode: 'FILE_UPLOAD',
      pluginType: 'DEUIACTION',
      rtobjectName: 'registerFileUploadProvider',
      rtobjectRepo: '@ibiz-template-plugin/file-upload@0.1.3-alpha.17',
      refMode: 'UIACTION',
      refTag: 'FRONT',
      runtimeObject: true,
      id: '文件上传',
    },
    {
      pluginCode: 'FILE_DOWNLOAD',
      pluginType: 'DEUIACTION',
      rtobjectName: 'registerFileDownloadProvider',
      rtobjectRepo: '@ibiz-template-plugin/file-download@0.1.3-alpha.17',
      refMode: 'UIACTION',
      refTag: 'FRONT',
      runtimeObject: true,
      id: '文件下载',
    },
    {
      pluginCode: 'COMMENT_ITEM',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizCommentItemRawItem',
      rtobjectRepo: '@ibiz-template-plm/comment-item@0.0.2-dev.98',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '评论列表项',
    },
    {
      pluginCode: 'FILTER_SEARCHBAR',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizFilterSearchBarControl',
      rtobjectRepo: '@ibiz-template-crm/tab-search-bar@0.0.2-dev.15',
      refMode: 'CONTROL',
      refTag: 'SEARCHBAR',
      runtimeObject: true,
      id: '过滤搜索栏',
    },
    {
      pluginCode: 'ATTACHMENT_GRID',
      pluginType: 'GRID_RENDER',
      rtobjectName: 'IBizAttachmentGridControl',
      rtobjectRepo: '@ibiz-template-plm/attachment-grid@0.0.3-dev.48',
      refMode: 'CONTROL',
      refTag: 'GRID',
      runtimeObject: true,
      id: '附件表格',
    },
  ],
  appUIThemes: [
    {
      themeParams: {
        'theme-package-path': '@ibiz-template-theme/omni@0.1.1',
      },
      themeTag: 'omni',
      id: 'omni',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '拒绝',
      name: 'DENY',
      id: 'deny',
    },
    {
      logicName: '无控制',
      name: 'NONE',
      id: 'none',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '分配关联销售',
      mapSysUniResCode: 'ASSIGNRELATEDSALES',
      mapSysUniResMode: true,
      name: 'SRFUR__ASSIGNRELATEDSALES',
      id: 'srfur__assignrelatedsales',
    },
    {
      logicName: '（其他）特殊处理',
      mapSysUniResCode: 'SPECIAL',
      mapSysUniResMode: true,
      name: 'SRFUR__SPECIAL',
      id: 'srfur__special',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
    {
      logicName: '流程启动',
      name: 'WFSTART',
      id: 'wfstart',
    },
  ],
  appFolder: 'crmweb',
  appMode: 'CLOUDHUBAPP',
  appType: 'WEBAPP_HTML5',
  appVersion: '1.0.0.0',
  caption: '客户关系管理系统',
  codeName: 'crmweb',
  dynaSysMode: 1,
  engineVer: 240,
  pfstyle: 'VUE_R7_EMPTY',
  pftype: 'VUE_R7',
  pkgcodeName: 'crmweb',
  serviceCodeName: 'crmweb',
  sysCodeName: 'iBizCRM',
  title: '客户关系管理系统',
  viewCodeNameMode: 'LOWER_UNDERSCORE',
  enableServiceAPIDTO: true,
  enableUIModelEx: true,
  useServiceApi: true,
  userParam: {
    'globalConfig.grid.overflowMode': 'ellipsis',
  },
  id: 'crmweb',
  appId: 'ibizcrm__crmweb',
};
