package cn.ibizlab.crm.crm.logic.note_attachlogic.assess_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.note_attach note_attachassess_notifydefault;
                    global cn.ibizlab.crm.core.crm.service.Inote_attachService note_attachservice;
        global cn.ibizlab.crm.core.crm.service.Inote_attachService iBzSysNote_attachDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "note_attachassess_notifybegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "note_attachassess_notifydebugparam1"
            when
            then
                        update(note_attachassess_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[实体通知]
            rule "denotify1"
            ruleflow-group "note_attachassess_notifydenotify1"
            when
            then
                        update(note_attachassess_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[实体通知]
            rule "denotify2"
            ruleflow-group "note_attachassess_notifydenotify2"
            when
            then
                        update(note_attachassess_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[实体通知]
            rule "denotify3"
            ruleflow-group "note_attachassess_notifydenotify3"
            when
            then
                        update(note_attachassess_notifydefault);//更新fact中变量值
            end

            //逻辑处理节点[实体通知]
            rule "denotify4"
            ruleflow-group "note_attachassess_notifydenotify4"
            when
            then
                        update(note_attachassess_notifydefault);//更新fact中变量值
            end