package cn.ibizlab.crm.crm.logic.note_attachlogic.asyncevaluatetoworkprogress;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.note_attach note_attachasyncevaluatetoworkprogressdefault;
                    global cn.ibizlab.crm.core.crm.service.Inote_attachService note_attachservice;
        global cn.ibizlab.crm.core.crm.service.Inote_attachService iBzSysNote_attachDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "note_attachasyncevaluatetoworkprogressbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "note_attachasyncevaluatetoworkprogressend1"
            when
            then
                        update(note_attachasyncevaluatetoworkprogressdefault);//更新fact中变量值
            end

            //逻辑处理节点[异步将评估更新到工作进展]
            rule "deaction1"
            ruleflow-group "note_attachasyncevaluatetoworkprogressdeaction1"
            when
            then
                        note_attachservice.async_evaluateToWorkProgress(note_attachasyncevaluatetoworkprogressdefault);
                        update(note_attachasyncevaluatetoworkprogressdefault);//更新fact中变量值
            end