package cn.ibizlab.crm.crm.logic.payee_statisticlogic.calculation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee_statistic payee_statisticcalculationdefault;
        global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService iBzSysPayee_statisticDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payee_statisticcalculationbegin"
            when
            then
            end

            //逻辑处理节点[删除已有数据]
            rule "rawsqlcall1"
            ruleflow-group "payee_statisticcalculationrawsqlcall1"
            when
            then
                        Map param = null;
                        String strSql="DELETE FROM PAYEE_STATISTIC;";
                        iBzSysPayee_statisticDefaultService.execute(strSql,param);//SQL调用
                        update(payee_statisticcalculationdefault);//更新fact中变量值
            end

            //逻辑处理节点[计算统计数据]
            rule "rawsqlcall2"
            ruleflow-group "payee_statisticcalculationrawsqlcall2"
            when
            then
                        Map param = null;
                        String strSql="INSERT INTO PAYEE_STATISTIC(ID,AMOUNT,NAME,TYPE,OWNER,STATISTIC_DATE,BUSINESS_LINE) SELECT UUID(),SUM(T1.AMOUNT),CASE WHEN T1.PLANNED_TIME IS NOT NULL THEN CONCAT(YEAR(T1.PLANNED_TIME),'-',LPAD(MONTH(T1.PLANNED_TIME), 2, '0')) ELSE '未明确' END,CASE WHEN T1.PLANNED_TIME IS NULL THEN 0 ELSE 2 END,T2.OWNER,STR_TO_DATE(CONCAT(YEAR(T1.PLANNED_TIME),'-',LPAD(MONTH(T1.PLANNED_TIME), 2, '0'),'-01'), '%Y-%m-%d'),T2.BUSINESS_LINE FROM PAYEE_PLAN T1,PROJECT T2 WHERE T1.PROJECT_ID = T2.ID AND T1.PLAN_STATUS = '10'  GROUP BY T2.OWNER,T2.BUSINESS_LINE,YEAR(T1.PLANNED_TIME),MONTH(T1.PLANNED_TIME) UNION ALL SELECT UUID(),SUM(T1.AMOUNT),CONCAT(YEAR(T1.PAYEE_DATE),'-',LPAD(MONTH(T1.PAYEE_DATE), 2, '0')),'1',T2.OWNER,STR_TO_DATE(CONCAT(YEAR(T1.PAYEE_DATE),'-',LPAD(MONTH(T1.PAYEE_DATE), 2, '0'),'-01'), '%Y-%m-%d'),T2.BUSINESS_LINE FROM PAYEE T1,PROJECT T2 WHERE T1.PROJECT_ID = T2.ID GROUP BY T2.OWNER,T2.BUSINESS_LINE,YEAR(T1.PAYEE_DATE),MONTH(T1.PAYEE_DATE)";
                        iBzSysPayee_statisticDefaultService.execute(strSql,param);//SQL调用
                        update(payee_statisticcalculationdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payee_statisticcalculationend1"
            when
            then
                        update(payee_statisticcalculationdefault);//更新fact中变量值
            end