package cn.ibizlab.crm.crm.logic.payee_statisticlogic.delete_statistic;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee_statistic payee_statisticdelete_statisticdefault;
        global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService iBzSysPayee_statisticDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payee_statisticdelete_statisticbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payee_statisticdelete_statisticend1"
            when
            then
                        update(payee_statisticdelete_statisticdefault);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "payee_statisticdelete_statisticrawsqlcall1"
            when
            then
                        Map param = null;
                        String strSql="TRUNCATE table payee_statistic";
                        iBzSysPayee_statisticDefaultService.execute(strSql,param);//SQL调用
                        update(payee_statisticdelete_statisticdefault);//更新fact中变量值
            end