package cn.ibizlab.crm.crm.logic.payee_statisticlogic.update_payee_allocate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.payee_statistic payee_statisticupdate_payee_allocatedefault;
                global cn.ibizlab.crm.core.crm.domain.payee payee_statisticupdate_payee_allocatepayee;
                global cn.ibizlab.crm.core.crm.domain.payee payee_statisticupdate_payee_allocatepayee_info;
                global cn.ibizlab.crm.core.crm.domain.payee_statistic payee_statisticupdate_payee_allocatepayee_statistic_info;
                global cn.ibizlab.crm.core.crm.domain.payee_statistic payee_statisticupdate_payee_allocatepayee_stistic;
                global cn.ibizlab.crm.core.crm.domain.payee_plan payee_statisticupdate_payee_allocatepayee2;
                global cn.ibizlab.crm.core.crm.domain.payee_statistic payee_statisticupdate_payee_allocatestatistic;
                global cn.ibizlab.crm.core.crm.domain.payee payee_statisticupdate_payee_allocatesub;
                    global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService payee_statisticservice;
        global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService iBzSysPayee_statisticDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "payee_statisticupdate_payee_allocatebegin"
            when
            then
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "payee_statisticupdate_payee_allocateloopsubcall1"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "payee_statisticupdate_payee_allocaterawsfcode1"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[拷贝参数]
            rule "copyparam1"
            ruleflow-group "payee_statisticupdate_payee_allocatecopyparam1"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "payee_statisticupdate_payee_allocatedebugparam1"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "payee_statisticupdate_payee_allocateend1"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "payee_statisticupdate_payee_allocatedeaction1"
            when
            then
                        payee_statisticservice.create(payee_statisticupdate_payee_allocatepayee_stistic);
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "payee_statisticupdate_payee_allocateprepareparam1"
            when
            then
                            payee_statisticupdate_payee_allocatepayee_stistic.set("name",payee_statisticupdate_payee_allocatestatistic.get("name"));
                            payee_statisticupdate_payee_allocatepayee_stistic.set("statisticdate",payee_statisticupdate_payee_allocatestatistic.get("statisticdate"));
                            payee_statisticupdate_payee_allocatepayee_stistic.set("owner",payee_statisticupdate_payee_allocatestatistic.get("owner"));
                                payee_statisticupdate_payee_allocatepayee_stistic.set("id",null);
                            payee_statisticupdate_payee_allocatepayee_stistic.set("amount",payee_statisticupdate_payee_allocatestatistic.get("amount"));
                            payee_statisticupdate_payee_allocatepayee_stistic.set("type",payee_statisticupdate_payee_allocatestatistic.get("type"));
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "payee_statisticupdate_payee_allocaterawsqlcall1"
            when
            then
                        Map param = null;
                        String strSql="  select t2.AMOUNT,t2.PAYEE_DATE,t1.USER_ID,t1.RATIO from payee_allocate t1 left join payee t2 on t2.id = t1.payee_id";
                        java.util.List<JSONObject> entities=iBzSysPayee_statisticDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    payee_statisticupdate_payee_allocatepayee_info.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[循环获取计划数据]
            rule "loopsubcall2"
            ruleflow-group "payee_statisticupdate_payee_allocateloopsubcall2"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode2"
            ruleflow-group "payee_statisticupdate_payee_allocaterawsfcode2"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam2"
            ruleflow-group "payee_statisticupdate_payee_allocatedebugparam2"
            when
            then
                        update(payee_statisticupdate_payee_allocatedefault);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_statistic_info);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee_stistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatepayee2);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatestatistic);//更新fact中变量值
                        update(payee_statisticupdate_payee_allocatesub);//更新fact中变量值
            end