package cn.ibizlab.crm.crm.logic.deallogic.asyncdealtoworkprogres;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.deal dealasyncdealtoworkprogresdefault;
                    global cn.ibizlab.crm.core.crm.service.IdealService dealservice;
        global cn.ibizlab.crm.core.crm.service.IdealService iBzSysDealDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "dealasyncdealtoworkprogresbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "dealasyncdealtoworkprogresend1"
            when
            then
                        update(dealasyncdealtoworkprogresdefault);//更新fact中变量值
            end

            //逻辑处理节点[异步将线索更新到工作进展]
            rule "deaction1"
            ruleflow-group "dealasyncdealtoworkprogresdeaction1"
            when
            then
                        dealservice.async_addDealToWorkProgress(dealasyncdealtoworkprogresdefault);
                        update(dealasyncdealtoworkprogresdefault);//更新fact中变量值
            end