package cn.ibizlab.crm.crm.logic.deallogic.changenotiy;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.deal dealchangenotiydefault;
                    global cn.ibizlab.crm.core.crm.service.IdealService dealservice;
        global cn.ibizlab.crm.core.crm.service.IdealService iBzSysDealDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "dealchangenotiybegin"
            when
            then
            end

            //逻辑处理节点[实体通知]
            rule "denotify1"
            ruleflow-group "dealchangenotiydenotify1"
            when
            then
                        update(dealchangenotiydefault);//更新fact中变量值
            end