package cn.ibizlab.crm.crm.logic.deallogic.get_task_and_maneuver;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.deal dealget_task_and_maneuverdefault;
                global cn.ibizlab.crm.core.crm.domain.task dealget_task_and_maneuvertask_and_maneuver_list;
        global cn.ibizlab.crm.core.crm.service.IdealService iBzSysDealDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "dealget_task_and_maneuverbegin"
            when
            then
            end

            //逻辑处理节点[线索关联查询]
            rule "debugparam1"
            ruleflow-group "dealget_task_and_maneuverdebugparam1"
            when
            then
                        update(dealget_task_and_maneuverdefault);//更新fact中变量值
                        update(dealget_task_and_maneuvertask_and_maneuver_list);//更新fact中变量值
            end

            //逻辑处理节点[获取线索关联任务和活动]
            rule "rawsqlcall1"
            ruleflow-group "dealget_task_and_maneuverrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",dealget_task_and_maneuverdefault.get("n_deal_id_eq"));
    String strSql="select t1.`CLOSED_TIME`, t1.`COST`, t1.`CREATE_MAN`, t1.`CREATE_TIME`, t1.`DESCRIPTION`, t1.`DUE_DATE`, DATEDIFF(CURDATE(), t1.`DUE_DATE`) AS `DUE_DATE_SORT`, t1.`END_TIME`, t1.`ID`, t1.`LAST_ASSESS_TIME`, t1.`LOCKED__S`, t1.`NAME`, t1.`OWNER`, t1.`OWNER_ID`, t1.`OWNER_NAME`, t1.`OWNER_SUBTYPE`, t1.`OWNER_TYPE`, t1.`PRIORITY`, t1.`REMIND_AT`, t1.`SEND_NOTIFICATION_EMAIL`, t1.`START_TIME`, t1.`STATUS`, t1.`SUBJECT`, t1.`TAG`, COALESCE(START_TIME, DUE_DATE) AS `TASK_DATE`, t1.`TYPE`, t1.`UPDATE_MAN`, t1.`UPDATE_TIME` from task t1  	left join relation t2 ON t1.ID = t2.TARGET_ID  	left join deal t3 ON t3.ID = t2.PRINCIPAL_ID where t3.ID = #{et.param0} ORDER BY TASK_DATE desc";
                        java.util.List<JSONObject> entities=iBzSysDealDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    dealget_task_and_maneuvertask_and_maneuver_list.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(dealget_task_and_maneuverdefault);//更新fact中变量值
                        update(dealget_task_and_maneuvertask_and_maneuver_list);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "dealget_task_and_maneuverend1"
            when
            then
                        update(dealget_task_and_maneuverdefault);//更新fact中变量值
                        update(dealget_task_and_maneuvertask_and_maneuver_list);//更新fact中变量值
            end