package cn.ibizlab.crm.crm.logic.deallogic.stageprobability;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.crm.util.errors.BadRequestAlertException;
                global cn.ibizlab.crm.core.crm.domain.deal dealstageprobabilitydefault;
                global cn.ibizlab.crm.core.crm.domain.deal_stage dealstageprobabilitydeal_stage;
                global java.util.Map dealstageprobabilityprobability;
                    global cn.ibizlab.crm.core.crm.service.Ideal_stageService deal_stageservice;
        global cn.ibizlab.crm.core.crm.service.IdealService iBzSysDealDefaultService;
        global cn.ibizlab.crm.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "dealstageprobabilitybegin"
            when
            then
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "dealstageprobabilitydeaction1"
            when
            then
                            cn.ibizlab.crm.util.helper.CachedBeanCopier.copy(deal_stageservice.get(dealstageprobabilitydeal_stage.getId()),dealstageprobabilitydeal_stage);
                        update(dealstageprobabilitydefault);//更新fact中变量值
                        update(dealstageprobabilitydeal_stage);//更新fact中变量值
                        update(dealstageprobabilityprobability);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam2"
            ruleflow-group "dealstageprobabilityprepareparam2"
            when
            then
                            dealstageprobabilitydeal_stage.set("id",dealstageprobabilitydefault.get("stage"));
                        update(dealstageprobabilitydefault);//更新fact中变量值
                        update(dealstageprobabilitydeal_stage);//更新fact中变量值
                        update(dealstageprobabilityprobability);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam1"
            ruleflow-group "dealstageprobabilitydebugparam1"
            when
            then
                        update(dealstageprobabilitydefault);//更新fact中变量值
                        update(dealstageprobabilitydeal_stage);//更新fact中变量值
                        update(dealstageprobabilityprobability);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "dealstageprobabilityend1"
            when
            then
                        update(dealstageprobabilitydefault);//更新fact中变量值
                        update(dealstageprobabilitydeal_stage);//更新fact中变量值
                        update(dealstageprobabilityprobability);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "dealstageprobabilityprepareparam1"
            when
            then
                            dealstageprobabilitydefault.set("stageprobability",dealstageprobabilitydeal_stage.get("probability"));
                        update(dealstageprobabilitydefault);//更新fact中变量值
                        update(dealstageprobabilitydeal_stage);//更新fact中变量值
                        update(dealstageprobabilityprobability);//更新fact中变量值
            end