global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService  payeeStatisticService;
global cn.ibizlab.crm.core.crm.domain.payee et;

    no-loop

    rule "payee_statisticcalculation"
    ruleflow-group "a01ac1360dd487472626b450a6caaab1"
    when
    then
    cn.ibizlab.crm.core.crm.domain.payee_statistic actionLogicDE =new cn.ibizlab.crm.core.crm.domain.payee_statistic();
    et.copyTo(actionLogicDE,true);
    payeeStatisticService.calculation(actionLogicDE);
    end