global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService  payeeStatisticService;
global cn.ibizlab.crm.core.crm.domain.payee et;

    no-loop

    rule "payee_statisticcalculation"
    ruleflow-group "78c60ed52c841af59a3caefe006dd9a7"
    when
    then
    cn.ibizlab.crm.core.crm.domain.payee_statistic actionLogicDE =new cn.ibizlab.crm.core.crm.domain.payee_statistic();
    et.copyTo(actionLogicDE,true);
    payeeStatisticService.calculation(actionLogicDE);
    end