global cn.ibizlab.crm.core.crm.service.Ipayee_statisticService  payeeStatisticService;
global cn.ibizlab.crm.core.crm.domain.payee et;

    no-loop

    rule "payee_statisticcalculation"
    ruleflow-group "fc316eb8b98794f91b01eb92b5bd4d6d"
    when
    then
    cn.ibizlab.crm.core.crm.domain.payee_statistic actionLogicDE =new cn.ibizlab.crm.core.crm.domain.payee_statistic();
    et.copyTo(actionLogicDE,true);
    payeeStatisticService.calculation(actionLogicDE);
    end